### ISSUE TITLE
Selecting a frame does not highlight the location in the editor

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1023]
STR:

1. go to https://replay.io/view?id=e5cba9d2-58ec-4bc9-ba02-c7051984d9cf&test=1
2. click on the marker with the comment
3. select other frames in the call stack

https://www.loom.com/share/891df22ac6bb4c748b0e9e4529e9e081

**Comment by karina-y** [comment]
also when selecting call stack, the line should be highlighted in blue, ie
![image](https://user-images.githubusercontent.com/19538307/100946209-b5e0cc00-34b7-11eb-994d-93fb6a0581c9.png)

**Comment by karina-y** [comment]
recording added by @jasonLaster  https://replay.io/view?id=db1e5523-4497-4510-b47b-f0d47124bd4b
