### ISSUE TITLE
Users do not have permission to view a new recording

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1039]
I've noticed a couple of times that users are not able to see their new recordings

after looking into it a bit i have a couple of hunches

1. DevTools fetches the recording from hasura, if it is not returned it assumes you do not have permission. Perhaps this is a race condition where it would be there on refresh. For some reason though, refresh does not work though. If it were a race condition, this would fix it (https://gist.github.com/0c0e1a980aff6054a659123ac3c27627)
2. occassionally the backend gets a bad packet and cannot save the recording to hasura. That is also debunked because i can see it in hasura. 

weird

**Comment by jazzdan** [comment]
Hmm @jasonLaster I can't reprodouce. Maybe I'm not trying to reproduce correctly. Here's what I'm doing:

1. Using production replay browser, create a recording
2. Navigate to replay.io/view
3. Click on the newly created recording in my recording list
4. Observe that I can view the recording.

**Comment by jazzdan** [comment]
I can also view new public recordings if I'm not signed in.

**Comment by jasonLaster** [comment]
Ahh. Sorry you actually have to create a new recording

**Comment by jazzdan** [comment]
@jasonLaster yeah I did that! With production browser and on replay.io/view, I can create and view new recordings OK
