### ISSUE TITLE
[Inspector] Inspector won't load for a specific replay

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1044]
This is specifically for this replay: http://localhost:8080/view?id=9c2467b5-d4b4-4c8b-bcde-883c764a15ff

The inspector stays in the loading state. This is regardless of whether or not it's the first selected panel upon loading the page.

![image](https://user-images.githubusercontent.com/15959269/99573187-9fe8ec80-298a-11eb-86b2-17c19ea368f4.png)

**Comment by hbenl** [comment]
The reason is that the backend fails on `CSS.getAppliedRules` (code 33 - Failed to perform command).
