### ISSUE TITLE
Node picker highlights nodes incorrectly

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1060]
I was looking at this [replay](https://replay.io/view?id=5199bf4b-a02a-423f-aea1-511b15233baf) and found that the node picker errantly highlights nodes when hovering on the DOM.

![image](https://user-images.githubusercontent.com/15959269/100011122-21bf8800-2d86-11eb-91c9-5b6799f8b3ff.png)

**Comment by jasonLaster** [comment]
This might be a duplicate of #232

**Comment by hbenl** [comment]
Closing as duplicate.
