### ISSUE TITLE
Devtools editor is sometimes missing when opened in Replay browser

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1068]

**Comment by jasonLaster** [comment]
<img width="1552" alt="Screen Shot 2020-11-25 at 12 08 46 PM" src="https://user-images.githubusercontent.com/254562/100276838-059f2080-2f17-11eb-9795-466381796c4f.png">

**Comment by jaril** [comment]
Haven't seen this in a while so closing for now.
