### ISSUE TITLE
Whitespace node appearing for every node in the markup view

### ISSUE THREAD

**Issue by gabrielluong** [RecordReplay/devtools#1081]
**Describe the bug**
Whitespace node for every node is appearing in the markup view.

**To Reproduce**

**Screenshots**
<img width="460" alt="Screen Shot 2020-11-26 at 12 30 52 PM" src="https://user-images.githubusercontent.com/1190888/100379697-4c5a4c80-2fe3-11eb-8616-898e4b689df4.png">

**Recording**
https://replay.io/view?id=3b35f329-dbf9-4117-8f6e-5d86ee48e75f

**Additional context**
<img width="1680" alt="Screen Shot 2020-11-26 at 12 34 13 PM" src="https://user-images.githubusercontent.com/1190888/100379892-b70b8800-2fe3-11eb-9783-62dd8e481873.png">
Looking at `action/markup.ts` - we can see that every other node that is returned by `childNodes()` is a whitespace node containing `\n\n\t\t\t`. I assume this is coming from the server, but we could fix this by filtering out `#text` nodes with this particular `nodeValue`

**Comment by hbenl** [comment]
Isn't this the desired behavior? The HTML does contain these whitespace text nodes, so we should show them, no?
If whitespace text nodes shouldn't be shown at all then they can be switched off with [this pref](https://github.com/RecordReplay/devtools/blob/41df39d43b4a325db83c84cdab0cf608794a8eff/src/devtools/client/inspector/prefs.js#L26).
