### ISSUE TITLE
localhost:8080 should help devs get started

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#109]
right now it looks broken. we can give some tips. or some good links

**Comment by princiya** [comment]
As a first step, we can list a few good links which can be clicked. Can you list them here? I can then work on this ticket.

**Comment by jasonLaster** [comment]
Love it!


We should totally link to:

1. our docs https://www.notion.so/Docs-56758667f53a4d51b7c6fc7a641adb02
2. our recordings list https://www.notion.so/Recordings-1b88640e6f1e4eceaeb7a3b6767379b5
3. our readme (https://github.com/WebReplay/webreplay-devtools) I believe vicki and janelle are working on better getting started docs

As a fun though, i'd love to have an input field where devs can put in the recording id and it navigates to it...

**Comment by princiya** [comment]
ok, i will get started anyways with the above links...

**Comment by jasonLaster** [comment]
closing as this now shows the accounts UI
