### ISSUE TITLE
[Code cleanup] remove devtool-toolbox

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1096]
We have this concept of a "Toolbox" with "Panels" (inspector/console/debugger) in Replay.

`src/devtools/client/debugger/panel.js`

`src/devtools/client/webconsole/panel.js`

`src/devtools/client/inspector/panel.js`

These panels are required for the actual React components for the debugger/inspector/console to work properly. But the logic is handled separately apart from the React lifecycle for mostly legacy reasons (?). This has led to race conditions whenever we change the order in which we initialize the panels relative to each other and the actual React components.

The panels are used primarily in the `devtools-toolbox` (`src/ui/utils/devtools-toolbox.js`). The toolbox is what's responsible for handling/initializing the panels, keeping a record of what's been initialized and what's not, and selecting a panel when one of the panel icons are clicked on.

Ideally this would all be much **simpler**. We should be able to move the react components for the panels around without having to worry about race conditions. 

So it would be nice if we could rely less on panels less. It would be even better if we can completely get rid of them, and move all of the panel initialization logic to their respective React components instead. If we're able to do that, perhaps we could even get rid of `devtools-toolbox` entirely.

**Comment by karina-y** [comment]
issue closed automatically because of a pr merge but there are still two parts to this, reopening.
