### ISSUE TITLE
lagging in devtools

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1102]
**Describe the bug**
when interacting with devtools for a minute+ it begins to severely lag. this happens in chrome, incognito chrome, brave, and ff. it's fixed by doing a hard refresh but still comes back after a minute or so of interaction. at first i thought it was my browser or settings but i realized this is persistent in multiple browsers and on a fresh chrome install with no settings or extensions.

recordings: https://www.loom.com/share/817745b4c4fb42c1b43d4715868c0d61
https://www.loom.com/share/e992d268801e4a2bbf50fcb8d92e2671

**To Reproduce**
1. open a recording: http://localhost:8080/view?id=9e683a8c-c342-43f4-a3d6-cc7e7df111c3
2. click on anything, just keep interacting with the page
3. notice lagging occur
4. gets worse with devtools open

**Expected behavior**
i expect the same behavior as the first few seconds after a hard refresh, everything highlights and clicks as soon as it's been hovered/interacted with

**Recording**
https://www.loom.com/share/817745b4c4fb42c1b43d4715868c0d61
https://www.loom.com/share/e992d268801e4a2bbf50fcb8d92e2671

**Comment by karina-y** [comment]
update: after switching to a different recording the lag is significantly less
c92de4b0-e01a-410a-939c-c2df2e325196

**Comment by jasonLaster** [comment]
My hunch was that this was fixed today with holger's perf update
