### ISSUE TITLE
[Inspector] persist markup expand state across pauses

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1116]
At the moment, the markup tree's expand state is lost every time we change pauses. It'd be great if we could make a best attempt at keeping the current expand state.

Brian mentioned the other day that expand state is managed in firefox devtools with selectors so this might be something we can do with the current architecture.

**Comment by bhackett1024** [comment]
Yeah, I saw some code in the firefox inspector that IIRC it uses to re-expand the right node after navigating.  It would try to construct a selector string for the expanded node(s) that should be able to identify the same node, or a similar one, after it gets the new DOM.  I believe that it had several ways to construct the selector of varying robustness.  I just looked for the code and couldn't find it, but one way of creating the selector would be to walk up the tree until finding a node with an ID ("foo", say), and then doing a selector like "#foo div:nth-child(3) li:nth-child(1)" to walk down to the target element.

The inspector could construct selectors for the nodes it has expanded, and then when switching to another part of the recording it could query those selectors to look for that node and expand it too if found.  This isn't perfect but it seems like it should do pretty well until we have IDs we can use to identify DOM nodes that are stable between pauses.
