### ISSUE TITLE
replay playback is slow in Replay browser

### ISSUE THREAD

**Issue by sw-yx** [RecordReplay/devtools#1118]
**Describe the bug**
replay playback is slow in Replay browser. filing as requested by jason.

loom recording pending

**Comment by sw-yx** [comment]
https://www.loom.com/share/fa27038c847b4fea867b86961d3e6303

**Comment by jasonLaster** [comment]
Thanks for sharing the loom. That helps a lot

1. pressing play at the end should restart the video. It currently doesn't [bug](https://github.com/RecordReplay/devtools/issues/1141)
2. pressing play should update the button to show a pause button. We fixed that this morning
3. sluggishness during playback. We should definitely speed this up so it's 1.1. 
4. commenting - we'll be improving that ux a bit next week to make it clearer how comments work. And yeah - speed is everything.
