### ISSUE TITLE
[UX] Design Doubleback #1 (Codename Moa)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1120]
This is a single bug that contains multiple small visual tweaks. We'll use this bug to track the status of each item, and split some items out into other bugs if necessary.

![Visual audit 1 - Ellen](https://user-images.githubusercontent.com/9154902/100822227-c3e21d00-34b6-11eb-82ea-c5d339ff4ca8.png)

- [x] A: The “click in place” trick doesn’t work for me in the title
- [x] B: For now let’s make a text link that says “Log in”
- [x] C: The left nav should extend all the way to the bottom of the page
- [x] D: The play button should have 20px margin left/right and 15px top/bottom
- [x] D: Hovering over the play button should turn it blue
- [x] E: There’s a little gap between the blue part of the timeline and the grey part
- [x] F: Let’s do the black background even if it is strange and flickery
- [x] G: The play/debug toggle should be 12px from the top, bottom, and right
- [x] H: The edge of the timeline should be 20px from the right
- [x] I: I’m calling this the “candybar” for now. Can we build it out as shown in the screenshot?
- [x] J: The page should load into “Play” mode by default. If I go into “Debug” then “Sources” should be expanded and “Outline” should be collapsed. Then, if I leave the page and return, it should remember where I last was (Play versus Debug) and the state of the expanded/collapsed controls. (1hr)

![Visual audit 1 - Diana](https://user-images.githubusercontent.com/9154902/100822246-cf354880-34b6-11eb-9977-b3bd02a1d24e.png)

- [x] K: Replace share icon with “three dots” icon in header
- [x] L: Add the “Transcript & comments” header as placeholder
- [x] M: Add the gear icon and a placholder events filter (placeholder: 2hr)
- [x] N: ~~Can we put in some fake text to feel how the transcript might look?~~ (Not doing this)

Everything else: 1hr

**Comment by karina-y** [comment]
when hovering your mouse over the scrollbar in the source file panel, you get the text hovering icon instead of a mouse. i can't screenshot my mouse but here's the scrollbar i'm referring to and here's an image from the internets of what i see when hovering over the scrollbar

![image](https://user-images.githubusercontent.com/19538307/100956318-10385780-34cd-11eb-9598-57e97fe6539e.png)

![image](https://user-images.githubusercontent.com/19538307/100956387-33630700-34cd-11eb-94fd-fb7f519341ca.png)

**Comment by jonbell-lot23** [comment]
I believe we can close this now? @jaril
