### ISSUE TITLE
[Comments] Comment items should be obvious even if the comments panel is toggled off

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1126]
Take two replays that target the same URL and record the same user interactions:

Replay A: replay with 0 comments
Replay B: replay with 10 comments

Right now, opening Replay A and Replay B shows the exact same layout. The secondary toolbox underneath the viewer defaults to opening the console panel. There's no way for the user to know that they should take a look at the comments panel for Replay B.

We should find a way to signal to the user that there are comments to look at when they open a replay.

**Comment by jasonLaster** [comment]
Is this something that is fixed by having a transcripts UI in the viewer?

Do we need something in the devtools ui?

**Comment by jaril** [comment]
Not quite–it's still possible for a user to open a replay for the first time and not realize that there are comments in that replay. 

Replay defaults to the viewer mode on first open for a user so you can't miss the comments. Problem is, we then share the preferred view mode across all replays. 

So replay no.1 opens up in Viewer mode. But if I switch it to DevTools mode, close replay no.1 and open replay no.2, replay no.2 will open in DevTools mode.

**Comment by jaril** [comment]
On second thought, we have the comment markers on the timeline. It's not the best, but it's something. 

We should close this for now, and reopen if we find that people are not opening up comments when they should and it's a problem.
