### ISSUE TITLE
Make breakpoints easier to hand off when sharing a replay

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1127]
We currently persist breakpoints in a replay, but in a very limited way. Adding a breakpoints to `replay A` and opening the same link in a different browser doesn't show the original breakpoints. Same thing happens when we share that link to somebody else who then opens it in their own browser.

**I stub my toe against this a lot**. 

At the most basic level, it makes it difficult to convey the same story that I'm looking at when debugging a Replay and I get the "a-ha!" moment. This is because that story is usually in the form of plain log messages (e.g. `script.js:12`) that are ordered in a particular way. As soon as I share that replay with somebody else, those meticulously added log messages disappear. 

The way I work around this is just by adding a comment to each of those log messages. If there were 3 important log messages to tell the story, I'll add a comment to each one of those. That way, the person I share the replay with can open the replay, check the comments and then add a breakpoint to each of those comments. Once they do that, they're now looking at the same thing I was when I had my a-ha moment.

This gets more complicated once I need more descriptive log messages to tell the same story (e.g. `script.js:12 {foo: 123}`). Now, I can't just do the same thing as I did before. Even if the person I share it with adds the right breakpoints, those breakpoints have the default log message. That's not good! That means that within my comment, I have to instruct them to edit each breakpoint expression.

And the pinnacle of complexity, what if I was using descriptive log messages **and** conditions? Now I have to add a comment to each of those breakpoints, and instruct them to edit the breakpoint expression as well as what condition to put for that breakpoint. **Oof.**

There are a few angles we could take to solve this:
- Persist breakpoints for a Replay by default.
- Add an "Include my breakpoints" checkbox in the dropdown where you copy the replay link.
- Add a "Set a breakpoint everywhere there's a comment" button
- Include and display breakpoint metadata with each comment (e.g. file and line number, the actual line of code, log message+condition for that location when the comment was added, etc)

**Comment by jasonLaster** [comment]
moved into our backlog https://www.notion.so/replayio/Holger-Jason-cc35923819de4d28ac68366968a445a8?p=08ccb322c4414450b8c3719bfa671dfd&showMoveTo=true
