### ISSUE TITLE
range error when clicking on highlighted breakpoint

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1138]
**Describe the bug**
when paused at a breakpoint, if you hover on the line that's breakpointed, a range error appears in the console

**To Reproduce**
1. stop at a breakpoint via the console or timeline
2. hover over the breakpoint line in the source file
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/19538307/101074066-2ab61380-3555-11eb-901f-2aa39e10e13a.png)

**Recording**
https://www.loom.com/share/9eae6381b3f44ed38c20089343b6b92e

**Comment by jasonLaster** [comment]
I think this is fixed, but would be nice to check

**Comment by karina-y** [comment]
no longer a bug
