### ISSUE TITLE
lag in render causes lines to push down

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1139]
**Describe the bug**
when clicking on something in the callstack, the source file is navigated to that point but the breakpoint panels are not yet rendered. once those render then the line we want to focus on gets pushed out of view

**To Reproduce**
1. stop at a breakpoint that has a few items in the callstack
2. switch between two different items in the callstack
3. notice when you click on one you're navigated to that line, but after a second one is clicked, the breakpoint panels appear and your line is pushed out of view

**Expected behavior**
the breakpoint panels are already rendered or they render after the fact but you still remain at the line you want

**Recording**
https://www.loom.com/share/fd2483f0aefb46b39b79cbf251636551

**Comment by jaril** [comment]
@karina-y Did #1411 solve this as well?

**Comment by karina-y** [comment]
@jaril looks like it!
