### ISSUE TITLE
[Comments] comments are lost over night :tears:

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1140]
I've added comments to this replay (https://replay.io/view?id=db1e5523-4497-4510-b47b-f0d47124bd4b) twice now and both times they were removed within a couple of hours.

I bet we have a race condition with multiple clients blowing away the data....

I propose we fix this by persisting comments in graphql via hasura. This is better anyways :)

**Comment by jaril** [comment]
Fixed in #1288
