### ISSUE TITLE
The "Play" button could have a "restart" state to jump to beginning when at end

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1141]
When you load a recording, you start by viewing the recording's final state, but this has the downside that if you press the "Play" button, it is a no-op because you're already at the end. It would be nice if pressing play when at the end jumped back to the beginning, and we could always have a different icon for that state to make that clearer.

**Comment by jasonLaster** [comment]
Yep. Play used to go back to the beginning, but i think we regressed here.
