### ISSUE TITLE
Console evaluation results should always show next to the input

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1143]
It's now possible to get the console evaluation results to show up in the wrong spot.

STR:

1. go to the console and do many evaluations
2. quickly change pause locations

ER: results show up next to inputs
AR: they show up next to recent pause

Loom: https://www.loom.com/share/dca4d08ed6a14de5bba5311cb647c6d8
^ view 0:33

**Comment by karina-y** [comment]
one edge case is left, https://www.loom.com/share/fb4aca38105742d5b17403b8719c2600

if you type something and hit enter really really fast they will end up out of order
