### ISSUE TITLE
[Devtools] Add a way for a user to open the recording target URL in a new tab

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1153]
There should be a way within Replay for the user to click on a link that opens up the recording target's URL.

**Comment by karina-y** [comment]
@jasonLaster @jaril what do you guys think about making the url that's already in the dashboard clickable?

![image](https://user-images.githubusercontent.com/19538307/102435964-64166680-3fcc-11eb-97a1-e0484621546a.png)
