### ISSUE TITLE
wrong cursor over scrollbar

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1157]
**Describe the bug**
when hovering your mouse over the scrollbar in the source file panel, you get the text hovering icon instead of a mouse. i can't screenshot my mouse but here's the scrollbar i'm referring to and here's an image from the internets of what i see when hovering over the scrollbar

**To Reproduce**
1. Go to any recording
2. hover over the scroll bar for the source panel

**Expected behavior**
cursor remains the same and maybe the scrollbar darkens on hover?

**Screenshots**
![image](https://user-images.githubusercontent.com/19538307/101227179-d5106280-364b-11eb-9179-6e46409a5a18.png)

**Comment by jaril** [comment]
Is this still a problem? I can't seem to reproduce it. This is my mouse while hovering on the scrollbar.

![image](https://user-images.githubusercontent.com/15959269/102299125-691ddc00-3f20-11eb-9566-d4a56d841430.png)

**Comment by karina-y** [comment]
no this issue is in the editor panel scrollbar, it's still showing the wrong curosr

**Comment by jaril** [comment]
This is on the latest master branch. Is this right?

![image](https://user-images.githubusercontent.com/15959269/102382364-61018300-3f98-11eb-9ee5-e554d16cfafc.png)
