### ISSUE TITLE
[Console] Revise the purple "debug" button

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1188]
When you're paused on a console messsage, we show a purple bookmark to the left to indicate that you're paused there. Hovering on that bookmark shows the "Debug" label and clicking on it opens up that source in the editor.

That was designed back when we had a separate console and debugger panel. Now, pressing the button doesn't feel so much like going to "debug" mode. Instead, it feels more like an "open in editor" button. 

We should change the label from "Debug" to something like "Show in editor"/"Open in editor".

![image](https://user-images.githubusercontent.com/15959269/101657672-01840000-39f9-11eb-96f4-96c0c983a98d.png)
![image](https://user-images.githubusercontent.com/15959269/101657610-f5983e00-39f8-11eb-81b0-3fde7064fddb.png)

**Comment by jasonLaster** [comment]
Thanks for filing. 


### here's my thought process for verbs

I agree that debug not quite right...

Lets differentiate with the source link, which jumps to the source code without seeking in the timeline.

Perhaps a verb such as "Jump", "Fast Forward", "seek"


### here's where i remember we have that

We already have the button for jumping to that point of time. The reason we didn't also select that location in the editor is we didn't want to leave the console. At this point, I think i would rather of fast forward also select the source and get rid of the debug step :) 

thoughts?

**Comment by jonbell-lot23** [comment]
@jasonLaster @jaril 

I agree. Clicking once to see the console and editor update would be tightly integrated and good. I assume there are some downsides we can imagine, like wanting to jump forward but keep the editor from updating. But is that likely to happen 80% of the time or is it more of an edgecase?

If it's an edgecase, I'd like to remove it.

**Comment by jaril** [comment]
Edgecase–I can't imagine a scenario where I'd rewind/fastforward to a message, but not want the editor to update accordingly. 

Removing it!
