### ISSUE TITLE
Improve timeline marker grouping

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1192]
console message grouping is weird. if thee are four message for one marker in the timeline, selecting the 2-4th console message do not light up the marker!

**Comment by karina-y** [comment]
notes:
when multiple breakpoints are too close together in time, we don't render them. as a side effect when you hit next at breakpoint 1 of 5 (for example), the next one doesn't get highlighted. 
this is applicable to:
- clicking on console breakpoint and looking at timeline
- clicking on breakpoint widget point, then step next within widget

check ln 82, Timeline/Message.js                 
check BreakPointTimeline.js

**Comment by karina-y** [comment]
`diff --git a/src/ui/components/Timeline/Message.js b/src/ui/components/Timeline/Message.js
index 923dd993..41a21a4f 100644
--- a/src/ui/components/Timeline/Message.js
+++ b/src/ui/components/Timeline/Message.js
@@ -104,7 +104,14 @@ class Message extends React.Component {
     const isHighlighted =
       highlightedMessageId == message.id || sameLocation(highlightedLocation, message.frame);
-    const isPauseLocation = message.executionPointTime === currentTime;
+    const pausedDistance = getPixelDistance({
+      to: message.executionPointTime,
+      from: currentTime,
+      overlayWidth,
+      zoom: zoomRegion,
+    });
+
+    const isPauseLocation = message.executionPointTime === currentTime || pausedDistance < 2.5;`

**Comment by karina-y** [comment]
edit: just remove the code that hides markers, via @jasonLaster
