### ISSUE TITLE
Right click to inspect element

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1207]
**Description**
It would be really nice to be able to right click in the viewer, select inspect element, and then jump to the elements panel and see the selected element.

**Comment by jonbell-lot23** [comment]
I'd chime in here from a design process standpoint:

This is one implementation, and I like it. But there may be some broader design explorations we want to do here as well. For example, someone talked about adding a comment to an object, which is a similar but different flow.

Ideally we'd make this part of a broader design exploration, but if we do push it quickly let's make sure to revisit.

**Comment by jonbell-lot23** [comment]
Following up: Jason and I talked about starting with two items in the right-click:

1. Inspect element
2. Add comment

**Comment by jasonLaster** [comment]
closing as this is documented in the viewer controls project
