### ISSUE TITLE
dark theme misses a few spots

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1229]
**Describe the bug**
in debug: the div that the collapsible panels live in remains white in dark theme
the console panel tabs' titles and icons remain black, making them difficult to see
in play: the comments section is white

**To Reproduce**
1. enable dark theme
2. collapse panels on left in debug mode
3. see white
4. switch to play mode
5. see white on right side in comments panel

**Expected behavior**
those divs should maintain the dark theme

**Screenshots**
debug mode:
![image](https://user-images.githubusercontent.com/19538307/102135516-f53edf00-3e0c-11eb-93b6-077792af5ede.png)

![image](https://user-images.githubusercontent.com/19538307/102135545-ff60dd80-3e0c-11eb-8f31-f52e616554a7.png)

![image](https://user-images.githubusercontent.com/19538307/102135814-5f578400-3e0d-11eb-9a11-97935f969961.png)

play mode:
![image](https://user-images.githubusercontent.com/19538307/102135580-0be53600-3e0d-11eb-816a-25704efa8273.png)

**Comment by jasonLaster** [comment]
dark theme is not a priority at the moment
