### ISSUE TITLE
[UX] Breakpoints timeline should look identical to main timeline

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1281]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/9154902/102554864-80c8b080-412a-11eb-91ba-13c39d79565c.png">

This is how the timeline looks in production, which causes confusion since it looks different from the main timeline. We have some ongoing discussions about where to put the hits label, but in the meantime I think we all agree this should have the same visual treatment. I consider this part of the Playability work.

**Comment by jaril** [comment]
Fixed by #1388.
