### ISSUE TITLE
[Flakey] sometimes the test gets stuck showing loading indicator

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1286]
I just got this after running: `node test/run.js --pattern object_preview-03.js`.  Three observations:

1. this is responsible for a good chunk of our test failures
2. i refreshed the tab when i saw this and it worked. so it is a timing related thing in the ui
3. this is intermittent, it could happen to any test with or without `--record-all`

<img width="917" alt="Screen Shot 2020-12-17 at 8 12 13 PM" src="https://user-images.githubusercontent.com/254562/102573870-41578100-40a4-11eb-9c0e-8ebef256f611.png">

**Comment by jasonLaster** [comment]
https://replay.io/view?id=1d91f1cd-056a-4567-bf6a-33cc4b3fa442&test=logpoint-02.js

**Comment by jasonLaster** [comment]
https://replay.io/view?id=49f55306-9a39-4dfe-a970-a1afcd3d3239&test=object_preview-05.js
^ this is the first test that we can actually debug

**Comment by jasonLaster** [comment]
After debugging this with @karina-y we found that `?loading=true` was never removed. Perhaps Replay never finished loading the sourcemap...

**Comment by loganfsmyth** [comment]
I'm going to guess that https://github.com/RecordReplay/backend/issues/659 and https://github.com/RecordReplay/devtools/pull/1318 have resolved this, we'll now show a full error if the session errors again, and with https://github.com/RecordReplay/devtools/pull/1318 fixed, we should never be in a place where we record the loading screen.
