### ISSUE TITLE
[flakey] inspector-05 waiting for debug view

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1287]
https://replay.io/view?id=9362141f-9669-4d73-8259-f6298dc7300b&test=inspector-05.js

this test failed because we didn't switch to debug view in time

**Comment by jasonLaster** [comment]
saw that again here

https://replay.io/view?id=9362141f-9669-4d73-8259-f6298dc7300b&test=inspector-05.js

**Comment by karina-y** [comment]
reopening as i'm seeing this on all my ci tests today:
https://github.com/RecordReplay/devtools/pull/1387/checks?check_run_id=1619492225
https://github.com/RecordReplay/devtools/pull/1389/checks?check_run_id=1619485233
https://github.com/RecordReplay/devtools/pull/1393/checks?check_run_id=1619674627

**Comment by loganfsmyth** [comment]
That first one has some JS errors in the log:
```
console.log: "Assertion failed!"
JavaScript error: http://localhost:8080/dist/main.js, line 258490: Error: Assertion failed!
console.log: "Finished resumeToLine in 3107ms"
console.log: "Starting stepOverToLine" 8
console.log: "Assertion failed!"
JavaScript error: http://localhost:8080/dist/main.js, line 258490: Error: Assertion failed!
console.log: "SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (2:0)"
```

that seems like the place to start.

**Comment by karina-y** [comment]
yeah i have an issue open for that one, seems to be throughout the app
https://github.com/RecordReplay/devtools/issues/1319
