### ISSUE TITLE
breakpoint widget in sidebar panel doesn't have a full border

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1292]
**Describe the bug**
when you're stopped at a breakpoint, it gets highlighted in the breakpoints panel by adding a purple border to the widget. the border however doesn't wrap all the way around the widget

**To Reproduce**
1. Go to any recording
2. add a console breakpoint
3. open the breakpoints panel in the sidebar panel
4. find your breakpoint

**Expected behavior**
border should wrap around entire widget

**Screenshots**
![image](https://user-images.githubusercontent.com/19538307/102660525-04d16700-4130-11eb-8214-2039674193de.png)

**Comment by karina-y** [comment]
this only happens on some of them, you can see here which have a border at the bottom and which don't
![image](https://user-images.githubusercontent.com/19538307/102661033-e7e96380-4130-11eb-819c-346c74e9097b.png)

**Comment by jasonLaster** [comment]
closing as i'd love to redesign the breakpoints panel UI

to be 

````
File
  - bp
  - bp 

File
  - bp
  - bp 

````
