### ISSUE TITLE
breakpoint widget in sidebar doesn't highlight new selection

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1299]
**Describe the bug**
when selecting a new breakpoint via the widget in the sidebar breakpoints panel, the newly selected widget doesn't inherit the old one's border

**To Reproduce**
1. Go to any recording
2. create some breakpoints
3. navigate to the sidebar > breakpoints panel
4. Switch between breakpoints by selecting different breakpoint widgets, you'll notice while the editor will navigate to that point, the widget that's highlighted doesn't change

**Expected behavior**
the widget you select gets a border and the old one loses its border

**Recording**
https://www.loom.com/share/7d806ea4463c4d1fa38539d0ae222106

**Comment by jaril** [comment]
Addressed by #1358.
