### ISSUE TITLE
Viewer breaks when user attempts to view deleted replay

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1304]
I tried to view a recording (https://replay.io/view?id=717bd218-c60d-4cea-8c15-eda81686ff06) and got a blank page with an error in the console: `TypeError: o is not a function`.  The line this corresponds to is this call in DevTools.js:

```
      setExpectedError({
        message: "You need to sign in to view this recording.",
        action: "sign-in",
      });
```

**Comment by karina-y** [comment]
to add more context, this happens when a replay has been deleted.
here is my console when trying to view a replay i've just deleted:
![image](https://user-images.githubusercontent.com/19538307/103320074-ee0cf900-49e8-11eb-82c9-eb0a054fa5aa.png)

**Comment by karina-y** [comment]
notes from @jasonLaster :

Thanks @karina I think you can do two things:
1. fix the foreign key issue in hasura
2. it looks like setExpectedError doesn't exists. Can we add that with connect
