### ISSUE TITLE
Clicking on dom element from inspector breadcrumbs doesn't bring element into view

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1306]
**Describe the bug**
when clicking on an element in the inspector breadcrumbs, the element gets highlighted but it isn't scrolled to.

**To Reproduce**
1. Go to any recording
2. click the elements tab in the toolbar panel
2. select a nested element
3. scroll down so the element and its parents are out of view
4. select an element from the breadcrumbs below the panel
5. notice we don't scroll to the element

**Expected behavior**
the element would be scrolled to just as in browser devtools

**Recording**
https://www.loom.com/share/9f3bae04ed9341bcbadc439efd9d374e

**Comment by jasonLaster** [comment]
closing as the elements panel is not a priority
