### ISSUE TITLE
Comments everywhere v1

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1309]
- Messages
- Element
- Pause
- Event

**Comment by jonbell-lot23** [comment]
I'm currently breaking items into smaller pieces, and here's how I'm seeing this one.

Priority #1 is clearly commenting on a pause event. We have this already.
We also have https://github.com/RecordReplay/devtools/issues/1405 that will allow us to right-click to add a comment to a pause event.

From there, I'd like to explore adding right clicks to everything else: Element, Event, Message. Stay tuned for that design.

**Comment by jasonLaster** [comment]
closing as we'll likely focus on nodes first when we get there
