### ISSUE TITLE
Scrolling the recording list on /view cuts off the bottom 1 1/4ish entries

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1317]
https://user-images.githubusercontent.com/132260/102826106-ddc79f00-4394-11eb-836d-91716fbb9057.mp4

You can see that the scrollbar only appears after a whole entry and a bit of the next is hidden.

**Comment by jasonLaster** [comment]
yep, the problem is that the container is the height of the window, but the headers take up about the height of one row.
