### ISSUE TITLE
[Timeline] Clicking breakpoints causes "Assertion Failed" errors

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1319]
**Description**
When clicking around timeline breakpoints two different errors appear in console

**STR:**
1. go to this recording http://localhost:8080/view?id=29b1f269-a3aa-40c3-aa62-71aa29dfaf69
2. open console and start clicking timeline breakpoints
3. after a few clicks the following errors will appear in the console
    - context.js:31 Uncaught (in promise) Error: Current thread has paused or resumed
    - utils.ts:53 Uncaught (in promise) Error: Assertion failed!

**Screenshots:**
note there is already an issue for the two first "Internal errors" but i'm posting the full screenshot anyway
![image](https://user-images.githubusercontent.com/19538307/102834378-b7abfa00-43a8-11eb-993a-7ae80145eee8.png)

this one is in webpack:///./src/devtools/client/debugger/src/utils/context.js
![image](https://user-images.githubusercontent.com/19538307/102834404-c7c3d980-43a8-11eb-93df-6fd3567527e7.png)

this one is in webpack:///./src/protocol/utils.ts
![image](https://user-images.githubusercontent.com/19538307/102834439-e32ee480-43a8-11eb-87ab-82fa184e6c2e.png)

in another test this error came up
![image](https://user-images.githubusercontent.com/19538307/102834611-63ede080-43a9-11eb-8ebd-a6fefb39f43b.png)

**Loom:**
https://www.loom.com/share/c152ac6cd2524555ab871ed58d7045f7

**Replay:**
i wasn't able to get all the errors on this replay but you can see some of them
https://replay.io/view?id=d3fa72a0-e3ca-4e89-ba99-ed948679cc3f

**Comment by karina-y** [comment]
these errors also appear on hovering in the gutter after setting a breakpoint in this recording:
http://localhost:8080/view?id=71a59f06-ce7e-458f-8331-6c3c1b551908

https://www.loom.com/share/922e3733a60b4de18a0b7f29f7d1d8f2

**Comment by karina-y** [comment]
also happens when rewinding/fastforwarding a breakpoint in the console

**Comment by jasonLaster** [comment]
The current thread has paused or resumed is expected.

**Comment by karina-y** [comment]
> The current thread has paused or resumed is expected.

@jasonLaster if that's the case should i close the issue?
