### ISSUE TITLE
[Debugger] undefined error on Tabs

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1322]
**Description:**
when dealing with the index file, i notice i now sometimes have two tabs open and when clicking one or the other, both get highlighted. when clicking on a different file's tab though, this error appears and the app breaks.
`Tabs.js:53 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`

**STR:**
these 3 tabs (2 being index, and the 3rd being a different file) were already open when i loaded the page. past that, here are the str
1. select index tab, notice both tabs are highlighted
2. try switching between the two index tabs, nothing happens
3. select the 3rd, non-index tab, see app break

**Screenshots:**
![image](https://user-images.githubusercontent.com/19538307/102917775-9eec2480-443a-11eb-960e-169460a049b2.png)

error is in webpack:///./src/devtools/client/debugger/src/components/Editor/Tabs.js
![image](https://user-images.githubusercontent.com/19538307/102917793-a7dcf600-443a-11eb-8bc4-918ecd3ef805.png)

**Loom:**
unable to fully reproduce in loom but you can see it happen immediately on refresh here
https://www.loom.com/share/dba7b79abcb648ee8c5efd52e9ccb75b

**Replay:**
https://replay.io/view?id=2bf2d299-6468-4766-ad7c-d65ba913954a

**Comment by karina-y** [comment]
another error related to the same line, this happens sometimes when selecting index from the source tree after closing its tab. this is after adding a temp fix of optional chaining off selectedSourceNode

![image](https://user-images.githubusercontent.com/19538307/102920442-a3670c00-443f-11eb-816f-7ba44e8bae38.png)

![image](https://user-images.githubusercontent.com/19538307/102920540-c396cb00-443f-11eb-9c34-43e47314237e.png)

**Comment by karina-y** [comment]
last related error:
when trying to ex out a tab these errors are produced: 
`tabs.js:135 Uncaught (in promise) TypeError: Cannot destructure property 'sourceId' of 'undefined' as it is undefined`
`tabs.js:125 Uncaught TypeError: Cannot read property 'sourceId' of undefined`

**Screenshots:**
![image](https://user-images.githubusercontent.com/19538307/102935355-d8348c80-445a-11eb-8f9f-f324ac68cfc1.png)

in the same tabs.js file as the other errors above
![image](https://user-images.githubusercontent.com/19538307/102935414-f26e6a80-445a-11eb-9aa6-3fb99d4fe4bc.png)

**Comment by jaril** [comment]
This appears to specifically affect sessions where the user opens up an HTML file with inline sources.

![image](https://user-images.githubusercontent.com/15959269/102945512-e8189480-448b-11eb-9111-7f8703f40b0c.png)

**Comment by jasonLaster** [comment]
I believe i fixed this this weekend
