### ISSUE TITLE
[Breakpoints] new feature to see method name in console doesn't show line or column number

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1335]
**Description:**
when you breakpoint at a method, the name of the method shows in the console but now the line number and column number don't show

**STR:**
1. go to this recording http://localhost:8080/view?id=98f31b06-f94e-4c24-9284-6449caa0cc01
2. navigate to app.js
3. breakpoint at line 18 and select the column breakpoint as well at i < 32
4. look in the console to see the method name but no line or column numbers

**Screenshots:**
![image](https://user-images.githubusercontent.com/19538307/102944179-e391b300-446e-11eb-85cf-4801dbe633d2.png)

**Loom:**
https://www.loom.com/share/c2d8217c3eb146f4a1e9de8e3003da95

**Comment by jasonLaster** [comment]
That's the desired behavior. the location info is on the right
