### ISSUE TITLE
Move the comment markers to the timeline progress bar

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1343]
Move the comments marker so they're occupying the same space as the console message markers on the progress bar.

This needs to be mocked up first.

**Comment by jasonLaster** [comment]
Jon, could you share some visuals for how this would look?

**Comment by jonbell-lot23** [comment]
I had original designs that had them on the bar itself, but I actually think putting them below is better now. Here's a mockup: 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/9154902/103244638-85ab2100-49c2-11eb-94be-f8d39a163626.png">

We're going to have tooltips on top, and the timeline itself can get cluttered. So this is the design point of view for now.

**Comment by jaril** [comment]
Looks like we're keeping the comments below. Closing this for now.
