### ISSUE TITLE
Add timeline marker tooltips

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1347]
It'd be nice to explore what adding a type icon + timestamp would do for the ui

<img width="307" alt="Screen Shot 2020-12-23 at 7 42 23 AM" src="https://user-images.githubusercontent.com/254562/103013732-7889c000-44f2-11eb-9436-73402db78688.png">

**Comment by jaril** [comment]
Latest iteration for the timeline marker tooltip:

![image](https://user-images.githubusercontent.com/15959269/103314443-1a2c7800-49f1-11eb-9e66-0a6813cfdfa7.png)

**Comment by jasonLaster** [comment]
@jonbell-lot23 how do you feel about this these days?

**Comment by jonbell-lot23** [comment]
I'd say this is the last gap in our "playability" improvements. Yesterday 100% of people understood the loading state, 100% understood that they were looking at a video, 100% understood the 1:1 relationship between events and the timeline. This is great!

But scrubbing and figuring out timestamps is still lacking, and causing confusion. I think this is still very important.

**Comment by jasonLaster** [comment]
Added it!
