### ISSUE TITLE
tooltip in gutter doesn't always work

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1354]
i'm not able to reproduce this in a recording but the gutter tooltip that shows how many hits you have doesn't always show up
i will update with a recording if i'm able to get it on video

![image](https://user-images.githubusercontent.com/19538307/103034035-d4ffd600-4518-11eb-89e7-b7bed0f779d7.png)

**Comment by jaril** [comment]
We recently added a fix for broken tooltips when hovering back onto the same line number (e.g. hover on 24, hover out from 24, hover back onto 24 => no tooltip) but this looks like it's different.

It might also be related to [Breakpoint shows no hits](https://github.com/RecordReplay/backend/issues/720). I'll be fixing that shortly so if it still persists let's look for STR for this again.
