### ISSUE TITLE
expanding different instance of same object in an evaluation expands all instances of that object's evaluations

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1355]
**Description:**
when you log the same objects in two different places (ie app.store and store), expanding one expands both and collapsing one collapses both.

**Steps to Reproduce:**
1. go to a recording
2. pause anywhere the store variable is available and log it as an evaluation
3. pause elsewhere and log app.store as an evaluation
4. try expanding one of those evaluations
5. notice both expand
6. try collapsing one of those evaluations
7. notice both collapse

**Expected Result:**
only the evaluation you are clicking on should expand/collapse

**Replay:**
https://replay.io/view?id=286bdff0-a274-4212-ad6e-5e973d3db042

**Comment by jasonLaster** [comment]
should be fixed now that we're not using the OI
