### ISSUE TITLE
[Debugger] Intermittent breakpoint rendering error

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#137]
This shows up occasionally when using the debugger.

<img width="406" alt="Screen Shot 2020-06-17 at 7 42 21 AM" src="https://user-images.githubusercontent.com/1062578/84931237-362c8580-b06e-11ea-849a-d9958104191a.png">

**Comment by jasonLaster** [comment]
I'll be fixing some code in this area soon. for the performance work.

**Comment by jasonLaster** [comment]
I think what you did recently to refresh codemirror when switching panels was great too
