### ISSUE TITLE
[UX] Hover UX alignment (Transcript + Timeline)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1372]
Hovering over an event in the Transcript should show a hover state that is echoed in the Timeline itself.

**Comment by jonbell-lot23** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/9154902/103182844-6acda380-4913-11eb-9173-6a227dc8eae2.png">

In our [Figma design doc](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=1665%3A1502), look for the page named "Exploration - Hover + Timeline"

Hover should be light blue (#F4F9FE) and selected state is our --secondary-accent purple.

**Comment by jasonLaster** [comment]
### playing the video should update the panels 
- [ ] viewer should update
- [ ] console pause line should update and stay in focus
- [ ] breakpoint widgets progress bar should update

### Hovering on a marker should update the other markers
- [ ] hovering on a breakpoint widget marker should update (console message, timeline marker, viewer)
- [ ] hovering on a timeline marker should update (console message, bp widget, viewer)
- [ ] hovering on a console message should update (bp widget, timeline marker, viewer)

### pausing on a marker should update the other markers...

**Comment by jasonLaster** [comment]
Closing as this issue is not a great fit and can go into the events planning ticket
