### ISSUE TITLE
Clicking in the timeline should not show the pauses pane

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1379]
We currently switch to the pauses pane every time the devtools pauses. This is true, even for pauses that won't show call stacks and variables, such as reaching the end of the recording or clicking somewhere in the timeline.

At a minimum we should not switch to the pauses pane unless we actually have that kind of pause data. I think `seek` has a `hasFrames` field which will help.

**Comment by jaril** [comment]
This is partially fixed by #1361. But good catch – we shouldn't be moving to the pause information panel if there's no frames in the first place. I'll file that in a separate PR.
