### ISSUE TITLE
Highlight other console messages

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1399]
When the user hovers on a console message, we want to highlight that message in the timeline AND the other messages that belong to that console.log.

I think the styling is similar to hovering on the gutter, where 

first we dim the timeline, 
then we highlight the console logs in standard blue
then we enlarge the message that is currently being hovered on

**Comment by jaril** [comment]
Now that #1386 landed, we can do this as a followup.

**Comment by jaril** [comment]
This was taken care of in #1480.
