### ISSUE TITLE
Cannot record a replay 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1450]
STR
1. open replay
2. log in
3. go to http://localhost:8080/index.html?id=fb0de5bb-02b6-4ca2-94b0-3c8c06ca4251

https://www.loom.com/share/e0aab61c3a4c49e7b2b82e5a1d444ccb?from_recorder=1

**Comment by jaril** [comment]
You're signed in on `https://replay.io/view` but not on `http://localhost:8080/`. Depending on which of those two you refreshed last, the browser toggles between the signed-in state where you can record. and the signed-out state where it tells you to sign in.

It's annoying, but it shouldn't affect regular usage for users who only have access to production. Closing this for now.
