### ISSUE TITLE
Timeline showing tons of events until I touch anything in the Events Filter, then they disappear

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1452]
Here's a screen capture of me reproducing this bug: https://share.descript.com/view/7j9DmyAyxTn

Notice that at first the timeline has lots of events, then when I click something in the Events Filter, they go away. Previously, clicking on the timeline again would make them come back, but I couldn't repro it in this recording.

Here's the Replay where I saw the error:
https://replay.io/view?id=51879b79-8827-4c44-8f71-c120771b0dcf

**Comment by jaril** [comment]
What was the source for all of the messages that were initially displayed in the console? Were they there because of a breakpoint? Or because of a checked event in the events filter?

**Comment by jonbell-lot23** [comment]
I hadn't set any breakpoints, this was just a default load of a new Replay.

**Comment by jaril** [comment]
@jonbell-lot23 Can you still reproduce this? I wasn't able to before and still can't now.

**Comment by jonbell-lot23** [comment]
Yup, here's a video: https://share.descript.com/view/JO5a2cwmuDy

Even if it's not the exact same issue, there's a similar result: a user clicks on a thing and the results are unexpected. I think we'll need to only swap out the timeline when we return results. That way changes are always understandable and predictable.

**Comment by jonbell-lot23** [comment]
Not seeing this anymore.
