### ISSUE TITLE
[UX] Viewer/devtools tab is sluggish

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1453]
When I click between Viewer and Devtools, I'm seeing a lag between clicking and the view rendering:
https://share.descript.com/view/BMo9WHaCYet

**Comment by jaril** [comment]
Copying the replay link [here](https://replay.io/view?id=51879b79-8827-4c44-8f71-c120771b0dcf). Not too surprised about the sluggishness given the number of markers displayed. 

Are you able to check which breakpoints you had in place to place that many markers? Though opening the same replay without any breakpoints feels snappy, I'd like to be able to stress test it with the same breakpoints.

**Comment by jonbell-lot23** [comment]
I think this is related to #1452 because I didn't do anything special to make it freak out with that many events. There were zero breakpoints set.

**Comment by jasonLaster** [comment]
closing as i can not reproduce. I think jaril's improvements to performance helped
