### ISSUE TITLE
If dispatch address is misconfigured when viewing a recording you get redirected to the recordings list

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#1465]
**Description:**
If devtools can't connect to the dispatcher when you are viewing a recording, it silently redirects you to the recordings list. 

**Steps to Reproduce:**
1. Visit https://replay.io/view?id=bbb1a8d2-3e34-4e17-bf5f-d67b0a252ae7&dispatch=ws://dispatch.replay.io

(note how I am overriding the dispatcher URL to use `ws` instead of `wss`, causing the issue)

**Expected Result:**
Some error is displayed saying that it can't connect to the dispatcher.

**Additional Context:**
I used Firefox for this, both the Repaly version and regular Firefox.

These messages are displayed in the JS console:

```
Assertion failed! instrument.js:109:45
Uncaught (in promise) DOMException: The operation is insecure. main.js:23
Uncaught (in promise) Error: Assertion failed!
    l utils.ts:53
    N apolloClient.ts:16
    i metadata.ts:89
    y metadata.ts:106
    t thunk.js:19
    c Redux
    nc App.js:69
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    F scheduler.production.min.js:17
    onmessage scheduler.production.min.js:14
    EventHandlerNonNull* scheduler.production.min.js:13
    Webpack 13
utils.ts:53:10
```

I believe the "operation is insecure" error is the problem because if you [disable that check in Firefox](https://discord.com/channels/779097926135054346/795692282053132299/796119652202971187) the page loads just fine.

Here's [a recording](https://replay.io/view?id=e10913d6-161a-4697-929b-1f455ee02d99), but it doesn't seem to exhibit the same behavior.

**Comment by jasonLaster** [comment]
@jazzdan would you be up for fixing this?

**Comment by jazzdan** [comment]
Yeah!
