### ISSUE TITLE
Outline view looks garbled

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1475]
**Description:**

While i was debugging framer, i noticed the outline view can look garbled if i select a location in the editor

**Steps to Reproduce:**

1. go to https://replay.io/view?id=0ec34c37-ba6a-4754-bc6a-1d0704a0566d
2. go to https://framer.com/s/vekter.4c7ea17/vendors~web.f8d0b867603bef2d49f7.js
3. go to line 55505

**Additional Context:**

Replay: https://replay.io/view?id=0ec34c37-ba6a-4754-bc6a-1d0704a0566d
Loom: https://www.loom.com/share/d84642fbf172436ea314d3cad6f51bbb

<img width="1605" alt="Screen Shot 2021-01-05 at 4 17 03 PM" src="https://user-images.githubusercontent.com/254562/103713546-794e3780-4f71-11eb-8d9e-14cac7bbda34.png">

**Comment by hbenl** [comment]
This is a bug in the Chrome rendering engine (the Outline view looks fine in Firefox and Safari), which would even crash the Chrome devtools when you try to look at the Outline view's markup. It is triggered by a nonsensical(?) `display: grid` on the outer `<ul>` of the Outline view.
