### ISSUE TITLE
hover-preview does not make it clear what value is being previewed

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1476]
**Description:**

<img width="584" alt="Screen Shot 2021-01-05 at 4 17 32 PM" src="https://user-images.githubusercontent.com/132260/103713836-1d37e300-4f72-11eb-8cfa-51005d6b472e.png">

**Steps to Reproduce:**
1. Open https://replay.io/view?id=3ec9a082-7e92-4fae-9f2d-cce8e0993983&test=stepping-05.js
2. Place a breakpoint on line 45 of socket.ts
3. Warp to any of those breakpoint hits
4. Hover over line 42

**Expected Result:**
I'd expect to see a preview for either `id` or `gNextMessageId`, but the whole line is highlighted and I can't tell if the preview value is the value of `id`, or `gNextMessageId`.

It is in fact the value of `gNextMessageId` which, given the whole-line highlight, is also the opposite of what I would have guessed since highlighting the whole line made me think it was showing the preview of the overall `const` declaration.

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
I think we should stop using the fancy ast selection technique and use the quick codemirror approach which should be the current fallback
