### ISSUE TITLE
Unable to access/connect to Replay

### ISSUE THREAD

**Issue by clsheppard09** [RecordReplay/devtools#1478]
Unable to connect to Replay. Tried using wifi and then hotspot. 

- Wifi connection was unstable and slow but was able to connect to replay earlier this morning on 01/05 and last night 01/04. However, when recordings started, the server crashed. 
- Hotspot connection was stable but unable to connect to replay.

Recording of replay screen trying to connect:
https://www.loom.com/share/76e5af418b1a484a8b5334f03cf4b4ee

**Comment by jasonLaster** [comment]
Thanks for filing. We'll need to speed up initial load
