### ISSUE TITLE
SET_PREVIEW can cause "sanitizeAction" to throw maximum call stack size exceeded

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1491]
I just noticed a few of these locally and wanted to file.

It looks like `SET_PREVIEW` passes in `.value.target` as  DOM element into the store, and sanitizing that leads to a datastructure that is cyclic, and `sanitizeAction` has no logic to detect cycles.

Here's the `path` from some time before it threw, which would have just kept growing:

    .value.target.offsetParent.offsetParent.offsetParent.CodeMirror.doc.children[0].lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines[0].parent.lines

We should probably add cycle detection to `sanitizeAction`, but also we shouldn't be putting DOM elements into the Redux store.

@jaril Any thoughts?

**Comment by loganfsmyth** [comment]
Short-term I guess we should add `SET_PREVIEW` to `excludedActions`?

**Comment by jasonLaster** [comment]
- agreed on cycle detection.
- we put elements into the store for positioning tooltips... but there's probably a better way to do that
- opening a pr for whitelisting :)

**Comment by jasonLaster** [comment]
fixed
