### ISSUE TITLE
Outline + Quick Open should highlight the line/function

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1505]
These two panels benefit from select location also highlighting the line, which i don't think we've supported in Replay

https://www.loom.com/share/7115a8c4dfde4949bf385684941601f4
https://www.loom.com/share/cbdbd5987d094fb5bff63e3a26acde30

**Comment by chujunlu** [comment]
For outline panel, how do you like the fading effect from Firefox?
https://www.loom.com/share/ae5a16813f3d44a884ba9f7f3cdd4e18

For quick open, Firefox has two different behaviors for mouse click and keyboard navigation.
If I click a function name in the dropdown menu, the first line of the selected function on editor is highlighted and then the highlight fades away. If I mouse up and down, the whole function on editor is highlighted in light blue, which then persists.
https://www.loom.com/share/a002570e4980484fa5928e76e8820859

I think it's ok to imitate what Firefox has.

**Comment by jasonLaster** [comment]
I haven't thought about this in awhile :) 

I think it's fine to start with the yellow one line fade and go from there.

**Comment by chujunlu** [comment]
Hey @jasonLaster, We have the [component](https://github.com/RecordReplay/devtools/blob/master/src/devtools/client/debugger/src/components/Editor/index.js#L417) that's highlighting line then fading, but it was commented out in this [PR](https://github.com/RecordReplay/devtools/commit/bdd4dfabe4cb56aec3bd95b6c12051aff61dda54#diff-339c69db6347fa8a8a45dd36263a500cf8dbb45bc960dd9684dc74b1c5558795R578). What was the consideration at that point?
