### ISSUE TITLE
Timeline comments are missing user details

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1508]
It looks like timeline comments are missing the user photo and name, which appear in the transcript and comments section

<img width="1440" alt="Screen Shot 2021-01-09 at 9 09 14 AM" src="https://user-images.githubusercontent.com/254562/104104039-6c279600-525a-11eb-8ef9-fa9d6a8e92f5.png">

**Comment by jaril** [comment]
The comment tooltip has been taken out with #1512.
