### ISSUE TITLE
[Timeline] Improve previews on slow connections

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#152]
When hovering over the timeline we start downloading a JPG of the graphics at the hovered point, for showing in the tooltip (and prior to that, the main graphics canvas itself).  When hovering through a section of the recording, many JPGs can be queued up to download.  On a slow connection, this is a lot of data, and the devtools will not really be usable again until everything downloads.  There are several ways this could be improved:

1. Limit the number of JPGs we are downloading at once, to cap the amount of data we ever have to download before the connection goes idle.
2. Produce lower quality or smaller dimension JPGs for use when we are just going to show it in the tooltip (this would require straightforward changes in the backend).  We would need to separately download higher quality images when pausing somewhere, but that won't be as big an issue as the hovering one.
3. Try to adjust image quality based on connection speed.  This would be difficult to get right and I'm hoping the first two items will be enough for now.

**Comment by jasonLaster** [comment]
Yep, agreed about 1 and 2.

**Comment by jasonLaster** [comment]
we can always file follow ups, such as downsizing tooltips
