### ISSUE TITLE
Loading async frames shouldn't block scope loading and other pause operations

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1532]
I've been seeing occasional instances where the scopes take ages to show up. Here's an example where I clicked to warp to a console message and the scopes just sat there empty: https://replay.io/view?id=ac746026-963d-4c29-a5b9-446d6a95b551

Looking at the recording a bit, it see seems to be slow because `loadAsyncParentFrames`: https://github.com/RecordReplay/devtools/blob/aab4d8cc650ba7e236dd8fe0c9da4773b5ac7195/src/devtools/client/debugger/src/actions/pause/fetchFrames.js#L21
call in `fetchFrames` is taking absolutely forever. In one case I saw it take 2 full minutes. The slowness in the backend is obviously a problem and I'll file a bug for that too.

Since async stack info isn't a blocker for interacting with a pause, in my opinion, it seems we should have that run in the background somewhere, so that the pause action can continue and load the scopes and such in the foreground. Otherwise we end up sitting at https://github.com/RecordReplay/devtools/blob/aab4d8cc650ba7e236dd8fe0c9da4773b5ac7195/src/devtools/client/debugger/src/actions/pause/paused.js#L28 and never get to https://github.com/RecordReplay/devtools/blob/aab4d8cc650ba7e236dd8fe0c9da4773b5ac7195/src/devtools/client/debugger/src/actions/pause/paused.js#L44

Thoughts?

**Comment by jasonLaster** [comment]
i think this was fixed
