### ISSUE TITLE
Screenshots disappear from a recording 6 minutes after it is saved, other items missing also

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1547]
**Description:**
When a recording is viewed immediately, everything looks correct. But after about 6 minutes, when the recording is re-opened, some items are missing. Screenshots are gone on both devtools and viewer tabs; events are gone on the viewer tab, possibly other items missing.

**Steps to Reproduce:**
1. Create recording, view immediately with expected result
2. Close replay
3. Wait 6 minutes, reopen recording
4. Screenshots, events, possibly other items missing from recording

**Expected Result:**
Recording to be retained with all items.
**Additional Context:**

* Screenshots:
Viewing recording immediately:
<img width="1440" alt="Screen Shot 2021-01-19 at 2 29 06 PM" src="https://user-images.githubusercontent.com/77456982/105186217-b7f5fd00-5aee-11eb-9557-356b8e044ae8.png">
Viewing after 6 minutes:
<img width="1247" alt="Screen Shot 2021-01-20 at 7 15 30 AM" src="https://user-images.githubusercontent.com/77456982/105186848-597d4e80-5aef-11eb-954a-0c380206001a.png">

* Video (Loom):
* Replay:
https://replay.io/view?id=35be30be-933c-43c7-b54a-05a5bfd91d2b

**Comment by jasonLaster** [comment]
Thanks for filing @lisahackett1978. It looks like you encountered an edge case, where you were viewing a recording created between saturday and wednesday, which we had to invalidate due to a backend bug.

If you go back, you should see the proper error message.
