### ISSUE TITLE
Icons are blank on first load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1549]
I'm not sure what the steps are to reproduce this, but it seems like when I come back to replay after a day or so, the icons are missing on the first load.

## Missing icons
<img width="1497" alt="Screen Shot 2021-01-20 at 10 09 27 AM" src="https://user-images.githubusercontent.com/254562/105216895-082d8900-5b08-11eb-9424-4ae7695a71e7.png">

## styles with the icon
<img width="420" alt="Screen Shot 2021-01-20 at 10 12 02 AM" src="https://user-images.githubusercontent.com/254562/105216885-049a0200-5b08-11eb-87df-d44b1dd3beaa.png">

## styles without the icon
<img width="462" alt="Screen Shot 2021-01-20 at 10 10 53 AM" src="https://user-images.githubusercontent.com/254562/105216890-0663c580-5b08-11eb-8e65-e65f647e61ba.png">

**Comment by jasonLaster** [comment]
I wonder if the fix might be a webpack config that builds a CSS file instead of creating the inline styles on the fly.

**Comment by hbenl** [comment]
I couldn't reproduce this but I think this would be a good chance to move to a standard webpack mechanism. See #1615.
