### ISSUE TITLE
Breakpoint Widget Markers get stuck in weird visual state

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1550]
**Description:**
The breakpoint widget markers don't look consistent between refreshes.

**Steps to Reproduce:**
Add a breakpoint to `app.js:9` in [this replay](https://replay.io/view?id=0343e714-9759-4797-bed7-a0d3cd3bbd44), make the editor as narrow as possible, and refresh the page.

**Expected Result:**
The markers should look consistent between refreshes. Instead, the marker shifts to the left and is cut off by the timeline's overflow.

**Additional Context:**

Demo: https://share.descript.com/view/Cbg4xMKApYR

![image](https://user-images.githubusercontent.com/15959269/105217646-23a58d80-5b22-11eb-9063-2a6511f119ba.png)

**Comment by jasonLaster** [comment]
does this still repro?

**Comment by jasonLaster** [comment]
closing as its not clear it repros. We can always re-open
