### ISSUE TITLE
On recordings page, the menu doesn't display correctly for the last recording

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1558]
**Description:**
When clicking on the little ellipsis to the right of a recording on the recordings page, a menu appears with 4 items. But the last recording in the list shows a truncated menu when you click on the ellipsis; three of the items are hidden. This also happens if there is only one recording in the list, because it is the last one.

**Steps to Reproduce:**
1. Open recordings page, have at least one recording in the list
2. Go to last recording in the list. Click on ellipsis to right of the recording to expand the menu
3. Menu items are hidden. They can still be accessed by scrolling, though.

**Expected Result:**
All menu items visible on last row
**Additional Context:**

* Screenshots:
Expected Result:
![Screen Shot 2021-01-22 at 8 39 08 AM](https://user-images.githubusercontent.com/77456982/105516196-d563cc00-5c92-11eb-9475-823d62738139.png)

Missing menu items on last row:
![Screen Shot 2021-01-22 at 8 14 11 AM](https://user-images.githubusercontent.com/77456982/105515655-2de69980-5c92-11eb-95af-cb4f4aeadc33.png)

* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Thanks for filing. 

I think we can fix this by using the PortalDropdown and some of the new viewport detection logic
