### ISSUE TITLE
Debugger actions can be hidden

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#1559]
**Description:**
If the left pane is narrow, the debugger actions (step into, step out) can be clipped without any indication they exist.

![image](https://user-images.githubusercontent.com/788456/105523507-4e632380-5c93-11eb-9b75-695b2452be5c.png)

**Steps to Reproduce:**
Shrink the left pane

**Expected Result:**

Some sort of visual indication that more buttons are there.

![image](https://user-images.githubusercontent.com/788456/105523596-6aff5b80-5c93-11eb-9b99-4c559fc36f69.png)

**Comment by jasonLaster** [comment]
Perhaps we want a minimum width that would include these buttons

**Comment by jasonLaster** [comment]
I think we're going to add a minimum to the sidebar
