### ISSUE TITLE
Number of hits does not show when hovering over a line number in pause mode

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1567]
**Description:**
When in the paused state in the breakpoints/debugging screen, the number of hits does not show. when hovering over a line number in the gutter.
This is an intermittent bug that clearly manifests in the replay, but can be difficult to reproduce otherwise.

**Steps to Reproduce:**
1. Go to breakpoints/debugging screen in Devtools
2. Click on a message in the console log to pause
3. Hover over a line number to see number of hits, the ellipsis remains, number of hits is never shown.
**Expected Result:**

**Additional Context:**

* Screenshots:
<img width="351" alt="Screen Shot 2021-01-23 at 10 24 31 AM" src="https://user-images.githubusercontent.com/77456982/105609244-3d82e280-5d65-11eb-810f-891e0ba9e161.png">

* Video (Loom):
* Replay:
https://replay.io/view?id=b13a688a-53eb-478b-a904-e8932136673e

**Comment by jasonLaster** [comment]
Thanks Lisa. This is a great example of how the UI at times stops being responsive.

We can look into the session on the backend and see if we can spot any slow analyses. 

One thing that could be helpful is if you could record the issue with Replay. If this is a client-side issue, then Replay is amazing for hunting down the issue :)

**Comment by bhackett1024** [comment]
This is actually another client side problem.  There's a replay above, but it is suffering from https://github.com/RecordReplay/backend/issues/1035 and is cut off.  I just landed a fix for that and will make a new recording.

**Comment by jasonLaster** [comment]
thanks @bhackett1024!

**Comment by bhackett1024** [comment]
OK here is an updated recording:

https://replay.io/view?id=aaffdb2b-796b-499c-b475-7fb6d2b5bb28
