### ISSUE TITLE
Problems selecting text while editing a logpoint

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1568]
**Description:**
While editing a logpoint, rendering issues appear to be causing copy and paste functions to copy and paste text other than the text that was selected.
This is an intermittent bug that clearly manifests in the replay, but can be difficult to reproduce otherwise.

**Steps to Reproduce:**
1. Go to breakpoints/debugging screen
2. Add logpoint
3. Edit logpoint
4. Under edit box, select text and copy. See that the selection is not correctly aligned with the text.
5. Try to paste that text, it is different from what was selected. Copying and pasting into the logpoint edit box is something a user is likely to do when adding code to a logpoint.

**Expected Result:**
Selected text copied
**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:
https://replay.io/view?id=47d08792-b711-4ce5-9718-81ffa6a62913

**Comment by jasonLaster** [comment]
It looks like this recording was also clipped. It's a shame because i was so excited to see what was going on :) 

@lisahackett1978 could you re-record it?

**Comment by bhackett1024** [comment]
Here is an updated recording:

https://replay.io/view?id=d343890c-864d-47c0-a0d6-58657b431094
