### ISSUE TITLE
Condense Login UI Flow to Improve Onboarding Experience

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1577]
**Description:**
Condense the login and sign up flow for a happier onboarding experience for users.

There are currently four screens to login, while users would benefit from a single "Sign Up or Login" page, where they can enter credentials and quickly get to the magic of Replay debugging!

**Steps to Reproduce:**
1. Start with a fresh replay installation
2. Open replay browser
3. Click Sign in Button (first screen)
4. Click Continue With Google button (second screen)
5. Enter Email (third screen)
6. Enter password (fourth screen)

**Expected Result:**
A single screen for logging in or signing up like users see on other websites
**Additional Context:**

* Screenshots:
![newloginscreen](https://user-images.githubusercontent.com/77456982/105761636-9fcc1680-5f10-11eb-94ca-bac886fecb43.jpg)

* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Thanks for the suggestion!

One logistical point, because we're using 3rd party login providers (google, github, oauth, others in the future), we have less control over the login flow. In this case, we're delegating to Google for their account, password, etc...

Onto the suggestion for condensing the flow. I'd love to hear what @jonbell-lot23 thinks, but my hunch is there is probably a UX reason most sites now have a clear signin or login call to action and flow.

**Comment by lisahackett1978** [comment]
I can look around for a good example website that handles google login elegantly in one screen. Maybe it's not possible? But until I look around, I won't know... :)
Eliminating just the first two screens would also be good.
This suggestion came out of a larger analysis. I documented the number of user actions it takes to onboard and reach the cool stuff in Replay (12):
![replay_onboarding_flow_01_25_2021](https://user-images.githubusercontent.com/77456982/105774604-afecf180-5f22-11eb-833a-027f5995cd11.jpg)

**Comment by jonbell-lot23** [comment]
Hello, and nice to meet you @lisahackett1978 ! (Xennial generation high five, I was born in 1979 :)

I'm buried in research right now, but wanted to poke my head up to say:

1. Love the idea of simplifying the flow
2. So if we can provide username/login in a single screen (considering the third party auth stuff) that'd be ideal

More later when I get a bit more un-buried. Thanks!

**Comment by lisahackett1978** [comment]
Hi Jon! Gen X high five right back at you! I hear you're in New Zealand. What a wonderful country. You are lucky, especially with the freedom to move around and work with users right now. :)
I've seen your extensive reports and videos from working with users and love your recommendations to improve the debugger. It looks like so much fun, too, to see their first impressions of Replay! Definitely looking forward to your future reports. :)

**Comment by jasonLaster** [comment]
Thanks Jon!  And thanks Lisa for sharing the onboarding analysis!

**Comment by lisahackett1978** [comment]
Thanks, Jason! It sounds like this change to the login flow is relevant but not a priority until we get to the closed beta phase. Would we be able to leave bugs like this open for the closed beta, with a label of some kind instead of closing them? Just some way to ensure they don't get lost or forgotten.

**Comment by jasonLaster** [comment]
Good point.

I went ahead and created a project
<https://github.com/RecordReplay/devtools/issues/1617> for optimizing the
onboarding flow and added it to our planning board. As a policy, we only
keep issues open that we plan on getting to within the next 2-4 weeks. This
helps us keep the queue actionable.

**Comment by jasonLaster** [comment]
fyi, i think linear's method (link <https://linear.app/method/introduction>)
has a good set of practices.

**Comment by jonbell-lot23** [comment]
And just wanted to chime in on the closed issue point above: I've been wondering about this too. When I take the time to write out an issue, it can feel jarring when it's closed without any resolution other than "let's do it later." I'm concerned it'll get lost, meaning eventually we might just end up re-writing the whole thing.

So maybe a "postponed" tag or something, and then when we count issues we search for "all open issues not tagged postponed?"

**Comment by jonbell-lot23** [comment]
From Linear's notes:
"You don't need to save every feature request or piece of feedback. Important ones will resurface and low priority ones will never get fixed. A more focused backlog makes it easier and faster to plan cycles, and ensures the work will actually get done."

This is a reasonable philosophy and I've seen companies land on either side of this debate. For me, the tradeoffs to this idea is "multiple discussions on the same idea, multiplied times a growing company, multiplied times months." As a person who believes in documentation, async communication, and scaling well, this is a very fragile methodology. It works alright for a small team, but makes scaling a lot harder. The ROI also seems poor, because it's not that hard to run a query that ignores a tag.

That said, we have more important fish to fry. Happy to debate this in the future instead :)

**Comment by bhackett1024** [comment]
I think we should only close issues when they're either fixed, not going to get fixed, or are replaced by another issue.  We can  use labels and project boards to manage the distinction between issues that will be fixed soon and issues that won't be.

**Comment by jasonLaster** [comment]
I'm hesitant to discuss process too much over text, but this feels a bit of a discussion around what we need now verse what we'll need later.

### Devtools vs Backend

We have a different process for managing issues on the frontend and backend. The devtools repo currently has ~50 issues, ideally it would be less. The backend currently has ~250. 

This helps Jaril and I quickly go through the issues and plan accordingly.  Sure we could filter with `-label`, but in practice this rarely happens. For instance we rarely subtract away projects, although we probably should.

### Is this process jarring

I can see how it could be. I think documenting the process publicly and labeling should alleviate that should alleviate that :)

**Comment by jasonLaster** [comment]
Thinking about this a bit more, I'd like to take the initiative to write up our process for product planning and user feedback.

For instance, I'm not sure how discoverable our [notion](https://www.notion.so/replayio/Planning-321adf7736444d398b71d2e378e53381) product planning and feedback section is.  The notion section replaced canny and in many ways is a much better place to discuss user feedback, feature requests that we are not actively working on.
