### ISSUE TITLE
Add comment should be more obvious

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1589]
At the moment, it can be difficult to find the "add comment" button in the timeline. It would be nice if there were a more obvious button.

Perhaps a button in the bottom of the transcript / comments panel when the viewer is shown?
Perhaps a button overlaying the viewer in the bottom right?

...

**Comment by jasonLaster** [comment]
This might be useful as well https://github.com/RecordReplay/devtools/issues/1405

**Comment by jaril** [comment]
Adding initial mockups from Figma:
![image](https://user-images.githubusercontent.com/15959269/106095394-bd140700-6101-11eb-99cd-90b29d795ca0.png)
