### ISSUE TITLE
Events: Mouse clicks should be selected by default

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1597]
**Description:**
We should show mouse clicks in the console so that there is a close to 1-1 relationship with the transcript.

**Comment by jaril** [comment]
Some considerations here before we move forward with it.

First, the transcript "mouse clicks" are really `mousedown` events that are tracked by the recorder and don't have corresponding frames (i.e. clicking on it won't correspond to a line of code). 

That means they're different from the event breakpoint `mousedown` events. That rules out just checking the `mousedown` event breakpoint for the user.

Instead, we'll have to manually insert the transcript `mousedown` events into the console output. That introduces non-native, frameless console message rows into the console output. 

If that was the direction we wanted to take it, we just need to mock up how the transcript events should be displayed in the console. Should the content be 1:1 with the transcript (e.g. "[click icon] Mouse click")?  Should they blend in with regular console messages, or stand out?

**Comment by jonbell-lot23** [comment]
That is very thoughtful, thank you!

With this information, I think it's clear we have work to do on the mental model. The Viewer mental model is solid: "a dot is a mouse click." But in devtools it's pretty confusing, for several of the reasons you mention.

I am concerned that simply adding the mouse clicks will actually mess up the mental model, for the reasons Jaril mentioned above. Whereas a redesigned Events Log (and other UX ideas I have) will more appropriately address these issues.

So let's hold off on now, but not close this issue just yet. I want to keep it around because this Devtools mental model issue is turning into my highest UX priority based on what the research is telling me.

**Comment by jasonLaster** [comment]
Totally agree.

Strawman proposal:

1. lets show mousedown event listeners by default, it's similar, but the differences _are_ explainable... 
2. when the user views the transcript in dev-mode, lets update the timeline to reflect that


This is a strawman for a reason... It has benefits / trade-offs. I don't feel strongly :)

**Comment by jonbell-lot23** [comment]
Sounds good. Let me make sure we're on the same page.

* Replay has 10 mouse clicks
* Viewer shows 10 dots in the timeline (and nothing else)
* Devtools shows 10 dots in the timeline. They're different, but it's not that hard to explain how.
* Those 10 dots don't preclude other dots from appearing, of course. You can go into the Events Filter and add other events, or remove mouse events.
* Short term, that's enough to close this issue.
* Longer term, we know we're going to improve the Events Filter experience.

**Comment by jasonLaster** [comment]
Hmm, I think we're close but not quite there

* Replay has 10 mouse clicks
* When the transcript view is visible there are 10 click sin the transcript view and 10 dots in the timeline 
* When the console view is visible there are 7 dots in the timeline and 7 messages in the console. There is a 1-1 relationship btw timeline markers and console messages.

The one interesting wrinkle is, what should we show in the timeline if the user is in DEV mode and is viewing the transcript? My proposal is, show the 10 mouse clicks so we're one to one. This is controversial of course and i'm not sure how i feel.


I feel 80% confident we should ofcourse by default show "mouse down" in the console. That's easy. 
I feel 60% confident we should show the t10 mouse clicks in the timeline if the user is viewing the transcript.

**Comment by jonbell-lot23** [comment]
Ah ha! I like that a lot. Let's do both of those things. This means dev's timeline dots will change based on whether or not you're in transcript or console.
