### ISSUE TITLE
Events is missing

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1599]
**Description:**
I went to use one of my favorite things in Replay, Events, and it is gone from the UI today!

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
<img width="1343" alt="Screen Shot 2021-01-27 at 9 51 22 AM" src="https://user-images.githubusercontent.com/77456982/106024730-4fc29080-6085-11eb-84f9-5e01c6b18964.png">

* Video (Loom):
* Replay:

**Comment by jaril** [comment]
Looks like it was being pushed past the window. Should be a quick fix!

**Comment by lisahackett1978** [comment]
Thanks Jaril! Events are back!
