### ISSUE TITLE
Test a real world app like firebugs

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1603]
**Description:**

It would be great if our e2e tests could test real world apps, which would provide more interesting test cases than our examples.

I imagine that we can have a build tool that git clones a project, checkouts out a commit, and runs the build step. This can be done once, and then after that the test script just needs to start and stop the development mode. 

The alternative is to just record the prod version, but i think it is good to have a locally reproducible build.

**Example**

We could write a test that tests going to firebugs, adding a breakpoint on App.js#render and confirms that the breakpoint is set correctly. We could also test `filters.js#update` function which has that weird case with the local variable and the case statement.

**Comment by hbenl** [comment]
Another problem with reproducibility is that it's not enough for the recorded code to be the same, the network requests that it makes also have to get the same responses. Here's a crazy idea: we could create a "recording" of the network requests during a test and then "replay" those requests when we rerun the test...

**Comment by hbenl** [comment]
https://github.com/assaf/node-replay

**Comment by jasonLaster** [comment]
After discussing this a bit more, i think we can probably just create a couple sample react, typescript, vue apps...

**Comment by jasonLaster** [comment]
closing this as we're improving our test suite in other places
