### ISSUE TITLE
Events dropdown is missing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1606]
**Description:**

<img width="1418" alt="Screen Shot 2021-01-27 at 10 23 58 AM" src="https://user-images.githubusercontent.com/254562/106036187-d4afa900-6089-11eb-9c4c-ebf55c8103b1.png">

**Comment by jasonLaster** [comment]
probably related to the width 100%

**Comment by jaril** [comment]
This should have been taken care of with #1599 which looks to have been deployed ~5 mins ago. Do you have the replay link?
