### ISSUE TITLE
Consider defaulting to devtools for new users

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1607]
**Description:**
As a new user, it was difficult to find the devtools screen with all the exciting Replay tools. It is buried several clicks deep after the recording comes up.
Consider showing the devtools Pause Information screen right after recording. This would get developers to that "ah-ha moment" sooner.
The tradeoff is that code showing up after recording could be confusing/intimidating for non-technical users, so it depends on who our target market is.

**Steps to Reproduce:**
1. Start with a fresh replay installation
2. Load Recording

**Expected Result:**

**Additional Context:**
![replay_debugging_ui_flowcurrent](https://user-images.githubusercontent.com/77456982/106042614-8656d600-609a-11eb-9329-31cd5c16ebde.jpg)
![replay_debugging_ui_flow_proposed](https://user-images.githubusercontent.com/77456982/106042834-cf0e8f00-609a-11eb-9e74-d919eb083fe5.jpg)

* Screenshots:

* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Thanks Lisa!


If I hear you correctly, the primary motivation was that new users might miss the "DEVTOOLS" button and not have the aha? I think that's a valid onboarding concern. It would be really sad if a new user tried replay and never saw the magical new debugger!

This feels like an onboarding concern that we can field when we're in the closed beta, but curious what @jonbell-lot23 thinks as well.

**Comment by lisahackett1978** [comment]
Yes, we don't want people to miss it. Another reason is so developers will be excited about what comes up after they make their first recording. After I made my first recording, I felt mildly confused about the viewer that appeared after.
But when I saw the Pause Information screen in devtools I felt excited and wanted to click around and explore!

**Comment by jonbell-lot23** [comment]
Thanks, Lisa!

An earlier version of the product did drop people straight into devtools and we discovered a few things:

1. It was an overwhelming marketing screenshot for non-technical folks
2. It was an overwhelming first experience for non-technical folks
3. It didn't highlight user events + comments well enough for anyone

So this model was born, which hopes to give the best of both worlds. 100% of people see the replay and any associated comments without being too overwhelmed ... then people who click into the devtools mode should hopefully feel right at home and be excited by the deeper features there.

As Jason mentioned, we're hoping to straddle this line better with onboarding features, marketing pages on the home page, and some other ideas. That should give us our cake and let us eat it too -- making sure the initial experience is welcoming for non-technical people while still being powerful and clear for technical folks.

**Comment by lisahackett1978** [comment]
Hi Jon! Thank you for sharing the backstory. I had a feeling this probably wasn't the first time showing devtools by default was proposed. :) There are so many considerations when it comes to usability of a product, and which use cases should be prioritized in the UI. There are always tradeoffs.

What I see in our research, is that developers are the ones excited about Replay and they will be our users first and the ones to ask for Replay to become a part of the development cycle at their organization. Non-technical users don't have much to do in Replay right now unless they are already collaborating with a developer. They aren't excited about the viewer. It is not unique.

This is just my opinion, to be considered with all the others, and I defer to your excellent judgement and holistic view of the project. As always, I look forward to your future reports! :)

**Comment by jonbell-lot23** [comment]
Totally agree! Although I'd say it like this:

* Average user: not interested in the viewer
* Developer: pretty excited
* Anyone who has ever filed a bug: often pretty excited

I love that you're talking about tradeoffs, because it's my favourite word in design :) We definitely want to make sure developers can get to the good stuff, and it's definitely possible to err on the side of hiding the good stuff away. Would love to chat with you more as we think through the onboarding stuff, because these tradeoffs are very important to get right!
