### ISSUE TITLE
Cannot reply to another author's comment

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1609]
**Description:**
I just tried replying to one of Brian's comments and did not see the dropdown. Perhaps we want a more obvious way to reply as well

**Steps to Reproduce:**

1. go to https://replay.io/view?id=d1b0ada5-7d39-447c-bd6e-5c5b2e073168
2. hover on a comment

**Expected Result:**

click on the comment dropdown

**Comment by jaril** [comment]
@jasonLaster This appears to be working for me. Can you check again?

![image](https://user-images.githubusercontent.com/15959269/106632526-d7a80f00-654b-11eb-8bfb-3e39360a6b1a.png)

**Comment by jasonLaster** [comment]
works for us
