### ISSUE TITLE
Consider adding feedback button

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1611]
I think it would be really nice to have a way to give direct feedback when replaying a recording isn't working for whatever reason.  We can see failures and slow things in the backend but it can be hard to connect the dots and see how users are being impacted.  If users could click a button and give a thumbs up / thumbs down on the session and/or leave a short message, it would be really helpful for identifying the most important frontend and backend problems.  It's also great to give users an easy way to have a voice: we want replay to work really well all the time, and it will be hard to get there without help from our users.

**Comment by jasonLaster** [comment]
Agreed.

We're re-adding intercom for customer engagements. It would be nice to use intercom's built in feedback tools such as [reactions](https://www.intercom.com/help/en/articles/415-get-feedback-at-scale-using-message-reactions).

**Comment by jonbell-lot23** [comment]
I agree on all points. Helpful for us for troubleshooting, and a great look from a PR/UX standpoint. Would love this.

**Comment by jasonLaster** [comment]
I think the settings design has a good support section.

**Comment by jonbell-lot23** [comment]
Dusting off and adding to my current list of items.

**Comment by jonbell-lot23** [comment]
@jaril and @jasonLaster I think the gold star answer for this is to put a textarea into our whoops screen asking people to describe the issue that led them to the whoops screen. How hard is this to do?

And in the short term, we can provide a link to discord and maybe even a bugs@replay.io email address. That's easier.

**Comment by bhackett1024** [comment]
This isn't about the whoops screen.  That is covered by https://github.com/RecordReplay/devtools/issues/2170 --- we shouldn't need the user to tell us things are broken when the devtools have broken completely.  The devtools can be buggy, the backend can be slow, etc. and it's hard to know how those things actually impact users unless they tell us.

**Comment by jonbell-lot23** [comment]
Thanks for the reference to #2170. I totally agree we need more datapoints, and I totally agree we shouldn't wait for the user to tell us when things are broken. We absolutely need a way to send proactive feedback.

That said, very few people are going to go digging around for a feedback button. So I'm all for it, and I want to drive people to it ... but I want to amplify the idea. I want to catch them right when they're frustrated and seeing issues, and the whoops screen is one of many places we can do that.

**Comment by jonbell-lot23** [comment]
Hey @jasonLaster I think it's a good idea to have a feedback email address. Can you set up feedback@replay.io in our google admin, then I'll slap it up on our existing support page here?

![image](https://user-images.githubusercontent.com/9154902/114325636-483f5d80-9b85-11eb-94e0-98ee07ae43aa.png)

**Comment by jasonLaster** [comment]
added ***@***.*** as a google group

**Comment by jonbell-lot23** [comment]
Closed because we added a feedback email, but still keeping an eye on other places to put this functionality as the UI evolves.
