### ISSUE TITLE
Consider having a way to indicate there are outstanding messages

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1613]
When using replay I keep finding myself going into the console and evaluating `outstanding()` to see if the frontend has heard back from the backend on everything it's sent and been able to update fully based on the result.  It might be nice to have a subtle spinner or other indicator that the frontend has outstanding requests with the backend.

**Comment by jasonLaster** [comment]
That's an interesting idea and something I'd definitely want to experiment with.

I wonder if this is something we want to show everyone. Perhaps. Or something we want to design for a debug mode... 

CC @jonbell-lot23

**Comment by jonbell-lot23** [comment]
Oh, I didn't realise this was a state you could get into. In my view, we absolutely want this for everyone.

It's like using an SFTP client or email. Most of the time things are ok, but being able to get into the raw transcript/status messages sometimes helps understand if there's a problem. I'd suspect we'd benefit from a similar model. Show the spinner, and hovering or clicking on the spinner can possibly provide more data.

**Comment by jasonLaster** [comment]
Replay has gotten fast enough that this no longer feels important. I would consider it a bug if requests showed up long enough to appear in a panel

**Comment by jonbell-lot23** [comment]
I would like to keep an eye on this, though -- bugs (especially ones related to connectivity/perf) will happen, so it's important to have a standard UX pattern of:

* It'll probably work
* Don't overload people with spinners (assume success)
* When things are slow, explain why (spinner)
* Give them the option to learn more and cancel

That doesn't mean we need to re-open this bug, but it's something to consider in all features. Assume success, but not to the extent that messaging is opaque when things do inevitably fail.

**Comment by jasonLaster** [comment]
Absolutely.
