### ISSUE TITLE
Consider highlighting new breakpoint messages

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1614]
When adding a breakpoint it's kind of subtle when new messages appear in the console.  Highlighting the new messages with a flash of yellow or something seems like it would both help new users understand how breakpoints in replay work, and help more experienced users identify the new messages added by a breakpoint, especially when the console is cluttered with other messages.

**Comment by jasonLaster** [comment]
Yep! This is something we're discussing.

CC @jonbell-lot23

**Comment by jonbell-lot23** [comment]
A lot of things have changed on this front -- how are we feeling these days?

**Comment by jasonLaster** [comment]
I think we can close this
