### ISSUE TITLE
Devtools stay interactive after socket has closed

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1627]
In some cases I've seen a message from the devtools after the remote connection has closed due to inactivity, but when I looked at a tab I left open overnight it still seemed responsive, though nothing requiring a remote connection worked and I could tell the backend session had closed long ago.

**Comment by jasonLaster** [comment]
It looks like we are handling one of two socket events

- onSocketClose - we should 
- onSocketError - we assumed error implied inactivity, which feels wrong

https://github.com/RecordReplay/devtools/blob/master/src/protocol/socket.ts#L115-L130
