### ISSUE TITLE
Hovering over an object to see properties shows unexpected text

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1638]
**Description:**
In the breakpoints/debugging screen, hovering over an object to see its properties shows unexpected text.

The replay shows this bug happening in two places, when hovering over a blank spot and also when hovering over src.

I added comments in the two places it happens! Nice! I am loving this feature. It was not working this week (for me).

**Steps to Reproduce:**
Go to breakpoints/debugging screen
Step through code, hover mouse over an object to see properties
A list of properties comes up, but it is from a nearby object, not the one you are hovering over

**Expected Result:**
See properties from selected object
**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:
https://replay.io/view?id=637e9451-723b-44a9-a1f2-1546bdc4645b

**Comment by jasonLaster** [comment]
Thanks @lisahackett1978 

I just left a comment in the replay, but the short answer is i think this is fixed. Could you retest?

**Comment by lisahackett1978** [comment]
Yes, this is fixed, but a regression came up which I filed in #1648
