### ISSUE TITLE
Let editor/element progress bars get to 100% before disappearing

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1647]
Follow up fix for #1634.

>Remember when we talked about the feeling of satisfaction when a bar animates all the way to the end? I want to make sure these panels don't load 40% then snap into place. I want it to show 40%, race to 100%, then load. If we do it fast enough it should only add .1 second but still provide that feeling of completion.

**Comment by jasonLaster** [comment]
closing as the elements panel is not a priority
