### ISSUE TITLE
While debugging, keywords and constants show hover text

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1648]
**Description:**
In the breakpoints/debugging screen, hovering over almost any text on the page says "undefined"

The replay shows this bug happening in several places

**Steps to Reproduce:**
Go to breakpoints/debugging screen
Step through code, hover mouse over almost any text
Keywords and constants have hover text "undefined"

**Expected Result:**
Keywords and constants should not have any hover text, variables and property accesses should have hover text
**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:
https://replay.io/view?id=772d2b40-5336-42fe-8d79-a9fd314eeae7

**Comment by jasonLaster** [comment]
Thanks @lisahackett1978. I left some comments with a proposed fix

**Comment by lisahackett1978** [comment]
Thanks, Jason! Loving the comments. :) I replied.

**Comment by jasonLaster** [comment]
note: look into gutter hovering, widget hovering
