### ISSUE TITLE
[UX] Project Left Wing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1655]
https://www.notion.so/replayio/Project-Left-Wing-73985fd200c445b3a6e55a54ec0182df

![image](https://user-images.githubusercontent.com/9154902/106662478-4e561280-6607-11eb-9ec5-0ba3eafe3f66.png)

This project combines moving the transcript from right to left, adding comment pins, and some other UX polish.

**Comment by jonbell-lot23** [comment]
https://www.notion.so/replayio/Project-Left-Wing-73985fd200c445b3a6e55a54ec0182df

**Comment by jasonLaster** [comment]
closing in favor of #1734
