### ISSUE TITLE
Session closed screen flashes while signing in

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1657]
This happens to me when clicking either of the sign-in buttons to log into the app.

https://user-images.githubusercontent.com/1062578/106398736-f08cb500-63d1-11eb-8f7c-1ae5cd060adf.mov

**Comment by jasonLaster** [comment]
This probably related to my latest change for #1627

**Comment by jaril** [comment]
Added more info on #1663.
