### ISSUE TITLE
Visiting local replay webserver signs me out

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1658]
STR

1. Open replay, sign in
2. Start devtools web server
3. Visit a recording, e.g. http://localhost:8080/index.html?id=c6700f16-2e9b-4c8b-bdd2-0c2aa0b82332
4. Notice that I'm now signed out of replay, and can't make a recording

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/ui/utils/browser.ts b/src/ui/utils/browser.ts
index 35291ab7..cca39227 100644
--- a/src/ui/utils/browser.ts
+++ b/src/ui/utils/browser.ts
@@ -1,5 +1,12 @@
+import { isDevelopment } from "./environment";
+
 export function setUserInBrowserPrefs(user: { sub: string } | null) {
+  if (isDevelopment()) {
+    return;
+  }
+
   const _user = user === null ? "" : user;
+
   window.dispatchEvent(
     new window.CustomEvent("WebChannelMessageToChrome", {
       detail: JSON.stringify({
```

prevents the browser from logging out, but the bigger question is why we started redirecting to replay.io post login. My conspiracy theory is that this started after the TokenManager landed.

**Comment by jasonLaster** [comment]
https://www.loom.com/share/fe83621900bc4b368a89d0452af02e39

**Comment by jasonLaster** [comment]
weird after coming back to master it seems to work... although i think being explicit about `returnTo` would help

https://auth0.com/docs/logout/redirect-users-after-logout

**Comment by hbenl** [comment]
Actually I think everything is working correctly, this is just a case of wrong expectations: `replay.io` and `localhost:8080` are 2 different applications from Auth0's (and generally the browser security's) point of view and therefore you have to login to each of them separately. When I switch between them, their auth state is remembered correctly (but separately).

**Comment by jasonLaster** [comment]
interesting. it's hard for me to remember all the states between browser / local vs prod. I'll keep a look out for this though

**Comment by jasonLaster** [comment]
This is happening because localhost:8080 and replay.io/view are different domains. The way to login in dev is to go to `localhost:8080` and click the signin button. 

Closing as there isn't anything actionable at the moment.
