### ISSUE TITLE
[UX] Playhead should start at the first meaningful paint

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1671]
Currently the Replay loads on the final frame. This causes confusion, so we should do one of two things.

1. If there's a comment, we should jump to the first one: https://github.com/RecordReplay/devtools/issues/1670
2. If there's no comment, we should jump to 2 seconds in

Q: Why not start at the end? A: It's causing confusion.
Q: Why not start right at the beginning? A: I want to show the timeline mostly grey but with a little bit of blue. Two seconds in allows for that visual effect.
Q: What about the black screen effect? A: Ideally we'd remove the black screen. But even if it's still there, I'd like to test this. I hypothesise that the play button on the bottom left is enough for people to grok it.

**Comment by jasonLaster** [comment]
I think we should start the video at the [first meaningful paint](https://web.dev/first-meaningful-paint/) or something approximating it.

@bhackett1024 @loganfsmyth are there easy ways to do this, basically looking at the screenshots and getting the first non black one.

**Comment by bhackett1024** [comment]
The client should do this by looking at the contents of the screenshots it gets from the backend.

**Comment by jonbell-lot23** [comment]
That would be great, thanks! 

One caveat, though. If we have a comment, I propose we jump straight there. (As seen in #1670)

**Comment by jasonLaster** [comment]
fair enough
