### ISSUE TITLE
[UX] Timeline line shouldn't dim on hover

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1672]
STR:

1. Load a Replay
2. Mouse over an event in the timeline

Expected:

1. The event you're hovering on should turn one colour
2. Related events should turn a different colour
3. Unrelated events should dim
4. The horizontal line itself should stay the same colour

Actual:

Right now 1-3 is happening. But the horizontal line is dimming, which is visually jarring. It should never dim.

**Comment by jaril** [comment]
Bumping this as it wasn't addressed in the recently merged #1741 PR.

**Comment by jonbell-lot23** [comment]
I love this change so much, thank you!
