### ISSUE TITLE
A friendlier whoops :smile:

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1675]
**Description:**
At the moment we use the same Whoops for a lot of different messages, it'd be nice to do a quick audit and facelift

<img width="1317" alt="Screen Shot 2021-02-02 at 2 23 05 PM" src="https://user-images.githubusercontent.com/254562/106670688-3bd5cd80-6562-11eb-9b18-d3aa5fb49ffd.png">

**Comment by jasonLaster** [comment]
@jonbell-lot23 would you enjoy taking a stab at this low hanging fruit?

**Comment by jonbell-lot23** [comment]
I'll take it, it'll just be lower in my queue.

**Comment by jasonLaster** [comment]
we landed a nicer oops
