### ISSUE TITLE
How should "Add Comment" look when there is a draft comment

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1694]
**Description:**

How do we want to handle the big add comment button when either

a) a user is adding a new comment
b) a user is editing an existing comment

Also, should we tidy up the save cancel buttons? not a big deal...

**Comment by jaril** [comment]
We now handle A by disabling visually and functionally disabling the button. B state is inapplicable as we've disabled comment editing. 

Closing this and moving the conversation to #1774.
