### ISSUE TITLE
Breakpoint tooltip shows 4 different values (3 hits, 0 hits, 20 hits, 0 hits)

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1701]
**Description:**
When I hover on the gutter the tooltip flashes several different values

**STR:**
1. go to http://localhost:8080/view?id=0f64a8ae-27df-47ec-9ec3-e57ffcbf7f7e
2. set a breakpoint in cursor.ts#639

**Expected Result:**

I see loading and then 0 hits, which is what the panel eventually shows

**Additional Context:**

* Screenshots:
* Video (Loom): https://www.loom.com/share/7fe03864e07a48a6bc91f9622ad0f0e0
* Replay: https://replay.io/view?id=d9215cc2-6591-4d96-88f7-fe4024a5c0e1

**Comment by hbenl** [comment]
The reason is that the analysis results are streamed to the devtools in multiple events, but each event is treated as the final result by devtools (note how the tooltip shows 3 / 0 / 20 / 0 hits and the console shows 23 = 3+0+20+0 messages).

**Comment by jasonLaster** [comment]
@hbenl nice find!
