### ISSUE TITLE
Breakpoint panel shows 0 hits, but many console messages are shown

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1702]
**Description:**
When I add a breakpoint, the panel shows 0 hits, but many console messages were shown.

1. go to http://localhost:8080/view?id=0f64a8ae-27df-47ec-9ec3-e57ffcbf7f7e
2. set a breakpoint in cursor.ts#639

**Expected Result:**

I see a breakpoint timeline with many hits, one per console message.

**Additional Context:**

* Screenshots:
* Video (Loom): https://www.loom.com/share/7fe03864e07a48a6bc91f9622ad0f0e0
* Replay: https://replay.io/view?id=d9215cc2-6591-4d96-88f7-fe4024a5c0e1

<img width="1498" alt="Screen Shot 2021-02-04 at 8 16 01 AM" src="https://user-images.githubusercontent.com/254562/106921820-3fcc3180-66c1-11eb-98fa-108aa271e8fb.png">

**Comment by hbenl** [comment]
The reason for this is the same as for #1701, both components get their data from the same selector.
