### ISSUE TITLE
Loading V2

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1705]
- [ ] indexing loading UIs
- [x]  uploading screen

**Comment by jonbell-lot23** [comment]
Loading UX documentation on Notion: https://www.notion.so/replayio/Loading-UX-89ec80c7d09e461e8500516638deec33

**Comment by jonbell-lot23** [comment]
This should be complete from a UX standpoint now.

[Notion link](https://www.notion.so/replayio/Loading-UX-89ec80c7d09e461e8500516638deec33)
And in [Figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=2313%3A2510) there's a page called Loading UX
