### ISSUE TITLE
Analyze node picker performance

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1708]
**Description:**
Looking at the performance of [GetAllBoundingClientRects](http://admin.replay.io/performance/GetAllBoundingClientRects) the node picker should be must faster. My guess is that sending one giant packet is too slow. Lets investigate though and find a way to speed it up.

**Comment by hbenl** [comment]
My impression the last time I looked at this was that the frontend is fast when `DOM.getAllBoundingClientRects` is fast, but RecordReplay/backend#1205 seemed to stall it. Now that this is fixed, the node picker usually works well for me, but I did see occasional failures of `DOM.getAllBoundingClientRects`.

**Comment by jasonLaster** [comment]
closing as the elements panel is not a priority
