### ISSUE TITLE
Use system-UI as main typeface, with Inter for special places

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1724]

**Comment by jonbell-lot23** [comment]
I like Inter! Let's document this decision for posterity so we're all on the same page.

**Comment by jaril** [comment]
This was drawn up without much consideration at the time, just to get the issue in. Unfortunately that had the effect of making it look like a prescription rather than a suggestion.

Taking a step back, the idea is to switch to a font (any font) that wasn't designed for print first then adapted for low-DPI screens in the 1990s _(looking at you, Arial)_.

We can be opinionated with Inter/San Francisco. Or we can do `system-ui` so the font always blends in with whatever OS the user happens to be on.

**Comment by jonbell-lot23** [comment]
I'm personally a fan of the system-ui approach carrying most of the UI (it's also really good for bandwidth considerations) and then Inter for key brand moments.
