### ISSUE TITLE
Devtools stuck on uploading screen

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1736]
I just created a recording 69e1d874-a565-4429-bafa-7278dc07270b.  After stopping recording it transitioned to the uploading screen below, and stayed there.  I looked up the recording ID  in the console and opened it in a separate tab, where it loaded immediately.  Several minutes later the first tab is still stuck on the uploading screen.

One thing that may have affected behavior is that I was running with RECORD_REPLAY_AUTHENTICATION_DISABLED set to work around https://github.com/RecordReplay/devtools/issues/1658

<img width="1358" alt="Screen Shot 2021-02-08 at 12 32 19 PM" src="https://user-images.githubusercontent.com/1062578/107271712-d8d4b280-6a09-11eb-9db7-eee9af838e0c.png">

**Comment by jasonLaster** [comment]
I've noticed this before too... It would be nice to get a good log of client/server events after the fact

**Comment by jasonLaster** [comment]
Just saw a recording stuck on the loading screen

https://replay.io/view?id=26f6b60d-319d-490a-9e64-d9ff20dda0de
sessionId: 6e1c2c70-33b5-454c-bb47-97b2634de801/8fe52d0e-55ea-48d7-9be7-ef4d0c2b0c2e
controller: 6e1c2c70-33b5-454c-bb47-97b2634de801

<img width="721" alt="Screen Shot 2021-02-09 at 12 52 16 PM" src="https://user-images.githubusercontent.com/254562/107426921-aee8c200-6ad5-11eb-9502-1d24dbf62b0a.png">

**Comment by jasonLaster** [comment]
I'll try and find some more of these

**Comment by loganfsmyth** [comment]
I think between https://github.com/RecordReplay/gecko-dev/pull/309 and https://github.com/RecordReplay/gecko-dev/pull/307, this should be in a pretty good place now.

If an error happens, you'll go to the unstable page, and if things succeed, you'll get the recording view. If you're on `loading=true` it should be exclusively time waiting for responses from our API.
