### ISSUE TITLE
[UX] Shouldn't see two of my face in the top nav

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1738]
<img width="147" alt="image" src="https://user-images.githubusercontent.com/9154902/107279303-bdc27b00-6abb-11eb-8ae1-c63d48839cd6.png">

When I'm logged in via two browsers, I see two of my face. The left avatar area should only show other people signed in, not me.

**Comment by jaril** [comment]
This was intentional as a set up for multiple sessions. @jasonLaster can explain more.

**Comment by jasonLaster** [comment]
So... 

You will see this if you have multiple tabs open at the same time... If it is silly we can adjust it now, but in the future, it might be nice to do something like this so you can see where you're paused in each tab...

**Comment by jonbell-lot23** [comment]
Got it. Yeah, in the meantime I'm getting comments during testing. Would be nice to toggle off for now.
