### ISSUE TITLE
Add a library skeleton viewer

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1754]
**Description:**

We currently use a purple triangle loader from lottie for loading the library viewer. We should remove it because its big and also inconsistent. It'd be better to use a library skeleton shimmer thing

Lottie was a fun experiment, but at the moment we only use it for the purple triangle loader, which could probably go away if recordings in the dashboard loaded quicker or had a skeleton view.

<img width="1080" alt="Screen Shot 2021-02-10 at 2 33 10 PM" src="https://user-images.githubusercontent.com/254562/107581812-774d4900-6bad-11eb-8409-353b1a2f5268.png">

**Comment by hbenl** [comment]
@jaril This is straightforward, but it needs an alternative to the animation in `src/image/lottie/forward.json`, so I'll pass this to you.

**Comment by jonbell-lot23** [comment]
In the meantime, let's remove the animation but not add a skeleton loader quite yet. We'll get there, but I'd like to split the tickets to prioritise them.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/9154902/116471582-f575dd80-a8c8-11eb-8dc5-1478144bfd87.png">
