### ISSUE TITLE
Wrong screenshot is shown

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#1769]
When the mouse hovers over the timeline or the console, the screenshot for the hovered point is shown and when the mouse leaves the timeline or console the screenshot should revert to the one for the current pause. But sometimes this doesn't happen and the screenshot for the last hovered point remains.
I have a hunch this happens when the mouse leaves the timeline or console before the screenshot download finishes (I think I saw the screenshot for the current pause flash shortly before being replaced by the one for the last hovered point).
To reproduce this, open a recording and quickly move the mouse to a console message and then out of the console. Note that this only seems to happen the first time you hover over a message, for all subsequent hovers over the same message, the screenshot is correctly reverted.

**Comment by jasonLaster** [comment]
Good find @hbenl. 

I've noticed this too. Lets record it!

**Comment by hbenl** [comment]
https://replay.io/view?id=5e536de5-56ac-44c0-8f71-b362a0c9f072
