### ISSUE TITLE
icons are black

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1786]
<img width="367" alt="Screen Shot 2021-02-11 at 1 09 35 PM" src="https://user-images.githubusercontent.com/254562/107699106-6f9faa00-6c6a-11eb-93b4-61dd94664980.png">

**Comment by jaril** [comment]
Fixed: https://github.com/RecordReplay/devtools/commit/16c1826c25b6f2e61e9097b0b38fa8d98510d4cb
