### ISSUE TITLE
Some icons are missing on chrome

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1810]
Node Picker, rewind, pause icons. It looks fine in brave...

<img width="755" alt="Screen Shot 2021-02-12 at 6 08 14 PM" src="https://user-images.githubusercontent.com/254562/107838937-62171c80-6d5d-11eb-87dd-3a9f360fae28.png">

<img width="1851" alt="Screen Shot 2021-02-12 at 6 09 23 PM" src="https://user-images.githubusercontent.com/254562/107838951-75c28300-6d5d-11eb-9196-5b3cf854ef5e.png">

**Comment by jasonLaster** [comment]
<img width="410" alt="Screen Shot 2021-02-14 at 7 30 11 PM" src="https://user-images.githubusercontent.com/254562/107902425-4184c900-6efb-11eb-9ed7-3b1dd9d018ed.png">

**Comment by hbenl** [comment]
I tried Chromium/Linux/locahost, Chromium/Linux/replay.io, Chrome/Linux/replay.io, Chrome/W10/replay.io, Chrome/MacOS/replay.io and Chrome/MacOS/localhost but couldn't reproduce this.
