### ISSUE TITLE
[UX] Timestamps should be on the right of each event

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1811]
The timestamps went missing here ->

<img width="354" alt="image" src="https://user-images.githubusercontent.com/9154902/107844929-8a297d00-6e3c-11eb-9c41-4fb93079145b.png">

They should still be on the side, roughly like this (but this is an old screenshot) ->

<img width="581" alt="image" src="https://user-images.githubusercontent.com/9154902/107844935-99102f80-6e3c-11eb-957b-627b304491be.png">

**Comment by jasonLaster** [comment]
oops, i probably went too fast (https://github.com/RecordReplay/devtools/pull/1809)

**Comment by jasonLaster** [comment]
Let's get this into figma with all the states (rendered, hovered, selected) and discuss.  I'd like to see what looks right when we have different types of events with descriptions...

For example a comment in code with the filename + location...

**Comment by jonbell-lot23** [comment]
Closed this out, timestamps are removed
