### ISSUE TITLE
[Playwright] Breakpoint messages do not appear

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1814]
While working on a new experimental playwright test I ran into a problem where if we simulate a click on the gutter to add a breakpoint with no hover first, the hovering logic that runs afterwards will clear the logpoint ID for the line and the breakpoint messages do not get added to the console.  See the recording below, made using playwright.  Unfortunately there are some problems figuring out the problem from the replay, I'll file separate issues for those.

https://replay.io/view?id=36dc99a2-9bf0-4314-b743-0ccda8c549c8

**Comment by bhackett1024** [comment]
https://github.com/RecordReplay/devtools/issues/1815 covers some of the many problems I ran into while looking into this.

**Comment by jasonLaster** [comment]
@bhackett1024 what priority do you think this should be?

**Comment by bhackett1024** [comment]
While I've only seen this with playwright, it certainly seems like it could be triggered by a user and lead to weird behavior.  It's also a problem with how the devtools are using logpoint IDs which could manifest in other ways, so it would be nice if it was fixed soon.
