### ISSUE TITLE
The source editor panel's overflow menu disappeared

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#1839]
![Screenshot_2021-02-16_14-51-40](https://user-images.githubusercontent.com/16060807/108071892-8bd68900-7066-11eb-8ecc-f65e013e1bf9.png)

**Comment by jasonLaster** [comment]
Hmm, i think we replaced it with scroll. try panning left and right. or shift scroll.

**Comment by hbenl** [comment]
OK, that works. I don't like the discoverability (or lack thereof) though. We could improve this by adding some sort of visual cue that the tabs are overflowing:
![Screenshot_2021-02-17_10-25-40](https://user-images.githubusercontent.com/16060807/108183701-a5311100-710a-11eb-85be-4f523dfc483c.png)
