### ISSUE TITLE
Comments: cannot delete replies to a comment

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1841]
**Description:**
The option to delete a comment exists only on the top level comment. Replies should also have a delete option. It would make sense users can only delete their own replies, which is how it appears to currently work on top level comments.

**Steps to Reproduce:**
1. Open a recording
2. Enter a comment, save
3. Reply to that comment by clicking directly on it, save
4. Try to delete your reply

**Expected Result:**
Should the user find an error in their reply, they should have the option to delete it without removing the entire comment thread
**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Yep. we're working on edit/delete replies

**Comment by jaril** [comment]
Just submitted #1847 which ought to do the trick!
