### ISSUE TITLE
Sentry: Add filter so that assertions show the more specific line

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1844]
Sentry offers really nice inbound filters so that it is possible to categorize assertions by where the assert came from.

https://docs.sentry.io/product/data-management-settings/filtering/

We're doing this in the backend and could benefit from this on the frontend as well.

**Comment by loganfsmyth** [comment]
It's "Stack Trace Rules" in the docs that you want. https://docs.sentry.io/platforms/javascript/data-management/event-grouping/stack-trace-rules/

In `backend` I added these so that the `assert` and `ThrowError` functions don't show up as the location of the error, but rather their callsites.
```
# Separate application and node_modules files
stack.abs_path:/*.js +app
stack.abs_path:**/node_modules/** -app

# Exclude assertion and ThrowError frames so the callsites of these are what
# show to distinguish the errors.
stack.function:assert ^-app -app ^-group
stack.function:Object.assert ^-app -app ^-group
stack.function:ThrowError ^-app -app ^-group
stack.function:Object.ThrowError ^-app -app ^-group
```

**Comment by jasonLaster** [comment]
Added one filter

```
stack.function:assert ^-app -app ^-group

```

https://sentry.io/settings/replay/projects/devtools/issue-grouping/
