### ISSUE TITLE
[UX] Moebio replay is unresponsive

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1857]
STR:

1. Go here: https://replay.io/view?id=df5708ca-4e0c-4bb1-81e5-ed77b34d0e10
2. Try to add a break point or click around

On my computer, it's almost completely unresponsive for minutes:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/9154902/108305003-05f54200-720e-11eb-86f6-43e5ef6f01b8.png">

I also got it into a state where a breakpoint said something like 10000/10000 steps.

**Comment by jasonLaster** [comment]
Oh nice, I think this is the video game use case with tons of hits :)

**Comment by hbenl** [comment]
Replaying the recording becomes slow as soon as you add a logpoint that gets hit thousands of times. This is not specific to this recording, displaying thousands of logpoint hits becomes a performance issue with any recording.

**Comment by jonbell-lot23** [comment]
Absolutely. Because this is a flaw in the user experience, we need to create a task so this doesn't happen.

We have another issue as part of Project Focus around making sure we message these situations better, so I'll close this issue.
