### ISSUE TITLE
[UX] Clicks do nothing while loading

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1862]
A customer filed this Replay, where clicking on the UI didn't do anything, which feels broken:
https://replay.io/view?id=f00443af-576f-45aa-b9f8-9eab980182db

Proposal:
We should probably dim this icon until the pane has loaded, to explain that it's not ready yet.

**Comment by jasonLaster** [comment]
@jonbell-lot23 Do you think this is fixed by the HUD loading indicator?

**Comment by jonbell-lot23** [comment]
Yup
