### ISSUE TITLE
Clicking in the breakpoint timeline navigated to www.<functionname>.com 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1867]
**Description:**
When i was testing with oliver, we found a bug where he accidently jumped to www.enodeURlyadayada.com which was prtty amazing. somewhere we must have a `window.location =` where we don't want too :)

**Comment by hbenl** [comment]
I couldn't reproduce this. The closest I could get was if a preview tooltip containing a URL shows up and covers the breakpoint timeline (e.g. https://replay.io/view?id=89bbc8bf-68fa-4711-8a7a-ed980563a544) - if the tooltip showed up a split second before the click, it could be overlooked. However, in this case the URL would be opened in a new tab and from the description it seems that's not what was happening.

**Comment by jasonLaster** [comment]
lets close this and re-open it if we see it again
