### ISSUE TITLE
Project GUTE-2

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1877]
GUTE-1 has finished, but we should polish the rough edges

- Commenting UI
- Sibling Markers
- Left sidebar

-----

Ready for Jaril:
- [x] Remove grey future treatment
- [ ] Move to 8px grid #1883
- [x] Inline replies #1887
- [x] Add HUD #1885
- [ ] System font #1724 

To discuss:
- [ ] Should be able to click button to reply #1881 (This may get less important when we get inline replies)
- [ ] Update comment markers in the timeline
- [ ] Consider removing sibling markers when hovering in the breakpoint timeline

**Comment by jonbell-lot23** [comment]
The first one was GUTE-1, in preparation for a few releases. Renaming to GUTE-2, happy to name back if we hate this name.
