### ISSUE TITLE
[FrameTimeline] does not include inner `for` loops

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#188]
I'll get an STR for this soon, but the gist of it is that a function like `foo` does not include inner FOR loops. It's possible that this is also true for `IF` and lexical scope

```js
function foo() {
  console.log('hi')
  for (const i = 0; i < 10; i++) {
    console.log(i)
  }
  console.log('bye')
}
```

A more specialized example would be:

```js
function foo() {
  console.log('hi')
  const list = [1, 2, 3]
  list.forEach(i => console.log(i))
  console.log('bye')
}
```

This feature is not the most critical, but little things like this are the kind of touches that would jump out to devs who want to quickly see complex / branchy functions.

**Comment by bhackett1024** [comment]
This is supposed to work.

**Comment by jasonLaster** [comment]
Here's an example where this fails.

STR:
1. go to https://webreplay.io/view?id=efa3f4bb-ef22-4f67-a117-d1cfe923091b
2. add a breakpoint in `breakpointAtLocation.js:56`
3. rewind

NOTE: this is an original file, but the generated file looks similar
