### ISSUE TITLE
Consider highlighting active line in transcripts and comments

### ISSUE THREAD

**Issue by lisahackett1978** [RecordReplay/devtools#1893]
**Description:**
When working with multiple comments/events in a recording, it is difficult to see which one is currently active. The purple indicator can be too subtle in some cases.

The attached recording shows a use case where I clicked an event toward the bottom of the list, then added a comment.

After clicking the event, the mouse pointer makes a long and confusing journey over other things that mouseover and appear active on its way to the "Add comment" button. 

While the purple indicator is always there, the mouseovers are more prominent, and make me wonder if my selection is still selected.

It would be easy to tell where the user is in a complex recording by highlighting the event/comment currently selected:

---

![Screen Shot 2021-02-23 at 8 40 47 AM](https://user-images.githubusercontent.com/77456982/108869231-3b09e780-75b4-11eb-8827-1a4a156693b0.png)

![Screen Shot 2021-02-23 at 8 13 40 AM](https://user-images.githubusercontent.com/77456982/108869326-507f1180-75b4-11eb-8551-9c0d4fb650fc.png)

**Replay:** https://replay.io/view?id=728c2902-9dda-4866-a609-aaa205299860

**Comment by jasonLaster** [comment]
CC @jonbell-lot23 is this covered in #1913 or #1877?

**Comment by jonbell-lot23** [comment]
Yup -- the design for this calls for a background colour, which addresses this issue as well as some others. It's not live yet, but is coming in GUTE-2 or GUTE-3.

**Comment by jasonLaster** [comment]
Thanks Lisa. closing as this is covered in other tasks

**Comment by jonbell-lot23** [comment]
Please keep it up, Lisa! :)

**Comment by jonbell-lot23** [comment]
Please keep it up, Lisa! :)
