### ISSUE TITLE
Hovering over a click event in transcript panel doesn't show marker

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#1898]
When in dev mode *and* showing the console panel, hovering over a click event in the transcript panel doesn't show the corresponding marker in the timeline.
I think the problem is [this condition](https://github.com/RecordReplay/devtools/blob/35637c26bc4bb4e3eae544209e7c7183a2debebb/src/ui/components/Timeline/index.tsx#L262).

**Comment by jasonLaster** [comment]
@hbenl could you record a replay of this so we can check? 😉

**Comment by hbenl** [comment]
In the meantime, a timestamp that is shown on hover has been added to the timeline, reducing the impact of this issue.
Here's the recording: 
https://replay.io/view?id=5e36d1dc-70fa-4565-b180-8adedc782ba4
