### ISSUE TITLE
[UX] Second attempt at a HUD

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1928]
We did a previous design that has some big issues. Now let's do another one.

**Comment by jasonLaster** [comment]
Jon, please tell me how you really feel!

**Comment by jasonLaster** [comment]
I took a stab at a video loading state and ended up moving the hud to the timeline

https://github.com/RecordReplay/devtools/pull/1930

nothing final, but perhaps better...

**Comment by jonbell-lot23** [comment]
In Figma I made a new page called "Timeline timestamps, hover, and loading". In it, I worked through several items we have floating around:

* How to show loading state for the sluggish player
* How to show timestamps all the time
* How to show a timestamp on the item you're currently mousing over (or the event attached to it on the left)
* General spacing/padding/margins/etc for the timeline

Here's a high level view, go to Figma to see more details.

![image](https://user-images.githubusercontent.com/9154902/109442813-00191f80-7a9e-11eb-8642-dc0a4a49d25e.png)

The next step for this task (after discussion) is for me to document the exact dimensions. I kept everything on a grid, but I have a little documentation to do before @jaril dives in.

**Comment by jasonLaster** [comment]
I like it. Event the comment text, which i wasn't sure about a couple of weeks ago

**Comment by jonbell-lot23** [comment]
Great! And the comment text is an easy toggle. The overall model works even without it.

**Comment by jonbell-lot23** [comment]
Alright, the graphic above has been modified ever-so-slightly.

* Don't show comment text in timeline
* Don't use purple text colour

Here are the final visuals, and they're also in Figma.

![1-loading](https://user-images.githubusercontent.com/9154902/109547988-f391d700-7b30-11eb-8705-a878c5118451.png)
![2-still buffering](https://user-images.githubusercontent.com/9154902/109547995-f4c30400-7b30-11eb-84c0-5c23d4ffa1db.png)
![3-tracking](https://user-images.githubusercontent.com/9154902/109547998-f55b9a80-7b30-11eb-81f1-10647190ccce.png)
![4-paused](https://user-images.githubusercontent.com/9154902/109548001-f55b9a80-7b30-11eb-8b8d-b0578cd46dde.png)
![5-tracking after pause](https://user-images.githubusercontent.com/9154902/109548002-f5f43100-7b30-11eb-8f67-9844e2716527.png)
![6-hover comment](https://user-images.githubusercontent.com/9154902/109548003-f5f43100-7b30-11eb-8dc5-72b6f49818fc.png)
![7-click comment](https://user-images.githubusercontent.com/9154902/109548004-f68cc780-7b30-11eb-9716-0119b9d3c375.png)
