### ISSUE TITLE
[UX] Project Focus UX Ticket

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1944]
- [ ] One minute limitation: https://github.com/RecordReplay/devtools/issues/1939
- [ ] Dim out panes that aren't ready: https://github.com/RecordReplay/devtools/issues/1938

**Comment by jasonLaster** [comment]
closing as a dupe of #1905

**Comment by jonbell-lot23** [comment]
I don't think of it as a dupe because I'm tracking UX only tasks as a project on my own board, whereas the master project has lots of things outside UX.

**Comment by jonbell-lot23** [comment]
On second thought, it only has 6 items and 4 of them require me to do stuff. I thought the ticket was way longer.
