### ISSUE TITLE
Show a separate timed out screen

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1951]
**Description:**
At the moment, we do a poor job of differentiating error screens in Replay. I'd like to have a separate timed out screen so that users know this is expected and they can just refresh

<img width="1414" alt="Screen Shot 2021-03-02 at 2 56 41 PM" src="https://user-images.githubusercontent.com/254562/109726397-8baab300-7b67-11eb-81f4-7028775e322c.png">

**Comment by jonbell-lot23** [comment]
Here's the proposed design:

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/9154902/109746167-d268dd80-7c39-11eb-9d2e-08873887337f.png">

And here's your SVG:


<svg width="100" height="101" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M50 100.551C77.2461 100.551 99.8047 77.9434 99.8047 50.7461C99.8047 23.5 77.1973 0.941406 49.9512 0.941406C22.7539 0.941406 0.195312 23.5 0.195312 50.7461C0.195312 77.9434 22.8027 100.551 50 100.551ZM50 92.25C26.9531 92.25 8.54492 73.793 8.54492 50.7461C8.54492 27.6992 26.9043 9.24219 49.9512 9.24219C72.998 9.24219 91.4551 27.6992 91.5039 50.7461C91.5527 73.793 73.0469 92.25 50 92.25ZM28.1738 52.9922C28.1738 65.1992 37.8906 75.0137 49.9512 75.0137C62.0117 75.0137 71.7285 65.1992 71.7285 53.1387C71.7285 51.332 70.166 49.8672 68.3594 49.8672C66.5527 49.8672 64.9902 51.332 64.9902 53.1387C64.9902 61.5371 58.3008 68.2754 49.9512 68.2754C41.6016 68.2754 34.9121 61.5371 34.9121 53.1387C34.9121 44.7891 41.6016 38.1484 49.9512 38.1484C50.5859 38.1484 51.2695 38.1484 51.7578 38.2461L46.9727 42.9336C46.3867 43.5195 46.0449 44.3008 46.0449 45.1797C46.0449 46.8887 47.4121 48.2559 49.1211 48.2559C49.9512 48.2559 50.7324 47.8652 51.2695 47.3281L60.7422 37.8555C61.9629 36.7324 61.8652 34.5352 60.7422 33.3633L51.3672 23.793C50.8301 23.207 50 22.8164 49.1211 22.8164C47.3633 22.8164 46.0449 24.2324 46.0449 25.9414C46.0449 26.8203 46.3867 27.6016 46.9238 28.1875L50.3906 31.7031C50 31.6543 49.4629 31.6055 49.0234 31.6055C38.0371 31.6055 28.1738 41.0293 28.1738 52.9922Z" fill="black"/>
</svg>
