### ISSUE TITLE
Improve comment formatting

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1972]
**Description:**

At the moment, comments are shown as an array of lines. We should format it ideally with markdown or something similar. Emojis would be nice too 😉

**Comment by jasonLaster** [comment]
https://github.com/remarkjs/react-markdown

**Comment by ryanjduffy** [comment]
Part 2: Emoji support

https://github.com/RecordReplay/devtools/pull/2017

**Comment by jasonLaster** [comment]
I think this just needs some polish 🎨
