### ISSUE TITLE
Clicking on the "A quick refresh should do the trick" page should refresh it

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#1987]
I just got this page and tried clicking on the
<img width="131" alt="Screen Shot 2021-03-04 at 3 13 14 PM" src="https://user-images.githubusercontent.com/132260/110043374-250ace00-7cfc-11eb-86e9-09595fa989fa.png"> icon for some reason expecting it to refresh since it looks like a browser refresh button. Seems like really we could have the whole page refresh on click though.

**Comment by jasonLaster** [comment]
haha - @jaril you called it
