### ISSUE TITLE
[UX] Comment UX font size and spacing

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1988]
- [x] Please change the header text from 12px to 14px
- [x] Please change the padding from 8px on the left and right to 24px
- [x] General spacing/grouping that we talked about on the phone

<img width="632" alt="image" src="https://user-images.githubusercontent.com/9154902/110046735-745f0600-7db1-11eb-9256-462e731f30cf.png">

**Comment by jasonLaster** [comment]
@jonbell-lot23 we actually changed the header from 14 to 12 today because it felt off with short comments. could you test it out and report back?

**Comment by jonbell-lot23** [comment]
Just had a session with Jaril, and we have a new design we like more. Lots of padding and spacing tweaks that will help comments feel grouped and make the space feel better overall

**Comment by jasonLaster** [comment]
Great! or should i say GUTE
