### ISSUE TITLE
createSession occasionally fails

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1990]
**Description:**

https://replay.io/view?id=f55a0e6d-8d8f-4b61-82a3-1c69490da2be&test=node_spawn-01.js
https://replay.io/view?id=cb0f76e8-e2e9-4295-89c2-5f7c2575acd5&test=breakpoints-01.js%20Test%20stripe%200
https://replay.io/view?id=ffdc6ba3-c151-45bc-8981-fe2ea6aae2b3&test=object_preview-02.js
https://replay.io/view?id=49774224-c0c5-4f8f-97a7-e28cb6155896&test=node_logpoint-01.js
https://replay.io/view?id=e7b7e7d8-1838-4f6f-a705-33998d266bb6&test=stepping-03.js

**Comment by kannanvijayan** [comment]
My latest (unlanded) patch for providing more context data in logs makes a change in how SessionInfo is constructed.  The way the code is implemented currently may be contributing to this: namely there are a bunch of hanging promises that are dispatched in the constructor for `SessionInfo`, which are not waited on for completion in anyway before returning.  Not sure if that's causing races with other parts of the code but it looked wierd to me.

Anyway, that bit of the code is changing and the promises will be explicitly waited on when my patch lands, so it may be good to keep an eye out for changes (for better or worse) in `createSession` failure after it lands.
