### ISSUE TITLE
Add comment @mentions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2006]
**Description:**

@mentions will let folks easily collaborate.

https://codesandbox.io/s/8n3zl4n9pl?file=/src/MyEditor.js:193-216
https://www.draft-js-plugins.com/plugin/mention

**Comment by ryanjduffy** [comment]
Some questions that come to mind around this:
* Should it be limited to team members or active collaborators?
* If not, maybe order by collaborators, team members, then all users?
* How are users notified of mentions? Email? Notification page a la GitHub?

First thoughts around the design:

* The plugin seems like it'd do the trick. The architecture of it is a bit weird but workable.
* When the user adds/edits a comment, fire off a request for the mention suggestions. Ideally, this would be cached and refreshed on future edits.
* When the commit is saved, the comment would be parsed for mentions and those would be inserted into a notifications table (linking comment, commenter, and mention and possibly recording for ease of access to that data).
* The notifications table would be the source for a standalone view and could be periodically queried to generate email.

**Comment by jasonLaster** [comment]
Great questions. I think we can keep the MVP fairly limited:

1. Only show recording collaborators, for most replays that actually means you wont use this feature unless you're viewing someone else's recording :)

2. Fetch the collaborators when the recording loads. We do this anyways for the share modal so not a big deal.
