### ISSUE TITLE
Viewer/devtools toggle is confusing

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2015]
It isn't obvious to me from the appearance of the viewer/devtools toggle whether the viewer or devtools is active.  To add to the confusion, clicking on either of them will toggle between the two, rather than select the one that I clicked.

**Comment by jasonLaster** [comment]
Thanks. We're working on fixing a couple items here:

1. Some of the visual details #2016 
2. Toggling behavior when you select the inner pill
3. Performance / timing details
4. Selected state appearance

**Comment by jasonLaster** [comment]
I started looking into toggling and got stuck

```diff
diff --git a/src/ui/components/Header/ViewToggle.js b/src/ui/components/Header/ViewToggle.js
index 0b5c6894..115863d5 100644
--- a/src/ui/components/Header/ViewToggle.js
+++ b/src/ui/components/Header/ViewToggle.js
@@ -43,12 +43,22 @@ function ViewToggle({ viewMode, setViewMode }) {

   return (
     <AnimateSharedLayout type="crossfade">
-      <button className="view-toggle" type="button" onClick={onClick}>
+      <div className="view-toggle">
         <div className="inner">
-          <Handle text="Viewer" isOn={viewMode == "non-dev"} motion={motion} />
-          <Handle text="DevTools" isOn={viewMode == "dev"} motion={motion} />
+          <Handle
+            text="Viewer"
+            isOn={viewMode == "non-dev"}
+            motion={motion}
+            onClick={() => setViewMode("non-dev")}
+          />
+          <Handle
+            text="DevTools"
+            isOn={viewMode == "dev"}
+            motion={motion}
+            onClick={() => setViewMode("dev")}
+          />
         </div>
-      </button>
+      </div>
     </AnimateSharedLayout>
   );
 }
```

**Comment by jonbell-lot23** [comment]
I can see the point that the selected state isn't as clear as if we used a more obvious treatment, but:

- This is a standard control, used across billions of devices around the the world, which helps cognitive load
- The page itself is pretty clear which is devtools and which isn't

I agree the toggle shouldn't switch back when you click on the selected state, but I propose the visuals stay.
