### ISSUE TITLE
[Console] Cannot create new functions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#202]
I'm experimenting with porting the react devtools to web replay and one of the things that surprised me was that when i'm paused i can declare new variables with primitives, but not functions

This would be nice because the React DevTools has some ueseful functions that would be good to declare once and then use. It's not essential, but would be helpful.

STR:
1. go to https://webreplay.io/view?id=71a5909b-f81e-4c91-8dde-2249d8629955
2. pause in any JS function
3. evaluate `a = () => 2;`
4. evaluate `a()`

<img width="634" alt="Screen Shot 2020-07-05 at 6 50 55 AM" src="https://user-images.githubusercontent.com/254562/86534268-05c95180-be8c-11ea-9995-ffa40596e834.png">

**Comment by bhackett1024** [comment]
Hmm, this WFM now.

<img width="269" alt="Screen Shot 2020-08-13 at 4 22 48 PM" src="https://user-images.githubusercontent.com/1062578/90207213-64ce9000-dd81-11ea-9fa9-2e260198f662.png">
