### ISSUE TITLE
[UX] Prevent logpoint evaluations when 100+ points

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2027]

**Comment by jonbell-lot23** [comment]
I'm not sure I understand this one. We're preventing things from showing in the console if over 250, but preventing evaluations at 100? That sounds backwards.

What's the experience we have in mind? If the person clicks something that was hit 101 times, are we just going to disallow clicking on it at all? Can we highlight anything in the timeline? What can we offer?

**Comment by bhackett1024** [comment]
We should limit the maximum number of logpoint results we can show at once (100? 200?) so that performance remains good, but people should always be able to change the logpoint message so that they can do evaluations at each of the points.  That's one of our key features, we never want to disable that.

**Comment by jonbell-lot23** [comment]
Thanks @bhackett1024, that squares with my understanding:

* You can always change logpoint messages
* We'll do our best (#2028 maxes at 250, meaning we ignore 251 and above with messaging)
* So if that's true, it sounds like this ticket is not needed?

Will discuss with @jasonLaster later this morning.

**Comment by jonbell-lot23** [comment]
Ok, we decided on a hard stop across both. So if our limit is x:

* Mousing over a breakpoint shows number of hits, even over x
* Clicking a breakpoint works if under x, messages the limit if over x
* Console evaluations run if under x, messages the limit if over x

**Comment by jonbell-lot23** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/9154902/110534799-5fed8580-8184-11eb-9096-c44f1e105a58.png">

@jaril and I are working on a system where my handoff makes clear what fidelity the design is at, so this is at "sketch" level.

I'd like to add this into the code for when breakpoints are large:

1. Color the tooltip #7E3636
2. Add a little alert icon on the left (using the Material icons)
3. Let's pop up a one-line placeholder error message

Once we have that working, I'll loop back and figure out the right copy and exact visual treatment.
