### ISSUE TITLE
Error context is missing 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2072]
**Description:**

 I left a comment in the [trace](https://replay.io/view?id=c84bda95-f340-4f06-af06-7c349e39eb7f) if you can see it. The last line I see executing before it throws is this `a = h()`, which in our code is this line: `const data = getDeviceInfo();` which is just a function call. Is that expected on your side? It’s a bit confusing. I’d expect to see the error creating the context. Looks like Firefox is internally failing to create the context.

 
![image](https://user-images.githubusercontent.com/254562/110673098-3aad4700-8185-11eb-8334-adacf0db5043.png)

**Comment by bhackett1024** [comment]
Looking into this some more, we could return null from getContext() instead of throwing, which would improve this and some other problems we've had related to WebGL support.  Filed https://github.com/RecordReplay/gecko-dev/issues/316
