### ISSUE TITLE
Exceptions not loaded at startup if checked in console settings

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2073]
STR

1. Visit https://replay.io/view?id=c84bda95-f340-4f06-af06-7c349e39eb7f
2. Enable exception logging (click on console settings button, click "Show Exceptions")
3. Observe several "Exception ..." logs being added to the console
4. Refresh

After refreshing, the Exception log messages are no longer in the console, but "Show Exceptions" is still checked.  Unchecking and rechecking it reloads the exceptions.

Expected

Exception log messages should be loaded at startup according to the user's settings.

**Comment by jasonLaster** [comment]
Nice catch. I think this would be fairly easy to fix if we had a replay of Replay successfully fetching exceptions when checked and failing to fetch when loading

**Comment by bhackett1024** [comment]
Sure, here's a replay that shows both the unsuccessful initial load and the uncheck/check steps to get the messages to load:

https://replay.io/view?id=422fad58-48cb-41aa-9bda-31c4a33f4cdd
