### ISSUE TITLE
"Point in time" shown for comments added to exceptions

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2074]
See comment in https://replay.io/view?id=c84bda95-f340-4f06-af06-7c349e39eb7f

This comment is on a scripted location where an exception is thrown, but the text above the comment says "Point In Time" instead of showing the scripted location as I would expect.

<img width="671" alt="Screen Shot 2021-03-10 at 11 13 57 AM" src="https://user-images.githubusercontent.com/1062578/110676946-cb8a1f80-8191-11eb-9c36-39ec2b9f70ef.png">

**Comment by jasonLaster** [comment]
This is probably similar to comments for other Event Listeners or Console Messages too...

**Comment by jonbell-lot23** [comment]
This is addressed because we have new comments now
