### ISSUE TITLE
Events at the end of the timeline are cut off

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2082]
Notice how this purple dot is cut off:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9154902/110719946-a02b3180-8272-11eb-8049-d873906e48e4.png">

**Comment by jaril** [comment]
Happens on both the start and the end.
![image](https://user-images.githubusercontent.com/15959269/110814638-9fd16d00-8257-11eb-9b10-4e8d71ea3cd8.png)
