### ISSUE TITLE
console_async_eval is failing and then refusing to open

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2083]
**Description:**
When I go to view some of these failing tests firefox grinds to a halt and chrome struggles as well

Failure console_async_eval.js https://replay.io/view?id=c5e30245-3bd1-4e23-8876-aa309fc98c9c 

https://github.com/RecordReplay/devtools/actions/runs/637958532
https://github.com/RecordReplay/devtools/actions/runs/637972099
https://github.com/RecordReplay/devtools/actions/runs/637575476

**Comment by hbenl** [comment]
The console_async_eval test was fixed in #2068 and the infinite(ish) loop that some recordings ran into was fixed in #2085.
