### ISSUE TITLE
Add a New Session email

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2102]
**Description:**

It would be nice if authors got an email when their replay has been viewed

**Subject** Your replay has been viewed: Cool Cat page
**Body** 

```
Cool Cat page was viewed for the first time by Jon Bell.


Happy Replaying!
The Replay Team
```

**Comment by jasonLaster** [comment]
Steps for setting up the email:

1. add an event in hasura
2. wire up the webhook in [replit](https://replit.com/@jlast/endpoints#index.js)

**Comment by jaril** [comment]
Just send the email when the user's first session.
