### ISSUE TITLE
Add timeout for createSession messages

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2114]
If the backend doesn't respond to the createSession message the devtools send at startup, the devtools will hang on the loading screen forever.  We should have a timeout to avoid wasting users' time if the backend doesn't respond to this message quickly.

**Comment by hbenl** [comment]
@bhackett1024 What would you consider a reasonable timeout?

**Comment by bhackett1024** [comment]
Hmm, maybe 10 seconds?

**Comment by jasonLaster** [comment]
https://github.com/RecordReplay/devtools/commit/ca6b1e5bb35051b95ce7328edb671495d8cc1514

**Comment by hbenl** [comment]
> [ca6b1e5](https://github.com/RecordReplay/devtools/commit/ca6b1e5bb35051b95ce7328edb671495d8cc1514)

why?

**Comment by bhackett1024** [comment]
I think this was backed out because of https://github.com/RecordReplay/backend/issues/1611 --- we were hitting the timeout when creating new recordings and waiting for the recording to upload.
