### ISSUE TITLE
Dragging up/down or scrolling on the timeline seems to zoom it?

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2115]
Just noticed this when trying something out.

1. Click and hold on the timeline
2. Drag your mouse down slightly
3. Drag your mouse up slightly

This also appears to happen if you scroll to zoom

See in the video all the points shift locations

If this is on purpose, then there definitely needs to be more of an indication of how to get things back to normal, because I definitely got confused about what had happened since I clicked and dragged trying to do something entirely unrelated to zooming.

https://user-images.githubusercontent.com/132260/111225621-43df4f00-859d-11eb-8b28-e7febe04a37a.mp4

**Comment by jonbell-lot23** [comment]
100%. This is sort of a hidden feature right now. I agree that if we do ship with this, we'd need to explain the feature more.

**Comment by loganfsmyth** [comment]
Got it, alright cool. I think one thing that made this extra confusing for me is that the zoom behavior persists across page refresh, so if you zoom accidentally, there is zero indication anywhere of what has happened or how to undo it and the UI just seems entirely broken.

**Comment by jonbell-lot23** [comment]
I've had that experience too -- I thought it was a bug until Jason told me it was a feature!
