### ISSUE TITLE
disabling "Show logs" should hide the console logs

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2136]
**Description:**

It can be distracting to see logs in the console. It'd be nice to disable them and still see logpoints

STR:
https://replay.io/view?id=3b182681-f929-4178-8814-bf3abca01d88

**Comment by hbenl** [comment]
disabling "Show logs" *does* hide the console logs. So I'm guessing that this issue is really about *not* filtering logpoints together with them ???
