### ISSUE TITLE
Replay takes awhile to startup 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2147]
**Description:**

I left some comments, but the basic problem is that it looks like its taking awhile to see the skeleton on page load...

https://replay.io/view?id=17d9ce8c-06f9-40d4-b810-055bf6033d3a

**Comment by hbenl** [comment]
I have added some comments to that recording: a large part of the time is spent waiting for the token from Auth0 (but there are also some delays that I'm not sure I understand correctly).
As a mitigation I have created #2162 to show the SkeletonLoader during initialization.
