### ISSUE TITLE
[inspector] fix collapse button

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#215]
The collapse button on the right column next to computed properties fails

<img width="1499" alt="Screen Shot 2020-07-08 at 6 47 25 AM" src="https://user-images.githubusercontent.com/254562/86926457-eed26b80-c0e6-11ea-88ae-2a14fef3402c.png">

**Comment by hbenl** [comment]
@jasonLaster Which collapse button do you mean? All the ones I could see on the screenshot are now working.
