### ISSUE TITLE
Improve frontToJSON

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2155]
**Description:**

I added `frontToJSON` while working on the react devtools panel so that we could serialize the JSON response. This works, but could probably be improved:

1. it makes several calls to load children. Could we use ObjectPreviewLevel to avoid this?
2. it converts the front to JSON. We probably should promote some form of this to ValueFront.

https://github.com/RecordReplay/devtools/blob/master/src/ui/components/SecondaryToolbox/ReactDevTools.js#L16-L39

**Comment by hbenl** [comment]
What should this function do exactly? Right now it tries to regenerate the entire object graph starting with its argument, running into an infinite recursion if the object graph contains a circle.
