### ISSUE TITLE
[inspector] property info tooltip fails

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#216]
The info tooltip fails to load. 

> Note this can probably be hidden for now...

<img width="298" alt="Screen Shot 2020-07-08 at 6 46 40 AM" src="https://user-images.githubusercontent.com/254562/86926502-001b7800-c0e7-11ea-977a-455ad08ac619.png">

**Comment by hbenl** [comment]
@jasonLaster I have seen no info tooltips in the new rules view - is this a feature that should still be added or should we close this issue (for now)?
