### ISSUE TITLE
Excalidraw: breakpoint hits come back out of order

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2160]
**Description:**

- The breakpoint hits come back out of order
- Clicking next on the breakpoint hits sometimes jumps several hits

**Steps to Reproduce:**

1. go to [excalidraw](https://replay.io/view?id=3a3c7c94-7dca-4a6b-82fa-a12a776006f0) 
2. Add a breakpoint in App.tsx:974 a log expression `"render", this.state.scrollX` 
3. Notice how the scroll position changes, but the video only changes once every ten logs

 **Replay:**
https://replay.io/view?id=aded64ab-4cab-4ae8-893f-42b087a7b4e3

**Comment by hbenl** [comment]
I think we shouldn't assume that we get the analysis points in chronological order, they are streamed to us from the backend in the order in which they are found.
The breakpoint navigation only works when the analysis points are in chronological order, so we sort them as soon as all of them have arrived.

**Comment by loganfsmyth** [comment]
Sorry for the repeat work @hbenl! Fixed with #2167
