### ISSUE TITLE
Send notification when devtools enter an error state

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2170]
It's hard to detect when users are encountering issues like https://github.com/RecordReplay/devtools/issues/2114 solely from the backend's behavior.  It would be nice to know when users are encountering errors.  One way of doing this is to send a telemetry ping when the devtools enter an error state (the code for where we ping telemetry in the backend is below, but this is an HTTP post which could be done from any service).  I'm sure there are other options too, though.

https://github.com/RecordReplay/backend/blob/40a668f2277ae02276cede94797511e83a9f8451/src/shared/instanceUtils.ts#L210

**Comment by jasonLaster** [comment]
can you describe other error states and what we see on the devtools that would not just come from the backend?

**Comment by bhackett1024** [comment]
I have recently seen many error states in the devtools recently related to workspaces, e.g. https://github.com/RecordReplay/devtools/issues/2239.  Having telemetry for this in the devtools will let us know how many times people are actually seeing these screens, regardless of the cause.  We need this information to actually understand how the devtools are behaving in practice and drive these errors down.

**Comment by hbenl** [comment]
`setExpectedError` and `setUnexpectedError` are the methods that are used to show an error screen to the user, so I'd add it there. What information do you think would be useful (except the basic information from the error object itself): I guess `recordingId` and `sessionId`, anything else?

**Comment by bhackett1024** [comment]
That sounds good, we can see what notifications we get and adjust the information in the telemetry ping if needed.
