### ISSUE TITLE
RPT-1 Welcome screen

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2194]
- [x] Default people to this welcome screen
- [x] Place to put text

**Comment by jonbell-lot23** [comment]
<img width="1440" alt="RPT-1 Welcome" src="https://user-images.githubusercontent.com/9154902/112562236-bcff6180-8e3b-11eb-8485-cafa3561b0d2.png">

Latest in Figma.

**Comment by jonbell-lot23** [comment]
Hey @jaril here are the additional screens we discussed.

Signed out, new user:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/9154902/113641526-e472eb80-96d1-11eb-97b7-9b25bfa19ded.png">

Signed in with zero Replays:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/9154902/113641558-f81e5200-96d1-11eb-8c45-624bc41e02e6.png">

Signed out but we recognise you:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/9154902/113641575-02d8e700-96d2-11eb-9cd4-55e0beda5642.png">

Signed in and you have at least one Replay:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/9154902/113641595-0f5d3f80-96d2-11eb-9f74-fdc1f151a109.png">

**Comment by jasonLaster** [comment]
Lets discuss this in the design sync.

**Comment by jonbell-lot23** [comment]
More discussion here: https://www.notion.so/replayio/Welcome-Screen-Discussion-6d51f23ae72b49679dc22bfabc21eae6

The end result is the same. Most of our flows/screens will stay the same, but we're adding a welcome screen for people in the Replay browser who have zero recordings.
