### ISSUE TITLE
Feedback from brian@tango.us

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2197]
https://app.tango.us/app/public/workflow/replay-feedback-caafdbf3e33744bbb11bf914f51e79c8

- [ ] Show author in the grid view of the library
- [ ] Screens are quite small in list view
- [x] Created by and shared by are dead links, that's frustrating
- [ ] Dropdown only appears on the first card
- [x] Switching between public and private doesn't show it worked
- [x] Settings is broken in library
- [ ] Filter icon confusing (add a tooltip)
- [ ] Concerns about the fact that things are public by default

**Comment by jasonLaster** [comment]
<img width="244" alt="Screen Shot 2021-03-26 at 10 14 45 PM" src="https://user-images.githubusercontent.com/254562/112710738-b47d4a00-8e80-11eb-9df7-db5eb2649683.png">

https://replay.io/view?id=e475b8c7-cf67-4910-85e7-839e4f30d047

**Comment by jonbell-lot23** [comment]
Moving these items into #2309 and #2308
