### ISSUE TITLE
[UX] Add ability to invite people on your domain

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2204]
If I'm a Replay user with the email domain tango.us, I should be able to easily share Replay with my coworkers as long as they have the same domain in their email address. (Note that this is not the same as being able to get invite codes for anyone at all, it's focused on people who already work together)

**Comment by jonbell-lot23** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/9154902/112785742-32279c80-90b1-11eb-96e9-09b0a7ad582f.png">

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/114325441-4c1eb000-9b84-11eb-86ec-3b04444a82d3.png)

Here's how the team settings currently look. We can just add a simple checkbox that says "Allow anyone with a <their domain> email address access this Replay?"

It should be off by default. And if the email is @gmail.com, don't show the checkbox at all.

**Comment by jasonLaster** [comment]
Let's discuss this in the design sync. I'm not sure if invite links are as important as other points of friction.

**Comment by jonbell-lot23** [comment]
De-prioritised

**Comment by jonbell-lot23** [comment]
Re-prioritised.

**Comment by jonbell-lot23** [comment]
De-prioritised again. Too hard right now.

**Comment by jonbell-lot23** [comment]
RE-PRIORITISED

**Comment by jonbell-lot23** [comment]
Getting addressed
