### ISSUE TITLE
It should be easy invited users to download Replay 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2210]
**Description:**

We used to let anyone download Replay, but that meant that one HN post could open the flood gates, which we're not ready for. 

We should now make it easy for folks who have been invited to download the Replay browser and encourage them to make their first Replay.

**Comment by jasonLaster** [comment]
My strawman UI is that the header should have a record button, that will either

1) open a modal for downloading replay
2) open a replay itself

**Comment by jasonLaster** [comment]
https://stackoverflow.com/questions/14415012/how-to-launch-an-application-from-a-link-in-a-webpage-on-mac

**Comment by jonbell-lot23** [comment]
I've been thinking about this, and I think this belongs in the dropdown. I don't think we should put more in the UI yet. (we'll end up with 9 icons up there soon enough, so let's be ruthless for now).

So let's have a link in the dropdown that says "Launch Replay" and it will work as described above. If Replay is installed, it launches. If it's not, you're taken to a download page. And if we know you're in the Replay browser, this item should disappear from the dropdown.

**Comment by jasonLaster** [comment]
Love it. I think as a short-term approach we can also just add a `Download Replay` link to `replay.io/welcome` if folks haven't made a replay yet...

**Comment by jonbell-lot23** [comment]
Ah, yeah. Good call.
