### ISSUE TITLE
Deleting a comment shouldn't remove it from the DB

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2217]
There are two sides to this:

- [x] When a user deletes a comment, we should do a soft delete
- [x] When a user deletes a parent comment, the replies will disappear from the UI, but it's even more important that we don't hard delete from the DB because those users didn't ask for their replies to disappear

**Comment by jaril** [comment]
https://hasura.io/docs/latest/graphql/core/guides/data-modelling/soft-deletes.html
