### ISSUE TITLE
[Outline] the UI does not scroll

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#223]
The Outline view does not handle long lists well

- It should scroll.
- The footer can become dislodged somehow

<img width="360" alt="Screen Shot 2020-07-11 at 9 49 22 AM" src="https://user-images.githubusercontent.com/254562/87229531-89d47b00-c35d-11ea-8992-3fb055c085fe.png">

**Comment by princiya** [comment]
I will pick this one.

**Comment by jasonLaster** [comment]
Thanks! So curious how we messed it up :)
