### ISSUE TITLE
Upload screen should appear immediately

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2235]
In the current flow, we upload until we're done uploading, then show the upload screen. But this is awkward and slow experience for end users. 

We need the upload screen to show immediately after pressing the stop button. I suspect this will be tough on the code side of things, but right now the screen can take two minutes to load, which is going to cause too much confusion. If I had to choose between a two minute delay or no upload screen at all, I'd pick no upload screen.

**Comment by jaril** [comment]
Continued in #2255
