### ISSUE TITLE
Confusing error message with typo

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2239]
I'm trying to view a replay I just made locally and am getting this error.  I don't know what it means, and the message has a typo.

<img width="754" alt="Screen Shot 2021-04-03 at 1 31 38 PM" src="https://user-images.githubusercontent.com/1062578/113486479-180b0700-9481-11eb-977f-70c67aad95a4.png">

**Comment by bhackett1024** [comment]
Here is a recording: https://replay.io/view?id=af92fb6a-072d-44ab-897a-9f95c19249c0

**Comment by jonbell-lot23** [comment]
Thanks! 

We originally called this a "draft" but I'm encouraging everyone to call this an upload screen. Drafts have a very specific meaning, so we should not use the word in Replay. We should say "upload" instead.

**Comment by jonbell-lot23** [comment]
Fixed: https://github.com/RecordReplay/devtools/commit/2214d21d77f0edb32b9abba1d09ce95ed1025731
