### ISSUE TITLE
Errors viewing recording locally

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2242]
I'm seeing a bunch of errors in the console when trying to view recordings I made locally, and the devtools don't actually load and the screen stays white.

<img width="1044" alt="Screen Shot 2021-04-04 at 3 48 05 AM" src="https://user-images.githubusercontent.com/1062578/113502175-935bcf80-94f8-11eb-9a14-45be2a8d0085.png">

<img width="1040" alt="Screen Shot 2021-04-04 at 3 48 32 AM" src="https://user-images.githubusercontent.com/1062578/113502187-a2428200-94f8-11eb-93ff-5cdb08855f8c.png">

<img width="1043" alt="Screen Shot 2021-04-04 at 3 48 58 AM" src="https://user-images.githubusercontent.com/1062578/113502195-b2f2f800-94f8-11eb-8356-10d7b4cc30a9.png">

<img width="1042" alt="Screen Shot 2021-04-04 at 3 49 16 AM" src="https://user-images.githubusercontent.com/1062578/113502200-be462380-94f8-11eb-88a4-bb086e19ede7.png">

<img width="1040" alt="Screen Shot 2021-04-04 at 3 49 52 AM" src="https://user-images.githubusercontent.com/1062578/113502215-d1f18a00-94f8-11eb-8d6a-1e902ca39d21.png">

**Comment by jasonLaster** [comment]
@bhackett1024 i just tried to reproduce with `app.features.workspaces` set to true and false. Could you record what you're seeing and share a replay?

**Comment by bhackett1024** [comment]
Good point, here is a replay: http://localhost:8080/index.html?id=1f81001b-fede-40d0-9f30-e76c4aa84f5d

**Comment by bhackett1024** [comment]
This is still impacting me, can we please get this fixed?
