### ISSUE TITLE
Add ability to click directly on playback region to add a comment

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2254]

**Comment by jasonLaster** [comment]
How do you feel about

1. removing the play/pause interaction
2. bringing the comment pin interaction in. so if there is no comment at this point in time users can set the pin and add a comment?

**Comment by jonbell-lot23** [comment]
Just following up on our call from this morning:

1. We lose the play/pause interaction, but the tradeoff is solid. It will direct people to the play button and the timeline, which is why a dragger is a good thing to add soon.
2. Adding in comment pins is the goal, yup.

**Comment by jonbell-lot23** [comment]
![Uploading image.png…]()

Look in Figma for a page called RPT-2 Comment Placement. @jaril I haven't done this carefully with auto-layout, but this is a strong sense of the direction.
