### ISSUE TITLE
Delete all doesn't actually delete everything

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2257]
More details to come. Here's a recording:
https://share.descript.com/view/fxYK6pplMIl

**Comment by jonbell-lot23** [comment]
See also: https://github.com/RecordReplay/devtools/issues/2257

**Comment by jonbell-lot23** [comment]
And https://github.com/RecordReplay/devtools/issues/2259

**Comment by jaril** [comment]
Fixed by #2297.
