### ISSUE TITLE
Deleted Replays come back

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2259]
I'm not sure how I did this, but I deleted all of my Replays, but then 15 minutes later they were back in my library.

**Comment by jasonLaster** [comment]
Haha could you try doing something similar with a couple of replays and see if you can repro... If so, record delete w/ replay so we can see which mutations fire

**Comment by jonbell-lot23** [comment]
Here's a Replay of a lot of things going wrong:
https://share.descript.com/view/AZsqOGYdAvw

1. We need confirmation dialogs when you try to delete stuff
2. Deleting simply didn't work at all this time
3. I tried moving things and it eventually worked but in a confusing way (no messaging)
4.

**Comment by jonbell-lot23** [comment]
The plot thickens. I attempted to grab a Replay of the issue here: https://replay.io/view?id=3673940b-3917-42bb-affa-3cfd23b21d84&point=76910897233877354397571717672225551&time=36240&hasFrames=false

And at one point I got an issue that said the Replay had been deleted! Which tells me that the library is showing items that it shouldn't. Hopefully this Replay helps track down our issue.

**Comment by jonbell-lot23** [comment]
See also: https://github.com/RecordReplay/devtools/issues/2257

**Comment by jaril** [comment]
Fixed by #2297.
