### ISSUE TITLE
Teams (aka workspaces) don't appear in library until about 5-10 seconds go by

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2265]
Replay: https://share.descript.com/view/Fy7ABUeqKNt

We need to make sure that UI appears immediately, and can never have a delay like this.

**Comment by jasonLaster** [comment]
We should be able to show the default workspace immediately and then show the dropdown 5 seconds later... Also, the fact that it is 5 seconds suggests we're fetching too much data

**Comment by jaril** [comment]
@jonbell-lot23 I notice this too, but it's usually ~1-2s. If you notice a really long one again could you get a replay?

**Comment by jaril** [comment]
Found a juicy 7s wait case:

https://replay.io/view?id=ba9c60ab-cdce-4716-9a91-dcdb23875555&point=33749929583581750599676199591478407&time=15123.4404551201&hasFrames=true
