### ISSUE TITLE
Recordings aren't defaulting to recent team (aka workspace)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2266]
https://share.descript.com/view/2UzZa7HZE9l

When I change my team to A-Team and then record something, it should default to the A-Team workspace. Not personal.

**Comment by jasonLaster** [comment]
@jaril we can use the Repl.it strategy here to listen for new recordings and set the workspace

**Comment by jaril** [comment]
Folding this into #2266.
