### ISSUE TITLE
UX "Point in time" marker doesn't always appear

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2268]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/9154902/113647459-f8711a00-96de-11eb-84cb-55674198eaff.png">

In this screenshot, there's no way to add a comment. I think this issue will go away when we add the ability to click on the Playback region to add a comment, but it's still worth calling out as a bug.

**Comment by jasonLaster** [comment]
yep. I think that happens when you click the pause button. could you make a replay so we can debug ti?

**Comment by jonbell-lot23** [comment]
Yup, it's triggered when you click on the timeline but not otherwise. Replay: https://replay.io/view?id=15423686-9086-4832-a7e6-8fa220f54a3b

**Comment by hbenl** [comment]
It seems that this was fixed in the meantime, I couldn't reproduce it.
