### ISSUE TITLE
Subset sourcemap issue

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2271]
**Description:**

https://replay.io/view?id=53b778b1-2afb-485d-b556-db18b8f84c7c&point=25312447186522709627409382619745720&time=31443.48681631819&hasFrames=true

**Comment by loganfsmyth** [comment]
@jasonLaster Can you clarify what the expected behavior here is? The comment mentions bad sourcemaps, but I don't know beyond that what I'm supposed to be looking for.

**Comment by jasonLaster** [comment]
agreed. They look fine to me now too.
