### ISSUE TITLE
Remarkable sourcemaps issue

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2272]
**Description:**

https://replay.io/view?id=38e45abc-7050-43a3-9d60-2bdd4227ef07&point=20444668887518695962633424710141624&time=7510.902205098215&hasFrames=true

**Comment by loganfsmyth** [comment]
I'd guess that this is because `categories` is an import, not a normal variable. I can look into whether this is something we can catch.

**Comment by jasonLaster** [comment]
Thanks. This might be another example of where we should fall back to generated scopes.

**Comment by loganfsmyth** [comment]
I'll have to look into it, but in the naive case that pretty much invalidates original scopes entirely, since probably a large percentage of bundled code will have unresolvable imports.

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
