### ISSUE TITLE
Support loading regions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2283]
**Description:**

The server will now unload regions when too much memory is consumed. This helps the server remain stable continue to be to the client responsive. When the client does want to interact with an unloaded region it should ask the server to load the region back in before interacting with it

NOTE: We will also have to add backend support for this as well.

### Tasks

- [x] https://github.com/RecordReplay/backend/issues/2469 
- [ ] DevTools let users load a new region

**Comment by bhackett1024** [comment]
Before support for reloading regions we also need to show the unloaded regions and fix the UX when running analyses or trying to pause in unloaded regions.  See https://github.com/RecordReplay/devtools/issues/2821

**Comment by jasonLaster** [comment]
Created https://github.com/RecordReplay/devtools/issues/2832 to track frontend work we should do soon to help users with unloaded regions
