### ISSUE TITLE
Simplify labels

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2307]
### Proposal

it would be nice to group the labels a bit more and be a bit more selective

* type-feature
* type-bug
* needs-design
* needs-discussion
* feature-comments
* feature-elements
* feature-sourcemaps

### Existing list

* Authentication
 * Backlog
 * Browser
 * Bug
 * Comments
 * Console
 * Debugger
 * Dependencies
 * design-complete
 * design
 * Documentation
 * Elements
 * Events
 * Feature
 * Good first issue
 * Header
 * Help wanted
 * In progress
 * Library
 * Loading
 * Miscellaneous
 * needs-design
 * needs-triage
 * Needs discussion
 * Needs information
 * P1
 * Perception
 * Performance
 * Project
 * Question
 * React DevTools
 * Recorder
 * Settings
 * sourcemaps
 * Timeline
 * Tooling
 * UI Polish
 * Video
 * Viewer

**Comment by jonbell-lot23** [comment]
There are a few items here:

1. Let's have fewer by grouping more
2. Let's use a different naming convention

I've started by removing all the labels that aren't being used. We can discuss the difference between "Feature" and "type-feature" later beacuse that's a smaller detail.

**Comment by jonbell-lot23** [comment]
Closing out as per Jason's "let's make sure to focus" points
