### ISSUE TITLE
Explore Notification Center integration like Replit

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2317]
I just used Replit and they asked for permission to connect to macOS's Notification Center.

Worth considering alongside our email integration.

**Comment by jasonLaster** [comment]
Lets add this as a discussion, since it's something that will probably bake for a little while as we figure it out with Knock or Courier

**Comment by jonbell-lot23** [comment]
Bingo, was just coming here to say the same thing.
