### ISSUE TITLE
[Inspector] Highlighter is not aligned

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#232]
STR:

1. go to https://webreplay.io/view?id=bbe26b60-2743-4dfb-86e0-1a7f4e777ce9
2. open inspector
3. select `#app`

[loom video](https://www.loom.com/share/4939e9a90b9642e9819e1fc404cf74ed)

**Comment by jasonLaster** [comment]
Haven't seen this lately

**Comment by jasonLaster** [comment]
Seeing this problem again 

STR:
1. go to https://replay.io/view?id=284da194-e97a-4bb8-879a-abc417b76f79
2. open the node picker

Notice how the highlighter is offset by ~30px in both directions.

https://www.loom.com/share/f9a5cd9b35844c2aa5941947e71bd152

**Comment by hbenl** [comment]
The highlighter isn't offset, it is zoomed.
This happens whenever you make a recording while the Replay Browser's zoom level is set to anything other than 100% and then watch that recording: the screenshot graphics will have the original size but coordinates from the protocol method DOM.getBoxModel are divided by the zoom level.
For example, I made a recording with zoom level 120%. The screenshots in that recording are 1234 pixels wide, but DOM.getBoxModel for a DOM node that fills the browser window reports a width of 1028.33 pixels, which is 1234 / 1.20.

**Comment by hbenl** [comment]
... which is correct because the screenshots consist of "device pixels" whereas the measurements from DOM.getBoxModel are in "CSS pixels". We just need to get the zoom level with which the screenshot was made and apply that to all those measurements.

**Comment by hbenl** [comment]
Depends on RecordReplay/backend#202

**Comment by jasonLaster** [comment]
closing as this will be fixed in the backend
