### ISSUE TITLE
Cannot leave a comment on a node replay

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2339]
**Description:**

Node replays are the first time our UI does not have debug a runtime with graphics. The short term fix is to drop the assumption that we have a canvas to drop a pin on. The long-term / better fix is to hide the viewer for node.

https://replay.io/view?id=819bf4ba-4d4a-4ca7-a194-57bb49f314a4&point=1298074215581716213961117900210243&time=2078.543298750794&hasFrames=true

**Comment by jaril** [comment]
Fixed by #2342.
