### ISSUE TITLE
Email invite got lost

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2344]
I sent an invite about 24 hours ago to a user with the domain pluralsight.com. He says it never arrived, not even in spam. Filing so we can track it down.

Notes from Jason:
"Hmm. We'd need to look in aws simple email. Courier will help here. Another question is did the invite get added to the db."

**Comment by jasonLaster** [comment]
I think this is something that hasura will tell us. Here's an internal doc. 

https://www.notion.so/replayio/Emails-not-sent-a5cd77c7f0884fb585ea4b9839e0f91b

**Comment by jonbell-lot23** [comment]
I have never seen this lonely and outdated document in my life, which is a problem 🙃

I want to make sure this doesn't fall between the cracks. If we're not going to do it in GitHub can you please recreate the GitHub functionality somewhere (including discoverability for the team) so we can track it and make sure it gets addressed?

**Comment by jonbell-lot23** [comment]
Jaril says this was fixed: 

"the replit endpoint's URL was changed, so we didn't know when any of the new database stuff was happening"
