### ISSUE TITLE
Pause object is not fetched

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2346]
**Description:**

1. go to this replay https://replay.io/view?id=559fdf04-a3df-4c6c-b727-15f2a00b4e8a&point=13629779253693719069388438864134332&time=8483.240663900415&hasFrames=true
2. add a breakpoint in app.js:75 and seek to the one hit

ER: see call stack and scopes
AR: not getting pause data

here is a replay of the problem: I dont see any pause requests
https://replay.io/view?id=6c936086-b9b1-469f-85ee-6812a93726ff&point=3569704091383952545280895913820390&time=2891.097884899164&hasFrames=true

**Comment by hbenl** [comment]
This is a backend issue, see RecordReplay/backend#1689
