### ISSUE TITLE
Invite link should live on top bar now that left nav is going away

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2349]
If we're going to remove the left nav from the library, we'll need something like this:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/9154902/114654777-f2161a00-9d3e-11eb-80d2-3a76a7c61358.png">

And we might as well bring it over to the devtools. (But only when there's nothing else to show because no one else is viewing the replay)
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/9154902/114654938-56d17480-9d3f-11eb-90df-4ab5c31bc291.png">

**Comment by jasonLaster** [comment]
So, i might be contracting myself ... but i would like to see what behavior we see when we onboard folks first

Like who do they add in the invite... what do they say when we talk to them

**Comment by jonbell-lot23** [comment]
I don't have an open research question around "will people see an obvious link quicker than one buried in a menu?"

I want to know the questions you're asking above, which aren't changed by making the button easier to find. In fact, it gives us more data because more people will see it.

**Comment by jaril** [comment]
The first one, a button for the team settings where you can add/delete team members, is necessary now that we don't have a left nav. I've addressed this in #2310 by moving it to the left side of the header, beside the team dropdown. Didn't make sense to me why we'd put those two things on opposite ends of each other.

As for the second one, it's not clear what the Invite others link should do. Should clicking that open the share modal, or the workspace modal, or the replay invitations? I think you meant to point it at the share modal, and if so, the call to action should be share, not invite.

**Comment by jonbell-lot23** [comment]
1. The reason for putting where I designed it was to use the same visual vocabulary between Library and a Replay. Having each screen be different even though they do the same things isn't ideal, and burying the "share" underneath an unlabelled icon isn't either. We'll probably end up putting the button back as per the design, but this is fine for now.

2. Good point about "Invite Others" being vague. The thing is, the word "Share" is vague also. I think in both screens the visual will probably end up being "Add collaborators," which goes to a "Share" dialog but ends up "inviting" people. On paper, it's a mess. But all a user cares about is "how do I get my coworker here?" This is fine for now, and we'll continue to iterate.

cc @jaril
