### ISSUE TITLE
[UX] Add comment to a line of code

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2358]
We need an entry point for adding a comment to a line of code:

![](https://user-images.githubusercontent.com/9154902/115791061-e05a0400-a41b-11eb-9de5-5b6752e5dc20.png)

**Comment by jasonLaster** [comment]
Yep! My head was here too. We could add a pen to the log expression button too

**Comment by jonbell-lot23** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9154902/115791061-e05a0400-a41b-11eb-9de5-5b6752e5dc20.png">

Here's our entry point. As Jason mentioned above, let's also change the cursor to a pencil when you hover over the log expression button. Once this is in place, we're going to redesign the Transcript more fully.

**Comment by jonbell-lot23** [comment]
Moving this higher in Jaril's priority list so we can have this prepped for our Comment V3 work
