### ISSUE TITLE
settings.js test perma-fail in backend CI

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2370]
This e2e test has started perma-failing in the backend (but not the devtools itself, strangely).  Here is a sample recording of the viewer: https://replay.io/view?id=5b6f7f29-7bb6-4b14-a800-75a59aff0720

This looks like a frontend problem but I'm not sure.

**Comment by bhackett1024** [comment]
This has started passing again, mysteriously.

**Comment by hbenl** [comment]
It was fixed in #2384
