### ISSUE TITLE
Snap close splitboxes vertically and horizontally

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2402]

**Comment by jonbell-lot23** [comment]
I'll soon be looking into addressing the console and video regions. It's possible we end up with a literal toggle button for turning the video on and off. As discussed with Jaril, this might be easier on the code and also easier from a UX standpoint.

Let's hold off on this in the meantime. Auto-snapping regions are both a) super common and b) problematic UX. I think we can do something that's easier on the code, easier on the user, and fits into where we're headed with devtools.

**Comment by jonbell-lot23** [comment]
I'm going to close this for now for the reasons stated above. Can re-open later.
