### ISSUE TITLE
[UX] No way to see Replays I've commented on in the Library

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2406]
1. We need to change the query to show all Replays (yours, ones you're invited to, and ones you've commented on)
2. With that in place, we can close this ticket and use https://github.com/RecordReplay/devtools/issues/2407 for other UX features we want in the library like a search box and filter dropdowns.

Read the design guidance here: https://www.notion.so/replayio/Library-Filtered-View-eb7d0cc6e7894d3ea6ebdf696d46b823

**Comment by jonbell-lot23** [comment]
@jaril and @jasonLaster please check the Notion document to see the short term and medium term work for the Library. I'm marking this particular issue as design-complete because the short term fix is a query change.

Then when this issue is complete, we move to the fuller design in https://github.com/RecordReplay/devtools/issues/2407

**Comment by jonbell-lot23** [comment]
Woo!

**Comment by jaril** [comment]
Reopening this because it was regressed by the new GraphQL API.

**Comment by jonbell-lot23** [comment]
This works again!

<img width="612" alt="image" src="https://user-images.githubusercontent.com/9154902/118922789-b8b07a00-b98e-11eb-88f7-b63d08124144.png">
