### ISSUE TITLE
Confusing behavior on subsequent recordings for same URL

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#2414]
When I make a recording for URL A, view it and set some breakpoints, and then I make another recording for URL A and view that those breakpoints are still present in that second recording.

Is this a bug or a feature? Sometimes it's useful (Yeah I was interested in the same info, but with a different circumstance), but other times it's annoying (what is all this garbage in the console?)

I brought this up in Discord and @jonbell-lot23 said:

>The design POV is:
>
>* Let's turn this off by default
>* And let's make an experimental flag for people that want to turn it back on

**Comment by jasonLaster** [comment]
I think we probably should convert this into a feature request for breakpoints saved per recording per user. 

This would move breakpoint management from localstorage to the db and open up new collaboration possibilities and work across browsers (chrome, firefox, etc...)

**Comment by jasonLaster** [comment]
closing since #2531 will fix it
