### ISSUE TITLE
Comments V3 (be more like usebubbles.com)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2424]
**Here's the final design:**
<img width="413" alt="image" src="https://user-images.githubusercontent.com/9154902/116807666-7f070300-ab88-11eb-995b-abf70bb7f2d9.png">

**Here are the code samples in Tailwind:**
[Entry point](https://play.tailwindcss.com/pxtn2tk6lE?layout=horizontal) 
[Composition](https://play.tailwindcss.com/0Pu8GtsnZA?layout=horizontal)
[Standard](https://play.tailwindcss.com/z9gLWbsSfh?layout=horizontal) 
[Line number](https://play.tailwindcss.com/d4F9aMIiFt?layout=horizontal) 
[Reply composition](https://play.tailwindcss.com/LzFAOPrz6m?layout=horizontal)
[Replay standard](https://play.tailwindcss.com/4sIhMQ3QGO?layout=horizontal)

**Here's the spec:**
[Comments V3 Quick Spec](https://www.notion.so/replayio/Comments-V3-Quick-Spec-14c1a8aa7d7f4dfb991faa8d005c067e)

**Next steps**
* Let's implement these as they are. @jaril and I talked a lot about edgecases last week so we should be in pretty good shape.
* With these ready to go, let's play around with it to see if we need to do anything else like add active and hover states
* #shipit!
* At that point, I can fine-tune the visuals myself as part of another ticket.

**Notes**
* Jason likes the idea that non-code comments have no "hat" gray bar across the top. I agree.
* We also have a new comments exploration, but that's in early exploration and will come later (if at all)

**Comment by jonbell-lot23** [comment]
This is almost done. We just need to figure out the visual treatment for line number/event. See the spec here:
https://www.notion.so/replayio/Comments-V3-Quick-Spec-14c1a8aa7d7f4dfb991faa8d005c067e

Should be done next week on Sunday/Monday.

**Comment by jaril** [comment]
Requirements:
- There should be a card for each root comment.
- Replies should be displayed in the same card as their root comment.
- Comment cards should have a focused state.
- A focused card should display the "Write a reply" prompt.

Questions:
- Should we indicate when a comment is paused on?

**Comment by jonbell-lot23** [comment]
Woooooo
