### ISSUE TITLE
Recordings not viewable when not signed in

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2428]
STR:

1. Go to replay.io and sign out.
2. Try to load an anonymous recording, e.g. https://replay.io/view?id=c3967b2a-221d-49df-be44-1b6db014116e
3. The recording never gets past "Fetching the replay information." while loading.

The console shows a bunch of apollo errors, and evaluating "outstanding()" shows that the backend finished loading the recording.

**Comment by ryanjduffy** [comment]
This is the same issue I saw with playwright recordings. I thought it was tied to playwright but perhaps not. My bisection revealed bdc9556434036c139f0388ee6dfe66f56a737e54 to be the offending commit.

**Comment by bhackett1024** [comment]
Thanks for finding the bad commit @ryanjduffy, @jazzdan can you see what's going on here?  Things do work for me when signed in, but the UI completely breaks when not signed in.

**Comment by bhackett1024** [comment]
Here is a recording of the UI failing to load:

https://replay.io/view?id=c06d125f-8db3-4d62-9fdf-304586e1b66f

**Comment by bhackett1024** [comment]
I reverted https://github.com/RecordReplay/devtools/commit/bdc9556434036c139f0388ee6dfe66f56a737e54 to unbreak this in prod while we investigate the underlying issue.

**Comment by jazzdan** [comment]
Going to wait on fixing this until the new API is rolled out since that will make being more sophisticated about these permissions a lot easier.
