### ISSUE TITLE
[UX] Add right-click to add comment to a line of code

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2441]
This is a bit more detailed than just adding it to a right-click menu. We also want to look at other items to make sure we like our right-click model.

**Comment by jasonLaster** [comment]
I think the challenge here is that it encourages folks to leave time-less comments which we dont like as much as a time-based comment when they are paused at one of several hits...

**Comment by jonbell-lot23** [comment]
Great questions! @jaril and I spoke about this at length and here's where we are:

* Timeless comments are definitely in our future. For example, we might want to add a comment on a file, not a line of code. Or a line of code that's not ever called. So there are cases where there just won't be an x,y or time-based way to place it positionally or temporally.

* Faced with this reality, we can 1) pin everything timeless to the top of the Comments 2) put the comment wherever the playhead happens to be 3) disallow all timeless comments

* For me, the best answer is #2 with a caveat. We put the comment wherever the playhead happens to be ... but the caveat is that we need to add the ability to reorder comments in the comments/transcript. I might file 4 comments, and then on the 5th comment I want to describe a summary of the problem. I need to be able to put it on the top. But not just a pinning mechanism. If we want the left-hand side of the page to tell a story, we need re-ordering.

So:

* Short term, we just align to wherever you are in the timeline playback
* But the full credit answer is adding the ability to reorder comments to tell a story

**Comment by jasonLaster** [comment]
👍 This feels like a thing where we've got to hold our nose and try it.

We'll have a much better intuition for how folks want to use Replay after playing with it for a little bit

**Comment by jonbell-lot23** [comment]
Update on this issue: we discussed the concept of "timeless comments" and now this issue is back to the original intent: a feature request for right-clicking to add a comment to a line of code.

That said, feature requests belong in discussions. Closing and linking -> https://github.com/RecordReplay/devtools/discussions/2666
