### ISSUE TITLE
Unknown recording error when adding comments

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2458]
I was trying to add a comment to [this replay](http://localhost:8080/view?id=232822a1-368a-480a-88e7-6030adfb5109&point=38293189332182169836991127272555329&time=16620&hasFrames=false), but was getting an error in the console instead. This was in Chrome — adding comments to the same replay worked in the Replay browser.

The error can't be reproduced in the replay browser, so here's a screen recording:

https://share.descript.com/view/nwWv2jdYxCM

Screenshot:
![image](https://user-images.githubusercontent.com/15959269/116636061-64395200-a92e-11eb-9c9d-40621915d928.png)

**Comment by loganfsmyth** [comment]
I realize with the logic as-is right now, the new API doesn't let you comment if you aren't a collaborator/workspace member/owner, so if you're logged in as some other user, that's probably why.
