### ISSUE TITLE
[debugger] Remove pause button

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#246]
It's a relic and no longer belongs

<img width="539" alt="Screen Shot 2020-07-13 at 8 00 45 AM" src="https://user-images.githubusercontent.com/254562/87319824-05116a80-c4df-11ea-90c7-4a7eec80b23f.png">

**Comment by hbenl** [comment]
This has been fixed in 2ba3e9844fdc7464fab5ea24c61e9678f6f1ba36
