### ISSUE TITLE
Improve Console Type filters

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2490]
Starting a conversation here around how we let users filter/view types of console messages (errors, warnings, logs, exceptions) etc

Here are a couple UX things
- [ ] re-style the dropdown to be consistent with tailwind dropdowns
- [ ] badge the cog so that it is clear things are selected
- [ ] show counters next to options so we can see how many items are in each bucket
- [ ] separate exceptions into their own group since they're not console.x messages

<img width="458" alt="Screen Shot 2021-05-03 at 10 07 06 AM" src="https://user-images.githubusercontent.com/254562/116908170-6f72d300-abf7-11eb-81c6-52c082d42cbf.png">

**Comment by jonbell-lot23** [comment]
Note: we also discussed splitting Console and Events into their own tabs, and this would go hand-in-hand with that.

**Comment by jonbell-lot23** [comment]
@jaril I'm marking this is design-complete.

Jason's checkboxes are mostly self-explanatory, and if anything causes churn let me know and we'll work through them quickly!

And then notice the link to #2900 -- that's a meaty change! Between Jason's checkboxes and #2900, we'll make a lot of progress on this front.

**Comment by jasonLaster** [comment]
Closing as a dupe of https://github.com/RecordReplay/devtools/issues/2900

**Comment by jonbell-lot23** [comment]
I did some cleanup and these items are being tracked here: https://github.com/RecordReplay/devtools/issues/3203
