### ISSUE TITLE
Upload screen V3

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2532]

**Comment by jasonLaster** [comment]
I can see how the current UI can be confusing, but I am not sure the solution is to remove the video. The goal of this step is to encourage folks to think about what they just recorded. 

* Add a description
* Place the replay in the best workspace
* Perhaps add other metadata in the future too, a good jira ticket, labels, ...

All of these things are easier if folks have a video to reference and get some context. 

So, why are folks confused now? My hunch is it is a bit too similar to the current UI so they are not sure what is going on. I think we can solve this in a variety of ways, but I would start by making the Upload panel more prominent and then if we feel it is necessary modifying the video ui...

**Comment by jonbell-lot23** [comment]
The issue is that there’s no single call to action. We’re presenting a fully functional UI with some strange stuff on the side.

it should be a modal to maintain context without presenting dualling next steps.

**Comment by jasonLaster** [comment]
Correct me if i'm wrong, but i think you're saying there should be one CTA here and i'm suggesting we should make the Upload the Primary CTA. Is that right?

**Comment by jonbell-lot23** [comment]
Yup.
