### ISSUE TITLE
Show an Events panel in the Viewer

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2535]
**Description:**

Now that we've simplified the comments panel we should find a new way to show events such as mouse clicks. Once we have this panel it will be technically easy to also show other user interactions like keyboard events...

- [x] Add back an events panel in the sidebar
- [x] Add mouse click events

**Comment by jonbell-lot23** [comment]
Adding comment from #2637:

Devtools has:

Comments
Source
Pause
Viewer should have:

Comments
Events (pick an icon for this)
For now, let's just let the Events look the way they used to, but we've gotta add time stamps to them this time. Then we'll add other modifications on top of that.

**Comment by jonbell-lot23** [comment]
De-prioritising for now so we can focus on onboarding stuff

**Comment by jonbell-lot23** [comment]
I need to crawl back in bed, but here's a down payment:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/9154902/122464388-e4b13080-d00a-11eb-910f-3f7d2d681b64.png">

We won't do keyboard yet, but when we do it could look like this
