### ISSUE TITLE
Duplicate comments are created

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2551]
**Description:**

It's fairly common for multiple comments to be created by accident

e.g. https://replay.io/view?id=7522bf08-03f0-4bfc-89e2-9f246bbeb7b3
<img width="840" alt="Screen Shot 2021-05-07 at 9 58 10 AM" src="https://user-images.githubusercontent.com/254562/117483654-d4da0300-af1a-11eb-9910-4ab6d7ac0cfa.png">

**Comment by jasonLaster** [comment]
I think a simple fix would be to disable actions while comments are pending.

**Comment by jaril** [comment]
Fixed with #2558.
