### ISSUE TITLE
Clicking "Or discard" in the UploadScreen leads to error screen

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2552]
After clicking "Or discard" in the UploadScreen, the recording is deleted, but the devtools don't navigate away from the recording, so eventually you see the error message "Sorry, you can't access this Replay. If you were given this URL, make sure you were invited." (which is also shown whenever you try to view a deleted recording).

**Comment by jasonLaster** [comment]
this should now be fixed
