### ISSUE TITLE
Library: takes awhile to load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2568]
**Description:**

The library can take awhile to load when there are lots of replays

**Comment by hbenl** [comment]
Adding Postgres indexes (RecordReplay/backend#1970) helped, but the performance still isn't optimal:
The query for the user's personal workspace contains two subqueries, if those are run separately and their results inserted into the main query, all those queries together run faster than the unmodified query. In other words, the execution plan that Postgres creates for the unmodified query isn't optimal.
We could change our database code to run the subqueries separately or we could try to give Postgres a hint for the execution plan for that query (apparently this is possible using the Postgres library `pg_hint_plan`).

**Comment by jasonLaster** [comment]
What are the average / P90 times for these queries? @jazzdan is honeycomb now collecting these stats?

Are there other things here like adding limits.

**Comment by jazzdan** [comment]
We don't have this info yet but hopefully we will soon!

**Comment by hbenl** [comment]
RecordReplay/backend#2017
