### ISSUE TITLE
Multiple sources are shown

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2570]
**Description:**

Multiple versions of the same file appear

Example 1:

**Steps to Reproduce:**
1. go to https://replay.io/view?id=905288c2-f610-471a-98c2-9c544104a601
2. go to DevTools 
3. press cmd+p

**Expected**
1 version of `application-9e586eab0f44cc309d13` 

**Actual**
4 versions of `application-9e586eab0f44cc309d13`

Example 2:

**Steps to reproduce**
1. go to https://replay.io/view?id=c44db129-50b8-4735-8331-cf4b4cf57343
2. go to DevTools
3. press cmd+p

**Expected**
2 version of `SectionContainer` 

**Actual**
2 versions of `SectionContainer`

---

Replay: https://replay.io/view?id=c2a09d0f-a801-4cdf-900e-696b62a84a27&point=103845937239313203955335534296958800&time=63409&hasFrames=false

**Comment by hbenl** [comment]
Fixed in #2812
