### ISSUE TITLE
Add a back to library button in the header

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2579]
There used to be a back button at the very left of the header that brings you back to the library. A few months ago, we hid it inside the dropdown to the very right of the header to keep it from getting cluttered. I think we should looking into bring it back. 

I was on board with hiding it away since it was very close to the browser's back button, which I presumed would take you right back to the library anyway. That wasn't quite right—it's possible to open up a replay from elsewhere outside the library, so the back button is not a good proxy for the library button.

Also in testing, I've found users don't always figure out where the library button is stashed away. It could stand to be more obvious.

**Comment by jonbell-lot23** [comment]
See https://github.com/RecordReplay/devtools/pull/2656
