### ISSUE TITLE
Properly handle breakpoint positions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2589]
**Description:**

We recently broke breakpoint hits that span multiple navigations while fixing #2482 which had multiple sources that shared the same url.

We should add some end to end tests that document the current setup and then come up with an option that works for both. Perhaps including multiple source positions for breakpoints... similar to how analysis can have multiple locations...

**Comment by hbenl** [comment]
#2628 fixes setting breakpoints in sources that were loaded multiple times, but there are other issues (#2570, #2600 and probably others) that still need to be fixed.
