### ISSUE TITLE
Improve handling of unloaded regions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2597]
**Description:**

We currently treat the server saying that a region is unloaded as a surprising exception when it should be predictable (the server has told us it was unloaded) and recoverable.

Eventually we'll be able to ask the server to load the region. In the meantime, we should be able to tell the user that the region is currently not available. 

There are a couple of cases to handle
1. showing the log as "unavailable" instead of "loading"
2. showing an unavailable message in the pause panel

We can do this in two ways
1. we can wait for the server to tell us the point is unavailable and handle it gracefully
2. we can store unavailable regions and use that in the relevant protocol classes

The two approaches are pretty similar so i do not think it makes a big difference

STR:
1. go to  https://replay.io/view?id=fd2792fb-20b1-4bb9-8943-715c39756eaf&point=17524001900259946975893210265550926&time=10691.953391578121&hasFrames=true
2. add a breakpoint in DashboardViewer.tsx:29 

Notice the errors in the console

<img width="1322" alt="Screen Shot 2021-05-13 at 8 48 01 AM" src="https://user-images.githubusercontent.com/254562/118150955-f8dc8f00-b3c7-11eb-9b79-fb709e56cf46.png">

<img width="1323" alt="Screen Shot 2021-05-13 at 8 47 48 AM" src="https://user-images.githubusercontent.com/254562/118150965-faa65280-b3c7-11eb-9a01-4e8281649091.png"> cu

**Comment by kannanvijayan** [comment]
See #2618, #2592, and #2589.  This issue is closed for backend and should be closed if frontend is otherwise ready.
