### ISSUE TITLE
The breakpoint panel in the editor disappears

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2600]
I just navigated to a breakpoint hit and then the breakpoint panel disappeared...
https://replay.io/view?id=8586ea6f-5b0c-4b52-a3f6-dca00b4dc40a

**Comment by jasonLaster** [comment]
Left some comments - the widget is definitely cleared

**Comment by hbenl** [comment]
I think this happens when the source has been loaded multiple times, in this case there are multiple `sourceId`s of preferred sources with the same URL. The editor identifies sources by URL, so it will always show only one of them, but the breakpoint panel identifies sources by `sourceId`, so it will only be shown in the source where the breakpoint was initially set.

**Comment by hbenl** [comment]
Fixed in #2812
