### ISSUE TITLE
PreviewFunction overloading

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#261]
It looks like PreviewFunction is being used in two contexts:

Brian's change
https://github.com/WebReplay/webreplay-devtools/commit/6eee3689504d7385d53de8f9744d937b156615e7

My recent change
https://github.com/WebReplay/webreplay-devtools/commit/942600c65412055ff804ae7d73cc03045b747077#diff-6e91227f01484d9997046acf5813f490L33

Here is a recording of how this function failed for me
https://webreplay.io/view?id=de64003e-e666-4c48-8288-008ab9079ead

i believe my use case comes from the Outline view being used with Symbol data whereas your use case relies on grips...

**Comment by bhackett1024** [comment]
Hmm, I just saw exceptions being thrown there when ValueFronts were used with it.  Ideally we would be using ValueFront everywhere, and have a way to create new fronts for the functions in the outline view.  A slightly easier alternative would be to make this code work on both kinds of values.

**Comment by jasonLaster** [comment]
Yeah - this data comes from the parser worker, so just having it take two data types is pretty simple
