### ISSUE TITLE
[UX] Should be able to add comment without a comment

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2615]
For example, adding a comment to a line of code. It should be possible to add a marker without a comment alongside

**Comment by jonbell-lot23** [comment]
1) It should not be possible to see this state:
![image](https://user-images.githubusercontent.com/9154902/126916578-8eb3521b-e1b6-495e-8947-e573978e7afe.png)

We should always jump to the first hit. If that's not a good idea for technical reasons, we should at least let the comment button be blue and clickable, then make the jump then.

2) We should say comments are optional, and never dim the button with gray. Like so:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/9154902/126916680-8d17babb-6ce2-44bd-bd60-3c5086416ebb.png">

3) The comment can look the same as if the comment were empty, like so:
![image](https://user-images.githubusercontent.com/9154902/126916707-d160120b-74f3-433f-bd30-3c8d767d66c8.png)

4) Clicking a comment pointed to a line number should take you to that line number. It currently feels broken.

**Comment by jasonLaster** [comment]
> 1. It should not be possible to see this state:

This is a difficult case. 

1. i think it would feel funny to seek to a position just by adding a breakpoint
2. i also think it would feel funny seeking to an arbitrary position by clicking the comment button. 

I agree that the disabled state is awkward. I think i would prefer revisiting the "timeless" comment that would either appear at the top of the comments pane or use the current point in time. One advantage with this approach is it would also work if you want to leave a comment at a position in the code that was never evaluated.

**Comment by jonbell-lot23** [comment]
In this example, I'm clearly on line 39:
![image](https://user-images.githubusercontent.com/9154902/126931737-2e39f9f5-4205-4d83-9f9b-7168ce92efb0.png)

Then I click into it, and I see this:
![image](https://user-images.githubusercontent.com/9154902/126931799-b507f34a-b8b1-468b-8b58-9c96a084a7a9.png)

Because there's only one hit, it's dimmed. Then I have to hit the back arrow (??) to get it to evaluate. So I see two levels of awkward:

* It should not be be possible to see a disabled state, which we can fix with the "floating comment"
* But even with 100 hits, why is picking the first hit (or closest to the console message you clicked) considered "arbitrary" or "seeking to a position?" Technically, it's seeking. But conceptually, what's the scenario where you didn't want it to seek to the thing you just referred to? Is it an 80% case?

**Comment by jonbell-lot23** [comment]
Continued:

If I'm at 29 seconds, and I make a breakpoint that was evaluated at 2 seconds, then there are two options:

1. Keep me at 29 seconds, and show me an inert breakpoint (what we do today)
2. Jump me to 2 seconds, and now the breakpoint is actionable

I see that option #2 takes me out of my previous state. But if we do the "floating comment" idea, does that mean the comment will go to 29 seconds, since that's where I am? That doesn't align with what someone thinks they're seeing when they're looking at a breakpoint dealing elsewhere.

I think jumping someone to second 2 is a good idea, and then if you then close the breakpoint without taking action, we can jump them back to second 29.

It sounds strange, but our current experience is broken 😂

**Comment by jonbell-lot23** [comment]
I'm going to move this conversation over to https://github.com/RecordReplay/devtools/issues/3112.

The title of this issue is still accurate: we need the ability to add blank comments.

**Comment by jonbell-lot23** [comment]
This issue got other items included in it but I removed them to simplify this issue.

**Comment by jonbell-lot23** [comment]
Closing for now -- we can discuss and revisit.
