### ISSUE TITLE
Upload screen should never time out

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2624]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/9154902/118343757-dc368780-b57e-11eb-8052-8e5ec6703ce7.png">

This is happening but we shouldn't end up in this state

**Comment by jasonLaster** [comment]
(i thought this was done, but now i'm not sure)

**Comment by ryanjduffy** [comment]
Would this be avoided if the session wasn't created until after the user saved?

**Comment by jasonLaster** [comment]
@ryanjduffy yep

**Comment by jonbell-lot23** [comment]
@ryanjduffy Which is a general issue overall: See https://github.com/RecordReplay/devtools/issues/2737 where for a while things could go live on the public internet before you even decided to save it, let alone make it public! 😱

We addressed one component of that, but we have some more holes in this vein. Do veins have holes? You get the idea.

**Comment by jaril** [comment]
@hbenl Any thoughts on this? Right now, we initialize the session whenever we're looking at a Replay. Ideally, we should wait to see if the replay is not initialized yet (i.e. just finished recording, needs to show the upload screen). If it's initialized, create the session. If it's not initialized, don't create a session immediately but do it immediately after the user hits the save button.

The deferred session creation goes against the grain with how you implemented the `PageSwitch` component, so wanted to run it by you first!

**Comment by hbenl** [comment]
@jaril I've created a draft PR to show how this could be done in principle: #2624
Eventually we need to overhaul how the app is initialized, currently it is always initialized for a particular purpose (library vs. devtools vs. UploadScreen) and always needs to be reloaded to switch.
