### ISSUE TITLE
I logged in and was taken directly to the Upload screen

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2625]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/9154902/118344670-93cd9880-b583-11eb-8584-1b39d38feb8f.png">

I did not expect this after upgrading my browser and logging in.

**Comment by jasonLaster** [comment]
Did you login from the browser blue button?

**Comment by jonbell-lot23** [comment]
I believe so, but not 100% sure

**Comment by jonbell-lot23** [comment]
I'm going to close this for now, we've been addressing a lot of these sorts of cases.
