### ISSUE TITLE
[UX] Add left-hand icons to Viewer to be consistent with devtools

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2637]
Devtools has:

* Comments
* Source
* Pause

Viewer should have:

* Comments
* Events (pick an icon for this)

For now, let's just let the Events look the way they used to, but we've gotta add time stamps to them this time. Then we'll add other modifications on top of that.

**Comment by jasonLaster** [comment]
closing since its part of #2535
