### ISSUE TITLE
Can't add email jonbell-1@lot23.com

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2639]
![image](https://user-images.githubusercontent.com/9154902/118564166-f57c4580-b7c3-11eb-9764-e82d2f6b432e.png)

More to come, but this is enough to start with

**Comment by jaril** [comment]
This works on my end. Can you get a replay?

**Comment by jonbell-lot23** [comment]
Will try to get a Replay later today. Here's the Descript: https://share.descript.com/view/9UPmS3rUarG

**Comment by jasonLaster** [comment]
@jonbell-lot23 why did you add a descript and not a replay 😉

**Comment by jonbell-lot23** [comment]
> @jonbell-lot23 why did you add a descript and not a replay 😉

I already had the Descript handy because it can record my entire screen without a refresh.

But hurray! I was able to repro the issue in Replay. Here it is @jaril https://replay.io/view?id=8d48ef40-e893-469b-b7f5-8494de5de607

**Comment by jaril** [comment]
This is so weird. Any workspace I try to add `jonbell-1@lot23.com` to throws an Internal Error. Will keep investigating.

**Comment by ryanjduffy** [comment]
![image](https://user-images.githubusercontent.com/788456/118712905-31200b00-b7d6-11eb-8491-ccb4db01758f.png)

**Comment by jonbell-lot23** [comment]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/9154902/118722354-2d48c300-b880-11eb-95b3-3034b2c4f5bc.png">

Super strange!
