### ISSUE TITLE
Comment syntax highlighting doesn't work before opening DevTools

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2651]
Syntax highlighting in the viewer doesn't work until the user toggle DevTools mode once.

This is likely because we don't set up CodeMirror until we open the DevTools Editor.

Screenshot:
![image](https://user-images.githubusercontent.com/15959269/118709129-9a117e00-b7ea-11eb-87db-8629202ea9f4.png)

**Comment by jasonLaster** [comment]
This is related to https://github.com/RecordReplay/devtools/issues/2452
