### ISSUE TITLE
Replay skipped UploadScreen

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2658]
**Description:**

This Replay skipped the UploadScreen initially which is kind of bazaar.
https://replay.io/view?id=91e73dae-21f1-4bf8-b708-736a8df1eb43

Now when I refresh it shows up. I wonder if there is an if statement that would allow this to happen...

**Comment by jasonLaster** [comment]
Seeing this a bunch when we're waiting awhile to see the upload screen. It's like there's a timeout or something...

**Comment by jasonLaster** [comment]
This might be related to whether we know if you're logged in

**Comment by jaril** [comment]
Yeah—it looks like it's possible for the `isAuthor` check to run before we have the userId for matching to the recording's userId. Fixed now!

**Comment by hbenl** [comment]
This is still (or again) happening: I just made 6 recordings and only got the UploadScreen for 2 of them:
5155e45e-d780-41f4-adee-f15109bbb9ac - no UploadScreen
a71e5e09-9923-4b60-a669-6f42ca508384 - no UploadScreen
cc4f863a-1fb9-4c3e-b22e-4ad81b44e79d - no UploadScreen
6a9ed4ab-4ec5-4382-a481-8a445ca7dfa9 - this one showed the UploadScreen
02ac3732-700e-481d-883d-b22f38a83458 - this one showed the UploadScreen
96492cbb-2a9f-442b-bd68-86c69b1f4bf5 - no UploadScreen
When I open an uninitialized recording again, I get the UploadScreen for it.

**Comment by hbenl** [comment]
I saw this again today.

**Comment by jasonLaster** [comment]
@hbenl is there a way we can ensure this does not get skipped? For instance, if this ever changes while viewing DevTools the upload screen is immediately shown?

**Comment by jasonLaster** [comment]
this seems fixed
