### ISSUE TITLE
Add a "loading progress" indicator

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2659]
Simple spec here:
https://www.notion.so/replayio/Universal-Progress-Bar-91c5eb577d9c4514b1a2a2d9691b8f06

1. Add a menu item called "Loading Progress"
2. Selecting it launches a modal dialog with some simple loading status stuff

We'll modify the entry point, text, and what shows in the log. But that will come later, once we get something simple wired up that we can play around with.

**Comment by jasonLaster** [comment]
Could you sketch what you think would go into the modal?

This is a bit surprising because 
1. I don't think we need that much
2. Hiding the loading status in the modal makes it harder for folks to see the progress


This is sort of the minimal viable progress indicator. There might be other places to put it, but the advantage of surfacing a small % progress indicator is that folks will get the apple perceived perf win by seeing us compute something quickly. Of course, we also have to be fast too, so any processing slower than 10sec will be treated as a bug.

<img width="2727" alt="progress spinner" src="https://user-images.githubusercontent.com/254562/118844551-e4910a00-b87f-11eb-9551-bd137bcd767d.png">

<img width="1481" alt="progress2" src="https://user-images.githubusercontent.com/254562/118845396-97616800-b880-11eb-9584-efb383feca73.png">



https://packages.framer.com/package/marshallswain/progress-circles

**Comment by jonbell-lot23** [comment]
Yup, we're all in agreement that we don't want to hide the real version. I'm just asking for us to put it into the dropdown in a quick release because something is better than nothing, then we'll do the UX design for it.

The design you posted is too heavy and inconsistent. I'd consider it a UX/branding regression with real-world impact because despite not being an 80% case, it's taking disproportionate attention in the nav.

So the question is between "throw up something too heavy and refine it" versus "throw up something subtle and refine it." I'd like to go with subtle.

--

Modal: I was thinking modal because there are helpful things we can show there beyond percentage. Short term, I'd just say "Scanning: 47% complete" in the dropdown without needing a link.

**Comment by jasonLaster** [comment]
Thanks! It's good to see we're just discussing which way to err (too subtle, too heavy).

I see how you can feel like this progress indicator is commanding disproportionate attention in the nav.

Throwing out two other ideas for indicator placement. Mostly to prompt discussion and new ideas. What visible real estate would you use if you couldn't hide it?

By the way, one argument for NOT the header, is we only need this for DevTools so why have it in the global header!

## Source Tabs

Adding a floating indicator on the right side would be visible but not compete with anything too valuable.

<img width="1315" alt="processing 3" src="https://user-images.githubusercontent.com/254562/118906588-e3d59380-b8d2-11eb-94f5-8ae06f732dec.png">

## Bottom Left

I think this is a nice spot for a feedback, info, help thingy majig. Starting with this indicator might be a good way to learn how people perceive things down there

<img width="1335" alt="processing 4" src="https://user-images.githubusercontent.com/254562/118906596-e7691a80-b8d2-11eb-8ab7-3c83332d8294.png">

## Better tooltips

I think regardless of where we place the global indicator, a better JIT indicator would go a long way.

![indexing5](https://user-images.githubusercontent.com/254562/118906895-79712300-b8d3-11eb-8584-ab9534102c5e.png)

**Comment by jonbell-lot23** [comment]
100% to all of that.

1. I am pleased we are not trying to decide between JIT or global. The answer is clearly both. We already have some JIT loaders and indicators, we just need to add and tweak to make sure we don't have gaps.
2. I totally agree that putting it only in devtools is reasonable. I haven't done a full audit to find holes in that theory, but I was hoping that's how we could end up.
3. Source tabs: pretty great
4. Bottom left: pretty great
5. The word "Processing" is probably not necessary, which frees us up a lot. A fantastic circle loader, with a clear tooltip, with JIT tooltips elsewhere ... that's getting us 99% of the way there. I'm not sure the extra word is as important, as long as the circle is big and obvious enough.

**Comment by jonbell-lot23** [comment]
Design, zoomed out:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/9154902/119062038-dda5fb00-ba29-11eb-9333-addb16832ba2.png">

Zoomed in:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/9154902/119062054-e696cc80-ba29-11eb-886a-6c9cb3c4d425.png">

Details:
24x24
Background color: #ECECED
Foreground color: #353535
Spaced exactly like the other icons in the devtools
