### ISSUE TITLE
Avoid recomputing when breakpoint expressions change

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2661]
**Description:**

From @andarist 
> you could prevent recomputing stuff when editing the breakpoint expressions - it probably both impacts the perf & input delay but it also leads to some weird, distracting, effect - notice that I'm just moving the cursor in the input using keyboard arrows and the timeline jumps

https://user-images.githubusercontent.com/254562/118841292-0c32a300-b87d-11eb-9e95-d807a28b1f4a.mp4

**Comment by Andarist** [comment]
Here is the replay of the problem~: https://replay.io/view?id=639e3a7f-658e-45bf-9a73-28fb8bee1f09
