### ISSUE TITLE
[UX] Invalid recording ID should have a login button

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2664]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/9154902/118903746-8130d600-b96c-11eb-98a1-36d2ba52b3d1.png">

This page looks like a 404 but there are cases where you just haven't been given access, or you've been logged out.

**Logged in text:**
Invalid recording id

This Replay could not be loaded. Please make sure you have permission to access it.
[refresh button]

**Logged out text:**
Invalid recording id

This Replay could not be loaded. Please log in.
[log in button]

**Comment by jaril** [comment]
Just saw this happen for a private recording when view as 1) a logged-out user and 2) a non-collaborator.

https://replay.io/view?id=b31b39cc-eabb-4b30-b9a7-4c9d9b79c64d

The appropriate authentication error is displayed. But then, we receive an error from the backend re: Invalid Recording ID, which generates another modal that gets stacked on top of the original error.

We should bail from that second error display logic if there's already an error present.
