### ISSUE TITLE
Prompt invited users to download Replay

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2673]
**Problem**
A bunch of folks are being added as collaborators, teams, etc... and not given a path to download Replay!

**Solution**
We should show folks a dismissable nag to download the browser.

> One probably obvious thought: I sent him a link to the replay, and bc he didn't have it installed, he basically just opened it in Chrome. When you do come out of closed beta, it would be cool if the person at that link, visiting it in [non-Replay browser] could see a download link to Replay. 

From AJ

**Comment by jonbell-lot23** [comment]
We do have a download link in the menu, so this comes down to “do we want someone’s first experience with Replay to be a nag screen asking them to download a whole other browser?”

I don’t think so. Let people see that Chrome is all they need in order to be a collaborator and don’t make them swat away screens in order to do that.

If we did a nag, we’d want it to be after x loads, not during the vital first impression.

**Comment by jasonLaster** [comment]
Thanks. That's so easy to miss :)

Gosh - trade-offs. We definitely want folks to have a great first experience, but also it's sad to think folks might not realize that they too can record. Lets see what we can do.

**Comment by jonbell-lot23** [comment]
I just realised when I drew up this flow chart that sending a "Welcome to Replay, here's a little bit of info, plus a download link" email really helps us here:

[User is invited] -> download link
[User has a Replay shared with them] -> Viewing Replay signed out -> Sign in -> Get onboarding email
[User is given direct URL] -> Viewing Replay signed out -> Sign in -> Get onboarding email

This gives us two great onboarding flows: the collaboration one, which should focus on commenting, and general Replay onboarding, which can focus on all the cool things we can do.

**Comment by jasonLaster** [comment]
closing as wee an revisit once the l

**Comment by jasonLaster** [comment]
This could be a dupe of #2335

**Comment by ryanjduffy** [comment]
@jonbell-lot23 - Let me know what you think for next steps on this one.

**Comment by jonbell-lot23** [comment]
If the library has a launch/download link, and it's also in the menu in the product, I think we're done!

**Comment by ryanjduffy** [comment]
Neat! That PR landed this morning (behind a feature flag) so we can call this done!
