### ISSUE TITLE
Uninvited people can record a Replay but then they get an infinite blue screen

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2684]
Went to random Replay URL ->
Clicked sign in ->
From Google, set up brand new email address (not invited) ->
Landed in the library ->
Pressed record ->
Asked to sign in again ->
Sign in successful ->
Record button active ->
Recording stalls forever on upload

![image](https://user-images.githubusercontent.com/9154902/119060659-c44f7f80-ba26-11eb-9d6b-77d2be81a74a.png)

Rather than letting them go all the way to the blue screen, we should do this:

* Don't show the library. Instead show a blue background and a modal dialog that tells them they haven't been invited to Replay yet, with an email link to support if they think they're seeing the issue in error.
* Some people might record anyway. So let's message them when they hit the infinite blue screen with the same approach. Blue background, modal, message, link to support.

**Comment by jaril** [comment]
I created a new account (uninvited). That account can create replays and view them just fine.

**Comment by jasonLaster** [comment]
Oops. That's just as bad.

We should show a blue background and a modal dialog that tells them they haven't been invited to Replay yet, with an email link to support if they think they're seeing the issue in error.

**Comment by jaril** [comment]
Just saw this happen when viewing a private replay as an anonymous user.
