### ISSUE TITLE
The library is missing a "Launch Replay" button

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2688]
Now that we can determine whether or not you're in the browser, we should do this:

In Replay:
(Do nothing, since you're already in Replay, right?)

Not in Replay:
Blue button that says "Launch Replay"
Clicking it launches Replay (do we have the technical ability to do this?)

**Comment by jonbell-lot23** [comment]
Here's how it should look in the Replay browser (no button because you're already in the browser):

<img width="649" alt="image" src="https://user-images.githubusercontent.com/9154902/120244855-7c024e00-c2bf-11eb-9811-4191b70bea95.png">

Here's how it should look if you're logged in but not in the Replay browser:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/9154902/120244867-87557980-c2bf-11eb-95e7-34d31255e778.png">

**Comment by ryanjduffy** [comment]
@jaril - I'm looking into the gecko-dev side of this now. The frontend side should be simple so I'll plan to tackle that as well if that's okay.

**Comment by jonbell-lot23** [comment]
Hello @ryanjduffy ! No rush, but I'm going through my onboarding audit and curious if you have an ETA for this?

**Comment by ryanjduffy** [comment]
It's next on my list once the error page wraps up. Probably before Monday? 🤞

**Comment by jonbell-lot23** [comment]
Awesome, thanks! Again, no rush but just getting some clarity for my design journal where I say WOW WE ARE MAKING GREAT PROGRESS

**Comment by jonbell-lot23** [comment]
@ryanjduffy See also: https://github.com/RecordReplay/devtools/issues/2335

**Comment by ryanjduffy** [comment]
Sharing an early implementation. Known issues:

* Button styling needs adjusted. It's too tall and too close to the ... menu. The hover styles are not good either.
* Currently launching two copies of replay on my box. Could be because I have two different installs (from my local build and in /Applications)
* No way to close the modal yet.
* Modal styling needs proper styling / copy.


... probably more .... it's an early impl after all :)


https://user-images.githubusercontent.com/788456/121760624-9b2f8580-cae0-11eb-8489-3c0311af21ab.mp4

**Comment by jonbell-lot23** [comment]
Thanks, @ryanjduffy !

1. The button colour and hover state can both be called with tailwind variables:
var(--primary-accent)
var(--primary-accent-hover)

2. Agree, the height should be pulled in a touch.

3. Seems like you don't need an "open replay" button in the modal. Let's drop it outright.

4. In my view, we can add a close button and ship this, then I'll tweak copy and visuals more.

**Comment by ryanjduffy** [comment]
3. Agree. I added a url endpoint for this as well so we could link into it externally and I think the button will be useful there since there isn't a backing page with the button. Not useful in the modal.

4. Just a close icon in the top right or a primary button where the 'launch' is now?

**Comment by jonbell-lot23** [comment]
Let's do the word "close" in the top right for now. We've never used this particular pattern so I'll standardise it later.
