### ISSUE TITLE
Add a team invitation approve step

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2690]
**Description:**

When someone invites you to a team with teamflow, teamflow does a great job of giving you an opportunity to first join the team before you're in the flow. 

We should do something similar. When the user goes to view the library and there's a pending invitation, we should show a modal that prompts them to accept or reject the team.

<img width="1617" alt="Screen Shot 2021-05-19 at 5 31 02 PM" src="https://user-images.githubusercontent.com/254562/119066558-e3053600-b994-11eb-982f-133ee7c452fc.png">

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/119768072-210dd700-bf0c-11eb-950c-f519f0f3582f.png)

![image](https://user-images.githubusercontent.com/9154902/119768086-266b2180-bf0c-11eb-8c03-62b16dc14eb3.png)

![image](https://user-images.githubusercontent.com/9154902/119768099-2bc86c00-bf0c-11eb-9ffa-464d678ab6e0.png)

![image](https://user-images.githubusercontent.com/9154902/119768116-3256e380-bf0c-11eb-98e2-52afdd0cbca7.png)

Working through the onboarding flow at https://github.com/RecordReplay/devtools/issues/2720 and this is a minor branch off the core flow.

**Comment by jonbell-lot23** [comment]
Here's the design, with TailwindCSS:
https://play.tailwindcss.com/XKTp6N3Rst

![image](https://user-images.githubusercontent.com/9154902/120123549-8ced8980-c203-11eb-8e01-b00ba59a98c7.png)

**Comment by jaril** [comment]
They click a link from their e-mail (because they were invited to a Replay team)
See the "you were invited to join the X team" prompt and sign in button
Sign in
Show them that team
