### ISSUE TITLE
Can't create comment using only keyboard

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#2691]
**Description:**
When I'm typing a comment I want to quickly press enter or ctrl+enter or something to create the comment, rather than have to click "Post" with the mouse.

**Comment by jaril** [comment]
The shortcut for post is Cmd+Enter. Can you check if that works on your end?

https://user-images.githubusercontent.com/15959269/119168514-fa90fd00-ba2e-11eb-8ffe-ace2996d17c5.mov

**Comment by jazzdan** [comment]
Ah yeah that works! Is it ctrl+enter on Windows?
