### ISSUE TITLE
Comment editor doesn't appear immediately when adding a recording's first comment

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2692]
When adding a comment (that's the first comment) on a replay, clicking on the video opens up the new comment card but it takes for the input box to load. 

This is likely because the pre-load logic for DraftJS is attached to the CommentCard component. When there are no comments displayed, DraftJS isn't loaded until the user adds a comment.

https://github.com/RecordReplay/devtools/blob/master/src/ui/components/Comments/TranscriptComments/CommentCard.tsx#L90-L95

**Comment by ryanjduffy** [comment]
Yup, good call. That should be moved up a level.
