### ISSUE TITLE
Better team invitations UI

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2694]
Filing here for @jonbell-lot23 to prioritize accordingly. This can be closed when we've decided the action (new issue or ignore) for each item.

The team invitations UI does the trick, but it's not great (yet) at instilling a lot of confidence. Things to think about:
- [x] Add the inviter name and email address to the invitation.
- [ ] Add team metadata, e.g. number of replays, members
- [ ] Long term: Find a better way to display pending team invitations that doesn't come at the cost of replay list.

**Comment by jonbell-lot23** [comment]
Closing for now -- not highest priority
