### ISSUE TITLE
Show a loading bar while uploading sourcemaps and scanning

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2696]
Add a loading bar for the uploading sourcemaps and scanning parts of the Replay.

![image](https://user-images.githubusercontent.com/15959269/119203645-8de32600-ba61-11eb-9116-a61a38b1b838.png)

**Comment by jonbell-lot23** [comment]
Love it. I think we should animate from blue to white or else it'll still feel jarring. Here's an animation @jaril:
https://share.descript.com/view/RjxhLwWN7Lg

**Comment by jasonLaster** [comment]
Thanks Jon!

**Comment by jaril** [comment]
Blue screen
- Right now it's a spinner => Change it to show a progress bar as well as some description of what's happening

Skeleton Loader
- Bye bye. Because land people in nondevview until scanning is ready and then they can click on devtools.

**Comment by jaril** [comment]
Rip out skeleton loader and put in place the white loading screen instead.

UI still takes as long as it did before to actually load.
