### ISSUE TITLE
Can't view replay I previously had access to

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2699]
My STR for https://github.com/RecordReplay/gecko-dev/issues/292 require visiting a specific replay, https://replay.io/view?id=02d1b4aa-16f4-4cba-a00d-2863f5c8b70a&point=0&time=0&hasFrames=false, which I was previously able to view without logging in.  Now I can't view the replay ("this replay is private") even after logging in, and can no longer reproduce my STR.  Did the permissions on this replay change, or is something broken?

**Comment by bhackett1024** [comment]
This WFM now, the problem seems to be a GraphQL outage we had earlier.

**Comment by jasonLaster** [comment]
This replay is generally available when graphql is up, but even when it is down it is now debuggable via `&test=true`

https://replay.io/view?id=02d1b4aa-16f4-4cba-a00d-2863f5c8b70a&point=2596148429360471873509589818277980&time=1459&hasFrames=true
