### ISSUE TITLE
Share emails not getting sent?

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2710]
Steps to repro:

* Open a Replay
* Click Share button
* Add an email

Expected:

* An email should appear

Actual:

* I've tried several examples, and Ryan did too. None of the emails seem to appear, and I've looked at spam/filtering without luck.

**Comment by jaril** [comment]
This is expected. We send emails whenever a non-registered user is invited to a Replay as a collaborator. We don't do the same for registered users. Yet.

Switching this into a feature request so we can prioritize accordingly.

**Comment by jasonLaster** [comment]
ooh - i love that feature request!

**Comment by jonbell-lot23** [comment]
Ah, here's another consideration:

"Replays shared with me" is successfully showing Replays shared with me. We might consider a notification in the library. "Yo, you were recently added to such and such" just like how we message pending invitations.

Sounds to me like a straight-up notifications drawer is probably in our future.

**Comment by jasonLaster** [comment]
Yep. Both. And i think courier can help us with that too

**Comment by jaril** [comment]
This is all done via replit/courier so there's no corresponding PR, but here's the current implementation.

https://user-images.githubusercontent.com/15959269/120585552-ec17ed80-c3ff-11eb-9770-0e3e8defa2b7.mov

This sends a simple email to the person who is being invited to the replay with a link to that replay.
- **For registered users:** This will likely behave exactly as you expect. Whenever registered-user@gmail.com gets invited to a replay, they get a notification e-mail. 
- **For non-registered users:** For now, this does not send an e-mail to the non-registered user. Once we land [this patch](https://github.com/RecordReplay/backend/pull/2181) tomorrow, we should get an experience closer to a registered user's.

**Comment by jonbell-lot23** [comment]
Roger that, @jaril -- will file a separate bug. Thanks for the handoff!

**Comment by jonbell-lot23** [comment]
See https://github.com/RecordReplay/ops/issues/90
