### ISSUE TITLE
Video playback always starts at the beginning

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2722]
When I enable the video playback feature in Firefox Developer Edition (89.0b15), playback always starts at the beginning, not the point in time that I have selected in the timeline. It seems that `Video.seek(time)` doesn't work in Firefox 89.

**Comment by hbenl** [comment]
I've just seen this happen in Chrome as well. It doesn't happen all the time though.

**Comment by hbenl** [comment]
This could also be related to RecordReplay/backend#2119 : if I initially seek to a point within the first 20 seconds, playback always starts at the right point in time. Only when I seek beyond the first 20 seconds (i.e. beyond the point where the video mysteriously stops), I see this issue.

**Comment by jasonLaster** [comment]
@hbenl can you repro this?

**Comment by hbenl** [comment]
This was caused by RecordReplay/backend#2119, which has been fixed.
