### ISSUE TITLE
Comment edits take a while

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#2724]
**Description:**
When I edit a comment, the edit goes through but the old edit text stays there for a while.

**Steps to Reproduce:**
https://replay.io/view?id=b46d8838-9af8-42d2-bf0d-2c550f325665

**Expected Result:**
I would expect the comment to be optimistically updated, but greyed out until the edit goes through in the database.

**Comment by hbenl** [comment]
The `updateComment` and `updateCommentReply` mutations should return the modified comment (just like the `updateRecording*` mutations return the modified recording), then the cached comments could be automatically updated, without having to implement optimistic updates.

**Comment by jasonLaster** [comment]
@hbenl is this better?

**Comment by hbenl** [comment]
> @hbenl is this better?

It would have made the frontend code more straightforward (compared to the attached PR). The downside would have been that the delay would only have been reduced but not completely removed.
