### ISSUE TITLE
Should clearly explain why breakpoints are not editable

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2735]
**Description:**

This replay shows how it can be unclear when a breakpoint is not editable 

https://replay.io/view?id=ec3d5be6-7eeb-448e-a3d8-2894d190442a&point=51273931488214264215177777360405495&time=25663&hasFrames=false

**Comment by loganfsmyth** [comment]
Jason from Glide ran into this. Surprised me at first too because there wasn't any UI feedback.
