### ISSUE TITLE
It's possible record something and have it go live without confirming first

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2737]
Just had this happen:

1. Recorded something in Replay browser
2. Taken straight to Replay but I was logged out
3. I think when I clicked log in, I was shown the upload screen
4. Pretty sure I clicked away and didn't successfully upload it
5. Pretty sure it was uploaded

Here's the link: https://replay.io/view?id=6890136a-abbe-4c49-92b4-804bc4a7996a

**Comment by loganfsmyth** [comment]
Hey Jon, could you clarify which part here is the part you're reporting as the issue? Is it that at step 2 you were taken right to the replay? Sounds like maybe we're skipping the `isInitialized` check if there is no user maybe, and instead we should be doing something else, like showing "access denied, please log in" or something?

**Comment by jonbell-lot23** [comment]
I think we have two issues:

* I should never arrive in devtools logged out right after recording. I'm clearly logged in well enough to record.
* I should never see a devtools player if I haven't chosen to publish first.

From a UX standpoint, a user will begrudgingly understand that sometimes they need to log in again. But if I record something sensitive, want the option to discard it without it being published, but discover the file has been uploaded publicly without my consent, that's super bad.

It's possible I misremembering and I did choose to upload. But I'm 90% this got posted live without permission.

**Comment by loganfsmyth** [comment]
Cool, agreed. The second point is definitely something we should fix ASAP.

The first point is much more complicated and blocked on a ton of other discussions.

**Comment by jonbell-lot23** [comment]
Roger that @loganfsmyth, will rename issue to reflect

**Comment by jasonLaster** [comment]
I think this is done...

**Comment by jonbell-lot23** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/9154902/121112367-6a431c80-c864-11eb-8af4-b84d8789a5ea.png)

In this recording, I haven't yet committed to Save & Upload, but the URL is publicly viewable.
