### ISSUE TITLE
[WebReplay] is missing locale strings

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#274]
The crash report UI is missing localized strings. Hopefully we an hardcode the browser to just use the english properties...

img width="1293" alt="Screen Shot 2020-07-23 at 5 23 22 PM" src="https://user-images.githubusercontent.com/254562/88350904-63252580-cd09-11ea-855c-61572c82a736.png">
<img width="3120" alt="Screen Shot 2020-07-23 at 5 22 37 PM" src="https://user-images.githubusercontent.com/254562/88350909-66201600-cd09-11ea-9b07-202ced53027e.png">

**Comment by bhackett1024** [comment]
This looks like the same problem as https://github.com/RecordReplay/gecko-dev/issues/145, which is fixed now (though not yet in the latest browser).
