### ISSUE TITLE
Last paint is shown before jumping playhead

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2744]
* Recorded a Replay
* Clicked through upload screen
* Skeleton loader
* Playhead stuck to the end of the recording
* After a bit (10 seconds?) the playhead jumped to the start

Expected:
* We shouldn't show the video playback region until it can show the first paint

**Comment by jasonLaster** [comment]
Is it possible to get a replay for this? It's hard to figure out from the description...

**Comment by jonbell-lot23** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/9154902/120248463-5d09b900-c2cb-11eb-8055-029ecd089920.png">

Notice how in this image our play button is a reload button, and the time is set to the end. In this video it only lasts for a second, but on other Replays I've had it last longer.

Here's a Replay: https://replay.io/view?id=24591fcd-729c-48d8-a126-4759b69f4042&point=32776373922348453504125223558971934&time=14279&hasFrames=false

(Most of the time these issues aren't reproducible in Replay because of the full page reload, and the fact that it's in Replay's upload flow. But we lucked out this time because I can reproduce it!)

**Comment by jonbell-lot23** [comment]
I just recorded this Replay and on load it goes to the last frame rather than the first one:
https://replay.io/view?id=052359c2-7b78-40c6-a48f-cc211616047f
