### ISSUE TITLE
Breakpoints not capped at 100?

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2747]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9154902/120249708-df947780-c2cf-11eb-8f09-e31540c368b6.png">

This breakpoint is called 374 times, which seems to work other than the browser error. 

Whether we revise our cap upwards or fix the bug, we should make a demo Replay with a lot of breakpoints that we can all refer to. When this is addressed, I'm going to address https://github.com/RecordReplay/devtools/issues/2422

**Comment by jasonLaster** [comment]
the limits are 200, 500. That's surprising that this would trigger a browser slow down though. Lets see if it repros for others.

Can you share the url you're using here? I wonder if it's partly due to other console messages too...

```
pref("devtools.maxHitsDisplayed", 500);
pref("devtools.maxHitsEditable", 200);
```

**Comment by jonbell-lot23** [comment]
Here's the Replay:
https://replay.io/view?id=1565076d-516a-4a77-986c-374a62471e6b

Here's the page I tried:
https://ep-gatsby.lot23.com/ (just clicking around on things for a while is how I got the numbers high)

**Comment by hbenl** [comment]
#2784 fixes the performance issue, which happened when you set a breakpoint in a source with multiple identical copies.

**Comment by jonbell-lot23** [comment]
@hbenl and @jasonLaster I'm still seeing this issue.

Repro steps:

1. Go here: https://replay.io/view?id=1565076d-516a-4a77-986c-374a62471e6b&point=185624612693923894367722486921953579&time=71919.28150714595&hasFrames=true
2. Open file songs.js
3. Click on line 28

Expected:

If we're limiting at 500 hits displayed and 200 editable, this example with 374 hits should show different behaviour.

Actual:

Everything appears to load normally for me.

//

Separate issue: can someone please point me to a Replay that has enough hits to trigger this different behaviour? I'm trying to reproduce it to provide UX for issue https://github.com/RecordReplay/devtools/issues/2422

**Comment by hbenl** [comment]
@jonbell This works for me, the logpoint is not editable.

> Everything appears to load normally for me.

The logpoint should load normally. It just shouldn't be editable, i.e. clicking on the log expression should do nothing.
