### ISSUE TITLE
Replay stalls when I don't have access

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2750]
Go here and it'll stall out rather than saying you don't have access:
https://replay.io/view?id=938323f7-b056-44fb-8431-365896437633&point=28233114176857742571739553770506004&time=12178&hasFrames=false

**Comment by jasonLaster** [comment]
@jaril @ryanjduffy did we fix this?

**Comment by jasonLaster** [comment]
Yep - this should show a blue error message

**Comment by jasonLaster** [comment]
https://replay.io/view?id=675b7cec-4408-454a-ba61-8ccaab21d3e2&point=24338891525377561451336720697001661&time=9276.26917632487&hasFrames=true

**Comment by jasonLaster** [comment]
<img width="882" alt="Screen Shot 2021-06-08 at 8 18 55 AM" src="https://user-images.githubusercontent.com/254562/121212476-3e0ea800-c832-11eb-8276-408883996dab.png">

This gets you pretty close, the two blockers are

1. copy
2. checking to see if the user is logged in first

```diff
diff --git a/src/ui/actions/session.ts b/src/ui/actions/session.ts
index e21c4e83..9cdfda7f 100644
--- a/src/ui/actions/session.ts
+++ b/src/ui/actions/session.ts
@@ -65,7 +65,20 @@ export async function createSession(store: UIStore, recordingId: string) {
     store.dispatch(actions.setUploading(null));
     prefs.recordingId = recordingId;
   } catch (e) {
-    if (e.code == 31) {
+    if (e.code == 9) {
+      const currentError = selectors.getUnexpectedError(store.getState());
+
+      // Don't overwrite an existing error.
+      if (!currentError) {
+        store.dispatch(
+          setExpectedError({
+            message: "Private Replay",
+            content: "The replay is unavailable. <><><><><><><>",
+            action: "sign-in",
+          })
+        );
+      }
+    } else if (e.code == 31) {
       const currentError = selectors.getUnexpectedError(store.getState());

       // Don't overwrite an existing error.
```

**Comment by ryanjduffy** [comment]
I was just looking at this too. Should have an initial fix soon. Couple questions/comments:
* Right now, we're swallowing errors when there is an existing unexpected error. Should we log them to sentry?
* The root cause of the "hang" is unhandled errors since this method rethrows for other error codes. I think we should have a fallback generic error as well to avoid that case.
* When the error _is_ handled, the UI moves past the blue spinner and pretends to be loading in the background. Hoping for a quick pointer on how to reset the app state to keep it on the loading page. cc: @jaril

**Comment by ryanjduffy** [comment]
One more ... what are your thoughts on the user's auth state? It looks like the backend responds with the same code for an invalid recording vs a unauthorized recording so I think our copy will be the same for an auth or anon user: "That recording either doesn't exist or you don't have access"

**Comment by ryanjduffy** [comment]
> When the error is handled, the UI moves past the blue spinner and pretends to be loading in the background. Hoping for a quick pointer on how to reset the app state to keep it on the loading page.

I think `DevTools.tsx` needs an additional check to handle this correctly.

https://replay.io/view?id=d91b5d12- fec1-4467-bcc3-7247fca6e15f&point=6814889627895759849468561400530802&time=4182.719467271181&hasFrames=true

**Comment by ryanjduffy** [comment]
I pushed a PR with some initial copy but updates welcome!
