### ISSUE TITLE
Console Rewind/FastForward markers sometimes aren't available right away?

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2773]
I was just looking over this recording https://replay.io/view?id=ed50543e-381b-4950-9184-cae09d698f3c and I was confused because I couldn't click on a console message to jump to that point in time. I'm not sure what's up exactly. After waiting a minute or 2, they did start showing up. Is there some dependency to see them? If so, it's very confusing to not get any UI feedback.
![Kapture 2021-06-04 at 11 20 56](https://user-images.githubusercontent.com/132260/120846677-55465080-c527-11eb-8968-4fb51b5876e2.gif)

**Comment by jasonLaster** [comment]
closing as we haven't reproduced in 2 months
