### ISSUE TITLE
[Inspector] Show whether a property is used

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#278]
The firefox devtools have server side logic to check that properties in CSS rules have an effect on the page --- the name is valid, and the property has an effect on the element.  We don't expose this information in the WRP currently so this logic is disabled, and properties are considered active/used by default.

See `src/devtools/client/inspector/rules/models/test-property.js`, `isValid`, `isUsed`, `isNameValid`.

**Comment by jasonLaster** [comment]
https://searchfox.org/mozilla-central/source/devtools/server/actors/styles.js#1670

**Comment by hbenl** [comment]
This seems to be fixed in the new rules view.
