### ISSUE TITLE
2 console messages are shown for 1 breakpoint hit

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2782]
### Description

See this replay

https://replay.io/view?id=2513fd0e-f274-4a42-a7c6-d63b17cab999&point=64254673627925381566142521748227781&time=26447&hasFrames=false

### Steps to Reproduce

1. go to https://replay.io/view?id=bf2f8245-8e05-472b-9f19-e0e628f38d90&point=1298074214909547988795216468377673&time=1397.489136451702&hasFrames=true
2. go to viewController.ts
3. add a breakpoint in the constructor

NOTE: When i just tried this i sometimes got 1 hit which is super weird. but even then i'd get 2 messages in the console

**Comment by hbenl** [comment]
This was another multiple-identical-sources issue, already fixed with #2784.
