### ISSUE TITLE
Explore improving UX around interaction of console messages and breakpoints

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2786]
In this loom which @Andarist created https://www.loom.com/share/da5010eec37041e3a01f4c6d9eb9eba2, at around 2:40 there is an issue where after jumping to a console message, it's possible to rewind to a breakpoint on the same line as the message, even though in the UI it seems like we're paused at the same place.  This happens because jumping to a console message brings the browser to the console.log call itself, which is a different place from the start of the line which logged the message (which is where we are after setting a breakpoint).  This is confusing, and it would be good to think about ways the UX could be improved here.  One option would be to find a way to distinguish the two cases with an icon or something when we are inside the console message, another option would be to find a simple way of flattening these two points together in the UI when stepping / using breakpoints, and maybe there are others.

**Comment by jasonLaster** [comment]
Removing from planning since this is more of a general UI polish which we should get to when we have cycles than a project that relates to launch
