### ISSUE TITLE
UX feedback (to organise)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2798]
Jason at Glide:

* New icon for the pause tools is much better
* This should be editable:
![image](https://user-images.githubusercontent.com/9154902/121259183-e3458100-c903-11eb-84d5-817f3a9978f6.png)
* This bar needs a label:
![image](https://user-images.githubusercontent.com/9154902/121259208-eccee900-c903-11eb-80b1-d1df66180714.png)
* Why is reverse step over not shift-F10?
* control-click to go to the method I'm hovering over instead of clicking a tooltip would rule

**Comment by jonbell-lot23** [comment]
@jasonLaster can you tell me which of these you'd like to address? Here's what I think:

* UX bug: dragbar thing needs a label (not sure what it's called)
* Feature request: editable panel (not sure what it's called)
* Feature request: control-click to go to a method

**Comment by jasonLaster** [comment]
UX bug: dragbar thing needs a label (not sure what it's called)

> Good call, everything should have a label. The bar visualizes where you are paused in the function, which is referred to as a frame when you are there. A simple label would be "Frame progress".

Feature request: editable panel (not sure what it's called)

> I think Jason would like to be able to edit the logs here. I think that is a bit too advanced for the time being. Safari has it and it feels to pro-user... :)

Feature request: control-click to go to a method

> This gets tricky when you want to draw a visual indicator like an underline, but the simple version is easy.

**Comment by jonbell-lot23** [comment]
Closing this because the last item we're working on is https://github.com/RecordReplay/devtools/issues/3113
