### ISSUE TITLE
Bug: Missing code hits

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#2815]
**Description:**
TS playground has no no hits for multiple places that I've tried:
<img width="403" alt="Screenshot 2021-06-10 at 23 59 31" src="https://user-images.githubusercontent.com/9800850/121602690-fcefe100-ca47-11eb-910a-3fb2176d8c3f.png">

This one should definitely have a single hit - it's the function that leads to the error diagnostic being created, the one that is visible on the attached loom/replay. On the loom I've also visited the very same playground with Chrome and I've been paused at this call site successfully.

**Steps to Reproduce:**

This is a little bit tricky (but just a little bit) because I've tried to use a **local** build of TypeScript there.

To get to that you need to clone TS repo and prepare it:
1. clone my fork of TS repo and use this commit: https://github.com/Andarist/TypeScript/commit/26aecc41bae28d6f0ca1fb9f38818899ac9e86ef
2. `npm install`
3. `node ./scripts/createPlaygroundBuild.js`
4. visit [this playground](https://www.staging-typescript.org/play?ts=dev#code/GYVwdgxgLglg9mABBATgUwIZTQZQgCzQFsMAeAFQD4AKDAfgC5EMwBPASifMQG8AoRInRQQKJBgDcfAL58+MMNhTAMENIgCiANzSKA8gCMAVmmi8BiKKwAOaJgGcoKBQHMpsvlduIAsqvwKuATEZOQAwgjYAB5QADSI5Nq6UIhoMboAJvaaOvrGplCUiAC85oL2wSSMZYLIkWlQ1eH1MVK1qblQ9k1Jim2I0v0I1fztANoA0ogKCb1QYwBEXmgLALqrIxbtqrAI3UzU0FFcEYoN7CVFWnAwGf2CgxbSiABkNYIA9B+WAdkELC40NkDGh8BgtPAUEwjCBHMwkAolPYCvAkAB3GBQfDw1gAP0QcHyZmWW0QCwAVAtqmAQEQQSh+o9HnwMqYADYYdCIUCQXZIVCYbB+AiBCinaJxWadVLpMBZXiWGx2RCOZxgFwDGgWCqEEhMYUBMBBXWhcUNeKJTqUPicRDXW5STxK3ysM0xEoKsAYIjK1WuAZSZYuuYeniK2xMBY4ACCAE0APoACQ0ABkU3oFgG5F9EICjc4INkFMA0Ch0BlEAYMMiKwgyUHrCg4BDWSh7As+AKsGgDYFqKMVZUMEwB4IIC0oEwu9g8CbSD5XROaOxYqS0J17FP0N3ZyF56w5svVw9jwSwCPSTGE8m03oL+1Pt8AEIAJT0Ew0ADl4uvdD84CALjYmihBIPgzalv6EEoD86gAAY7Ki9hwYgjZwLYKBWIgaLqBALAqmg6hYrhcBlgUbKsNMYAlmRGQfGhLZoBWQbAKRiBwUccGkoIiF7AcRwXMURSjg+GBsqWUCHFAUQAHRej67D3LU0inieTyrtIinZt8OZpNYbIwBAmIUahTaMRWeaQYWfA5tOPb+KKC5upKh79jZ3yCAgF45u0V5Jqm6beR5D45gA6noL4TDg7kPjx0BIfx0mCcJMWxTx4mYVJsnyWgWk+Q+Kmpcpq75YVOaaVIQA)
5. Now you should be able to open `typescriptServices.js` file and search for `function assignParameterType` there

* Video (Loom): https://www.loom.com/share/da5010eec37041e3a01f4c6d9eb9eba2
* Replay: https://replay.io/view?id=aaabf130-30ad-44e1-a265-74827b022928

cc @bhackett1024

**Comment by jasonLaster** [comment]
This is another example of a missed breakpoint hit https://github.com/RecordReplay/gecko-dev/issues/347

**Comment by hbenl** [comment]
`typescriptServices.js` is loaded twice: in the main thread and in a worker. The breakpoint is hit in the worker. Replay doesn't support inspecting worker scripts yet, so only the source and breakpoint hits from the main thread are shown but there are no hits on the main thread.

**Comment by hbenl** [comment]
By the way, some reproduction steps were missing:
2a. `npm run build:compiler`
2b. `mkdir internal`

**Comment by Andarist** [comment]
@hbenl thanks for checking this out! had no idea that there is currently such a limitation - it makes more sense now :p Is this something on your nearest roadmap? Or not as important for now?

> By the way, some reproduction steps were missing:

Sorry for that - I probably had those things executed already from some older plays with TS repo. Gonna try on a completely fresh clone of a repo next time, to be sure I got everything right.

**Comment by jasonLaster** [comment]
Worker support is definitely on the roadmap, but it is a significant amount of work and this is the first time someone has reported the issue, so lower on the list than improved call stacks and certainly the network monitor. https://www.notion.so/replayio/Roadmap-321adf7736444d398b71d2e378e53381


I wonder if it would be easy to move the computation off of the worker? It'd be cool to have a TS sandbox hosted somewhere that we can record...

**Comment by hbenl** [comment]
> Is this something on your nearest roadmap? Or not as important for now?

Not as important for now. I've opened a [discussion](https://github.com/RecordReplay/gecko-dev/discussions/419) to track this.

> Sorry for that - I probably had those things executed already from some older plays with TS repo.

No worries, it was easy to figure out. I just thought I'd mention it in case someone else wants to try this.

**Comment by Andarist** [comment]
> I wonder if it would be easy to move the computation off of the worker? It'd be cool to have a TS sandbox hosted somewhere that we can record...

The worker is created by the Monaco Editor and I couldn't find an easy way to disable that.

**Comment by jasonLaster** [comment]
ah good to know.
