### ISSUE TITLE
[UX ❤️] When the progress circle is done, it should blip away

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2816]
From here: (https://github.com/RecordReplay/devtools/pull/2779)
Jon said: "Agree @ryanjduffy , I was imagining a fade for ease of dev. But would be super delightful to have a little animation of it blipping away."

So this is on Jon to design. Good moment of delight.

**Comment by jonbell-lot23** [comment]
Still love this idea. Should set time aside for these sorts of delights.

**Comment by jasonLaster** [comment]
@jonbell-lot23 do you have the blip animation we can include?

**Comment by jonbell-lot23** [comment]
Yup. I think the best approach is to put this simple one in for now, just to dip our toes in the water of Rive. Better animations (including full hooks into code and reacting to state) to come, but it'd be good to learn from this one.

**Comment by jonbell-lot23** [comment]
@jaril I've never imported a Rive file, so I'm not sure how painless this will be:

1. I invited you to Rive
2. Here's how to embed a Rive file: https://github.com/rive-app/rive-react
3. Here's the RIV file: [loading.riv.zip](https://github.com/RecordReplay/devtools/files/7018219/loading.riv.zip)

**Comment by jonbell-lot23** [comment]
Closing this out for now. We're dealing with Rive in other tickets
