### ISSUE TITLE
breadcrumbs.js is missing breakable positions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#282]
STR:
1. https://webreplay.io/view?id=78ad3dca-76a6-473e-b9f8-7a4a1d50726e
2. go to `client/inspector/breadcrumbs.js`

NOTE: breakpoint positions are missing

**Comment by bhackett1024** [comment]
Hmm, this WFM.  If it is still broken for you, can you record the problem (debugger inception x2)?

**Comment by bhackett1024** [comment]
WFM
