### ISSUE TITLE
Analyses running in unloaded parts of the recording show "Loading..." forever 

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2821]
When parts of a recording have been unloaded, it looks like analyses running in those unloaded parts will show "Loading..." forever. It's hard to make a recording of this because of https://github.com/RecordReplay/backend/issues/2295

**Comment by jasonLaster** [comment]
@bhackett1024 can we reproduce this with an e2e test which uses `unloadRegion` and runs an analysis?
