### ISSUE TITLE
Feature request: add and edit description on Replay

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2823]
Split out from this item:
https://github.com/RecordReplay/devtools/issues/2740

**Comment by jasonLaster** [comment]
Sorry for the confusion. The goal of the GTM doc was to add a summary section. Lets use #2740 and think about it from a user perspective

**Comment by jonbell-lot23** [comment]
Happy to remove the GTM issue tag, but would like to track this as an item.
