### ISSUE TITLE
[Outline] selection should fill the full width

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#283]
STR:

1. go to https://webreplay.io/view?id=d8dbdd03-1ee8-4779-af83-995d69eb1c11
2. open `https://firebugs.dev/static/js/main.466d878e.chunk.js`
3. select the outline pane

<img width="308" alt="Screen Shot 2020-07-28 at 9 24 31 AM" src="https://user-images.githubusercontent.com/254562/88705060-db9e3480-d0c3-11ea-9aef-fa51da5c55a3.png">

**Comment by princiya** [comment]
Thanks for creating this issue. I will address this in my PR.
