### ISSUE TITLE
Private by default

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2838]
**Description:**
We should redesign the privacy toggle in the upload and share screen to be private by default. I think a good option would be to have a toggle with a clear explanation of the risks associated with making a replay public.

**Comment by jonbell-lot23** [comment]
Step one: Jaril to do super-quick text change so we can fix this quickly:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/9154902/122127030-b276c600-ce86-11eb-951f-0ea6767fda34.png">

Next we're redesigning the upload and share screens:
* https://github.com/RecordReplay/devtools/issues/2862
* https://github.com/RecordReplay/devtools/issues/2863
