### ISSUE TITLE
"Inspect" fights with "Add comment" in devtools

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2846]
When you turn on the Elements panel, you can't inspect anything because the Add Comments bubble gets in the way.

Proposal: for now, let's remove Add Comments if you have this Experiment turned on.

More long term, we might just drop Add Comment from devtools outright.

**Comment by jaril** [comment]
Ironically, if you have the Elements panel on, that's probably the exact scenario in which you'd want to be able to leave comments on the video itself while in DevTools.

I think there should be an easy way to deactivate commenting while the node picker/inspector is active. That should take care of this particular case!
