### ISSUE TITLE
[Timeline] Revisit zooming

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#285]
At the moment zooming is done via dragging.

This has some advantages, we can be really precise about the window we want to see. 
The drawbacks are:

1. it is hard to zoom out
2. it is unintuitive. many people want to press and move to scrub the timeline

An alternative is to do a more windowing approach which relies on scrolling

1. scroll or cmd+scroll to zoom
2. shift scroll to pan left and right

The advantages I see are:
1. it is intuitive (to me :))
2. it is easy to zoom out
3. it is possible to pan

Details:

Windowing -- https://github.com/WebReplay/webreplay-devtools/issues/184

**Comment by jaril** [comment]
Closed by #534
