### ISSUE TITLE
[UX] Simplify share screen

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2863]
*The problem statement*

Our share screen is complicated because we show everything at once. We should use concepts of progressive disclosure to show the most important information (copy URL) easily and tuck the other stuff away.

**Comment by jonbell-lot23** [comment]
An ugly copy/paste for now but I think this is roughly where we're headed:

![image](https://user-images.githubusercontent.com/9154902/122140367-30df6200-ce9f-11eb-970d-3b7f63635b05.png)

**Comment by jonbell-lot23** [comment]
* Jaril: don't like collab langauge
* Jason: put it the edit thing
* Remove "copy link"

**Comment by jonbell-lot23** [comment]
Assigning to @jaril to align to our upload screen. As above, here are the items we're modifying:

* Don't use the word "collaborators"
* Remove the "copy link" button
* Edit should work the same as the upload screen

**Comment by jonbell-lot23** [comment]
I put a page in Figma called "Share screen redesign"

@jaril I'd like to chat about the onboarding screens you just built because they'll inspire the final design for this.

**Comment by jasonLaster** [comment]
Thanks @jonbell-lot23 

Copying over the [figma share link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=5896%3A33734) which should go to this page.

**Comment by jaril** [comment]
Notes from design kickoff
```
- Have a summary version and an expanded version
- Summary version should only show 1) Public/Private, 2) Team/User's Library, and 3) number of collaborators if applicable. E.g. Shared privately with Team X and 3 collaborators
- There should be an edit button that expands and allows the user to make changes to those 3 things
- There should be a way to add collaborators, and a list of current collaborators
- Keep it as a modal, but also consider creating a dropdown (?)
```
