### ISSUE TITLE
[Timeline] Fix overlapping markers

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#287]
Message markers on the timeline which were 1px away from each other have been fixed by #281. With this fix, a new marker is only displayed if it's more than 1px away from the previously displayed marker. This spaces out the markers and somewhat reduces visual clutter on the timeline. 

It works for now, but it's not ideal for two reasons:
1) There's still some clutter. Markers can still overlap as each one is about 7px wide (screenshot below).
2) The timeline becomes less reliable. Right now, users can miss messages that are hidden just because they're not displayed.

Leaving this issue here for when we come up with a new way to display multiple markers close to each other while not obscuring any information from the timeline. 

![image](https://user-images.githubusercontent.com/15959269/88874804-f10f7d80-d1ed-11ea-8f16-6ae8ecddb8ed.png)

**Comment by jasonLaster** [comment]
I think this is now covered by other issues
