### ISSUE TITLE
Add better management for outstanding invite links

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2873]
Right now, a team is assigned an invitation code when it's created. Whoever has access to the link (unless guarded by email address domain, see #2872) can use it to gain access to the team. 

There should be some way to manage invitation codes. Rough ideas are (in order of complexity):
- Add a button for "shuffling" the code.
- Creating time-limited invitation codes.

We likely don't need this in the short term, but tracking it here so it's not lost.

**Comment by jonbell-lot23** [comment]
@jasonLaster and I discussed in Discord and we'd like to punt on this for now, as mentioned in the original comment.

But one idea is to set a time limit of a week for now. It's not the perfect solution but it does give us a bit more control and lets us punt further out.
