### ISSUE TITLE
[Timeline] Timeline marker and zooming selection are not aligned

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#288]
When holding the mouse down then dragging in the timeline to zoom, the marker is 1-2 pixels away from the end of the zooming selection. 

There should not be a gap after the marker. Instead, the marker should be flush with the end of the zooming selection.

![image](https://user-images.githubusercontent.com/15959269/88876803-12726880-d1f2-11ea-9cb5-256f4cb07013.png)

**Comment by jasonLaster** [comment]
closing as this is no longer relevant
