### ISSUE TITLE
[Recording] Back button should go back to the url we were recording

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#289]
One of my small pet peeves is that after saving a recording the page is replaced with the webreplay.io recording page and it is hard to go back. 

It would be nice if the back button would work so we could easily go back.

**Comment by bhackett1024** [comment]
With the next version of the browser (to be released shortly) you can go back/forth between the view URL and the recorded URL.  Other uses of the session history won't happen --- you won't see the URLs in the back/forward button drop downs or get the history when restoring.  I looked into hooking into the session history stuff that controls a tab's history, but it didn't work out.  It can't be manipulated from JS (unless I missed something) and the C++ is really complicated, with data/logic in both the parent and content processes.  The fix (link below) modifies browser.js to support navigation without having to interact with the internal session history, which is simpler and more self contained.

https://github.com/RecordReplay/gecko-dev/commit/f5d3032e13eccb788d1d3959ac971bdafc67c9c9
