### ISSUE TITLE
Onboarding: Let teams whitelist a domain 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2894]
**Description:**
It would be great if teams could whitelist other users from their domain. So for instance all new users with an email domain from `reclaim.ai` would be added to Reclaim. This is another option that could really help make signup easier.

Tracking: 
- [ ] Add API for adding users to teams who toggle domain match on [#2408](https://github.com/RecordReplay/backend/pull/2408)

**Comment by jonbell-lot23** [comment]
Oh, I get it. So there are two things to consider:

1. Invited to Replay
2. Added to a team

We had addressed the first one at a domain level, but not the second one. Fantastic idea.

**Comment by jasonLaster** [comment]
Not mine. Two users requested it :P

**Comment by jasonLaster** [comment]
we're going to hold off on this for now since anyone can signin with any email
