### ISSUE TITLE
[replaying] evaluating `user` returns null

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#290]
STR:
1. go to https://webreplay.io/view?id=6aaa4aa7-b55c-46f8-9d5c-b58c3bc91df2
2. add a breakpoint in `lib/user.js#49`
3. rewind to the last hit
4. hover on `user` evaluate `user` in the console

ER: get an object
AR: get `anonymous` and null

Here's a recording with the values:
https://webreplay.io/view?id=01482136-3068-4f2f-9223-4b4bac6b499b 

<img width="1329" alt="Screen Shot 2020-07-31 at 8 06 45 AM" src="https://user-images.githubusercontent.com/254562/89049288-e0eac180-d305-11ea-8e53-752bc1e063fb.png">

**Comment by bhackett1024** [comment]
This is fixed now.
