### ISSUE TITLE
Fix video playback in frontend

### ISSUE THREAD

**Issue by kannanvijayan** [RecordReplay/devtools#2907]
Video playback in frontend does not work as expected, when experimental feature is enabled.

**Comment by ryanjduffy** [comment]
I think this will be fixed by #2921

**Comment by kannanvijayan** [comment]
Almost good to go, but a couple of remaining issues:

1. I managed to hit the "play" button and still replicate the transparent playback issue (checkerboard background).
2. The replay playback button should be grayed out until the video blob is loaded.  I kept clicking it and there was no visual indication of when the video playback was ready.

**Comment by kannanvijayan** [comment]
Closing to move over to new issue.
