### ISSUE TITLE
Share and invite screens not using reverse-chron

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2917]
Screen one:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/9154902/122866317-dac95d80-d37b-11eb-83e2-48ae21708916.png">

Screen two:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/9154902/122866286-cbe2ab00-d37b-11eb-9390-2e3e6725175b.png">

(Also notice that jaril@replay.io is still in the text field after adding in the share screen. That shouldn't happen, the field should get blanked out.)

**Comment by jasonLaster** [comment]
@jonbell-lot23  @jaril is this fixed?

**Comment by jasonLaster** [comment]
looks good
