### ISSUE TITLE
Team dropdown in UploadScreen not initialized

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2925]
STR:
- select a Team other than "Your Library" in the library view
- make a recording

expected: the UploadScreen's Team dropdown is set to the Team that the user selected earlier
actual: the dropdown is set to "My Library"

This may have been caused by recent changes to how the UploadScreen is loaded: the dropdown value is initialized [here](https://github.com/RecordReplay/devtools/blob/b4a2ce306178b3f1eb5b4d420b9dc18bfdf6abcb/src/ui/components/UploadScreen/UploadScreen.tsx#L170-L172) in a `useState` hook with a value from an Apollo hook. But the value from the Apollo hook will initially be `undefined` unless Apollo already cached the query (and subsequent values from the Apollo hook will be ignored by the `useState` hook). Relying on the Apollo cache in this way creates invisible dependencies in the code (i.e. you need to have used query X in some component Y before you can use component Z) that can lead to bugs caused by seemingly unrelated code changes.

**Comment by jaril** [comment]
Good call—the invisible dependencies are not ideal.

This case is fairly simple so we can get around it by querying, loading and passing the `userSettings` from the parent component. Will keep an eye out for what we can do to lessen those kinds of things moving forward.
