### ISSUE TITLE
Breakpoint markers are sometimes not rendered correctly

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2926]
I think this happens when the breakpoint marker is set before the editor is shown (which would mean it can only happen for breakpoints saved from previous sessions).

https://replay.io/view?id=4422e79c-9e31-496c-af34-7358f6b07beb

![image](https://user-images.githubusercontent.com/16060807/123105933-7cae8000-d438-11eb-80bc-efc9bafb9f6d.png)

**Comment by jasonLaster** [comment]
closing since i haven't seen this in awhile
