### ISSUE TITLE
New tab page and first-run of browser should lead user's eye to record button.

### ISSUE THREAD

**Issue by kannanvijayan** [RecordReplay/devtools#2963]
**Description:**

In the new tab page, we see the following text centered on screen:

`Please navigate to the page you want to record, then press the blue record button.`

The words `blue record` should be replaced with an icon showing the actual record button.  This will let the user quickly visually identify the button in the UI.

The page could also have a helpful arrow (in the page contents) pointing to the location of the record button in the UI.

This would also be good to show up, on first-run of the browser, on the first tab that's opened (currently it loads the library view).  So first-run opening of the browser could show the "new tab screen" with the aforementioned visual cues, and maybe fade-out to show the library screen.  We can expect a lot of users to have an empty library when first starting.

**Comment by jonbell-lot23** [comment]
These are all great comments, and covered here: https://github.com/RecordReplay/devtools/issues/3108

Closing as duplicate
