### ISSUE TITLE
Leaving a Replay open results in "Unexpected socket error"

### ISSUE THREAD

**Issue by jkup** [RecordReplay/devtools#2965]
**Description:**
If you leave a Replay open for a long time eventually you get an "Unexpected socket error". I think the socket closing is expected but maybe we could give a better error message? It's not really so bad because the error asks you to refresh and when you do it loads again. Just thought I'd make a note of it in case you all want to change the wording!

**Steps to Reproduce:**
1. Open any Replay
2. Leave it open until the socket closes
3. Observe error message

**Expected Result:**
Maybe a different message? Saying that the socket has been closed due to timeout instead of an error?

**Additional Context:**

* Screenshots:
![Screen Shot 2021-06-25 at 5 29 16 PM](https://user-images.githubusercontent.com/490294/123487152-64c33180-d5db-11eb-9f0a-afe7aed2d9b5.png)

* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Good catch @jkup. This looks like a regression since we used say something a bit more descriptive ...
