### ISSUE TITLE
Show loading event listeners

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2971]
**Description:**

I bet we can use `findAnalysisPoints` to show loading event listeners much faster. For example, when the user clicks on Mouse Events, we could show the 5 mouse events in the console as loading within 100ms

**Comment by jasonLaster** [comment]
Now that we have the count for event listeners, we should be able to immediately show the loading messages in the console.

**Comment by hbenl** [comment]
We're doing this already: https://github.com/RecordReplay/devtools/blob/fef99de2afa0c2fbfa0a48a2b7057d9182cccb79/src/protocol/logpoint.ts#L402
