### ISSUE TITLE
Number of hits tooltip sometimes cut off

### ISSUE THREAD

**Issue by jkup** [RecordReplay/devtools#2972]
**Description:**
Sometimes the # of hits tooltip is cut off and you can't see the number. I was a bit confused when I couldn't leave a comment on a line until I realized it was never hit! I think this is only a problem when you don't have an active sidebar (like no comments, source explorer, or pause information).

**Steps to Reproduce:**
Open a replay and a source file. Close all sidebars and hover over a line number.

**Expected Result:**
You should be able to see the number. Maybe the tooltip should be off to the right or higher above the line in this case?

**Additional Context:**

* Screenshots:
* ![Screen Shot 2021-06-27 at 4 07 04 PM](https://user-images.githubusercontent.com/490294/123558671-83edca80-d765-11eb-9820-23cc04bf6f31.png)
* 
* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
This is one of those funny design tradeoff qs. I've thought about this one for a bit and I think we should show the tooltip above the gutter when the panel is collapsed. Curious what others think
