### ISSUE TITLE
Add a tooltip when commenting is disabled

### ISSUE THREAD

**Issue by jkup** [RecordReplay/devtools#2973]
**Description:**
Feel free to disregard this one! I was a little confused the first time I saw the comment button greyed out inside the DevTools. I think it just is disabled when you add a breakpoint to a line with 0 hits? It might be nice to add a tooltip to the button so folks know why they can't click. It also might be obvious to everyone else and just confusing to me 😅

**Steps to Reproduce:**
Open a Replay and a source file that is not executed. Add a breakpoint to a line with 0 hits. Notice the comment button is greyed out with no tooltip.

**Expected Result:**
I would expect either to be able to add a comment anyway or to see a tooltip explaining why I can't.

**Additional Context:**

* Screenshots:
![Screen Shot 2021-06-27 at 4 06 43 PM](https://user-images.githubusercontent.com/490294/123558834-65d49a00-d766-11eb-95f3-d09c60173f16.png)

* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
This feels like we could simplify this until we have timeless comments

**Comment by jasonLaster** [comment]
closing as we now support always adding comments
