### ISSUE TITLE
Polish the comment pane

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2979]
Tasks
- [x] comments should have padding
- [ ] the comment pane should be a fixed width. At the moment they can be different between modes too
- [x] the timeline should be full width (or at least consistent with dev/non-dev)

### comments no longer have padding
<img width="387" alt="Screen Shot 2021-06-28 at 5 20 03 PM" src="https://user-images.githubusercontent.com/254562/123718889-2163ff80-d835-11eb-84ff-0f6bbe0c872e.png">

### the viewer is to the right of comments in the viewer mode and below comments in dev
<img width="614" alt="Screen Shot 2021-06-28 at 5 20 09 PM" src="https://user-images.githubusercontent.com/254562/123719032-638d4100-d835-11eb-8122-c54b22151a4f.png">

**Comment by jaril** [comment]
fixed to 400px width
