### ISSUE TITLE
Requesting source content without SourceId somewhere

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2988]
Was just opening https://replay.io/view?id=cf2da81f-3a74-45ba-9241-f6d4361a52f5 and noticed the following:
<img width="1471" alt="Screen Shot 2021-06-29 at 1 26 50 PM" src="https://user-images.githubusercontent.com/132260/123863183-1dd88300-d8de-11eb-88fc-6fb10c925fbb.png">

**Comment by jasonLaster** [comment]
Here's a replay of the same problem
https://replay.io/view?id=57eecbe2-1589-40f5-99ca-4166e75caf08&point=14603334916551911451730785918255483&time=8006.274133723768&hasFrames=true

but yeah - i wasn't able to hunt down where the bad request was coming from either...

**Comment by jasonLaster** [comment]
okay - added a couple of comments to the replay. my guess is that this comment comes from before we saved sourceIds in the db for comments

**Comment by hbenl** [comment]
> my guess is that this comment comes from before we saved sourceIds in the db for comments

Exactly, so this happens only when you open a recording with a source comment that was added before #2007 landed.
