### ISSUE TITLE
Add tooltip for "Frame progress"

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3022]
Right now there's no header for the frame progress dragger thing:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/9154902/124870660-2edc6f00-e017-11eb-82a9-259d47d9eae5.png">

But I think a header will be too heavy. We'll do a tooltip instead.

**Comment by jonbell-lot23** [comment]
@jaril I tried to do this with an alt tag but couldn't get it to work. Any thoughts?

**Comment by jaril** [comment]
@jonbell-lot23 Any thoughts on what should go on the tooltip?

**Comment by jonbell-lot23** [comment]
I'm digging into old correspondence and I can't find what Jason said. Is "Frame progress" what you were thinking, @jasonLaster ?
