### ISSUE TITLE
New welcome/download screens for people invited to Replay

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3046]
Our "You have a new team invitation" is a fine modal for people who already use Replay, but it's a strange experience for brand-new people. Here's what we're going to change to:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/9154902/126255431-d4c3c5a0-5647-4549-96e2-6946a9c74dcd.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/9154902/126256478-3f83af43-0bfc-4ae1-9c0b-1fca0d18d162.png">

There are a few key details here:

1. This is only what invited users will see. Brand new users will see something similar, but I haven't diagrammed that bit out just yet.

2. Notice that I'm sending a person to the team *or* downloading Replay. We can do this because on the team page we'll still have a download Replay link. Also, quite a few people will want to collaborate with others but not actually want to download the product themselves.

**Comment by jaril** [comment]
go to a team should be default immediately.

**Comment by jonbell-lot23** [comment]
Note from Jaril chat:

* I think having a fixed height works best when you have next/previous buttons to go between screens
* Most screens don't have next-previous buttons
* So I think our component should not have a fixed height by default
* But there's a way to set it to a fixed height for when that's necessary
