### ISSUE TITLE
Proposal: Frontend Architecture

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#3058]
# Summary
Reorganizing devtools will allow clearer URLs for our customers and better separation of concerns within our codebase.

# Current State

Devtools is a combination of the legacy devtools codebase and various new submodules to support replay such as the library, user profile modals, and cross-cutting concerns like auth and logging. URL routing is mostly limited to choosing between the library and the recording view based on presence of a recording ID query string parameter. 

# Target Architecture

## URL Structure

The following structure would be rooted on `app.replay.io`:
* `/library` - The library view listing the user's (or selected team's) recordings
* `/recording` - An "empty" path that would redirect to `/library`
  * `/:recordingId` - Home for a specific recording. Redirects to `/:recordingId/view`
    * `/view` - The viewer panel
      * `/share` - Share modal
      * `/settings` - Recording settings modal
    * `/devtools` - The devtools panel
      * `/share` - Share modal
      * `/settings` - Recording settings modal
* `/profile` - User profile page
  * `/settings` - User settings / preferences
    * ~`/billing` - Payments and billing set up~ No individual billing at the moment
    * `/apikeys`
    * `/preferences`
    * `/experimental`
    * `/support`
    * `/legal`
  * `/teams` - Team membership / management
* `/team` - no-op?
  * `/:id` - library view for that team
    * `/settings` - settings modal
      * `/members`
      * `/billing` - billing pane 
      * `/apikeys`
      * `/delete`
* `/browser` - Potentially any empty path but could be the landing page for or a redirect to downloading the browser
  * `/new-tab` - Displayed by the browser when opening a new tab
  * `/welcome` - Displayed by the browser when the user launches replay for the first time
  * `/error` - Displayed by the browser when a recording is unusable

## Logical Architecture

The logical architecture describes the distinct capabilities provided by the application without prescribing how they are built, packaged, or deployed. This maps well to the URL structure which represents the logical features of the application from the perspective of the user. There are often shared capabilities that aren't represented in the URL structure but are within the logical architecture.

* Library - Ability to view, sort, and manage recordings for a user or team
* Profile - Ability to set user preferences, managing billing and payments, and manage team membership
* Viewer - Ability to view a recording and comment at specific times and screen locations 
* Devtools - Ability to view a recording, step through code execution, and comment on lines of code at specific execution points
* Browser Views - Ability to view branded content and actions from the Replay browser
* Design System - Shared components and styles used across the application
* Shared (Auth, logging, etc) - Cross-cutting capabilities used across the application

## Physical Architecture Proposal

Currently, most of the capabilities above are intermingled with the devtools repo. One exception is the browser views which span devtools and the replay.io website. For the near term, I'm proposing an incremental migration from the current architecture into submodules within the devtools repo for each logical capability. Over time, we can further decompose into separate deployable apps or reorganize into a monorepo if there's value at that time.

* [X] Current State
  * Website includes some browser views
  * Devtools includes everything else
* [x] #4253
  * Consolidate browser views into devtools
  * Implement URL structure
* [ ] V3
  * Refactor design system into a submodule within devtools
* [ ] V4
  * Refactor browser views into a submodule
  * Refactor shared capabilities into a submodule
* [ ] V5
  * Decouple and refactor viewer and devtools
  * Refactor profile into submodule

## Benefits

* Improve our separation of concerns
* Allow better webpack chunking enabling faster load times for users
* Enable deployment and scaling as separate apps

**Comment by jonbell-lot23** [comment]
I am supportive of this, and have considered it pretty important to the UX for a while.

The only part that jumped out as me as unnecessary was the /share/ endpoint, but as I considered it more I changed my mind. Being able to link directly to share does have value, and having distinct urls is best practice. 

I think it’s just a matter of prioritising this work against other priorities. From a design POV, this is foundational work we’ll end up doing eventually. I’d prefer to do it now, rather than needing to migrate after launch.

**Comment by ryanjduffy** [comment]
> The only part that jumped out as me as unnecessary was the /share/ endpoint, but as I considered it more I changed my mind. Being able to link directly to share does have value, and having distinct urls is best practice.

I doubt it'll be used frequently as an endpoint but i like that it's an option and that mutating the URL for view changes means that the back button works "for free" (though managing URL state is never that free :) )

**Comment by hbenl** [comment]
Thanks for kicking off the discussion! I'd like to propose some small changes to the routes:
- the routes for the modals don't contain the panel that is visible in the background of the modal, so for example if you open the sharing modal from either `/:recordingId/view` or `/:recordingId/devtools`, you'd always end up at the `/:recordingId/share` route even though different panels are shown in the background. Angular solves this with auxiliary routes (e.g. `/:recordingId/view(modal:/share)`), but I haven't seen a similar concept in the React world, it seems most people go for routes like `/:recordingId/view/share` ...
- the `/view` top-level route seems unnecessary
  - `/view/:recordingId` redirects to `/:recordingId/view`
  - `/view/profile` and `/view/browser` could be replaced by `/profile` and `/browser`

**Comment by ryanjduffy** [comment]
Thanks, @hbenl. `/profile` and `/browser` should be at the top level. That was a formatting mistake :)

I like the idea of embedding the modals below both parent paths. I'll update that above.

If we wanted a more REST-like URL structure, we could use `/recordings` or `/replays` as the root for the library and then `/recordings/:recordingId` as the root for an individual record. This is useful if we want some future flexibility for other top-level paths but we could also drop that level and use the root, `/` as the library and `/:recordingId` for a record. `/profile` and `/browser` could still be at the root as well.

**Comment by ryanjduffy** [comment]
+ conversation from #3072 regarding direct linking to the API Keys settings page to ease adoption for other entry points like the CLI

**Comment by ryanjduffy** [comment]
Pulling this into the current project as a reminder to work on the V2 part of this ticket. Some of this is already in progress.

**Comment by ryanjduffy** [comment]
@hbenl and I discussed today and our current plan is to break V2 into (at least) 3 tickets:
* Move the browser routes into dev tools
* Add the recording id into the URL to split between the library and the viewer
* Add support for routing to the modals

**Comment by jasonLaster** [comment]
@ryanjduffy i believe we all agree with this proposal. Is there anything else to discuss here?

**Comment by ryanjduffy** [comment]
I don't think so. Should we add it to the "post-launch" planning board to queue it up?

**Comment by jasonLaster** [comment]
closing as a lot has changed post-next.
