### ISSUE TITLE
Synchronize mouse & static paint rendering with video playback

### ISSUE THREAD

**Issue by kannanvijayan** [RecordReplay/devtools#3059]
The current UI does not propelty visually synchronize the rendering of mouse movements with the view of the browser presented by the video playback mechanism.

Video playback uses a letterboxing approach for dealing with size changes - it boxes the playback view within a 1280x720 view area.  It scales each paint, preserving aspect ratio, to either the horizontal or vertical bounds of the 1280x720 area, and centers it in the view with respect to the narrower dimension.

The mouse rendering currently employed matches the rendering of the static paints in the playback view.  These paints scaled (aspect preserved) to the dimensions of the entire view space in the playback window.  The view space is taller than it is wide, and most paints fill the horizontal dimension and leave empty spaces above and below.

Both the static paint rendering and the mouse rendering need to have the same translation/scaling logic applied.  Currently, this problem is most glaring with mouse event rendering.  Mouse clicks and movements are slightly off, and it's possible for the user to see it.

**Comment by jasonLaster** [comment]
we can come back when we re-enable playback RecordReplay/backend#2742
