### ISSUE TITLE
"Fetching data" causes a blue flash when loading a replay

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3063]
This replay is a bit slow so it doesn't seem like a flash, but typically the blue "fetching data" screen is so fast it is a bit jarring

https://app.replay.io/?id=60506935-d146-4787-8796-22f9aa7106d4&point=17848520453612074740704932777689430&time=8551&hasFrames=false

**Comment by hbenl** [comment]
I've been thinking about our loading screens because the flashing gets worse with #3135 . I think we should have one loading screen component that we use everywhere and that component should figure out what to show (e.g. if there should be a progress indicator or not) based on the state in redux.

**Comment by jaril** [comment]
Making a separate issue for auditing/consolidating the loading screens #3173.
