### ISSUE TITLE
Invite checkmarks are confusing

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#3079]
**Description:**
When you look at the list of invites it shows a list of green checkmarks:

![Screen Shot 2021-07-15 at 11 34 04 AM](https://user-images.githubusercontent.com/452453/125818343-8778bcb6-900c-46b3-ba28-aae79f16fe6c.png)

They can't be clicked on, and there's no hover text that explains what the checkmark means.

**Steps to Reproduce:**
Send someone an invite, checkmark is immediately present

**Expected Result:**

I would expect there to be a state for invites where there _wouldn't_ be a green checkmark, like when someone has yet to accept the invite, but that doesn't appear to be the case.

**Comment by jonbell-lot23** [comment]
@jaril said

"it used to be a :octagonal_sign: right after inviting somebody, and then once they registered, it became a :white_check_mark:
regressed when we moved to the new graphql api
thanks for filing!"

Assigning to Jaril

**Comment by jasonLaster** [comment]
Adding to this week while we revisit the share modal

**Comment by jaril** [comment]
This issue was from when we had replay invitations. Now that we've launched, this issue's outdated.

Will be closing this with a PR to take out the associated code.
