### ISSUE TITLE
[Debugger] Scopes is missing `time`

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#309]
STR:
1. go to https://replay.io/view?id=41f7dec2-54f1-4e19-b652-58b642f4d2a7
2. open timeline/index.js 
3. set a breakpoint on line 24 
4. rewind

ER: time appears in the local scope. evaluates in console
AR: appears in arguments,

<img width="1501" alt="Screen Shot 2020-08-10 at 8 30 53 PM" src="https://user-images.githubusercontent.com/254562/89854405-ade7cf80-db48-11ea-9041-44a2009daf14.png">

**Comment by bhackett1024** [comment]
The time variable shows up in the scopes now, and is defined when evaluating in the console here.

<img width="926" alt="Screen Shot 2020-08-13 at 3 02 37 PM" src="https://user-images.githubusercontent.com/1062578/90201436-955cfc80-dd76-11ea-86d2-44cb755b3e93.png">
