### ISSUE TITLE
Can't play recording / broken video

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3092]
When visiting the recording below the "play" button on the timeline was grayed out, could not be clicked on, and did not show any tooltip or other info.

https://app.replay.io/?id=d66c8ac1-1e50-497d-ab0a-a66bd09e3822&point=149603053241900415423632182098265403&time=79623&hasFrames=true

**Comment by bhackett1024** [comment]
After closing the tab and reloading I was able to play the recording, but when clicking the play button the screen is just black, with no useful video content.  So there are two problems here:

* Can't play the recording while the video is being generated (?)
* The generated video is broken.

**Comment by jasonLaster** [comment]
Thanks for filing.

1. The disabled play button is a poor experience.  We should consider waiting to show the viewer until the video has loaded or supporting streaming video.
2. We should add a video encoding KPI
3. I also see a black video pretty often. @ryanjduffy added a partial fix last week

**Comment by bhackett1024** [comment]
I thought we were streaming video.  I think waiting until the entire video is generated before loading the viewer would be a pretty bad user experience, as in this case the viewer loaded several minutes before the video was available.

**Comment by jasonLaster** [comment]
closing as this was related to video playback and we can come back when we re-enable playback here https://github.com/RecordReplay/backend/issues/2742
