### ISSUE TITLE
No easy way to add comment on a console message

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3094]
We have an "add comment" button when a breakpoint is set on a line, but when paused at a console message there probably isn't a breakpoint.  In this case going to the comments pane asks to click on the video to add a comment.  Mousing over the video shows a nonsense tooltip "Add comment to this line of code".

The tooltip needs to be fixed, but this UX is pretty awkward regardless.  It should be easy to add a comment when in the comments pane, without having to click on the video.

**Comment by jonbell-lot23** [comment]
This will be addressed as part of our console improvements. Right now this is the proposal:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/9154902/126916950-ebbdc22e-fa8c-412d-9061-49f47dc7048d.png">

There's no resistance to the idea of adding a comment to a console message, so it's just a matter of finding the right entry point for it. Stay tuned.

**Comment by jonbell-lot23** [comment]
Alright, we've got a settled design for this. It's in Figma and I'll document it more later. Jason and I spoke today, then Jaril and I synced, so we have our plan. To discuss more tomorrow.

**Comment by jonbell-lot23** [comment]
Closing because this is about to go live

**Comment by jonbell-lot23** [comment]
This didn't go live because of a merge conflict. Check out #3184 to follow progress.
