### ISSUE TITLE
Devtools pegging CPU on Firefox

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3096]
When debugging recordings the content process CPU usage quickly climbs to 100% and stays there on Firefox 90.0 or the Replay browser itself.  This seems to be a recent regression, and users have encountered this as well.  Chrome does not seem to be affected.

**Comment by loganfsmyth** [comment]
Alright I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1721284 I think this is triggered by the `currentTime` assignments in https://github.com/RecordReplay/devtools/blob/a4782593c36292efc1f69b933af4a78f8d0026b4/src/protocol/graphics.ts#L173,L185

**Comment by jasonLaster** [comment]
closing as this is related to a firefox issue with the video encorder we are using
