### ISSUE TITLE
Ensure that the main bundle remains small

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3101]

**Comment by jasonLaster** [comment]
we're now running a check in CI

**Comment by hbenl** [comment]
Actually I never merged the PR because the check that I initially implemented isn't very meaningful anymore: we now have a lot of bundles and we should check the total size of all the bundles that are loaded for
- the browser pages
- the library
- the viewer

**Comment by jasonLaster** [comment]
closing since we can come back to this when it breaks. Also if we go with next, then we'll get better chunking
