### ISSUE TITLE
Reduce the size of the main bundle

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3102]

**Comment by ryanjduffy** [comment]
This is looking much better (at least compared to when I first started looking at it a few months ago). Some quick stats from today:

* Library with 2 recordings: 1.5mb of JS, 1.8mb total resources
* Library with 13 recordings: 1.5mb JS, 2.2mb total
* Sign In Page: 1.5mb JS, 1.6mb total
* `/browser/new-tab`: 704kb JS, 709kb total
* Recording: 2.2mb JS, 2.5mb total

The main bundle is pretty small (121kb) but we should do more analysis on what else can be minimized.
