### ISSUE TITLE
Control-click should go to a method

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3113]
See here: https://github.com/RecordReplay/devtools/issues/2798

Jason (customer) said:
Feature request: control-click to go to a method

Jason (Replay guy) said:
This gets tricky when you want to draw a visual indicator like an underline, but the simple version is easy

**Comment by jonbell-lot23** [comment]
Marking as design-complete because the feature is clear: right-click should go to a method.

That said, I'm sure we'll discover challenges. Let's chat when you come across them, @jaril ! :)

**Comment by jasonLaster** [comment]
I'd vote for punting on this pre-launch since it is surprisingly difficult to do with our current editor (codemirror) and has lots of corner cases.
