### ISSUE TITLE
July Comments Update

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3114]
- [x] https://github.com/RecordReplay/devtools/issues/3094
- [x] https://github.com/RecordReplay/devtools/issues/2614
- [ ] https://github.com/RecordReplay/devtools/issues/2615

Also:
* Clicking on a "line of code" comment in the left-hand comments pane should take you to that line of code (or console message)

Should consider as a follow-up:

* Mark as resolved
* cc @username to flag them in an email

**Comment by ryanjduffy** [comment]
> cc @username to flag them in an email

Ran into this when I tried to add mention support to the comment editor. I didn't see a username for our users since they're all added via google auth. Some have a `nickname` but I don't think it's guaranteed to be unique so we'll need to address username selection or generation as part of this.

**Comment by jonbell-lot23** [comment]
Closing because we got the two most important items. The "comment without a comment" item can be a follow-up.

**Comment by ryanjduffy** [comment]
Created #3211 to track the set of tasks necessary for proper @ mention support
