### ISSUE TITLE
Console and Events July update

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3115]
- [ ] https://github.com/RecordReplay/devtools/issues/2490 (Marked as design complete)
- [ ] https://github.com/RecordReplay/devtools/issues/2900 (Marked as design complete)
- [ ] https://github.com/RecordReplay/devtools/issues/3113

**Comment by jasonLaster** [comment]
Closing this issue because #2900 is its own project and I think we should punt on #3113
