### ISSUE TITLE
[Replay] Revisit source-mapping field

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#312]
It is really easy to forget to enable sourcemapping. It would be nice to revisit this:

a) enable it by default for now
b) make a checkbox prominent in the UI

**Comment by bhackett1024** [comment]
I'm confused, we always map sources unless the user has explicitly switched to the generated source when paused.

**Comment by jasonLaster** [comment]
this is the config on the Replay side for enabling source maps when recording

**Comment by bhackett1024** [comment]
Source maps should be uploaded by default in the latest build.

https://github.com/RecordReplay/gecko-dev/commit/2edecfa6fbc58ca92f27a95f41ab15dc92cb29c5
