### ISSUE TITLE
Include user info in telemetry events sent to backend

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#3152]

**Comment by jazzdan** [comment]
Specifically for DevtoolsUnexpectedError

**Comment by jasonLaster** [comment]
@jazzdan another way to do this would be to add the userInfo from the telemetry side since we should be able to look it up from the session info

**Comment by jazzdan** [comment]
@jasonLaster totally, I'd rather avoid adding unnecessary load tot he database if possible but it's probably not a big deal.

**Comment by bhackett1024** [comment]
> @jazzdan another way to do this would be to add the userInfo from the telemetry side since we should be able to look it up from the session info

We often have session IDs for these messages, but in cases where the devtools had a problem before creating a session then we won't.  It would be nice to consistently have this info to help with understanding the causes of these errors and how they are affecting users.

**Comment by jasonLaster** [comment]
Great point
