### ISSUE TITLE
Consolidate loading screens

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3173]
As Holger mentioned in #3063, we have a lot of loading screens and it's getting harder to track what they do, leading to non-intentional flashes. Let's audit all of the big loading screens and make sure we consolidate them where we can to avoid flashing.

```
I've been thinking about our loading screens because the flashing gets worse with #3135 . I think we should have one loading screen component that we use everywhere and that component should figure out what to show (e.g. if there should be a progress indicator or not) based on the state in redux.
```

**Comment by jasonLaster** [comment]
Adding two other issues here:

Description:
The Loading label should either be hidden or replaced with the indeterminate spinner.

https://app.replay.io/?id=7fff2504-36c1-4a01-b5d6-7843dc30ff61&point=3569704091223727585021232993534151&time=1969&hasFrames=true


This is another loading issue we might be able to fix at the same time

https://app.replay.io/recording/ac04fc44-4e1e-4a07-bb79-132770c9aaa8?point=1947111322887612301547710892212271&time=1468&hasFrames=false
