### ISSUE TITLE
Add top level routing to devtools for library/viewer

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#3177]
* Add recording ID into URL
* add support for routing to either library or viewer based on URL
* Update retrieval of recording id from redux to something that pulls the current path

See also: #3058

**Comment by ryanjduffy** [comment]
I don't know that this is critical to do right now so I haven't added it to an active project for now.

**Comment by jasonLaster** [comment]
closing as we're now routing for recording id.
