### ISSUE TITLE
Update modals to be opened by routing

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#3178]
* Add routes for modals (settings, sharing, launch browser)
* Update triggers and redux to align with this change

See also: #3058

**Comment by jasonLaster** [comment]
closing since this is covered by #3058

**Comment by ryanjduffy** [comment]
I created this as a sub task for that project ticket. If you want to handle this differently, that's fine with me too.￼

**Comment by jasonLaster** [comment]
basically equating the two, but yeah happy to re-open as well as long as they're different

**Comment by jasonLaster** [comment]
@ryanjduffy where are we at now post-next?

**Comment by ryanjduffy** [comment]
i think the important routes are covered so let's close this.
