### ISSUE TITLE
Sidebar scrolling and layout can break

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3187]
I noticed two issues recently with the devtools sidebar:

1. The vertical scrolling looks broken
2. Sometimes the layout can be shifted to the right. I think this happens if a source is particularly wide or there are lots of editor tabs

<img width="898" alt="Screen Shot 2021-08-04 at 1 53 37 PM" src="https://user-images.githubusercontent.com/254562/128253392-ddf2e4db-f5f8-4ac1-acbc-657a3b6758aa.png">

<img width="1497" alt="Screen Shot 2021-08-03 at 8 51 45 AM" src="https://user-images.githubusercontent.com/254562/128253540-5071bf04-6de3-40e3-b84b-b94620f95f89.png">

**Comment by jaril** [comment]
The tabs behavior in the editor may be contributing to the layout jank.

**Comment by jasonLaster** [comment]
It looks like the editor is now stretching. This might have happened after we removed the splitter

<img width="1859" alt="Screen Shot 2021-08-06 at 11 32 09 AM" src="https://user-images.githubusercontent.com/254562/128556267-40fe2a29-12ef-4b19-8681-a7034075f532.png">

**Comment by ryanjduffy** [comment]
The layout bug can be reliably reproduced by opening multiple sources so that the first source's tab is offscreen to the right and then selecting that tab from the explorer.
