### ISSUE TITLE
Prod deployment

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3194]
Currently we're doing a prod deployment every time a PR is merged or someone pushes to master. We should either only deploy to prod when the tests in GitHub CI succeed or switch to manual prod deployments.
We could achieve this by creating a new branch and configuring Vercel to use that branch for prod deployments. Then we'd keep working on the master branch and trigger a prod deployment (either automatically or manually) by setting the new branch to the commit that we want to deploy.
Alternatively, we could use one of the preview deployments for prod: Fetch `/index.html` from the preview deployment, add `<base href="https://devtools-...-recordreplay.vercel.app/">` to it and serve that as `https://app.replay.io/index.html`. The big advantage of this approach would be that this should get rid of `ChunkLoadError`s due to new deployments: Since the user still has the same `<base>` tag in his browser that points to the old deployment, he will still be able to dynamically load the old chunks.

**Comment by jasonLaster** [comment]
I'm a bit confused by what you're proposing here. Could you walk through an example, like there is a vercel preview branch `devtools-123-recordreplay.vercel.app` that becomes prod and what would happen?

Proxying `app.replay.io` to a preview branch and keeping preview branches around admittedly feels pretty hacky, but i want to better understand what you're suggesting.

**Comment by hbenl** [comment]
To make `devtools-123-recordreplay.vercel.app` the prod deployment:
- download `https://devtools-123-recordreplay.vercel.app/index.html`
- add `<base href="https://devtools-123-recordreplay.vercel.app/">` to it
- deploy the modified `index.html` to `https://app.replay.io/index.html`

(obviously this would need to be automated)
Now when you go to `https://app.replay.io/`, you'll get the `index.html` containing the `<base href="https://devtools-123-recordreplay.vercel.app/">` tag, so a URL like `/main.345.js` will resolve to `https://devtools-123-recordreplay.vercel.app/main.345.js`.
When the prod deployment is changed, a new `index.html` will be deployed to `https://app.replay.io/`. But if you started using Replay before that new deployment, your browser is still working with the old `index.html`, so if it needs to download the chunk `/1.345.js`, it will still get it from `https://devtools-123-recordreplay.vercel.app/1.345.js`, i.e. from the old deployment.
This is not proxying, we're using a `<base>` tag to tell the browser to get all assets from a different host.
