### ISSUE TITLE
Add first-run prompts

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3197]
[Edited by Jon]

Here are some ideas after looking at our first cohort:

1. We should prompt people to leave a comment in the viewer
2. We should prompt people to click on a console message
3. We should prompt people to click to add a breakpoint
4. We should prompt people to edit a breakpoint (nobody did this ;) 
5. We should prompt people to create a 2nd replay by either launching Replay again or opening a new tab

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=5535%3A25549

### Invite email

<img width="824" alt="Screen Shot 2021-08-05 at 5 02 48 PM" src="https://user-images.githubusercontent.com/254562/128549291-bc6ffc41-e088-4352-b644-6ef1c4c2c0ee.png">

### guide

<img width="820" alt="Screen Shot 2021-08-06 at 10 36 27 AM" src="https://user-images.githubusercontent.com/254562/128550248-96fc7e66-98b3-4fe1-adab-e5a638fe7241.png">

**Comment by jonbell-lot23** [comment]
@jasonLaster We should absolutely work on this, but note that http://replay.io/demo does put each of these steps in the console. So we can add these, but we should do it in a way that pairs with the demo console messages.

**Comment by jonbell-lot23** [comment]
Closing this broad issue in favour of https://github.com/RecordReplay/devtools/issues/3561
