### ISSUE TITLE
Pause panel should use a stacked sidebar accordion

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3200]
I just landed Ryan's PR which fixes the layout issues for the pause panel, but unintentionally switched the pause panel to the sources accordion ux where the panels are evenly spaced.

Lets bring back the stacked accordions which avoids unnecessary empty space for the top panels

**Comment by jcmorrow** [comment]
It seems to me like there's a few different behavior options, one set around expansion/spacing, and one around scrolling (and it seems like there also might be *different* answers to these questions for the Sources vs. Pause accordions).

# Scrolling

### Accordion Scrolls
(notice how the Outline header starts out of view and scrolls in)

https://user-images.githubusercontent.com/5903784/136445383-064498e2-b8fa-4bb6-bab1-fd6a99479825.mp4

### Panes Scroll

https://user-images.githubusercontent.com/5903784/136445439-86766a9d-78f1-47e6-8f83-a263aee85249.mp4

# Contraction/Expansion

### Panes are always about the same height as each other and can scroll individually

![panes_are_proportional](https://user-images.githubusercontent.com/5903784/136445850-c1ccc8f9-d7e0-4564-9834-97024ff0a803.png)

### Panes with less content take up less space (they try to not take up more space than their content).

![panes_fit_content](https://user-images.githubusercontent.com/5903784/136445939-82fd9530-568b-49cb-8835-79939ee28f16.png)

AFAICT, VSCode does the last option, but then also allows the user to resize things manually.

**Comment by jasonLaster** [comment]
Yep the last option seems good and we don't need to support resizing :)
