### ISSUE TITLE
Events Update (August 2021)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3203]
- [x] #3204
- [x] #3205
- [x] #3206
- [x] https://github.com/RecordReplay/gecko-dev/issues/440
- [x] #3207
- [x] #3208
- [x] #3209
- [ ] #3210

(Cobbled together from other issues like https://github.com/RecordReplay/devtools/issues/2900 that were getting really messy)

**Comment by jonbell-lot23** [comment]
Moving into the "shovel ready" section of http://go/designhandoff.

2 items for @jaril , 1 item for @loganfsmyth , nothing requiring design input.

**Comment by loganfsmyth** [comment]
Alright, we've officially got `Session.findNavigationEvents` and `Session.findKeyboardEvents` to query for the new events.

**Comment by jonbell-lot23** [comment]
Going to close this larger issue because we're down to just #3210
