### ISSUE TITLE
Team invite onboarding improvements

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3220]
1. Instead of landing directly on a login screen, people should get more context about why they were invited:

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/9154902/129504007-deb24ca7-3601-408a-bc12-5ca8407a770e.png">

Current on the left, proposed on the right.

2. And once logged in, we're still keeping the "go to team or login" choice, just with a different visual treatment:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/9154902/129504034-7232003b-6897-462a-9ed3-31a68b6fd1b3.png">

Current on the left, proposed on the right.

here's a video explaining the thinking:
https://app.usebubbles.com/2MjGkfpv1br3QkoLYJstrk/comments-on-app-usebubbles-com

And here's the background we discussed in Discord: https://discord.com/channels/779097926135054346/873274683661885460/876573752614346862

**Comment by jonbell-lot23** [comment]
Proposed design:

![01-Email](https://user-images.githubusercontent.com/9154902/129496547-4e3f7ae8-3fb8-4a27-b65e-fdf1c70ae221.png)

![02-TOS](https://user-images.githubusercontent.com/9154902/129496544-48bce463-9b31-4e3e-8ee1-e65ec68d6648.png)

![03-Jump into your team](https://user-images.githubusercontent.com/9154902/129496545-4b8a8eb6-1b2e-4031-87b2-607266c69691.png)

--

We're in a funny place with our brand and visual design where we've got things cooking in the background (branding work, website work, illustrations, animations) but they're not firmly defined yet. So this layout makes things nicer but also leaves the door open to any sort of branding changes that might come.
The exact text is, of course, debatable and we'll tweak it a bunch. But I think this approach is right.

**Comment by jasonLaster** [comment]
Couple of thoughts

1. I think we can drop the first paragraph description in favor of focusing on welcoming
2. The download screen should show the download actions with a tooltip for windows coming soon
3. I think the library option could be secondary similar to how teamflow does it [link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=5743%3A28251)
4. I like our branded circles :) 



[figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=5743%3A28227)

<img width="1956" alt="simplified 2" src="https://user-images.githubusercontent.com/254562/129614701-66818d7d-e43a-4efe-baac-633d003e4c25.png">

**Comment by jonbell-lot23** [comment]
Pretty sure this is closed out
