### ISSUE TITLE
- "Go to Replay work" needs quotes around the team name

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3238]

**Comment by jasonLaster** [comment]
@jonbell-lot23 can you share more context? not sure where this is...

**Comment by jonbell-lot23** [comment]
We can close this. I forget the exact screen, but it's in some notification, email, or header where it says 

You've been invited to the A-Team team

But should use quotes to be more clear, like

You've been invited to the "A-Team" team
