### ISSUE TITLE
New user onboarding improvements

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3240]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/9154902/129504681-f5181afc-5fbf-439c-af71-39066ee66ed7.png">

Here's a quick video of me talking through the steps: https://app.usebubbles.com/c1j1EEZjg9gyLZbgK1A1Ps/comments-on-app-usebubbles-com

(See "Onboarding updates" in Figma.)

**Comment by jasonLaster** [comment]
A couple of thoughts

1. I think we should give users a clearer way to decide if they'd like to setup a team early on. 
2. Once they decide to create a team, they should give it a name first. This is consistent with TeamFlow first giving you the opportunity to setup your company
3. Download Replay should probably have a windows button thats disabled
4. Download Replay should probably let you skip to go to the library

**Comment by jonbell-lot23** [comment]
@jaril to confirm, we shipped this a few days ago, right?

**Comment by jaril** [comment]
Yes, it's fixed by #3262. 

I've filed a follow-up issue for applying the same styling to the rest of the onboarding flows here: #3292.
