### ISSUE TITLE
[Debugger] Object properties in the Scopes view aren't sorted

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#325]
![Screenshot_2020-08-13_15-42-06](https://user-images.githubusercontent.com/16060807/90141659-b411c200-dd7b-11ea-8abe-7fc85c0a2af3.png)

**Comment by jasonLaster** [comment]
What is the default behavior in chrome and firefox?

**Comment by hbenl** [comment]
Both sort alphabetically, with one minor difference: in Firefox capital letters come first, in Chrome they come last

**Comment by hbenl** [comment]
fixed by #665. I've decided to sort case-insensitive because the variables in a scope are also sorted case-insensitive.
