### ISSUE TITLE
Auth0 redirects back to the sign in page

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3263]
**Description:**

When I sign in to google, auth0 redirects me back to the sign in page until the sign in is complete. we should take users to a loading screen while we wait for auth0.

**Comment by hbenl** [comment]
I assume that you meant this behaviour (which is actually not caused by a redirect): https://app.replay.io/recording/fe030ef7-61e6-4075-8b81-a1b50b1cb879
