### ISSUE TITLE
Auth0 authenticate fails with a bad redirect_url

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3284]
Recently I've been seeing white screens occasionally (20%) which go away when i refresh

<img width="1873" alt="Screen Shot 2021-08-20 at 8 28 50 AM" src="https://user-images.githubusercontent.com/254562/130257054-d32004fe-bbec-4f4c-8958-017e26d74ef9.png">
<img width="1870" alt="Screen Shot 2021-08-19 at 3 28 42 PM" src="https://user-images.githubusercontent.com/254562/130257069-94b3bdab-933b-4c67-8422-2f8336d8b79c.png">

**Comment by hbenl** [comment]
* The error message in the first screenshot seems to come from Auth0's [authorize endpoint](https://auth0.com/docs/protocols/protocol-oauth2#authorization-endpoint). That's the endpoint that the browser gets sent to when you click the "Sign in to Replay" button, and it usually responds with a HTTP redirect 
 to `https://webreplay.us.auth0.com/u/login`. I don't know why Auth0's servers responded with HTTP 403 in this case.
* The error message in the second screenshot corresponds to [this issue in Sentry](https://sentry.io/organizations/replay/issues/2490100737/events/?project=5399075). I've looked at several of the reported errors in this Sentry issue and found that in each case the browser tried to load a chunk from a deployment that had already been replaced. For example, [this error](https://sentry.io/organizations/replay/issues/2490100737/events/5762327b961a4970b37e028dce616476/?project=5399075) was seen by @jasonLaster at Aug 24, 2021 7:06:25 PM UTC but it mentions the file `988.b1286ec9e95f2fb70d11.js`, which is part of [this deployment](https://vercel.com/recordreplay/devtools/9DHKVWDb4auzGoJ1n5VFozcQm9WW), which had already been replaced by [this deployment](https://vercel.com/recordreplay/devtools/7frE2XTbXG5wJAXZ3PaCMDDNa4di) hours earlier (at 3:37 PM).

**Comment by hbenl** [comment]
@loganfsmyth Thanks, that's the default redirect URL, which we override in all calls to `loginWithRedirect()`. But apparently Auth0 uses the default URL anyway in some situations, so I've fixed it.

**Comment by jasonLaster** [comment]
splitting out the syntax error https://github.com/RecordReplay/devtools/issues/3403
