### ISSUE TITLE
Upload Screen: Default privacy should be more obvious

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3288]
**Description:**

It should be more clear that the replay will be private

<img width="912" alt="Screen Shot 2021-08-22 at 7 07 20 PM" src="https://user-images.githubusercontent.com/254562/130372920-b9312f34-e1a3-4d3a-8bcc-d692a798f478.png">

**Comment by jonbell-lot23** [comment]
We're going to add a line of text:

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/9154902/130390653-bfeecf27-6241-4506-9c77-55e3a9b1f1ab.png">

Privacy settings: private
or
Privacy settings: public

**Comment by jasonLaster** [comment]
I wonder if theres a nice way integrate this into one sentence as opposed to two lines.

Also `Privacy settings` feels a bit awkward

**Comment by jonbell-lot23** [comment]
@jaril based on our chat this morning, it sounds like "Shared publicly with TEAM NAME" is the right way to go.
