### ISSUE TITLE
Unpredictable behavior of Apollo's MockedProvider

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3303]
In our tests we use Apollo's MockedProvider to mock the GraphQL queries. While looking at #3301 I noticed that the result is not what I expected: open https://app.replay.io/recording/96f6d84d-e8c4-41a7-9d0e-2aa43d231614 and set a logpoint as indicated in the comment. The logged user id shows two different values, one of them is expected and should come from [here](https://github.com/RecordReplay/devtools/blob/783f0686af5219569e138539575c21986b59107c/test/mock/src/graphql/recordings.ts#L66). But the other value (`00000000-0000-0000-0000-000000000000`) is unexpected and seems to come from [here](https://github.com/RecordReplay/devtools/blob/783f0686af5219569e138539575c21986b59107c/test/mock/src/graphql/recordings.ts#L19) (which is used [here](https://github.com/RecordReplay/devtools/blob/783f0686af5219569e138539575c21986b59107c/test/mock/src/graphql/recordings.ts#L90)).
I couldn't find anything explaining this behavior, all the examples I could find were for unit tests where there are only few GraphQL requests (often only one) per test.
I think we should investigate this so that our mock tests don't become unpredictable.

**Comment by jasonLaster** [comment]
@hbenl is this still relevant and/or a priority?

**Comment by jaril** [comment]
@hbenl Think this is worth working on in the next 2 months or meh?

**Comment by hbenl** [comment]
Meh. It's currently no problem but did get in the way last time I worked on the mock tests.

**Comment by jasonLaster** [comment]
Let's close but of course feel free to fix this the next time you're working on the tests.
