### ISSUE TITLE
Comment editor shouldn't appear when not logged in

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3304]
When viewing a recording anonymously, the user can click "Add a comment" on a logpoint and the comment editor will appear, even though anonymous users can't add comments to recordings. When clicking "Post", the frontend actually tries to save the comment, but the backend replies with an "Authentication required" error (and in the UI the comment simply disappears).

**Comment by jaril** [comment]
Addressed this in https://github.com/RecordReplay/devtools/issues/3388.

The new behavior is that we don't allow anonymous users to actually post a comment, but we don't stop them until they hit `Submit`. This will happen when clicking the add a comment button in the breakpoint widget and the console message (#3184).

Adding a comment to the video/screenshot behaves differently. The anonymous user won't see the add a comment button in the first place unless they're logged in.
