### ISSUE TITLE
Next button when inviting team members during the onboarding is not displayed

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3305]
The current team member page in the onboarding flow has a large minimum height. When a user has a small window, it cuts off the next button, so they end up thinking there's a bug. They refresh the page, hit the onboarding flow step 1 again, and then just skip the entire thing.

We should handle shorter window sizes better.

https://github.com/RecordReplay/devtools/blob/master/src/ui/components/shared/TeamLeaderOnboardingModal/TeamLeaderOnboardingModal.tsx#L201-L287

**Comment by jonbell-lot23** [comment]
We should stop using the minimum height here and in other similar screens. It looks visually awkward having the link floating in space down there. Please structure like this:

1. Add email address
2. Divider line
3. Copy link

And when you add an email address, space is added between 1 and 2.
