### ISSUE TITLE
Display event metadata better in the events sidepanel

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3318]
Follow up from #3307.

Right now, we tacks metadata (e.g. the key that was pressed, the URL navigated to) immediately after the event name (e.g. `Key Press Enter`, `Navigation www.replay.io`. We should find a better way to display the metadata — maybe as a secondary line.

**Comment by jonbell-lot23** [comment]
Closing for now -- post launch tweak that's not a P1 for launch
