### ISSUE TITLE
[Viewer] Keep the resolution at maximum 1x

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#332]
Sometimes when the recording is of a small viewport, it can naturally fill to expand the viewer and be 2X...

This should be a relatively easy fix.

<img width="1979" alt="Screen Shot 2020-08-13 at 5 09 11 PM" src="https://user-images.githubusercontent.com/254562/90198888-f5a86a00-dd87-11ea-810d-eac1834cc26e.png">

**Comment by hbenl** [comment]
This is due to the device pixel ratio being ignored in scaling computations. Fixed in #666.
