### ISSUE TITLE
Collapse consecutive keypress events in the events sidepanel

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3320]
Follow up from #3307.

Add heuristics for collapsing keyboard events that should be together. Instead of having `Key Press H` and `Key Press I`, there should be some logic that realizes that perhaps the user was typing something and it should be presented as `Typed HI`.

**Comment by jasonLaster** [comment]
Nice I think some form of tree view makes sense in the future. Today, I think we just need a subset of events we show now. For instance, I think it's fine to pluck the first of n events so the user seeks `Key Down "H"` and not Down, Press, Up. This should both be simpler and still literal.
