### ISSUE TITLE
Team creation flow makes it easy to forget to add a person

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#3331]
I was just creating a team and noticed that at
<img width="530" alt="Screen Shot 2021-08-25 at 2 05 13 PM" src="https://user-images.githubusercontent.com/132260/130864656-3d8f918c-2fb2-45a6-abdc-a70a23d23dc9.png">

I typed in an email but forgot to hit the "Invite" button. I noticed just as I was clicking Next, and it did not invite the user, but allowed me to proceed. 

I'm thinking we shouldn't allow users to press Next if there is anything typed into the email field.

**Comment by jasonLaster** [comment]
@jonbell-lot23 can you include this in your audit?
