### ISSUE TITLE
Unexpectedly prompted about "skip this step"

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#3334]
I opened replay and I was prompted to accept membership in a new team. I accepted both invitations, but once I was done and tried to go back to what I was doing, I got this prompt unexpectedly.

I'm guessing the intent is to encourage people to press "Open"? It feels very heavy. I opened replay to do a task, I don't care that someone invited me to a team, and the fact that the it's so aggressively prompting me, and probably most importantly so _vague_ about what I'm being prompted _about_ is frustrating.

What step is "this step" in this popup even referring to?

<img width="587" alt="Screen Shot 2021-08-25 at 6 58 20 PM" src="https://user-images.githubusercontent.com/132260/130887817-1c7f4a5e-0745-4a22-bfe5-a6e792cc6ddb.png">

**Comment by jasonLaster** [comment]
@jaril do you know what's going on here?

**Comment by jonbell-lot23** [comment]
@jaril I wasn't able to repro this, but I'd agree with @loganfsmyth that this is odd. Can we remove this prompt? Can we spot a valid reason for it to exist?

**Comment by jaril** [comment]
This modal doesn't exist anymore and has been replaced by a shim team link in the library, so the issue can be closed.
