### ISSUE TITLE
[Toolbox] Panel selection not working

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#334]
In the recording below which @jaril created, the debugger panel in the toolbar is clicked on, and gets selected, but the console continues getting rendered instead.  I looked a little bit and the toolbox does call renderDebugger() after the panel is clicked, but I didn't look into why the console stays on top.

https://replay.io/view?id=56a8e053-3fb2-4b8a-aad3-5234ce907ac8

**Comment by jasonLaster** [comment]
I think #348 fixed it.

**Comment by jasonLaster** [comment]
I can still reproduce it when the console is selected and the user refreshes in chrome. Sometimes in firefox...

I left some comments here (https://replay.io/view?id=56a8e053-3fb2-4b8a-aad3-5234ce907ac8)

**Comment by jasonLaster** [comment]
CC @jaril
