### ISSUE TITLE
[Inspector] Highlighter is missing on some nodes

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#335]
STR:
1. https://replay.io/view?id=56a8e053-3fb2-4b8a-aad3-5234ce907ac8
2. select a point 2/3rds in
3. go to the inspector
4. expand to one of the toolbox nodes

https://www.loom.com/share/1dc9eb6975f14fb9994c15aae84620d2

**Comment by bhackett1024** [comment]
Can you create a recording of the problem?  cc @jasonLaster

**Comment by jasonLaster** [comment]
I tried this again and it seemed to work.

here's the recording https://replay.io/view?id=712cc08b-6ae7-4ac1-8375-62168624036b

it's certainly weird, but i think it is okay.
