### ISSUE TITLE
User can't log out when looking at an error

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3350]
![image](https://user-images.githubusercontent.com/15959269/131043443-187004c8-c64e-4929-941b-bd2a925ce287.png)

I was trying to open this Replay that Jason made. At the time, I was logged in to my non-replay email, so I was not able to view it.

Knowing what my error is, it would be nice to have an escape latch — some indication of what account I'm logged in with so I can be 100% sure that I'm on the wrong account, and some way to log out so I can log in properly.

This probably applies to all authentication-related errors that the user could run into.

**Comment by jaril** [comment]
This is handled sufficiently by #3391 and can be closed.

**Comment by jasonLaster** [comment]
<img width="678" alt="Screen Shot 2021-10-14 at 8 57 40 AM" src="https://user-images.githubusercontent.com/254562/137354146-51be2ac4-35aa-4d43-878f-cc518424ef77.png">

**Comment by jcmorrow** [comment]
Closing in favor of https://github.com/RecordReplay/devtools/issues/3853, which is closely related.
