### ISSUE TITLE
The hover previews should not include splats

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3353]
https://app.replay.io/recording/b1632af8-6835-4f80-bf08-75de3daa53dd?point=19471113223695965990772849317512258&time=8386.944036464927&hasFrames=true

**Comment by jaril** [comment]
What are splats?

**Comment by jasonLaster** [comment]
Splats are `...` e.g. `...obj`

Left some more comments in https://app.replay.io/recording/b1632af8-6835-4f80-bf08-75de3daa53dd?point=16874964794329495466674858793894435&time=7533.97183221418&hasFrames=true
