### ISSUE TITLE
It should be possible to hide Console Exceptions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3361]
I was not able to hide these purple exceptions in the console. I was also surprised to see similar exceptions when I selected show exceptions....

https://app.replay.io/recording/54ee91e0-7c17-42ac-bec9-6cca443b2e7c?point=10709112271181975650992204084675142&time=14002.430068041906&hasFrames=true

**Comment by hbenl** [comment]
- the messages show exceptions but the reason they are shown is that they are passed to `console.error()`
- `console.error()` messages got type `error`, but `console.log()`, `console.warn()` etc. got type `log` and the filters are only applied to messages with type `log` or `javascript`. The linked PR changes their type to `log`.
- I noticed we have filters "Show Info" and "Show Debug". I assume those were supposed to filter `console.info()` and `console.debug()` calls, but our backend actually doesn't distinguish those from `console.log()` calls, so I removed those filters.
- I'm not sure what "Show Exceptions" does, but it seems to show where exceptions are generated. The exception messages that you couldn't filter out are from a `console.error()` call in a `catch` clause. So it seems that these could indeed be the same exceptions, just at different points in their lifecycle
