### ISSUE TITLE
DevTools tab is very sluggish

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3367]
It takes a full five seconds to load the DevTools tab in this Replay:
https://app.replay.io/recording/438f8d07-053f-4b70-b2ed-c21c76ba2efd?point=23689854433342155656206590058431186&time=14066&hasFrames=false

This toggle is every developer's first impression with Replay, and an action many people will perform many times. We need to make this load instantaneously, even if it means some pre-caching in the background. We can't lazy-load it and bottleneck on requests.

**Comment by jasonLaster** [comment]
After digging in,

1. it looks like we do not spend that much time in this replay waiting for the devtools to be imported

2. we _do_ wait awhile for codemirror.

The easiest thing to do is to preload the modules.

**Comment by jasonLaster** [comment]
Here's one option with the import at the top of the module
https://app.replay.io/recording/fe3c49ef-2bd9-468f-b53f-e8038f529c21?point=28557632730613195713585259671978303&time=15514.539742166824&hasFrames=true

**Comment by jaril** [comment]
> Here's one option with the import at the top of the module
> https://app.replay.io/recording/fe3c49ef-2bd9-468f-b53f-e8038f529c21?point=28557632730613195713585259671978303&time=15514.539742166824&hasFrames=true

This looks good — doesn't appear to get in the way of the first viewer load, but starts importing the slow stuff when nothing's really happening. Can we merge it?
