### ISSUE TITLE
Reenable limited markdown support for comments

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3370]
**Description:**

We should support the simplest form of markdown where atleast formatting is preserved

### editing
<img width="236" alt="Screen Shot 2021-08-29 at 12 34 30 PM" src="https://user-images.githubusercontent.com/254562/131258113-89950e18-4756-425b-b11e-26509180d9e1.png">

### rendered
<img width="234" alt="Screen Shot 2021-08-29 at 12 35 15 PM" src="https://user-images.githubusercontent.com/254562/131258112-70ac9249-9bed-4cab-8033-a2b99c6c89d8.png">

**Comment by hbenl** [comment]
Did we ever have markdown support in comments? Otherwise I'd suggest simply wrapping the content in [`<ReactMarkdown>`](https://www.npmjs.com/package/react-markdown).
