### ISSUE TITLE
Webpack server crashes after a couple of minutes

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3371]
I believe this started happening after the move to webpack 5

<img width="1440" alt="Screen Shot 2021-08-29 at 12 46 56 PM" src="https://user-images.githubusercontent.com/254562/131258460-9d5b291a-ffa7-49c9-9d1b-433972f04d54.png">

**Comment by ryanjduffy** [comment]
I get this from time to time too. I assumed it was due to running the backend and the frontend locally but perhaps its a broader issue.
