### ISSUE TITLE
Editor tabs context menus no longer work

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3373]
**Description:**

The context menus for editor tabs stopped appearing

https://app.replay.io/recording/3e36a34a-754b-40b9-ab2d-dba667080231

**Comment by jasonLaster** [comment]
likely a regression from the flexbox changes @ryanjduffy made a month or so ago to fix the scrollbars

**Comment by jaril** [comment]
https://app.replay.io/recording/39f1b457-2443-4d55-ab28-0474f3f74464?point=23040817311622803852906223686911602&time=10331.227173913043&hasFrames=true
