### ISSUE TITLE
Our browser onboarding flow needs alignment with other flows

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3383]
Specifically we want the look and feel to look like the black background onboarding flows that are coming elsewhere in the product.

**Comment by jonbell-lot23** [comment]
Ryan, @jaril is just about done with the new onboarding flows with a black background. When he's done, can you implement those changes into the browser? It'll look sort of like this, stay tuned for final visuals:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/9154902/132597636-ef34b80b-ecdd-487c-ae1f-e6495603fd12.png">

**Comment by jonbell-lot23** [comment]
Oops, these are in devtools so let's just keep it with Jaril

**Comment by jaril** [comment]
`src/views/browser/welcome.tsx`
