### ISSUE TITLE
Update Console interactions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3398]
**Description:**

I have a couple of concerns about the new console interactions

* They're significantly smaller than before
* They're on the right and hard to see

I propose we use something similar to what we had before, but with a bit of a design system touch up

[Figma link ](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=6035%3A27664)

Caveat - This design works if the icons receive the right amount of visual love so they're consistent and fit the space well. My quick attempt shows what not to do :)

### proposal

<img width="818" alt="proposal" src="https://user-images.githubusercontent.com/254562/131420848-a69344c3-c0d2-4196-980e-bd51347ac803.png">

### current

<img width="1094" alt="new design" src="https://user-images.githubusercontent.com/254562/131420741-57784ffe-7d2c-42ae-b9a9-866f361660d5.png">

### old

<img width="819" alt="old design" src="https://user-images.githubusercontent.com/254562/131420766-cc5961bd-e8be-4f45-bc89-222aee3650d7.png">

**Comment by jonbell-lot23** [comment]
I think we all agree the current interaction needs iteration. Here are some of the issues we've worked through:

**Small icons vs full text**
Both the pro and the con of icon-only is that it doesn't take much space. The pro and con of using full text is that it's very clear ... but heavy.

**Expanding text versus tooltip**
We had a design that expanded the text with an animation effect, as we've done in the past. For this version we agreed on a tooltip, but it's clear we should go back to the expanding text version. It gives us subtly at a glance and clarity on mouseover.

**Left versus right**
We have a tiny console width, and the only way to resize it conflicts with putting them on the left. It is my strong point of view that these interactions be on the right.

--

<img width="472" alt="image" src="https://user-images.githubusercontent.com/9154902/131483150-0765b5f3-c8f8-41ca-ad12-5e749a98e4a0.png">

The components that will make this design work well are:

* A minimised icon that appears on row hover
* A fuller button that animates in on object hover (with a delay)
* A full line height so the action fits snugly into each console row
* Right-alignment, to not interfere with the resize experience

Other details:

* Console messages in the past should have a slightly different treatment than ones in the future.
* We don't need the purple pause icon. It's not actionable or clear.
* The delay, animation, and possible dropshadow will require finessing to make it feel right.

**Comment by jasonLaster** [comment]
I absolutely love the design details here

1. the full height layout with icons / copy treatment look great
2. the highlight effect (gradient/dropshadow)

I'll admit, i'm not sure about the left/right distinction, but it's easy to go with the right and then flip if we find the left more discoverable.

I'm happy dropping the pause icon. We can always tweak the purple paused line treatment down the line too
