### ISSUE TITLE
Disable logrocket on devtools

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3471]
We talked about this in stand-up. We'll be disabling logrocket on devtools for the meantime. This is a temporary measure until we have enough sophistication to allow users to log-in to logrocket and/or are satisfied with the redaction.

https://github.com/RecordReplay/ops/issues/118

Assigning @jonbell-lot23 and @ryanjduffy just because you guys were assigned to the original ops issue. Feel free to modify the issue in case that's not the best way to proceed!

**Comment by jonbell-lot23** [comment]
Here's a write-up for how I propose this would work:
https://replayio.notion.site/Logrocket-Opt-in-194d3bb9dd3b4617bef428ce64cad9b6
