### ISSUE TITLE
The Inter font is not being properly loaded in the Replay browser

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3506]
Looks like not all font weights for Inter are being exported properly into Firefox.

Screenshot below. It looks like Inter with `font-weight: 600` which is applied to the header/function name in a comment doesn't work, and so the browser falls back on `sans-serif`.

Firefox | Chrome
-- | --
![image](https://user-images.githubusercontent.com/15959269/132612787-eb14af37-8974-460e-b360-fbea63675a50.png) | ![image](https://user-images.githubusercontent.com/15959269/132612826-be351830-2fa5-49a7-8ae8-ebcc276d376c.png)

**Comment by jaril** [comment]
On second look, it looks like we didn't export that weight at all. So Chrome falls back on what Inter it can find, but Firefox bails and fall backs on sans-serif.

**Comment by jonbell-lot23** [comment]
Whoops! Here's the fix: https://github.com/RecordReplay/devtools/pull/3507
