### ISSUE TITLE
Global timeline can't be clicked

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3509]
It feels weird that the global timeline can't be clicked to jump to a particular moment in time but the current time handle can be dragged to do that. As a user I would expect for the regular clicks to be working as it's basic feature of the most video players

**Comment by jasonLaster** [comment]
Wow, that's a great point. Surprised we haven't noticed that yet :)

**Comment by hbenl** [comment]
Could you make a recording of this? It works for me in both Firefox and Chrome.

**Comment by Andarist** [comment]
Can't repro it either at the moment. For the record - it has happened on [this recording](https://app.replay.io/recording/021b77d8-dff3-4f0f-b857-6a6733bba947) in the Replay browser. I'll close this issue for now and make sure to record a replay when reporting a problem (if only that will be possible). I've assumed that this problem was universal and I just didn't bother with that - my bad 😬
