### ISSUE TITLE
[Recorder] recording ahana.com does not load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#353]
Miriam and I were playing with Replay and found two things;

1) Replay could not connect to the server for the first 3 tries
2) Replay could not load one of the pages while recording

### Replay could not load one of the pages while recording
Here is the recording we tried -- https://replay.io/view?id=727b229a-9e8f-4cbe-abfa-7f4c8c1de295
It should look something like this:

<img width="1144" alt="Screen Shot 2020-08-15 at 11 41 20 AM" src="https://user-images.githubusercontent.com/254562/90317063-a07d6d00-dedb-11ea-8743-9694749a2714.png">

**Comment by bhackett1024** [comment]
Hmm, I'm not sure what happened here, does it reproduce?  I just made a recording of this site and it worked fine.

https://replay.io/view?id=530f66cd-90bd-4009-9f18-76974d69788d

**Comment by jasonLaster** [comment]
@miriambudayr  could you try re-testing?
