### ISSUE TITLE
Evaluation blocker breaks CI

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3544]
The recording below shows test failures where the devtools are disallowing evaluations because the user isn't part of a team plan.  These are CI recordings, however, and the user needs to have access to developer features.

https://app.replay.io/recording/11724327-65de-4f07-b887-141f47fad2ed
https://app.replay.io/recording/b677c133-1f35-40d5-9793-8870f4bdfec2

**Comment by ryanjduffy** [comment]
Fixed by https://github.com/RecordReplay/backend/pull/2970
