### ISSUE TITLE
Non-owners should not be allowed to apply changes to a replay

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3549]
In the Library's table of replays, we hide the recording dropdown from a user if that user is not the owner of the recording. This prevents them from performing actions, e.g. delete, private/public, move to a different team.

We don't have a similar check for when we're doing bulk actions to the replays. The backend doesn't permit the operation but the frontend makes it look like it does.

During a bulk action, we should hide the checkboxes for replays that don't belong to a user. An extra step would be to hide all non-editable (read: non-owned) replays for that user, but let's try this out first.

**Comment by jasonLaster** [comment]
Nice
