### ISSUE TITLE
Update the comment icons in the timeline

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#3552]
Right now those icons are ~15px and the edges aren't crisp. Let's use something that's easier to make out — maybe even the comment icons currently being used in the library to keep it consistent. 

Material icons are 24px standard and maintain the crispness on multiples of 6 (12/18/24). That would require bumping it up to 18px though, so we'll have to experiment with it.

timeline comments
![image](https://user-images.githubusercontent.com/15959269/132924475-a9e4457a-1c6c-4da5-ab58-6d8fef4b7be8.png)

replay table comments
![image](https://user-images.githubusercontent.com/15959269/132924499-27c02370-831a-4e7f-95b8-abca6a84fbf2.png)

**Comment by jasonLaster** [comment]
I wonder if 12px and lighter would work too...
