### ISSUE TITLE
The library should show the title when narrow

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3555]
**Description:**

We should collapse the columns on the right instead of hiding the the title, url and screenshot. I think we could do this by setting a min-width for the left columns

<img width="1001" alt="Screen Shot 2021-09-11 at 8 53 55 PM" src="https://user-images.githubusercontent.com/254562/132971495-55040522-58e1-4cf9-8a2d-22eb5c9b3e29.png">

**Comment by jaril** [comment]
This is now mitigated by https://github.com/RecordReplay/devtools/pull/3643. 

The title only disappears now if you make the window _very_ narrow. The next step would probably be to add some sort of width breakpoint after which we snap into a narrow mode of sorts. But I think this is good enough to be closed.
