### ISSUE TITLE
Polish the Print Statement panel

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3557]
**Description:**

It would be nice to polish the print statement panel so that it looks as good as possible

1. Should the expression have a border around it? Should there be a background color?
2. How should we handle hovering? what cursor should we use? What treatment should it have?
2. Should we syntax highlight the expression? I know we discussed in the past, but I think that would look nice. 
3. How should we show the edit field? Should there be a border? A background color?

**Comment by jonbell-lot23** [comment]
See https://github.com/RecordReplay/devtools/issues/3558
