### ISSUE TITLE
Update Print Statement UX and First Use

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3558]
**Description:**

We should have some print statement tooltips the first time that users add a print statement. Here is a rough version.

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=6400%3A32527
<img width="1755" alt="tooltip" src="https://user-images.githubusercontent.com/254562/132997172-d3916028-c0b9-4316-9460-85debd625938.png">

**Comment by jasonLaster** [comment]
1. the expression is syntax highlighted (similar to how we highlight expressions in the breakpoints pane)
2. the top section is the editor
3. the comment button is replaced with a save button
4. We use a hat design for the nag (design needed)

**Comment by jonbell-lot23** [comment]
Here's the loom discussion: https://www.loom.com/share/0f9e18b3f6d64ff9bf5eead81d51bc02

**Comment by jonbell-lot23** [comment]
Here's the proposal:

![image](https://user-images.githubusercontent.com/9154902/133015043-7712b656-cc5b-4e36-bab4-bb981df4d8b8.png)

1. Nag screen as "hat" on top of the log panel
2. Encourage them to edit the line
3. Tell them to look at the console

Then without a hat the logpoint panel looks pretty similar.

Here are some additional cases:

![image](https://user-images.githubusercontent.com/9154902/133015125-af50310d-9c74-4890-84ce-676c0812981a.png)

1. Hover state will show edit cursor and dotted underline
2. Error state will show red text and no save button

**Comment by jonbell-lot23** [comment]
Here's an alternate treatment with black background:
![image](https://user-images.githubusercontent.com/9154902/133015312-21e279b0-dc60-48e6-9ee6-14ac28cc3635.png)

**Comment by jasonLaster** [comment]
* both the blue and black look good
* what's the thinking behind not centering the pencil? 
* the dotted line looks pretty dope

**Comment by jonbell-lot23** [comment]
@jasonLaster Ah, that was a mistake. I was trying to say the pencil should be a cursor. So there wouldn't also be a mouse cursor.

**Comment by jasonLaster** [comment]
I have no idea how hard/how weird a pencil cursor would be so purpose that's a follow up, but i think the dotted lines as a text treatment should work
