### ISSUE TITLE
Create Replay screen has a blank textfield

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3564]
[Update: this page is going to be re-written once we have our auto-record functionality live. Stay tuned.]

This shouldn't be blank.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/9154902/133005618-0b52eaaa-6e91-482b-9a1d-7ad376cb0ce5.png">

**Comment by jasonLaster** [comment]
Lets go with this screen!

<img width="1440" alt="time-travel" src="https://user-images.githubusercontent.com/254562/133006649-768bcf0d-a6bf-430e-96b4-b8896319ec67.png">
