### ISSUE TITLE
Upload screen edit is broken

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3565]
Clicking the edit button shows this. The team dropdown isn't loading.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/9154902/133005639-df16b0f1-acf4-4827-8179-03c44c3996a6.png">

**Comment by jaril** [comment]
Which account were you on when this happened? This is an expected case for users with 0 teams, where we just hide away the team dropdown part. That said the `TEAM` label shouldn't show up. Filed a PR to fix that and the font size.
