### ISSUE TITLE
Make default teams page

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3573]
The current teams page default is pretty boring:
![image](https://user-images.githubusercontent.com/9154902/133058911-0c77b577-1186-4079-ab6c-5c1f1c8ab1a7.png)

We'd like to add an illustration. Eventually we'll come up with something more Zypsy-tastic, but for now this is a good placeholder:
![image](https://user-images.githubusercontent.com/9154902/133059007-a20b572c-9b7e-4c66-8eee-cc0fe1595450.png)

**Comment by jasonLaster** [comment]
Couple of thoughts:

1. I like the idea of having an illustration. Not sure if resting is what i'd go for though. The sentiment should be more active. Like buying a new car and taking for a test spin... right? like waiting wont get you replays :)

**Comment by jonbell-lot23** [comment]
Totally agree @jasonLaster . What I'd love is something time travel themed that is more active, but haven't found that yet. But yeah, a couch is as passive as possible. Will find something better!

**Comment by jonbell-lot23** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/9154902/133188513-b48388e0-9e3a-4940-8487-936446a6c50c.png">

Time travel, cool, nerdy, more active than passive, and PUNS.

**Comment by jasonLaster** [comment]
haha alright - we can ship this, we just need to help users know what to do... which includes downloading the browser if they dont have it already and recording their first replay

**Comment by jonbell-lot23** [comment]
Good news -- you don't appear here without downloading Replay. The standard flow goes like this:

Website ->
Download Replay ->
Launch Replay -> 
Demo ->
Create new team flow ->
*Then* you'd see this.
