### ISSUE TITLE
Add Oauth data to Devtools telemetry messages.

### ISSUE THREAD

**Issue by kannanvijayan** [RecordReplay/devtools#3576]
Devtools telemetry is sent from the frontend, not the browser, and does not send along user data for `DevtoolsUnexpectedError` messages (and probably others).

Adding an `Authorization: Bearer <token>` header to the telemetry requests sent by this code will allow the telemetry server to associate inflated user data with the messages.

**Comment by jasonLaster** [comment]
we're sending the user object along https://github.com/RecordReplay/devtools/blob/master/src/ui/utils/telemetry.ts#L102
