### ISSUE TITLE
[Tooling] Setup Jest

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#358]
It would be great to setup jest again and be able to run the Jest Debugger + Console test suite. Some of the tests have definitely gone stale, which would be fine disabling or removing, but being able to manage the test suite again will be a big deal.

**Comment by jasonLaster** [comment]
Here are some files from gecko-dev
https://searchfox.org/mozilla-central/source/devtools/client/debugger/jest-test.config.js
https://searchfox.org/mozilla-central/source/devtools/client/debugger/jest.config.js

**Comment by hbenl** [comment]
First steps: https://github.com/hbenl/webreplay-devtools/tree/setup-jest
