### ISSUE TITLE
Library actions dropdown is clipped on short list

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3598]
**Description:**
When there aren't that many replays, the actions dropdown gets clipped

![image](https://user-images.githubusercontent.com/254562/133288759-3505ab17-9a1b-408b-8236-c6cb2c5c610a.png)

**Comment by ryanjduffy** [comment]
I think this is actually a bug with showing "Move to" when there's nothing to move to. I do think we have a dropdown placement issue though as opening it on the last item in the list causes it to render out of view below instead of flipping to the top.
