### ISSUE TITLE
CodeSandbox Client.ts sourcemap is off

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3600]
**Description:** The sourcemap for Client.ts in this [replay](https://app.replay.io/recording/fd597a4d-5b6d-4ec6-a8a6-b5a0a39008e7
) is pretty weird

**Bug Report:** [Replay](https://app.replay.io/recording/dc0b1499-8d1a-4ce5-9f11-0ae326f2ea37?point=62307562311732062712984887359440295&time=26672&hasFrames=false)

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
