### ISSUE TITLE
Unexpected session error

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3632]
**Description:**

Our "unexpected session crash" modal is confusing. It assumes users know what a session is and suggests that refreshing can help. We should probably use this opportunity to teach people a bit about what is going on in the backend and let them know we're on it. 

<img width="506" alt="Screen Shot 2021-09-16 at 11 24 21 AM" src="https://user-images.githubusercontent.com/254562/133665043-696848c2-0167-4a82-bcc7-d4ff5f57988a.png">

**Comment by jonbell-lot23** [comment]
I changed the text to:

Our apologies!
Something went wrong, so we've contacted our engineers and they'll look into it as soon as possible.

**Comment by jasonLaster** [comment]
Our apologies!
Something went wrong on our end. We'll look into it as soon as possible and let you know what we find.

**Back to library**
