### ISSUE TITLE
Re-Add Intercom Messenger

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3660]
**Description:**

Talking to brian schultz, having a support messenger helped them get 200-300 messages from their 2k new users in onboarding. That's a huge asset for 2 reasons: 1. feedback means they can learn 2. conversations help them build relationships

I think we can do something similar by re-adding the intercom messenger in the bottom left of the replay. This space is great because we use it to when starting up the replay for the progress spinner and then we give it back. 

Lastly, this doesnt have to be a long term solution, but we should definitely have something in the short-term to learn from our new users.

**Comment by jonbell-lot23** [comment]
Do we have a design for this? @jaril @jasonLaster

**Comment by jasonLaster** [comment]
Nope, lets discuss soon
