### ISSUE TITLE
Comment buttons are wrong

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3665]
This doesn't look right:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/9154902/133950011-04e07fad-c09a-4ec6-b1b5-b7da85e0bad7.png">

**Comment by jaril** [comment]
@jonbell-lot23 What specifically doesn't look right?

**Comment by jasonLaster** [comment]
we're axing the buttons
