### ISSUE TITLE
Add content to login page to better direct users

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#3670]
We had someone land on app.replay.io from a referral from a teammate looking for product info and thought they needed to log in to get that info. That seems like a reasonably likely scenario in the future and wondering if we should flesh out that auth landing page a bit to help inform and direct people a bit better.

**Comment by jonbell-lot23** [comment]
**Design POV**

1. In TailwindUI, check out this component in the modals section: [Centered with single action](https://tailwindui.com/components/application-ui/overlays/modals#component-31555aec01de5027d6696629eb60f673)

2. In Figma, look for page [Better login page #3670](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=6629%3A38645) to find my design

![image](https://user-images.githubusercontent.com/9154902/134110181-2a4866d6-16c7-4636-96bc-2cf0968cd1b1.png)

We'll have plenty of time to work on this page (I'm envisioning more personality/illustration) but this is a good start.
