### ISSUE TITLE
Overlay on list of recordings is cut off

### ISSUE THREAD

**Issue by cbejensen** [RecordReplay/devtools#3671]
When viewing a list of recordings on https://app.replay.io/ , you can click the 3 dots icon on the far right to open an overlay. However, this overlay gets cut off at the bottom of the list.

![image](https://user-images.githubusercontent.com/12374723/134044550-a29de412-e73d-4ed1-9d13-0de43297ed3e.png)

[Here's a Replay](https://app.replay.io/recording/d9f8c140-b1c1-43fd-9d80-c60669ec3ea4)

**Comment by jasonLaster** [comment]
Thanks for filing @cbejensen!
