### ISSUE TITLE
Enabling/disabling a breakpoint scrolls the console unexpectedly

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3685]
**Description:**

**Steps to Reproduce:**

1. Have a breakpoint
2. debug to get yourself into a different pause point
3. enable a new breakpoint there
4. disable that breakpoint

**Expected Result:**

I'm unsure. For the most part, I would not expect the console to be scrolled like that. If anything scrolling when **enabling** makes some sense but I'm also unsure if that's super needed. Especially given the fact that you might have many hits for a certain breakpoint, so where do you scroll to in such a situation? 

Scrolling the console when **disabling** a breakpoint is rather unwanted and distracting for me.

**Additional Context:**

* Screenshots:
* Video (Loom): https://www.loom.com/share/032896b2961c450baccd28eff3a91973
* Replay:

**Comment by hbenl** [comment]
@Andarist Perhaps the best solution is simply to only scroll when you're jumping to a different point in time. You can try it out at https://devtools-chx99cnfq-recordreplay.vercel.app/, tell me what you think.

**Comment by Andarist** [comment]
@hbenl that may very well be subjective - but it feels better to me 👍
