### ISSUE TITLE
Free Trial badge v2

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3699]
We tried making a trial badge in this ticket: https://github.com/RecordReplay/devtools/issues/3651#issuecomment-924423928

We landed on a simple text treatment, like this:
![image](https://user-images.githubusercontent.com/9154902/134255372-885dcfcf-ee97-48d4-8574-26a8f0913d15.png)

But next we need to update our billing page and add nags as the trial gets closer to expiring. That's where we'll get more bold and obvious.

**Comment by jonbell-lot23** [comment]
For the same reasons as our V1 discussion, I prefer the simple "(Trial)" treatment, but this time with a second line:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/9154902/134844275-1c41d52e-8ae2-4a0c-b235-2b2704c62331.png">

And then it would go hand-in-hand with the [billing page polish ticket](https://github.com/RecordReplay/devtools/issues/3681), currently in low fidelity:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/9154902/134844308-035146d2-2cf8-4ed3-a260-a20712c7b1cf.png">

And then there are other things to consider, like showing status in loading screens, or even in the product:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/9154902/134844862-e0a0ec7f-8686-4292-b51c-26327dbe854f.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/9154902/134844881-98317963-77fd-4b86-8e59-9219ecd8978e.png">

**Comment by jonbell-lot23** [comment]
Here's my proposal.

1. Left sidebar: simple link as second line
<img width="352" alt="image" src="https://user-images.githubusercontent.com/9154902/135370593-4f743d00-9c4d-4bbe-a62c-4ec384f31363.png">

2. Replay title: simple link as second line (I think one line is clumsy)
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/9154902/135370639-1dafafc0-4a42-4d80-80b7-62a985ceaeb1.png">

3. Loading screen
<img width="630" alt="image" src="https://user-images.githubusercontent.com/9154902/135370689-ca7e28b7-f34d-4cb2-8ca4-b12668760920.png">

The loading screen needs work. I think a circle will be better, and I think we should animate it. But putting this text in somewhere is a good idea.

**Comment by jasonLaster** [comment]
Couple of thoughts:

1. putting the badge next to the library team title is more prominent when you're viewing the team
2. putting the badge to the right of the title in the replay gives you more vertical space to catch people's attention and does not change the default styling of the title
3. the loading screen (i think) is too fast and would not let people act on it... like one second its there the next its gone.
4. the upload screen would be great because we can message there that in 4 days, new replays wont be viewable which is awesome because that's also a great place to message after its expired that you cant see the new replay.

![Frame 21](https://user-images.githubusercontent.com/254562/135389479-fec27bd8-ec33-4c5c-a6fd-cb0b1ac350a2.png)


<img width="1537" alt="Frame 20" src="https://user-images.githubusercontent.com/254562/135389468-3e83bf5e-57fa-46fd-892f-4b8d7ced4de2.png">

**Comment by jonbell-lot23** [comment]
Works for me. A few notes:

* Through a tradeoffs lens, we're saying we want something more prominent rather than something less prominent. In both cases, we're playing with the default styling. A second line can be both consistent (adding a second line sticks to the design pattern rather than being considered a new approach or design element) and obvious (by using colour). A badge goes all-in on discoverability. I think it's a bit over the top, and uses a pattern we use nowhere else, but I'm fine with it.

* The loading screen doesn't need a call to action, it's fine just having a quick line of text. Our loading screen is quicker than over, but it's not so fast someone can't read a line of text. Happy to punt on this for now, especially because the loading page needs an overhaul anyway.

* I think the upload screen is a fantastic point, I'll draw something up.

**Comment by jonbell-lot23** [comment]
Alrighty, here's a design I like.

(Nitty gritty: we're using the same font size, with the same spacing, and the same border radius.)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/9154902/135401831-36899266-6765-4f71-bc25-18982549246d.png">

We can use gray at first, then switch to a brighter colour like this yellow when it gets closer to the trial expiration, like a week. And then here's how it could look in the upload screen. I like it as a capsule positioned right at top rather than trying to position it inside the component itself.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/9154902/135402140-cba3eed1-8f46-4e95-a066-66f0fd74b464.png">
