### ISSUE TITLE
Breakpoint overlay recently broke on Safari

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3705]
**Description**
I have a Replay that doesn't show the breakpoint overlay when hovering in the gutter.

**STR**
1. Go to https://app.replay.io/recording/2e6e30f0-f0eb-48e1-9bae-a1072dc4c124
2. Try to set a breakpoint

**Expected**
It should work like other Replays.

**Actual**
Nothing happens. Unfortunately I couldn't reproduce in Replay. Here's a Loom I recorded while using Safari: https://www.loom.com/share/8bcb7928ee1b4c5eb7509c164159ea58

The Replay is old, so maybe that's part of the issue?

**Comment by jasonLaster** [comment]
@jonbell-lot23 can you record a replay of the bug?

**Comment by hbenl** [comment]
This doesn't work in Safari - like (probably) many other things in Replay (the library layout looks broken, for example). If we want to support Safari, we'll need to track all of these down and be more careful about Safari compatibility in the future. In any case I guess we should make clear that Safari currently isn't supported and what our plans for future Safari support are.

**Comment by jonbell-lot23** [comment]
I use Safari as my primary browser and Replay works exactly the same as Chrome. (When it hasn't, I've filed a bug. For example the library used to be messed up, but it no longer is.)

Breakpoints do work in Safari, just not this particular Replay.

**Comment by hbenl** [comment]
Interesting. I was using Safari 14.0, I guess you're on 14.1? Do I need to update MacOS to update the browser?

**Comment by jonbell-lot23** [comment]
Apologies for this task being overly vague @hbenl . Let me go do a better audit of where Safari is working and not working and I'll circle back on this.

**Comment by jasonLaster** [comment]
Yep - I'll add it to airtable. I think it is reasonable to put a nag/banner at the top of the replay saying that Safari is not supported.

**Comment by jonbell-lot23** [comment]
Odd! I know breakpoints worked on Safari until very recently, but unfortunately I can't pinpoint exactly when they stopped working. I just experimented on 7 random replays and none of them worked, so clearly it's not unique to a single Replay, which was my original belief.

I'm not arguing that we need to support Safari 100%, but this is our star feature, Safari works in all other cases I've seen, and I know this is a regression. So we should either a) fix this or b) throw a warning in Safari that says we don't support our star feature in Safari. Right now it just fails silently, which isn't acceptable.

**Comment by jonbell-lot23** [comment]
> Yep - I'll add it to airtable. I think it is reasonable to put a nag/banner at the top of the replay saying that Safari is not supported.

Our comments passed each other in transit. Strongly disagree with a blanket "not supported" message when we're just dealing with a single regression on our star feature. It's a bad look and the fix should be trivial since it's always worked before now.

**Comment by bhackett1024** [comment]
> > Yep - I'll add it to airtable. I think it is reasonable to put a nag/banner at the top of the replay saying that Safari is not supported.
> 
> @jasonLaster
> Our comments passed each other in transit. Strongly disagree with a blanket "not supported" message when we're just dealing with a single regression on our star feature. It's a bad look and the fix should be trivial since it's always worked before now.

I agree, things need to work in safari.

**Comment by jasonLaster** [comment]
Ahh - i was under the impression that many things were absolutely broken in Safari. I've never tested Replay in Safari and thought folks were saying it'd be a lot of work to fix it all.

**Comment by jonbell-lot23** [comment]
Woooo -- really hoping it's simple, since it was working until recently

**Comment by jaril** [comment]
Looked a bit into this. It looks like it's some CSS issue — the tooltip's appearing, it just happens to be behind the sidebar.

![image](https://user-images.githubusercontent.com/15959269/136228412-edfdf735-95bf-467b-95ad-030c944afa0e.png)
