### ISSUE TITLE
[Recording] framer.com

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#371]
logging into framer and recording a new project is fascinating

https://replay.io/view?id=e1bb6afa-307d-4cfe-9928-eb309dae59ad

I don't think it finished loading, but it did not crash either...

**Comment by bhackett1024** [comment]
Hmm, recording a new project with some content WFM.

https://replay.io/view?id=605bb31e-cf5c-450d-965a-469bd52ac7b9
