### ISSUE TITLE
Clicking on a line of code comment should take me to that line of code

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3713]
Check out this Replay: https://app.replay.io/recording/f35ca05d-9695-4139-ad2a-79a6177cd649?point=11033630825642825368688768254476469&time=5470.448706512043&hasFrames=true

It's Dan Replaying a Replay, and also me adding comments that aren't jumping to a line of code. Inception!

**Comment by jasonLaster** [comment]
@jonbell-lot23 what was your first comment trying to say?

**Comment by jonbell-lot23** [comment]
@jasonLaster Yup, echoing Dan's comment. I was just adding a comment on a random line of code. No deeper meaning.

Agree with the hover effect. Here's a range of proposals:

Three icons
No hover, slight colour on hover, slight colour + circle icon

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/9154902/134595057-1c5f0442-db8c-4edc-bbc7-760983b21e76.png">

Thoughts? My favourite is probably the bottom right corner -> Code icon in a circle. But open to thoughts!

**Comment by jasonLaster** [comment]
Yep, bottom right is nice although not sure we need the underline if we've got the hat background color and icon changing on hover along with the cursor.

**Comment by jonbell-lot23** [comment]
Ok, marking as design-complete after a chat with @jasonLaster :

![image](https://user-images.githubusercontent.com/9154902/134600990-9fa3a94b-6630-48e8-9aee-a14801eda8a0.png)

* No underline needed
* Slightly tint the top of the div (#F9F9F9) on hover
* Code icon with a nice little circle around on it hover

**Comment by jasonLaster** [comment]
Landed the first bit [here](https://github.com/RecordReplay/devtools/pull/3723) because I was embarrassed that a user who i was sharing a comment with would miss that the comment linked to the code 😉

**Comment by jasonLaster** [comment]
We also have a new issue here too

Clicking on line of code reference in a comment should change to DevTools, not stay in viewer #3751

https://app.replay.io/recording/20356f94-d575-4e43-9624-1fc5ea72fcef?point=22067261650975253139456809047688154&time=9508&hasFrames=true
