### ISSUE TITLE
Replay back button should return to the team library

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3721]
**Description:**

Currently clicking on the back button in the replay takes you back to your library, not the team library.

**Comment by jasonLaster** [comment]
This is a really nice improvement and will force us to have better routing 
https://github.com/RecordReplay/devtools/pull/3510

**Comment by hbenl** [comment]
This has nothing to do with the back button: restoring the user's selected library was broken for a while, but it was already fixed by [this commit](https://github.com/RecordReplay/devtools/commit/82ca931084d8f23c849e900c5cac9e72f851200e)

**Comment by jasonLaster** [comment]
We're talking about the `<` in the replay that takes you back to the library

**Comment by hbenl** [comment]
> We're talking about the < in the replay that takes you back to the library

That button was broken and is now working again for the same reason.
https://app.replay.io/recording/32c6de92-adde-4470-be5b-068d778318bc

**Comment by jasonLaster** [comment]
Hmm, i'm confused... 

If I currently am viewing "my library" and then click the back button for a replay in the "Stately" team, it should take me to the stately team, but i'm pretty sure it will bring me back to "my library". 

I dont know if we specified this before, but it is a strong argument for workspace id in the library url

**Comment by hbenl** [comment]
OK, I thought the expectation was to return you to the team that you had selected the last time you were viewing the library. But you expect to be taken to the team of your last viewed recording (which is the same if you opened it from the library, but not necessarily otherwise).

**Comment by jasonLaster** [comment]
closing as this is not a priority. This will also be a lot easier with next.js routing
