### ISSUE TITLE
Improve console error styling

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3747]
* The hover background is off
* Links should be move obviously clickable

Replay with the [error](https://app.replay.io/recording/dd74c91a-4e82-4b56-ac11-7f175e8dcd79?point=32451855370276779961995920356148098&time=18108&hasFrames=true)
Replay of the [hover effect](https://app.replay.io/recording/fd98ff17-4d65-4b61-99b8-59c34e4876)

<img width="806" alt="Screen Shot 2021-09-26 at 10 45 48 AM" src="https://user-images.githubusercontent.com/254562/134818350-a3989066-efcc-4805-a7ce-139b342c76c1.png">
1d

**Comment by jaril** [comment]
Hover effect link: https://app.replay.io/recording/fd98ff17-4d65-4b61-99b8-59c34e48761d
