### ISSUE TITLE
Console: Expanding an error should not trigger a scroll

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3748]
**Description:**

We should not scroll when the error is expanded

Replay with the [error](https://app.replay.io/recording/dd74c91a-4e82-4b56-ac11-7f175e8dcd79?point=32451855370276779961995920356148098&time=18108&hasFrames=true)
Replay of the [scrolling](https://app.replay.io/recording/fd98ff17-4d65-4b61-99b8-59c34e4876)

**Comment by hbenl** [comment]
I couldn't reproduce this: expanding and collapsing the error in the first recording never scrolled the console for me. And the second recording ([fixed link](https://app.replay.io/recording/fd98ff17-4d65-4b61-99b8-59c34e48761d)) doesn't load.
