### ISSUE TITLE
[UX] Improve LogRocket Telemetry

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3750]
We discussed LogRocket over here: https://github.com/RecordReplay/ops/issues/118

But this is the ticket for the UX side. Here's the discussion in Notion:
https://replayio.notion.site/Logrocket-Opt-in-194d3bb9dd3b4617bef428ce64cad9b6

In Figma, look for the page "Assigned to Dev -> Logrocket Opt-in"
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=1913%3A1

**Comment by jasonLaster** [comment]
Now that we're post-launch we can invest in proper redactions and go with an opt-out approach.

*What would be redacted?*

- Intellectual property: source content, file paths
- Runtime values: console logs, object previews
- Sensitive user data: payment method

*How will we maintain user's trust?*

- Our terms of use and privacy policy explicitly state our stance on privacy.
- We publish our approach to security and privacy on our website.
- Our frontend is available on GitHub for anyone to see which fields are redacted.
- Going forward, users who are concerned will be able to disable LogRocket.
- Going forward, we will fully document our approach to telemetry and the heuristics we use.

Next Steps:
- [ ] Devtools redactions should be more fine-grained
- [ ] Update current redactions
- [ ] Add an opt-out step in the User Setting modal and perhaps somewhere in onboarding
- [ ] Add Telemetry documentation
