### ISSUE TITLE
Resume from a comment immediately pauses

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3752]
https://www.loom.com/share/b6da452d09fc4b1fae23140b092c06fc

tried recording in Replay, but could only repro in chrome

**Comment by hbenl** [comment]
This happened because the comment marker was implemented as a `<button>`, but HTML buttons generate click events when they are focused and certain keys are pressed. So our frontend thought you had clicked on a comment marker immediately after pressing the space bar.
