### ISSUE TITLE
JS Symbols rendered as `undefined`

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3759]
**Description:**

I've noticed that Symbols are not displayed correctly. Notice at the end of this replay that I see `$$typeof: undefined` but in reality, the value of this property is a Symbol which is usually rendered like `Symbol(react.element)`:
https://app.replay.io/recording/419bda49-0bbc-40de-9ce6-bccae98b10d3

Also, notice how I've been searching for `accordion`, I've chosen the first result, setup a breakpoint there, and ended up being "redirected" to another representation of this file that had no breakpoint on it (which is not that big a problem - I would just prefer to select the "correct" file in the first place).

**Steps to Reproduce:**

For instance - inspect any React element and its `$$typeof` property

**Expected Result:**

I should see a resolved/correct representation of a Symbol

**Comment by jasonLaster** [comment]
Thanks. Moved this issue to a discussion since is more of a feature request that we should add to the roadmap. By the way, the benefit of discussions is that it should be easier for community members to follow and particpate in

**Comment by jasonLaster** [comment]
We should use this issue to show a better error message and #3765 to add proper symbol support

**Comment by hbenl** [comment]
There is currently no way for the frontend to distinguish between `undefined` and a Symbol - in both cases we receive the same value from the backend.

**Comment by hbenl** [comment]
> Also, notice how I've been searching for accordion, I've chosen the first result, setup a breakpoint there, and ended up being "redirected" to another representation of this file that had no breakpoint on it (which is not that big a problem - I would just prefer to select the "correct" file in the first place).

I created a separate issue for this (#3788)
