### ISSUE TITLE
[Inspector] Highlighting creates a new root node

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#377]
https://replay.io/view?id=60acf4c7-7517-4380-85ac-64f3163748f7

STR:
1. go to https://replay.io/view?id=e0854458-5bcd-431e-8489-a66e2ad4be48
2. open inspector and expand some nodes
3. use highlighter to inspect a node

**Comment by bhackett1024** [comment]
This is a regression from https://github.com/RecordReplay/devtools/pull/195.  It used to be that when moving to a new place in the recording we would completely destroy the markup pane, and regenerate it at the new point.  We don't destroy the markup anymore, and don't clear it when moving in the recording either, so the old root node was still in place in the inspector.
