### ISSUE TITLE
[Replaying] preactjs.com

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#378]
STR:

1. go to preactjs.com
2. start recording
3. click on getting started
4. save recording

Notice how the replaying stops with updating the header, but doesn't show the getting started page

here's my recording
 https://replay.io/view?id=e0854458-5bcd-431e-8489-a66e2ad4be48

**Comment by jasonLaster** [comment]
I left some comments in the recording. 

Here is what it should look like

![Uploading Screen Shot 2020-08-19 at 9.56.29 AM.png…]()

**Comment by jasonLaster** [comment]
here's the repo 
https://github.com/preactjs/preact-www

**Comment by marvinhagemeister** [comment]
FYI: When clicking any of the documentation links or the ones on the landing page, we do the navigation immediately, although the content is still loading. We currently fetch a markdown file from the server, process that in a worker and only then do we update the content of the page.

The main loading logic is here: https://github.com/preactjs/preact-www/blob/master/src/components/controllers/page/index.js
And the component that delays rendering is here: https://github.com/preactjs/preact-www/blob/master/src/lib/hydrator.js

**Comment by jasonLaster** [comment]
Thanks @marvinhagemeister!

**Comment by bhackett1024** [comment]
Hmm, so I made a new recording of this at [1] and did some investigation.  After clicking on the getting started link there is a call to setContent() in components/controllers/page/index.js which uses the correct content for the getting started page AFAICT.  I'm not sure why it keeps rendering the old page's content, but there aren't any calls to Hydrator.render() after this setContent() call.  I added comments to the recording, but you might need to set app.features.comments = true in the normal browser console to see them (see https://github.com/RecordReplay/devtools/issues/387).

[1] https://replay.io/view?id=eb9db6fe-3ca7-4eca-87ea-1096fbbde83c

**Comment by jasonLaster** [comment]
Just enabled comments :) 

@marvinhagemeister do you think `Hydrator.render()` needs to be called?

**Comment by jasonLaster** [comment]
> It's an usual pattern to delay tearing down old content until the new one is ready, no doubt! In either way it renders correctly in all browsers, so there must be something else going on

~ Marvin

**Comment by bhackett1024** [comment]
This definitely could be a bug in the browser, but it's hard to say without more understanding of how the site works.  I looked some more at the setContent() call commented in the recording, but the source maps seem to be messed up (are they out of date?) --- stepping into setContent goes to code that is out of range of the source file, which makes it hard to understand what is going on.  I see the same source map behavior in Chrome.

**Comment by Garbee** [comment]
I re-ran this test just now. https://replay.io/view?id=2a148b19-1e7b-460a-b6d3-56e79a6ee55f

I got the getting started page.
