### ISSUE TITLE
Align to Zypsy's recommended blue?

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3785]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/9154902/135375848-b0da4e0b-0b26-4d86-91dc-dbb4af700746.png">

Our blue is darker than Zypsy's blue. Here are the steps I see for moving forward.

1. Talk to @jasonLaster and others -- do we like their blue?
2. If so, do a contrast check. I think the blue may be too light for accessibility reasons when you use it as a button with white text. To verify.
3. Then it might be valuable to make the change in two steps rather than all at once. Partially to ease into the contrast issue, and partially because people are less likely to react negatively if it's done in two steps.

Thoughts?

**Comment by jasonLaster** [comment]
@jonbell-lot23 you have my blessing. The zypsy blue grew on me and it is friendlier which is on brand for education and any company that has play in its name :)

**Comment by jonbell-lot23** [comment]
Exciting! Will push forward

**Comment by jonbell-lot23** [comment]
I was excited to go with a bold colour, but here are the results of my accessibility audit:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/9154902/135406994-7053d798-7a75-40ca-af8b-b5ed427928e8.png">

The cowboy in me, and the designer, likes the striking blue they chose. But this colour fails accessibility guidelines, which I'm reluctant to ignore.

We know the white text on Zypsy blue is an accessibility issue, but I'm going to do some exploring to see what we're dealing with in the UI. Obviously 500 small words at low contrast is quite different from 1 large word at low contrast, so I'll see what I can come up with.

**Comment by jonbell-lot23** [comment]
Here's a rough idea -

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/9154902/135410008-26155cf2-3722-4a1e-b57f-1a728b65edca.png">

Icons on the left are doable, perhaps. But the blue text on light gray gives me a headache. The breakpoint area is iffy. And even the timeline is a bit over-bright. So there are ways to pair the bright colour work with a darker blue, perhaps. But I'd recommend against a straight drop-in. The contrast isn't good enough to work as application UI.

**Comment by jasonLaster** [comment]
Thanks @jonbell-lot23 

- It's nice to see the accessibility audit. 
- I love zypsy blue for icons, but yeah the text is a bit much
- I wonder if we should be using the blue text for the editor tab. re console, there's no way around it we do need to something there. Is there an option where we keep zypsy blue and have a variant for text?

Also, please keep exploring, very cool.

**Comment by jaril** [comment]
Looks like this is closed by #3849
