### ISSUE TITLE
"Go to file" should only offer the original version of a file (if available)

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3788]
From #3759:
> Also, notice how I've been searching for accordion, I've chosen the first result, setup a breakpoint there, and ended up being "redirected" to another representation of this file that had no breakpoint on it (which is not that big a problem - I would just prefer to select the "correct" file in the first place).

The reason is that "Go to file" offered both a pretty-printed minified version and the original version of that file and the user chose the pretty-printed one. But the UI favors original versions, so when the user jumped to a breakpoint hit in that file, the editor switched to the original version.

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
