### ISSUE TITLE
Tooltip aspect ratio doesn't match screen recording aspect ratio

### ISSUE THREAD

**Issue by marvinhagemeister** [RecordReplay/devtools#379]
The timeline tooltip uses hardcoded width and height values. Those will only match a small portion of available screens.

https://github.com/RecordReplay/devtools/blob/b5e44e448c7c4ef3338b678f75b6e0358e189399/src/ui/components/Toolbox.css#L85-L86

Here is an example on my ultra wide monitor. Notice the white "bars" of the tooltip background behind the image. It is smaller than the image inside it and the image overflows the container horizontally.

![Screenshot 2020-08-19 at 19 01 58](https://user-images.githubusercontent.com/1062408/90667388-fd1bb780-e24e-11ea-9e9b-123773edc62e.png)

Ideally the tooltip should have the same aspect ratio as the screen recording.

**Comment by jasonLaster** [comment]
Great call! I believe we have that data here (https://github.com/RecordReplay/devtools/blob/master/src/protocol/graphics.js#L234)

**Comment by jasonLaster** [comment]
@hbenl I believe this is fixed. Is that right?

**Comment by hbenl** [comment]
Unfortunately not:
![Screenshot_2020-09-23_18-51-04](https://user-images.githubusercontent.com/16060807/94043616-761daa00-fdcd-11ea-898a-f94e419ed988.png)

**Comment by hbenl** [comment]
Fixed in #726
