### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3796]
While working on #3749 I ran into lots of issues with imports being `undefined` due to circular dependencies: when there is a dependency circle, webpack needs to pick one of the involved modules to be loaded first, before all of its imports were loaded.
Another dependency problem came up when we started splitting our bundle: the frontend often loads a lot of code that it doesn't need for the currently active view, e.g. our main bundle currently contains code from `src/devtools/client/debugger` even though it isn't needed for the login screen or the library.
I keep running into these issues and resolving them takes a lot of time, I want to find a way to deal with them more systematically:
- many issues could be avoided by making our imports more focused, e.g. no more `import { actions } from "ui/actions";`
- AFAIK webpack has a better way to deal with circular dependencies when using ES6 module syntax, i.e. `const { foo } = require("bar");` may fail where `import { foo } from "bar";` works
- AFAIK circular dependencies are a non-issue as long as all involved modules use ES6 module syntax and only contain declarations, but no top-level code that runs on module initialization
- I think webpack is better at tree-shaking when the modules use ES6 syntax, but I'd have to verify that
- I need to develop a better understanding of webpack's module resolution and tree shaking strategies

**Comment by hbenl** [comment]
https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/

**Comment by jasonLaster** [comment]
closing because we should re-evaluate bundles post-next
