### ISSUE TITLE
Browser Errors page is not found

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3813]
Cannot find the browser errors page

<img width="1605" alt="Screen Shot 2021-10-02 at 9 04 32 AM" src="https://user-images.githubusercontent.com/254562/135724156-c6d68080-791a-494f-8eee-0437543c2b0d.png">

**Comment by jonbell-lot23** [comment]
I'm seeing the same thing with any site I try. Here's what happened when I updated:

1. No green badge telling me to upgrade Replay
2. Went to About
3. It checked and saw there was an update
4. That showed me a button that talked about updating, so I clicked it
5. I had to do the whole onboarding again, including 2FA and importing bookmarks from another browser. 6. During that, I had two instances of Replay and two icons in my dock. The original instance had a little message that said "Updating from other instance" or something.
7. Now that it's all done, I'm back to a single Replay install.

**Comment by ryanjduffy** [comment]
The error page needs a gecko fix but curious if we can add a redirect to webflow as well for a more immediate fix. I thought this came up earlier on another path so it might be a solved problem.

cc: @jazzdan

**Comment by jazzdan** [comment]
@ryanjduffy what direct do we want to add? `/browser/error` -> ?

**Comment by ryanjduffy** [comment]
from replay.io to app.replay.io

**Comment by jazzdan** [comment]
![Screen Shot 2021-10-04 at 4 23 22 PM](https://user-images.githubusercontent.com/452453/135919450-5af605df-fcc6-41c5-ac68-54c8f088d985.png)

Like this?

**Comment by jasonLaster** [comment]
@jazzdan that should work. lets talk in discord which is more sync tho
