### ISSUE TITLE
Remove Call Stack "Expand rows"

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3816]
This button comes from the early firefox debugger days and is partially about perf... 

It doesnt justify being there now and would be simpler to just remove
<img width="382" alt="Screen Shot 2021-10-02 at 12 12 36 PM" src="https://user-images.githubusercontent.com/254562/135729180-bec781c4-7598-449b-9560-d81b1c5d83fc.png">
<img width="400" alt="Screen Shot 2021-10-02 at 12 12 33 PM" src="https://user-images.githubusercontent.com/254562/135729186-1d8d3d78-7fe8-4b76-ad06-aa6800cfc50b.png">

**Comment by jonbell-lot23** [comment]
What's the trade-off?
