### ISSUE TITLE
Inconsistent auto-label when adding a breakpoint

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3817]
**Description:**

I've noticed, when just using the Replay and not trying to stress test it 😉 that the auto-label can fallback to the filename. This caught my eye and was surprising - which distracted me from my debugging sessions for a sec.

**Steps to Reproduce:**

Most likely it's about adding a breakpoint quickly - it might lack some required information and fallback to the filename.

**Expected Result:**

Consistent auto-labeling.

**Additional Context:**

Replay: https://app.replay.io/recording/bc8238e0-c017-47ec-9660-aa2af7156f8c

Notice how I add a breakpoint and I get `tsc.js` as my label and then just turn it off and on, on the same line and all and I get `checkObjectLiteral`.

**Comment by jasonLaster** [comment]
left some comments https://app.replay.io/recording/bc8238e0-c017-47ec-9660-aa2af7156f8c?point=43485486213886275195718580402389422&time=18482.85466997185&hasFrames=true

I think it is reasonable to prefer to use the function name and fall back to the filename...
