### ISSUE TITLE
Resuming on a line with replay breakpoint and debugger statement stays on the same line

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#3818]
**Description:**

Resuming on a line with replay breakpoint and debugger statement stays on the same line.

This is a fun problem 😅 I didn't realize at first why I'm staying on the same line and thought that was a bug. Only later I came to the conclusion that this is probably because of the `debugger` statement - but from the UX perspective, this was confusing, even if "technically" correct.

**Steps to Reproduce:**

Add a replay breakpoint on a line with the debugger statement, got to one of its hits, and press Resume.

**Expected Result:**

I should resume to a further point in the recording.

**Additional Context:**

Replay: https://app.replay.io/recording/a3d7e9dc-9832-4484-a826-a83c9351e098

This somewhat goes into our discussion if you should stop on a debugger statement (or other lines when the intention is like step out, go to a next hit etc) at all.

**Comment by jasonLaster** [comment]
left some comments. Funny, i thought we fixed this last october. cc @bhackett1024
