### ISSUE TITLE
Add Team Inboxes

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3827]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=8290%3A54494)

### Discussed in https://github.com/RecordReplay/devtools/discussions/3801

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** May 16, 2021</sup>
**Description:**

One of the top requests we have heard from teams is the ability to receive replays from their users. 

**The UX should be pretty simple:**
1. Laura (user) records a replay and is brought to the upload screen
2. Laura selects "Public Inbox" from the workspace dropdown list.
3. Laura searches for the team she is interested e.g. ReplIt 

One caveat here is that not all workspaces should be public. This means that when users create a workspace, they should be given the option to make it public. Also the name they come up with should be globally unique.

**Benefits**

I think this feature will unlock a lot of new use cases, not just one :) 

* Open source teams can ask that all replays be added to their workspace. This way, even private replays can be available to the maintainer team
* Companies can ask users on twitter to submit a replay to their inbox.
</div>

**Comment by jonbell-lot23** [comment]
I recorded a minute long video to get our gears turning on Team Inboxes:
https://www.loom.com/share/7716d86e8b5147e6af33a78aec086930

**Comment by jasonLaster** [comment]
This looks good to me.

**Comment by jonbell-lot23** [comment]
Well that was easy! Will flesh it out more with edge-cases and stuff.

**Comment by jonbell-lot23** [comment]
**Some thoughts**  
[This simple Figma page](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=8290%3A54494) shows a super simple sketch. And it's fine for a simple use case, but it made me think of some other topics.

**Are we moving or copying?**  
If I record something and send it to the React Replay Inbox, am I *moving* it into that box, or making a copy? If we move it without making a copy, that implies I'd be able to see my upload but no one else's. Is that right?

I'd be ok with this, but it's something to think through.

**Is share the same as upload?**   
So let's say I save something into my library, then go into the share menu. With today's design, I'd see this:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/9154902/140689610-b816aef0-24e9-465e-88b6-6e70fafd6520.png">

If we stuck with the same pattern, we could roughly use the same approach here. The dropdown would have a "move to team" option, which would swap out the text field, have search-while-you-type, and that's how you'd move something.

But this brings up some old issues I was concerned about. I don't have a final answer, but I'm concerned that we're trying to be too clever here. I think my design where there are two super clear dropdowns is more clear than trying to tuck things away like this. To discuss.

**Comment by jaril** [comment]
@jasonLaster I think you mentioned some external discussion from last week that was related to team inboxes. If you have notes mind throwing them in here?

**Comment by jasonLaster** [comment]
@jaril here's a quick loom on what I'm thinking about.

https://www.loom.com/share/d9e862210c2f4cb5ba970e69eef42990

Please ignore all the bad design details :P
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=10540%3A99476

**Comment by jaril** [comment]
Closed in favor of #3827.

**Comment by jonbell-lot23** [comment]
> Closed in favor of #3827.

@jaril this link goes to itself.
