### ISSUE TITLE
Allow editing the condition for a breakpoint if it exceeds 200 hits

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3829]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3273

<div type='discussions-op-text'>

<sup>Originally posted by **jaril** July 20, 2021</sup>
Right now, if a breakpoint has over 200 hits, we restrict editing the breakpoint. This includes the log message and the condition.

There are cases where the user bumps into our 200 hit limitation, and knows how to be more specific about which hits they're interested in. When that happens, they're stuck. They can't edit the condition.

[This Replay](https://app.replay.io/?id=c859afd3-1040-4fdb-a9b2-a04bdc76c21c) has some good lines on script.js to add a breakpoint on to test this. 

## Examples

**A1: Hovering on a line with <200 hits (the button is clickable)**
![image](https://user-images.githubusercontent.com/15959269/126408060-87e57d53-4026-4412-9376-e426c674d145.png)

**A2: After clicking the button on a line with <200 hits**
![image](https://user-images.githubusercontent.com/15959269/126408154-f6e45169-6320-40da-92e1-2b18813ab038.png)

**B1: Hovering on a line with >200 hits (the button is disabled)**
![image](https://user-images.githubusercontent.com/15959269/126408089-62bb26a5-bcb0-4c61-8285-8f5bfe186a93.png)
</div>

**Comment by bhackett1024** [comment]
Unfortunately the breakpoint condition can't really be used right now to make things more efficient in the backend --- a conditional breakpoint still needs to be evaluated at every point where the breakpoint is hit.  There is work we can do to make conditional breakpoints super efficient, but it's not on the roadmap currently.  As an alternative, it might be nice to give users a way to select a range of hits they want to show the message for.

**Comment by jasonLaster** [comment]
Agreed. I think we'll get the benefits by doing #3396
