### ISSUE TITLE
Console search (cmd+f)

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3834]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3803

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** October  1, 2021</sup>
The console should have a simple cmd+f search ui</div>

**Comment by jaril** [comment]
Cmd+F does work in the console.

Uploading Screen Recording 2021-12-14 at 2.16.37 PM.mov…

**Comment by jasonLaster** [comment]
This is filter, not find

**Comment by jasonLaster** [comment]
Yep - both chrome and firefox have console search and filter. Put simply filter will reduce the list of messages where search will jump to the next prev match.

**Comment by abstractalgo** [comment]
Heavily deprioritized compared to other work.

**Comment by markerikson** [comment]
In general, the console messages logic (including filtering) exists in [`devtools/client/webconsole/reducers/messages.ts`](https://github.com/RecordReplay/devtools/blob/master/src/devtools/client/webconsole/reducers/messages.ts), which I recently refactored to TS+RTK.  There's also a related pair of `actions/messages` and `selectors/messages` files as well.

I wrote some notes about the messages reducer logic _before_ I refactored it, as well as the overall component structure of the "web console" panel (the whole lower-right corner of the UI). Most of this information should still be valid:

- https://github.com/RecordReplay/devtools/blob/master/docs/codebase-notes/messages-reducer.md
- https://github.com/RecordReplay/devtools/blob/master/docs/codebase-notes/webconsole-ui.md
