### ISSUE TITLE
Console formatting

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3837]
### Discussed in https://github.com/RecordReplay/devtools/discussions/2371

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** April 16, 2021</sup>
https://levelup.gitconnected.com/add-styles-and-formatting-to-your-console-log-messages-in-javascript-5f14819b1c5d</div>

**Comment by jasonLaster** [comment]
Moving to december so we can focus on Net Monitor

**Comment by jaril** [comment]
Replay for testing a styled console log:
https://app.replay.io/recording/styled-console-log--fd300336-27bd-4475-9581-e61b6abf4343

**Comment by jaril** [comment]
This feels cosmetic and not high priority. Any push back if I were to just close it? @jcmorrow @jasonLaster
