### ISSUE TITLE
Add SourceMap Visualizer

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3839]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3769

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** September 18, 2021</sup>
**Description:**

At the moment, it is impossible for users to visualize  their source map's mappings. This is important because without being able to see what the mappings are it is impossible to be able to see why some positions are breakable and others are not.

I think this should be a relatively quick win. When users right click on an original or generated file (with a source map) we should given them the option to visualize the mappings. When they select it we should navigate to `/recordings/<>/source-map-visualization/<sourceId>` and show the source map visualization.

https://github.com/evanw/source-map-visualization
https://evanw.github.io/source-map-visualization/</div>

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38

**Comment by jcmorrow** [comment]
Nvm, we're doing this!

**Comment by jaril** [comment]
@hbenl I think this is ready to be closed. Feel free to reopen if I'm wrong!
