### ISSUE TITLE
[Replay] the initial browser download stale

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#384]
I *think* the way things work is the initial download is a bit out of date, and that gets fixed in the next download... The issue is that when users get setup they get a slightly older / more broken version

The biggest issue i see people run into is the `devtools.recordreplay.uploadSourceMaps` is false and that is super confusing. There are other subtle things like the logo being old, that are just unfortunate. It would be nice if we could bump the DMG as part of our deploy process.

<img width="1552" alt="Screen Shot 2020-08-19 at 11 14 09 AM" src="https://user-images.githubusercontent.com/254562/90682433-c9726a80-e219-11ea-914e-49e0ce4ac385.png">

<img width="786" alt="Screen Shot 2020-08-19 at 11 14 52 AM" src="https://user-images.githubusercontent.com/254562/90682424-c5dee380-e219-11ea-93dd-11ead2a226ee.png">

**Comment by bhackett1024** [comment]
We update the download DMG every time we release a new browser.  I'm trying to reproduce this but I can't even install the downloaded DMG as Apple says it is damaged, even though it is identical to a DMG which Apple notarized for us.

**Comment by jasonLaster** [comment]
@bhackett1024 is this fixed now?

**Comment by bhackett1024** [comment]
Yes, the replay.dmg link will be the latest one.
