### ISSUE TITLE
Support Expression history with up/down arrows

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#3842]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3767

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** September 21, 2021</sup>
**Description:**

Users should be able to see previous console terminal expressions by pressing the up arrow when focused in the terminal.</div>

**Comment by jasonLaster** [comment]
@jcmorrow here's a gist with some notes on where you can get started
https://gist.github.com/e97ebda33500e47f2de1aec6efeb8c0c

happy to discuss tomorrow. Also saw a ton of code you can delete too
