### ISSUE TITLE
Hard to add comment after stepping

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3869]
When I've stepped through a frame to a place where I want to add a comment, there isn't any easy/obvious way to do so.  I tried going to the comments screen, but while it shows the existing comments there isn't a way to add a new one.  Clicking on the video seems to be the only way to add a comment, with the somewhat strange tooltip "Add comment to this line of code".

**Comment by jonbell-lot23** [comment]
#3644 has gone live, so now it's possible to do this:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/9154902/139599460-f4c6e350-a7b5-4652-8ae5-2c53e29848a4.png">

I believe we've also done away with the "add comment to line of code" tooltip as well, so I think we can close out this item.
