### ISSUE TITLE
In progress comment disappears when clicking on a different comment

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3872]
If I start writing a comment and then click on another comment, the comment I was working on disappears entirely, along with its content.

**Comment by jaril** [comment]
Laying out the cases here so we can figure out how to handle this:

Case | While editing | After clicking away (current) | After clicking away (proposed)
--- | --- | --- | ---
New comment | ![image](https://user-images.githubusercontent.com/15959269/136847499-3334b6ef-292b-462a-81cd-99fc40eee5af.png) | N/A | TBD
New reply | ![image](https://user-images.githubusercontent.com/15959269/136847408-2916cf43-a797-45a3-bfbf-0cb891e59a32.png) | N/A | TBD
Editing a comment | ![image](https://user-images.githubusercontent.com/15959269/136847536-238f0504-fe6e-42f5-b539-a186897268d9.png) | N/A | TBD
Editing a reply | ![image](https://user-images.githubusercontent.com/15959269/136847580-0bd9c177-8d06-48d7-b328-5733ae778e08.png) | N/A | TBD

**Comment by jonbell-lot23** [comment]
I do think a one-time alert (as mentioned in the previous comment) with personality could go a long way here. I'm going to close this for now, but will dust off later as part of polish work.
