### ISSUE TITLE
Code Editor not visible when Comments or Events selected

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#3876]
**Description:**

<img width="1749" alt="Screen Shot 2021-10-05 at 10 16 50 AM" src="https://user-images.githubusercontent.com/132260/136071463-0cbaed66-1a40-461f-9971-b3b533fb9994.png">

As you can see, I've got comments selected here, and the code editor isn't visible for some reason. If I select Sources or Breakpoints, it will appear no problem, but it vanishes for Comments or Events.

**Additional Context:**

* Screenshots:

* Video (Loom):
* Replay: https://app.replay.io/recording/28461236-4a1b-46d3-af85-e327ab4d3135

**Comment by jasonLaster** [comment]
Oh, i wonder if i broke this with the redactions PR...
