### ISSUE TITLE
Screenshot is cached between recordings

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#3879]
i think we have some module-scoped data in graphics.ts that needs to be cleaned up
likely an artifact of switching to routing since we no longer do a full refresh for each recording

https://app.replay.io/recording/e3c5d297-fc38-4410-9c19-b0ab986cad2b

**Comment by jasonLaster** [comment]
Seeing this come up post next.js

**Comment by hbenl** [comment]
Fixed by #4393. We're now back to always reloading the app when switching between library and recording, but that can be fixed in a follow-up.
