### ISSUE TITLE
Clicking on timeline does not update video until Play is pressed

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#3900]
**Steps to Reproduce:**

1. Open a recording
2. Press play to the point where you can see an image
3. Click on the timeline somewhere later in the recording

**Expected Result:**

Image should update to reflect the state at the point in time you clicked. It appears to continue to display whatever image was there before until you press Play again.

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:

**Comment by jasonLaster** [comment]
Thanks. Left some comments.
