### ISSUE TITLE
[Timeline] tooltip has wrong initial position

### ISSUE THREAD

**Issue by marvinhagemeister** [RecordReplay/devtools#391]
When the timeline tooltip is initially set to the wrong position before being moved to the cursor. See the following gif:

![Kapture 2020-08-20 at 9 37 31](https://user-images.githubusercontent.com/1062408/90730888-2d07a100-e2c9-11ea-97ce-b3d7b35f3dba.gif)

**Comment by jasonLaster** [comment]
Thanks for filing @marvinhagemeister 

Let's try and get a recording for this bug. I'm happy to try and repro as well
