### ISSUE TITLE
DevTools should prompt users to setup sourcemaps

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3916]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=8783%3A71242)

This replay would be 10x better if the user published sourcemaps with Next.js. We should have a nag that points them in the right direction.

https://app.replay.io/recording/7d36814c-62eb-40a9-a791-f052d7f87879

**Comment by jasonLaster** [comment]
Here's a nice first pass. The second thing will add this ([figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8879%3A75681)).

<img width="985" alt="Frame 308" src="https://user-images.githubusercontent.com/254562/142062711-87b6a80d-9f9b-467a-ac80-42b28bb9e82b.png">

**Comment by jonbell-lot23** [comment]
Dig it.

Are we going to do the "we see a source but we can't access it" louder notification as part of this ticket?

**Comment by jasonLaster** [comment]
Probably, just wanted to spin this out because this is settled

**Comment by jonbell-lot23** [comment]
Hello! Here's the design POV:

![image](https://user-images.githubusercontent.com/9154902/142551203-11d0dba9-0723-4159-b10c-334e7493ac86.png)

* For this release, I'm fine keeping the yellow bar on the bottom when sourcemaps aren't found. We can always add the complexity of the checkbox later, but I don't think it's needed now. Concerned it'll just add extra clutter that we don't need for an MVP.

* I also removed the copy that talks about how it's tied to teams. That can be in the documentation link. I think it's good to keep this team light.

* I'm totally fine if y'all change this copy. I like this copy but will defer to the team if there are better ideas.

**Comment by jasonLaster** [comment]
Lets show a warning for files like this
https://app.replay.io/recording/7d36814c-62eb-40a9-a791-f052d7f87879?point=2920666983146968579788167882735683&time=1771.0895515509058&hasFrames=true
