### ISSUE TITLE
[Timeline] tooltip flickers when moving mouse cursor

### ISSUE THREAD

**Issue by marvinhagemeister** [RecordReplay/devtools#392]
When moving the cursor around on the timeline bar, the tooltip flickers. This presumable happens when the new image is displayed. Best illustrated with a gif:

![Kapture 2020-08-20 at 9 43 29](https://user-images.githubusercontent.com/1062408/90731241-bcad4f80-e2c9-11ea-8ba4-56f304f3dad3.gif)

**Comment by jasonLaster** [comment]
Yes! This is a great bug because it is probably also adding a lot of performance overhead as well.

Lets try to get a recording of this as well and see if we can be smarter about caching

**Comment by jasonLaster** [comment]
@jaril this might be a good one to prioritize

**Comment by jasonLaster** [comment]
@bhackett1024 this might be a good bug to think through a holistic server/client story around 

* tooltip filesize
* caching in the protocol
* loading performance 
etc

**Comment by jasonLaster** [comment]
Closing as it feels much more stable after a couple of timeline patches have now landed.
