### ISSUE TITLE
Elements Node Picker states

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3925]
**Description:**

The Node picker should have an active and loading state

**Comment by jonbell-lot23** [comment]
Apologies Jason, I missed your reply. I just put this video together:
https://www.loom.com/share/e9526be5193f41b7aa8c08223b179249

We definitely want to find a balance between feeling sluggish (a reaction that kicks in after .1 seconds) and feeling super heavy and flickery if most requests succeed after .11 seconds. I suspect that making a very light mask will help, and we can fiddle with the timing.

**Comment by abstractalgo** [comment]
Fyi, active state for Node picker was addressed in https://github.com/RecordReplay/devtools/pull/4881.
