### ISSUE TITLE
Replace ReactDOM.render with createRoot

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3959]
ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by jasonLaster** [comment]
Pretty sure @jcmorrow either knocked this out or we got it for free with Nex.tjs

**Comment by jcmorrow** [comment]
I certainly didn't do this, but it does seem to be gone. We still have `Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.` in quite a few places as well as many other warnings to clean up though!
