### ISSUE TITLE
Standardise our contextual menus

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4007]
Thanks to [this ticket](https://github.com/RecordReplay/devtools/issues/3933#event-5458614056) we have some more standardisation in our UI:
![image](https://user-images.githubusercontent.com/9154902/137214064-6f1f104e-c0f4-4aa8-b747-1ef74dcbdcff.png)
![image](https://user-images.githubusercontent.com/9154902/137214071-72cb3921-9409-4cba-bab8-bb41fcba2bb7.png)

But I just noticed this ugly context menu, which should also align. (Smaller font sizes are ok, but as much as possible they should feel the same)

![image](https://user-images.githubusercontent.com/9154902/137214047-2668f4ee-2c70-4c17-a8aa-decba9af5403.png)

We shouldn't just update this menu, we should make sure to componentize these so any new menus we make will inherit the right visual properties.

**Comment by jcmorrow** [comment]
I'll probably end up picking this up, but just in case someone else does, https://github.com/RecordReplay/devtools/pull/4204 starts us down a road of centralizing context menus and adds a `ContextMenu` component which can handle the positioning and styling. I'm not 100% sold on the "centralized in global state approach", but the styles/component should be useful!

**Comment by jasonLaster** [comment]
We are using a component for new tooltips and when we work on a tooltip it is easy to convert it over. In the interim, it is probably fine to either

1. close this general ticket since it is not actionable
2. make it more specific to this context menu

**Comment by jonbell-lot23** [comment]
Happy to close for now, will keep an eye out
