### ISSUE TITLE
[Inspector] add missing images 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#401]
I think we could add these to `images/image.js` and it will probably fix them. if not we need to use searchfox.org to find the svgs and add them as well

<img width="925" alt="Screen Shot 2020-08-20 at 8 28 04 AM" src="https://user-images.githubusercontent.com/254562/90793379-85867080-e2c0-11ea-94b2-30076e4c7449.png">

**Comment by hbenl** [comment]
This has already been fixed.
