### ISSUE TITLE
Console should short-circuit evaluation when possible

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#4023]
I'm not sure how often users will have this experience, but when I've played with the console to try something *very* basic like typing the literal `1` into the console and hitting `Enter` I get the following experience:

https://user-images.githubusercontent.com/5903784/137428860-5f8a28d4-24e3-4183-bb3a-b64b825ca4c6.mp4

I realize that with most expressions there is a minimum processing time that is going to be present and hard to speed up, but it would be great if we could not be sluggish whenever possible. From talking to @jasonLaster it sounded like maybe there was an opportunity to short-circuit somewhere based on an expression being only a combination of literals that don't need to be evaluated, so maybe that's one good place to make the console feel more like, well, a console.

**Comment by jasonLaster** [comment]
Just checked and this might only work for logpoints where we know that it's an expression and not a statement. 

https://github.com/RecordReplay/devtools/blob/master/src/protocol/logpoint.ts#L300-L323

This approach is not using Babel and we'd have to switch to babel to do this in the more general case

**Comment by jasonLaster** [comment]
closing since this requires babel and will be a bit out of scope

**Comment by bhackett1024** [comment]
(Eager evaluation is also a nice feature because it could be used to implement conditional breakpoints and logpoints with a bunch of hits much more efficiently.)
