### ISSUE TITLE
Add "your comment is going to be clobbered" nag (to be shown once)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4042]
We decided to allow new comments to destroy half-written comments. Explanation here:
https://www.notion.so/replayio/When-to-delete-user-input-8bea4556c48743b985f55c8c129f2897

But the transition can still be better. We should have a single nag that explains this behaviour so it feels less broken when it does happen to someone for the first time.

![image](https://user-images.githubusercontent.com/9154902/137814801-efcef7e1-bc60-4ff1-a1c0-6800dc20db31.png)

This is very heavy, and only happens once. This lets us check the box of "we shouldn't delete user input" but then we don't need to do it after the first time it loads.

One nuance: if a person says "don't delete," the nag should appear the next time they hit this scenario. If the person says "Yes, delete" we're going to take that as a "Never ask me again" confirmation.

**Comment by colbyr** [comment]
Closing this in light of broader design decisions today!
https://discord.com/channels/779097926135054346/904840751127601265/904840753505771571
