### ISSUE TITLE
Clean up our reducers

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4047]
So far we've been throwing nearly all UI-related redux state in `/app.ts`. We're long overdue for a bit of a cleanup.

For this week's garden trimming we should at the very least extract the layout-related items from there. While we're at it, we should add other layout things to the replay-specific layout items that we persist (e.g. `sidePanelSize`).

From a discussion in https://github.com/RecordReplay/devtools/pull/4027.

**Comment by jasonLaster** [comment]
https://redux-toolkit.js.org/

**Comment by jasonLaster** [comment]
All for this cleanup, but two things:

1. a more specific title like split up app reducer is more actionable
2. not sure if we want to be tracking small cleanups. part of gardening in general is just doing small things that are on your mind...
