### ISSUE TITLE
Handle different loading states in the video

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4108]
This is to continue the discussion from #4093, #4096, #4513

We have a few outstanding loading handling items:

- Initial screenshot: When you open up a replay and you're met with a blank screen on the video.
- Video loading: When the video is loading slower than it's playing, and it stutters or doesn't play at all.
- Screenshot repainting: When after navigating, the takes a while to update.

The first one was fixed by #4096. However, we still have the rest. Talked with Jason about this and our conclusions were:
- Video loading: Stuttering is not ideal. We should add some buffering logic that lets the Video indicate that it's buffering, get n (5?) seconds worth of loaded playback, then resume playing until it hits an unloaded screenshot. In which case, it just buffers again.
- Screenshot repainting: We should find a way to be really fast at this so we never have to deal with the 1-2s screenshot update delay between navigations.

**Comment by jasonLaster** [comment]
A third one is waiting for the node picker rectangles. 

All of them could be handled by a spinner in the bottom right of the video
