### ISSUE TITLE
Trimming UI polish

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4128]
https://www.loom.com/share/3022c650f1784ef2972e65cbf78755aa

- [ ] mouse up is lost when not in the footer
- [ ] Update toggle button states
- [ ] dragging past the timeline should not affect the width
- [ ] should not feel sluggish
- [ ] initial size should be the current trim
- [ ] clicking the mask should cancel with a prompt
- [ ] scrolling up down should zoom in and out
- [ ] scrolling left/right or with shift should pan left and right
- [ ] escape should cancel

**Comment by jasonLaster** [comment]
Taking this out of the sprint because we can revisit once onboarding/engagement is in a better spot.

**Comment by jaril** [comment]
Lumped together with #3396.
