### ISSUE TITLE
Include security + privacy messages

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4139]
**Description:**

We do a great job of including our approach to security and privacy on replay.io and replay.io/security-privacy. We should bring this into the product in a couple of places to help build trust with our users.

I think it can go in a couple of places, but three places where it would feel natural to me would be:

1. https://app.replay.io/browser/new-tab
2. upload screen
3. loading ui 

[figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=7760%3A48981)

### Here are some examples messages
![Frame 952 (1)](https://user-images.githubusercontent.com/254562/138573506-f0793c8b-27f7-42f0-a4d5-64cd27b94705.png)

### Here's an example of what it could look like in the loading ui. 

I imagine that the cards could be clickable and link to the relevant section of our /security-privacy page.

![Uploading Flow (1)](https://user-images.githubusercontent.com/254562/138573505-1f6ae2f3-6df8-4ffd-8e26-f583213f2677.png)

**Comment by jaril** [comment]
Definitely with the progress bar, but try to push it earlier on as well.
