### ISSUE TITLE
Comment polish

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4146]
**Description:**

- [x] #4257
- [x] #4256
- [x] #4258
- [x] #4259
- [x] https://github.com/RecordReplay/devtools/issues/4133
- [x] https://github.com/RecordReplay/devtools/issues/4120

**Comment by colbyr** [comment]
I added https://github.com/RecordReplay/devtools/issues/4259 which is the change I had to revert late last week.

**Comment by jcmorrow** [comment]
https://github.com/RecordReplay/devtools/pull/4267 Is the last piece of this! Closed!
