### ISSUE TITLE
Use "priority" and "name" fields when initializing analyses

### ISSUE THREAD

**Issue by kannanvijayan** [RecordReplay/devtools#4147]
Context:
https://github.com/RecordReplay/backend/pull/3313

In a recent metrics discussion regarding a slow controller we ran into the issue that every new devtools sessions sends off a LOT of automatic findAnalysisPoints to get event counts for each individual event type to show passively in the UI.  We wanted to distinguish these requests from "interactive" requests sent on behalf of the user.

The conclusion of that discussion was to decide to at least expose to the backend information on who created the analysis: the application, or the user by performing an action.

The linked backend PR just landed, and exposes an optional "name" and "priority" field that can be initialized on analyses when they are created.  Priority can be one of `app` or `user` at this time.

Frontend should be updated to set these optional fields when creating automatic analysis, and also to explicitly mark user-driven analysis as well.  For now, leaving the priority field unfilled will be treated as a default `user` priority.

Where possible, also modify uses of `findAnalysisPoint` to have a name that is descriptive of the origin of the request.

**Comment by jasonLaster** [comment]
Closing as we can now use `name` and `priority` field when we want to measure the performance of individual or slow analysis.

**Comment by kannanvijayan** [comment]
> Closing as we can now use `name` and `priority` field when we want to measure the performance of individual or slow analysis.

Is there a frontend patch that landed for this?  Could you link the PR?
