### ISSUE TITLE
"Loading events" screen looks awkward/broken

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4209]
Here's how it currently looks:
![image](https://user-images.githubusercontent.com/9154902/139221375-4fd22c8f-07c7-441b-b917-70867280dbb0.png)

Here's how it should look:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/9154902/139613466-5342bbe3-368f-4207-9e2d-18651289f666.png">

* Notice the three event lines have been converted into one.
* We should show this line when things are still loading.
* When the page is done loading, the line should disappear, meaning the pane will get slightly shorter.

**Comment by jonbell-lot23** [comment]
Assigning to Jaril and marking as design-complete.

**Comment by jasonLaster** [comment]
@jonbell-lot23 this feels inconsistent with other loading states where the loading indicator is in the same context. How did you come up with this decision? Also, did you consider a simple pogressbar similar to what we do in the elements panel and other places?

**Comment by jonbell-lot23** [comment]
1. Loaders communicate their scope. Stretching across the entire interface means "global." Stretching across a small pane implies "waiting on this one part of the UI to load." But that's not what's happening here. We're putting a global loader in a small pane, which communicates clumsily.
2. So we use text to explain what's going on. We originally wanted this feature to have lots of detail, so in this revision I'm cutting three lines down to one. But zero is too far, especially considering item 1 above. It would express "we are waiting for this pane to load" but then the pane would load and nothing would change, which is awkward.
3. The original version of this feature was a radial loader, the slightly revised version was a radial loader, and keeping that consistent is a nice bit of continuity as we chase items out of the chrome and into panes.
4. The layout in this entire pane has a series of (mostly) rounded icons next to descriptive text. That's another nice bit of continuity and consistency. It makes a visual cadence as your eye scrolls down the list.

**Comment by jaril** [comment]
Closed by #4249.
