### ISSUE TITLE
Blank "error" message when you don't have permission to view a replay

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#4221]
![CleanShot 2021-10-28 at 17 19 23](https://user-images.githubusercontent.com/5903784/139353274-1543f46d-c7a3-4ba4-8707-8fb387775b5e.png)

This screen is very beautiful and also not very helpful 😄 

**Steps to Reproduce:**
- Sign out of Replay
- Try to visit a Replay

**Expected Result:**
- Maybe show a message that indicates that you need to sign in or sign up, along with a link to do so?

**Comment by jasonLaster** [comment]
Description:

Make a new recording and hit Stop
Redirected to Upload screen for title editing and stuff
Copy the URL and open it somewhere that you're NOT logged in, like private browsing window
Page does not render and offers no feedback instructing the user to log in
Additional Context:

Replay: https://app.replay.io/recording/24806b77-845c-44e0-b573-b29d02a84d67

**Comment by jaril** [comment]
This appears to be happening when you open a replay while not logged in AND you're in dev. If you're in prod, the sign in button shows up properly.

What's happening is instead of displaying the regular error as we do in prod, we print out the errors in the same component in dev.

**Comment by jcmorrow** [comment]
Yep, you're right, this does include a more helpful call to action when not in dev!
