### ISSUE TITLE
Console + editor onboarding flow

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4223]
Step two of [Project Mad Hatter](#4214)

Resources:
[Discord channel](https://discord.com/channels/779097926135054346/903353850566672465/903353852814839849) 
[Jason's first Loom](https://www.loom.com/share/ea7bf4e14fc845f2bb2998bd5b1c3b08) 
[Figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=7995%3A50177) 

**Console**
The key with this visual is that it's using the exact same spacing as is seen in #4222. This screenshot is in Figma, not taking a screenshot of the actual UI, so things won't line up exactly right. But the idea is that #4222 and #4223 should match. (Copy may change but of course that's easy)

<img width="754" alt="image" src="https://user-images.githubusercontent.com/9154902/139395829-041f3960-fd5b-4cef-b7e5-2e43f053959c.png">

**Editor**
Guess what?! SAME DESIGN, BY DESIGN.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/9154902/139399198-40eeca18-2ffb-42ae-b667-546fe9e0b054.png">

Everything should be identical because we're using a single hat component.

**Who should see this?**
More long term, we're going to make these nags dynamic. For example, if it's your own Replay, we might use this copy. But if it's a publicly shared Replay, we might consider hats with different copy. But that will come later.

**For now, we'll show nags to:**
* The author of the Replay
* If they've never seen the nags before

**FAQ:**
Q: Is it possible for someone to see the console nag at the same time as the editor nag? For example if the editor window has been opened?
A: My proposal is that we don't allow that. Only show the editor nag once the console nag has been dismissed because someone has clicked in the console.

**Comment by bhackett1024** [comment]
I reverted #4285 because it broke all of our tests, see https://github.com/RecordReplay/devtools/issues/4296

**Comment by jaril** [comment]
Closed by #4341, and checked with tests locally to make sure it's not throwing.
