### ISSUE TITLE
Pane defaults (for example, Replay Info when there are no comments)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4249]
**Description**
Today we open to the most recent pane you were looking at, and if you've never looked at a Replay, we default to the Comments pane. We're going to add some conditional logic in a few different places.

**Default to Replay Info (aka Events) unless there are comments**
Obviously we should show comments if there are comments. But otherwise, we should default to Replay Info.

**Default to Pause Info when setting a breakpoint**
This seems like a reasonable default since it's directly related to breakpoints.

**Comment by jonbell-lot23** [comment]
Assigning to Jaril and marking as design-complete.

**Comment by jaril** [comment]
> **Default to Replay Info (aka Events) unless there are comments** Obviously we should show comments if there are comments. But otherwise, we should default to Replay Info.

This one's trickier in practice. We have to load comments, and that takes a second. That means we have no idea of knowing whether we should open to the replay info pane immediately. So either we 1) open up to comments, then yank them to replay info once we know that there's nothing to see in comments, or 2) we put the entire sidebar into a loading state until we get comments data back and we know which to display. Both are non-starters IMO — it's possible there's something I'm missing so I'll let it marinate til we chat later!

**Comment by jonbell-lot23** [comment]
Can we store a little bit of data called hasComments?

It'd be set to true or false, which we can load super quickly.

**Comment by jasonLaster** [comment]
@jonbell-lot23 good idea. maybe we need to call out `first-comment`
