### ISSUE TITLE
Implement Net Monitor Table

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4251]
**Description:**

We should be able to get up and running with [React Table](https://react-table.tanstack.com/docs/overview
) and [React Window](https://github.com/bvaughn/react-window) out of the box.

A couple of open questions/comments:
1. Do we want to use flexbox or a table HTML? 
2. Do we want to use [Tailwind UI](https://tailwindui.com/components/application-ui/lists/tables) out of the box?

Columns:
* Status
* Method
* Domain
* File
* Initiator
* Type 
* Transferred
* Size

Features
* Ability to resize columns
* Ability to filter by url
* Ability to filter by type
* Ability to sort by column
* Ability to hide/show columns with a context menu

Gecko Dev
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-list/RequestListItem.js
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-list/RequestListColumnStatus.js
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-list/RequestListColumnFile.js
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-list/RequestListColumnMethod.js

<img width="462" alt="Network Monitor" src="https://user-images.githubusercontent.com/254562/139618358-db762141-8c85-4f5c-87ed-05aee92ccc08.png">

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8062%3A51000

**Comment by jcmorrow** [comment]
I'm gonna close this for now, I think the main outstanding point is adding request/response body, but that should probably be its own ticket.
