### ISSUE TITLE
Implement Net Monitor Resource

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4252]
**Description:**

We should be able to add a SplitBox that is either horizontal or vertical. Likely stacked vertically that shows resource level data such as Headers, Request, Response, ...

For Headers:
* GET request which expands to show query params
* Summary level information (status, version, transferred referrer policy)
* Response Headers (Raw/summarized)
* ...

* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-details/HeadersPanel.js
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-details/RequestPanel.js
* https://github.com/mozilla/gecko-dev/blob/master/devtools/client/netmonitor/src/components/request-details/ResponsePanel.js

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=7368%3A30014

<img width="628" alt="image 3" src="https://user-images.githubusercontent.com/254562/139618749-bbd730f8-8d9a-4025-b478-720974f1311e.png">

**Comment by jcmorrow** [comment]
I'm gonna close this for now, I think the main outstanding point is adding request/response body, but that should probably be its own ticket.
