### ISSUE TITLE
Our sign in screen lost its text

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4283]
Looks like this now:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9154902/140017011-8bf10e9c-9f7a-4391-b498-c22536e914cc.png">

We used to have more text explaining Replay.

**Repro**
Go here while logged out: https://app.replay.io/recording/17c86e5e-9da2-4adc-ae58-78b34f5bfce9?point=6490371073168747826141472678215754&time=5898&hasFrames=false#

**Comment by jasonLaster** [comment]
I believe this was fixed in another issue/pr
