### ISSUE TITLE
Timeline inconsistency

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#4289]
https://app.replay.io/recording/ea5b079c-9ca8-4ff8-9087-a22a2302d15c

In this recording, seeking from the first to the second comment moves the pause marker in the console to an _earlier_ message. The second comment has a time that is larger than the first comment's time (that's why it's shown _after_ the first comment), but its executionPoint is smaller than the first comment's (that's why the pause marker moves to an _earlier_ message).

**Comment by hbenl** [comment]
Whilte #4291 was technically correct, it makes Replay look broken: in many recordings there's a big gap between the first two paints and clicking in the timeline in this gap always jumps to the beginning of the recording.
We need a way to get an execution point for a given time (or very close to that time) without relying on paints and mouse events only.

**Comment by hbenl** [comment]
See also #4350

**Comment by jasonLaster** [comment]
re-upping Holger's point

> We need a way to get an execution point for a given time (or very close to that time) without relying on paints and mouse events only.

**Comment by jaril** [comment]
@bvaughn With the new timeline, mind checking if this still applies??

**Comment by bvaughn** [comment]
Don't think my timeline work would have impacted this?

**Comment by jasonLaster** [comment]
Yep - this is different

@hbenl added this to the next sprint. Feel free to punt, but feels like an important "broken glass" issue that we should fix on the backend.

**Comment by jcmorrow** [comment]
>  We need a way to get an execution point for a given time (or very close to that time) without relying on paints and mouse events only.

💯 

This would be useful in general as well, not just for this problem.

**Comment by gideonred** [comment]
This might be fixed in https://github.com/RecordReplay/backend/pull/5565.

**Comment by jcmorrow** [comment]
@hbenl I've put my face on this because it is closely tied to #6820, I hope that's ok!
