### ISSUE TITLE
Multiline print statements in the breakpoint panel

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4302]
I got this from copy pasting multiline expressions. We could either do proper multiline support and expand the height of the panel or replace new lines with spaces...

I think we should expand the height which is tricky with CSS, but correct for semantics

<img width="509" alt="Screen Shot 2021-11-03 at 11 56 20 AM" src="https://user-images.githubusercontent.com/254562/140391715-9bc044c3-adba-47ff-9f5e-7136bfe8f70a.png">

**Comment by jaril** [comment]
Kinda related to #5242.

**Comment by jasonLaster** [comment]
Yep
