### ISSUE TITLE
Fix CommentLine error

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#433]
The error below can cause symbols to fail to load for a script, which can break automated tests.  For now I'm going to disable the symbol checks in our tests so they continue to pass.

Action setSymbols had an exception: Error: "Property comments[0] of File expected node to be of a type ["Comment"] but instead got "CommentLine""

https://replay.io/view?id=33c724f4-ee3b-4132-9b01-29e361ccd379

**Comment by bhackett1024** [comment]
This is still happening.  Here is a fresh recording with a comment.

https://replay.io/view?id=272486a3-3f86-4306-93ea-95806085eea6

**Comment by jaril** [comment]
Looks like this might be this known babel issue: https://github.com/facebook/jest/issues/10208

@bhackett1024 Do you have STRs for the error?

**Comment by jasonLaster** [comment]
Seeing this come from sentry: (https://sentry.io/organizations/replay/issues/1884503955/?project=5399075)

```
./src/devtools/client/debugger/src/workers/parser/index.js in findOutOfScopeLocations at line 14:17
./src/devtools/client/debugger/src/actions/ast/setInScopeLines.js in getInScopeLines at line 29:30
./src/devtools/client/debugger/src/actions/ast/setInScopeLines.js in action at line 57:25
```

**Comment by jasonLaster** [comment]
STR:

1.  go to https://replay.io/view?id=230b80c5-bdc8-44c6-8715-aa5ff71855d4
2. select animate.html in the source tree

**Comment by jasonLaster** [comment]
Still seeing this issue

https://sentry.io/organizations/replay/issues/1900283668/?project=5399075&query=is%3Aunresolved

**Comment by jasonLaster** [comment]
seeing the issue in &test=breakpoints-02.js

**Comment by jasonLaster** [comment]
Fixed by (https://github.com/ryanjduffy/parse-script-tags/compare/master...jasonLaster:bump-babel?expand=1)

**Comment by jaril** [comment]
PR got merged, so I'm going to go ahead and close this.
