### ISSUE TITLE
Hot Reloading woes

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4331]
**Description:**
With hotreloading a bunch of globals are being re-executed such as
* `Error: Duplicate event listener: Recording.uploadedData`
* syntax-highlighted
* ...

These should be easy fixes with a somewhat long tail...

**Comment by jcmorrow** [comment]
@jasonLaster I'm gonna close this after:

- https://github.com/RecordReplay/devtools/commit/42c2cf4602cc053c78aa603a9b8099f0ddc88522
- https://github.com/RecordReplay/devtools/commit/b77eac4c1c2b1fc0823f5797867df57dcdb47026
- https://github.com/RecordReplay/devtools/commit/6fa10363a8af6c519652605e5646f38c8282039d
- https://github.com/RecordReplay/devtools/commit/439a21f60b3366007e7ae742794c9253ab6d7c6d

Lmk if you see anything else!
