### ISSUE TITLE
Loader is hanging off the side in new design

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4337]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/9154902/140572568-3f2c0ab1-954f-4924-8703-7fa8f470b16d.png">

We're going to be dealing with the loading stuff in the new Replay Info tab. We should remove this circular loader.

**Comment by jasonLaster** [comment]
Hmm. This is a difficult one because it affects when people can see breakpoint hits... also sources ... if the info pane is hidden they would miss this too... Not saying no, just requires some thought

**Comment by jcmorrow** [comment]
This thing just says "indexing" when we are loading, maybe we should replace it with a mini version of this same loader? 

![CleanShot 2021-11-05 at 20 44 58](https://user-images.githubusercontent.com/5903784/140596872-3c8649e6-5492-4134-b19b-536e79840611.png)

**Comment by jasonLaster** [comment]
Not a bad idea. I also like the Ellipses animation where it goes from one dot to two to three, down to one. I say this because we also show Indexing... in the tooltip which might not look as good with a spinner

**Comment by jonbell-lot23** [comment]
Yup, and this gets back to something we've discussed a lot:

* A global download optimises for showing something at all times, but is bad at context
* Versus showing *in context* when something might not load, which is easier to message

If we think we can do it contextually, it's less cruft *and* communicates more successfully. "You can't do X" is always more clear than "Just so you know, things are happening."

**Comment by jasonLaster** [comment]
I think we're in a much better spot with respect to contextual loading states. The only thing we're not doing with the contextual loading states is showing progress which is nice.

My take is that we probably should keep this global progress circle, but clean up the alignment and soften the color, the black is very strong in this softer ui.

**Comment by jonbell-lot23** [comment]
We agree with making it more subtle, visually. But I don't think the loader has earned the right to take such a prominent place in the UI.

**Users/scenarios where the loader is extra chrome with no benefit and adding confusion:**
* Anyone who stays in Viewer
* Anyone who just wants to scrub through video
* Anyone who just came to add a commnet
* Anyone who just came to look at events
* Any situation where things are fully loaded before the user attempts them

**User scenarios where the loader is worth the extra chrome:**
* Complex actions like breakpoints that aren't ready yet -- but that can and should be done contextually, and should not be doubled up in the UI.

**Comment by jasonLaster** [comment]
We're going in the right direction.

1. This should not show up in the viewer so, if it does then that's an easy fix
2. In DevTools it is important because indexing will prevent sources, console logs, and other data from appearing. That's obviously no bueno as the user's waiting

I'd be open to other treatments to, like using the header Trial Expiring badging. That might be a bit better since it'd let us add a label next to the spinner.

**Comment by jonbell-lot23** [comment]
#2 makes sense. So I think we just need to come up with the best alignment/visual treatment and we're all set. (And as you say, remove it from Viewer)

**Comment by jonbell-lot23** [comment]
I tried to come up with a simple location/visual treatment tweak, but nothing looks right. The old loader only worked in the old interface, and the new one makes using a similar circle look silly.

But this aligns to the new design well. Use the loader in the background of the play button like so:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/9154902/140860221-16e83efb-071d-414c-a31a-6a4af0659769.png">

That's my proposal for the best way to keep this without it feeling stapled awkwardly onto the UI.

**Comment by jasonLaster** [comment]
worth trying 😉 

With the right tooltip I think it very well might do the trick

**Comment by jonbell-lot23** [comment]
#shipit

Need anything else @jaril ?

**Comment by jonbell-lot23** [comment]
I think this is the right approach, but just to keep pushing on this point:

"In DevTools it is important because indexing will:
1. prevent sources
2. console logs
3. other data from appearing.

That's obviously no bueno as the user's waiting"

Console logs are easy. They say loading in the console, so that's a non-issue.

Source are easy. We just show a loader when you try to go into those panes, and they're not nearly as common as the default comments tab.

What other data are we missing? What's the tangible use case where not having a global loader is making the page feel broken, and why does it require a vague global loader rather than showing a loading message in context? I don't think we've made the case here yet.

**Comment by jaril** [comment]
> #shipit
> 
> Need anything else @jaril ?

Nope! Let me get through to the end of the day and see what this week's list looks like, and then assign it to either this wek or next week.

**Comment by jaril** [comment]
Fixed #4536.
