### ISSUE TITLE
Truncate call stack filenames

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4347]
At the moment we truncate the function name and not the filename. We probably should do both lol, but the filename should certainly be truncated first
<img width="356" alt="call-stack-formatting" src="https://user-images.githubusercontent.com/254562/140597195-aee5c0cb-3e1c-484c-86b8-48e90a9cbf79.png">

**Comment by jasonLaster** [comment]
Scratch that, looks like we are truncating both, but for some reason we the filename is much longer

**Comment by jaril** [comment]
I think that meant to close it. Closing it.

**Comment by jasonLaster** [comment]
Reopening because it would be nice for the filename to be 70% vs 30%
