### ISSUE TITLE
Clicking in the timeline jumps to the beginning

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4350]
**Description:**
I think we started fixing this last week. 
https://app.replay.io/recording/438e4261-cd32-4f50-a0dd-3cb309c6d9e6?point=22716298759798976152465774693319598&time=8443&hasFrames=false

**Comment by hbenl** [comment]
This is a result of #4291: In the underlying recording, there is a big gap between the first and second paint point: the first is at 34ms, the second at 21916ms and there are also no mouse events during that time. When the user clicks on the timeline, we jump to the most recent paint or mouse event. We also did this in the past but covered it up by showing the user he was paused at the time he requested, but under the hood the devtools used an execution point for a different time.

**Comment by jasonLaster** [comment]
Thanks for explaining. Let's discuss before planning.

**Comment by jasonLaster** [comment]
Here is a Loom so others can see what we're discussing
https://www.loom.com/share/461e105fc46841408caf54da94471674

There are certainly trade-offs with using the user selected time that you call out in #4291 and @bhackett1024 called out https://github.com/RecordReplay/devtools/commit/a788374595a2ed65ddd928f41db2ead4343d55cc, but like @bhackett1024 called out in the initial commit it is important that the timeline act like a video player.

**Comment by jasonLaster** [comment]
closing so we can focus on #4289
