### ISSUE TITLE
Comment flashes when i add a console comment

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4353]
STR:
1. click "add comment" from the console
2. add a comment

https://app.replay.io/recording/22153f35-c4aa-4266-86e2-45857952ce3f?point=29206669832321578344721041103782839&time=11674.827566544851&hasFrames=true#

**Comment by jcmorrow** [comment]
Closed by https://github.com/RecordReplay/devtools/pull/4638
