### ISSUE TITLE
Console filter drawer

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4364]
**Description:**

We don't currently have an empty state which is more interesting than it sounds for a couple of reasons. First, it can be an opportunity to show the user that they are filtering the messages either with the filter query or by hiding logs, errors, warnings. Also, it's an opportunity to teach users to add print statements.

**Comment by jasonLaster** [comment]
It'd be nice to use this opportunity to revisit some of the Console information architecture.

Here's what we know
* The events dropdown is hard to find
* The console settings are hard to find
* The console can initially be noisy which can be an onboarding journey dead-end. And hide print statements.
* The console trash can is confusing because it is in the same spot as standard devtools, but works differently

Here's a rough proposal 

* Add a Console drawer similar to Chrome's
* Show the drawer initially. This is key for navigation and surfacing useful events (mouse clicks)...
* Either start with an empty console or filtered console

[Figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9379%3A100225)

### Drawer
<img width="576" alt="Console Object (1)" src="https://user-images.githubusercontent.com/254562/144759986-af64872c-642a-440e-a882-a0426766a45d.png">

### Empty State

<img width="576" alt="Console Object (2)" src="https://user-images.githubusercontent.com/254562/144759998-b8e256e3-a5ff-4745-9b96-432618264fae.png">


### Closed drawer

<img width="466" alt="Console Object (4)" src="https://user-images.githubusercontent.com/254562/144760000-e00ecb36-5fa5-4acf-a842-32f28aafd59b.png">

**Comment by jonbell-lot23** [comment]
I love this! I propose we build it out (while making sure the font sizes are standard of course) and get rolling on it. It's clearly a huge step forward for one of the biggest issues of our console. (Several issues, in fact)

**Comment by jaril** [comment]
Renamed this to console filter drawer since it's not really talking about just the empty state anymore.

**Comment by jonbell-lot23** [comment]
I did some explorations around font sizes. In this visual, the filters are all using our standard font size with the exception of the search text and the label.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/9154902/146299139-43a586fb-ce6a-435f-962c-9e9a439bb8ad.png">

**Comment by jasonLaster** [comment]
@jonbell-lot23 looking good. Do you think we should also show the console settings in the drawer or keep them in the dropdown in the right... Most replays dont have all these events because we only show categories with events

**Comment by jonbell-lot23** [comment]
Good question @jasonLaster

1. I think it's important that the gear/settings button be there in all cases, without an ability to scroll off screen for big replays with lots of events. 
2. So one idea is to use a fixed settings area like we do in library. Will think about it.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/9154902/146338050-1dd55c7b-4568-4843-a856-2b826bba7670.png">

**Comment by jonbell-lot23** [comment]
Here's a 30 second loom explaining the design: https://www.loom.com/share/337c5169ec3141c9ac6869a1aacba402

[Here's the link to the Figma screens](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9664%3A115536)

**Comment by jonbell-lot23** [comment]
Following up on the chat we had yesterday:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/9154902/147007580-2b27fc42-44be-428e-a0cc-166156b1b7fe.png">
