### ISSUE TITLE
"Let the UI breathe" follow ups

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4368]
**Description:**

- [x] #4369
- [x] #4360
- [x] https://github.com/RecordReplay/devtools/issues/4337
- [x] https://github.com/RecordReplay/devtools/issues/4380
- [ ] https://github.com/RecordReplay/devtools/issues/4247

**Comment by jonbell-lot23** [comment]
Note: These are all UI things, but I wouldn't consider them all equally important. 

Logo is a bug, so that's high pri
Margins is fit and finish, so that's medium pri
Zypsy icons are low pri
Loader is a broader conversation
