### ISSUE TITLE
Replay Logo is in the top left

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4369]
The logo now appears in the top left before either CSS or JS loads.

I think this is because of Server Side Rendering. We can probably test this by removing the stylesheets to simulate the loading experience

**Comment by ryanjduffy** [comment]
I don't think this is occurring any longer but I can't say why. I tried disabling JS and then hard refreshing the app and the logo is appearing in the center now. I can verify that it _was_ broken but doesn't seem to be now!

**Comment by jasonLaster** [comment]
haha - i think you're right. but not sure why either
