### ISSUE TITLE
Add Repainting Nag

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4376]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/?node-id=8329%3A56273)

**Description:**
We should show a dismissable nag that lets folks know that Repainting was just enabled, link to docs.

This is an example of us making the replay app a bit more mature.

**Comment by jonbell-lot23** [comment]
There's a certain bar to reach before something deserves a nag. What's the scenario where someone needs this nag? We know the drawback to nags -- it's right there in the name ;) What's the drawback to *not* having this nag? Is it truly an 80% use case?

**Comment by jasonLaster** [comment]
Nag might not be the right term here - this is not an onboarding nag, it is for users who have been using Replay to let them know about a new feature. As we grow up, we'll show other new dismissible feature nags in the future too.

It is also a bit of CYA (cover your ass) because I dont fully trust this feature and it is hidden, there's no UI treatment we're changing the behavior, so if they start seeing something weird i want them to let us know.

**Comment by jonbell-lot23** [comment]
Roger. So if it's feeling a little rough around the edges and we want feedback, I can see the messaging for that a lot clearly.

More broadly, as the app develops, we'll have channels like changelogs, weekly emails, "what's new" dialogs in our menu, etc. Reasonable people can disagree on exactly when to throw a big "we did something!" modal, but a lot of companies do this clumsily. It's easy to throw one up every time, but they can add up and degrade the experience. 

I want to provide other channels so it's truly special when something deserves that spotlight in our UI.

**Comment by jonbell-lot23** [comment]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8329%3A56275)
Screenshot:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/9154902/140832261-01e45f46-7e0e-4939-b04a-66275b4b754f.png">

**Comment by jonbell-lot23** [comment]
I think this got lost in the shuffle. The Figma link above has Jason's proposed text:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/9154902/142279286-73121bb4-dc49-4824-9524-4e82c496bea4.png">

**Comment by jasonLaster** [comment]
Yep - and you added some suggestions like

## Introducing On Demand Paints
...

**Comment by jonbell-lot23** [comment]
Ok @jaril here's what I think is the final design:
![image](https://user-images.githubusercontent.com/9154902/142540082-996985c2-73e9-4919-9472-2e9b57f08276.png)


Introducing On-Demand Paints 🎨 🚀

On-Demand Paints unblocks the Elements Panel and editable styles in the future, but is a tad glitchy.

Please let us know if you see any black boxes in the video.

**Comment by jasonLaster** [comment]
It's fine to ship repainting without a nag
