### ISSUE TITLE
Support (BigInt, ResizeObserver)

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#438]
https://sentry.io/organizations/replay/issues/1852751139/?project=5399075&query=is%3Aunresolved
https://sentry.io/organizations/replay/issues/1852461334/?query=is%3Aunresolved&statsPeriod=14d

**Comment by hbenl** [comment]
Polyfilling is impossible (BigInt) or not recommended (ResizeObserver), so I used a "ponyfill" for ResizeObserver in #685 and replaced BigInt with JSBI in #687.

**Comment by hbenl** [comment]
Fixed in #685 and #688
