### ISSUE TITLE
Left Sidebar follow ups

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4380]
**Description:**

- [x] Comments pane should be full height ([replay](https://app.replay.io/recording/2427cec0-402f-428e-bcdf-435a5d2e0336?point=31478299709572518192655888419914782&time=11807&hasFrames=false#))
- [x] Pause panel should be full height ([replay](https://app.replay.io/recording/2427cec0-402f-428e-bcdf-435a5d2e0336?point=130131940028949087559984414229266432&time=45216&hasFrames=true#))
- [x] https://github.com/RecordReplay/devtools/issues/3200
- [x] Comment editor should have left padding ([replay](https://app.replay.io/recording/2427cec0-402f-428e-bcdf-435a5d2e0336?point=34074448139099899665308916081755410&time=12623&hasFrames=true#)
- [x] Revisit comment background colors ([replay](https://app.replay.io/recording/2427cec0-402f-428e-bcdf-435a5d2e0336?point=31478299709572518192655888419914782&time=11807&hasFrames=false#))
- [x] Move marker should re-open the comments pane

https://www.loom.com/share/874359f9d5ff4bf3b16f132ffdea857b

**Comment by jonbell-lot23** [comment]
I disagree, but not enough to debate it. #shipit
