### ISSUE TITLE
No useful UI feedback when opening a recording and not authenticated

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4386]
**Description:**

1. Make a new recording and hit Stop
2. Redirected to Upload screen for title editing and stuff
3. Copy the URL and open it somewhere that you're _NOT_ logged in, like private browsing window
4. Page does not render and offers no feedback instructing the user to log in

**Additional Context:**

* Replay: https://app.replay.io/recording/24806b77-845c-44e0-b573-b29d02a84d67

**Comment by jasonLaster** [comment]
duplicate of #4221
