### ISSUE TITLE
Make print statements discoverable

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4387]
**Description:**
It is essential that people learn how to add print statements when they onboard into Replay.  It is also important for them to learn about what is possible when they pause and to learn about what we do to protect their data.

### V1
- [x] console + editor nags
- [x] #4405
- [x] https://github.com/RecordReplay/devtools/issues/4500 
- [x] Use empty editor space better to teach people how to search (cmd+p) (Jon)
- [x] #4614
- [x] Full Text search (Colby)
- [x] pause panel nags
- [x] #4634
- [x] https://github.com/RecordReplay/devtools/issues/4139

### V2
- [x] #4675
- [x] #4676
- [x] https://github.com/RecordReplay/devtools/issues/3916
- [x] https://github.com/RecordReplay/devtools/issues/4618 
- [x] https://github.com/RecordReplay/devtools/issues/4617
- [x] https://github.com/RecordReplay/devtools/issues/4682
- [x] #4698

### V3
- [x] https://github.com/RecordReplay/backend/issues/3151 😳
- [x] https://github.com/RecordReplay/devtools/issues/4364

**Comment by jonbell-lot23** [comment]
Jason and I had a good chat today, and I'll be syncing with Jaril on Monday to prioritise, organise, and tackle each of these. Some items will take no design effort, some are sort of vague, some are waiting on Jon, some are waiting on Jaril, etc. Working that out is step one, then the rest will be pretty straight-forward!

**Comment by jonbell-lot23** [comment]
Most of these are making progress. I've carved off a few items as discrete issues for better tracking.

**Comment by jaril** [comment]
Some things talked about in Dec 1 office hours that are not noted here:
- Making auth0 better: Everybody's complaining about having to keep logging in. Started seeding the idea of doing session management ourselves.
- Extension: Chrome extension for launching a website in replay to record.
- Guest count: Some indication of visitors to a replay similar to Loom.

**Comment by jonbell-lot23** [comment]
Thanks @jaril ! This will help me with a task I have open, which is to try and split out some new projects.

**Comment by jonbell-lot23** [comment]
This feature has grown up to include lots of great Dev NUX (new user experience) stuff so please see https://github.com/RecordReplay/devtools/issues/4828 for another way to slice and dice the issues @jaril @jasonLaster
