### ISSUE TITLE
Screenshot not updated while dragging timeline

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#4395]
If the user has repainting enabled and drags the time marker over the timeline, the screenshot is not updated.
Repainting enabled: https://app.replay.io/recording/88782d05-6d88-4826-bbcf-714ce15e0516
Repainting disabled: https://app.replay.io/recording/780130b4-99b9-4db8-a867-2db4bcf375ca

**Comment by jasonLaster** [comment]
Thanks for filing
