### ISSUE TITLE
Replay Info Pane should include the last URL

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4398]
It's important for users to be able to quickly get the recorded URL. Today the best way to do that is to go to the library or run location.href in the console.

In the future, i think the URL should be available above the video because it can change but that's not needed now.

NOTE: it is fine to just show the domain and on click copy the full url.

**Comment by jonbell-lot23** [comment]
Agree -- and this can go hand-in-hand with the idea that we default to the Events pane (when there are no comments).

We're creating a entryway into Replay with this pane, and this isa a natural thing to put there.

**Comment by jonbell-lot23** [comment]
Also see https://github.com/RecordReplay/devtools/issues/4407, it's part of the same redesign.

![image](https://user-images.githubusercontent.com/9154902/143505987-a1ed23b5-ac26-4186-9238-ed30f207b3db.png)

Jaril note: I used non-Material design icons here. To discuss.

**Comment by jasonLaster** [comment]
1. When viewing a replay, I couldn't find what URL the user used. For bloom & Wild this is really important as we have lots of "Secret" querystring flags that changes the behaviour of the site.

re Josh: we could link to the net monitor request which shows the query string
