### ISSUE TITLE
When there are no events, there should be no red line

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4402]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/9154902/140998367-bc0cddbd-1cee-47bb-819b-7dc5a3042ec3.png">

Notice in this example there's just a red line floating there. We should remove the red line.

While we're at it, we might as well have some default text that says "This Replay has no mouse clicks or keystrokes," in this style, with an icon on the top in the same way:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/9154902/140999121-e7b25b4f-f169-4e9a-9668-86e66586a436.png">

**Comment by jaril** [comment]
Getting rid of the red line is easy. The empty state for the events panel has more considerations so moving it to: #4653.

**Comment by jaril** [comment]
Fixed by #4656
