### ISSUE TITLE
Clean up tabs

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4403]
**Description:**
We should try to unify/clean up tabs now that we have editor tabs and the secondary toolbox

- active state
- hover state
- close button for tabs

NOTE: I tried to do this earlier and found it a bit more difficult than i thought it would be :)

**Comment by jasonLaster** [comment]
@jonbell-lot23 is this something you'd like to prioritize?

**Comment by jonbell-lot23** [comment]
Yup!

I've spent a while wrestling with the styles, and they're not straight-forward. When I'm done formalising the visuals I'll hand it off to code up.

**Comment by jasonLaster** [comment]
closing as this is stale. We can re-open it when we have an opinion on how to move forward
