### ISSUE TITLE
Sources pane should recommend searching for files with quick open

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4405]
We should add a small specialty hat for searching for files with cmd + p

**Comment by jaril** [comment]
Add a search button on top right that persists.

**Comment by jaril** [comment]
Figma:https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8676%3A67878

**Source file name search:**
- Adding a search bar to help frame the source tree:
<details><summary>Mockup</summary>
<img src="https://user-images.githubusercontent.com/15959269/141888028-f2509688-72a6-491c-bf6b-26bdf6b2f617.png" />
</details>

**Search behavior:**
- Should we present a flat list of source files whose name matches the search string? Or keep it grouped based on top level directory (similar to VS code)?
<details><summary>Mockup</summary>
<img src="https://user-images.githubusercontent.com/15959269/141888178-5dafa4cf-5c53-4ad6-b4f6-f551976627fd.png" />
<img src="https://user-images.githubusercontent.com/15959269/141888191-963eec89-d5d8-4bd1-8ee8-be822c27608c.png" />
</details>

**Cmd + P Nag**
- Clicking into the search within the source tree should always be there, but ideally, people can level up and just start using Cmd + P to get to their files faster.
- Might be too heavy to immediately show the shortcut as the user focuses in on the input box. Maybe delay it a few seconds?
- When should the nag disappear? It is after the user does their first Cmd + P? Is it after an explicit click on a dismiss action? Something else?
<details><summary>Mockup</summary>
<img src="https://user-images.githubusercontent.com/15959269/141888398-90b130b2-cd01-41a5-ba7d-b4c9b3856902.png" />
<img src="https://user-images.githubusercontent.com/15959269/141888413-0143ffdd-a40c-4f78-a6f2-d15d850d02b6.png" />
</details>

**Comment by jasonLaster** [comment]
Couple of notes

1. we're adding a header background to sources
2. we're adding a mag search button in the top right that launches QO
3. we're adding a gap between the sources and outline pane 

<img width="358" alt="Screen Shot 2021-11-16 at 12 22 45 PM" src="https://user-images.githubusercontent.com/254562/142059938-5f087c00-80c8-44f1-8a56-38a2fb0ddac4.png">

**Comment by jaril** [comment]
Fixed by #4534.
