### ISSUE TITLE
Replay info pane should call out longer replays

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4407]
**Description:**

When recordings are longer than 2 mins we should call that out in the info pane

[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9165%3A115269)

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/143505870-c75216fd-759d-4323-8608-9c36e08a5a95.png)

Also see #4398, it's part of the same design.

Jaril note: I used non-Material icons here. To discuss.
