### ISSUE TITLE
Node picker fails to find  characters

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4421]
### Replay Demo

STR:
1. go to https://static.replay.io/demo/
2. use the node picker in chrome 
3. go to https://app.replay.io/recording/b76cedc1-dcd2-4a5f-af5b-0fcdde133cf2
4. try the node picker in replay
5. notice how we get stuck on the orbs

https://www.loom.com/share/6055b09d765143c1bc4e2c57fe2b17f7

### CNN

Try enabling the node picker at the end of this [replay](https://app.replay.io/recording/3660cf83-5c25-4202-a638-57b3ead2b67e?point=9086519504459632267633610440312249&time=4686&hasFrames=false#) for CNN 

### ESPN
Try enabling the node picker at the end of this [replay](https://app.replay.io/recording/a2c4b547-c4c1-4c2a-9eae-42759d941620#) of ESPN

**Comment by hbenl** [comment]
Will be fixed in the next browser release.
