### ISSUE TITLE
Elements Panel right sidebar

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4422]
- [x] Accordion heights are off
- [x] The layout sidebar should have an overflow scroll
- [x] We probably need a vertical border between the right sidebar and markup tree
- [x] It should be clear that CSS files are not links 

<img width="505" alt="Screen Shot 2021-11-09 at 11 33 54 PM" src="https://user-images.githubusercontent.com/254562/141069651-9c595351-510e-4ad8-a165-7ea63200172f.png">
<img width="398" alt="Screen Shot 2021-11-09 at 11 34 17 PM" src="https://user-images.githubusercontent.com/254562/141069646-3f99aac8-7c76-4292-9513-2189cab20b42.png">

<img width="429" alt="Screen Shot 2021-11-09 at 11 34 25 PM" src="https://user-images.githubusercontent.com/254562/141069641-3d643813-c97b-483b-81a2-ffa57811cd5b.png">

**Comment by jonbell-lot23** [comment]
Status update: I won't be addressing this ticket in this sprint. Heather and I have a lot of foundational work to do on for outreach.
