### ISSUE TITLE
Drag target placement for console/elements/video resizing seems too high?

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4437]
See video, but basically the cursor changes to indicate dragging too high up, seems like maybe it's exactly between the video and the tab bar instead of right at the top of the tabbar?

https://user-images.githubusercontent.com/132260/141170017-d08450a8-f71e-41a1-a07e-e36e17762e80.mp4

**Comment by jasonLaster** [comment]
This now feels better
