### ISSUE TITLE
Fix Failing and Disabled Tests

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#4438]
As part of #4346, I disabled some tests in `manifest.js`, and others are still failing, though intermittently. There's a few steps here:

1. We should add a `pending` or `skip` flag to manifest, rather than commenting things out, so the test runner can yell at us 😄 
2. We should add back the commented out tests and mark them as skipped or pending
3. We should fix them 🚀 🚀 🚀

**Comment by jcmorrow** [comment]
https://github.com/RecordReplay/devtools/pull/4473 Fixes the intermittent tests (mostly), but we should still do the pending/skip stuff!

**Comment by jaril** [comment]
Closing this to continue tracking it in #4589.
