### ISSUE TITLE
Outline view should be virtualized

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4442]
**Description:**
The outline view should use a virtualized list, probably with React Window

**Comment by jasonLaster** [comment]
Here's one lesson. We currently show classes with a tree structure. For react-window we should refactor this so the whole thing is a list with class functions indented. That way react-window will just work...

**Comment by jasonLaster** [comment]
just tried installing react-window and hit some issues with dependencies

**Comment by jasonLaster** [comment]
```
npm i react-window
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: recordreplay-devtools@1.0.0
npm ERR! Found: react@0.0.0-fec00a869
npm ERR! node_modules/react
npm ERR!   react@"^0.0.0-experimental-edfe50510-20210823" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0 || ^17.0.0" from react-window@1.8.6
npm ERR! node_modules/react-window
npm ERR!   react-window@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jasonlaster/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jasonlaster/.npm/_logs/2021-11-13T05_31_42_850Z-debug.log
```

force works, but yikes

**Comment by jasonLaster** [comment]
This replay of airtable is so slow bc the outline view takes forever
https://app.replay.io/recording/931da6b2-3a80-499a-9ad6-954c4cfd28b2?point=11033630830215362784505313745699266&time=7680.93799440185&hasFrames=true

**Comment by colbyr** [comment]
@jasonLaster remind me, did you have a branch someplace where you started to work on this? also fwiw, I don't have access to that replay

**Comment by jasonLaster** [comment]
Yes! Here https://github.com/RecordReplay/devtools/pull/4488

**Comment by colbyr** [comment]
Here's the progress I made on the virtualized list https://github.com/RecordReplay/devtools/pull/4592

**Comment by jasonLaster** [comment]
Thanks! 

Closing because the work you did memoizing made it _just_ good enough. I'd like to come back though when things calm down and add proper virtualization
