### ISSUE TITLE
Command+Clicking on a recording in the library view should open the new tab in the background

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4443]
Currently the behavior is:
* Clicking a library list entry opens the recording in the current tab
* Command+Clicking the entry opens a new tab that is force-focused

I don't know why we're force-focusing the tab, but it's quite annoying if you want to open multiple recordings quickly since your focus gets pulled away from the library view.

**Comment by jasonLaster** [comment]
Good call - this logic is pretty weird now, but this will force us to refactor it.

**Comment by jcmorrow** [comment]
Yep, this also breaks right clicking to copy the link, which is frustrating.
