### ISSUE TITLE
Login screen flash

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#4466]
When I login on `http://localhost:8080`, I see the login screen flashing shortly after login:
https://app.replay.io/recording/67717774-d301-4fcd-9b72-56b3532dcd1c
This seems to be a bug in the Auth0 client library.

**Comment by jaril** [comment]
I vaguely remember seeing this myself, but I just tested it and doesn't appear to be happening in dev anymore. 

Closing for now. Feel free to reopen if I got it wrong! @hbenl @ryanjduffy
