### ISSUE TITLE
Privacy tips revisions

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4478]
Jason's original link:
https://app.replay.io/recording/9eb824dd-1db5-41bc-992a-0b06f8507cd3?point=8762000951960559194531502995013937&time=7206&hasFrames=false#

Jon's additional feedback:
This design needs revisions. Sure, we can disable it for the library, but I am inclined to revert it entirely and try again. Right now the feature:

* Looks spammy, like an ad or a cookie dismiss screen
* Has no way to skip (once or permanently) 
* Is using a carousel pattern in a non-standard and confusing way

This is an important enough screen that we should regroup and try again. And for something this significant, I'd expect to be looped in on the design side before it goes live.

**Comment by jaril** [comment]
Continued in #4541.
