### ISSUE TITLE
Editing the title of a recording should update the window title

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4481]
Here for example I edited the title to add on

>  with some new title text added on

after the existing title, but the FF tab itself still reflects the old title

<img width="541" alt="Screen Shot 2021-11-12 at 4 11 47 PM" src="https://user-images.githubusercontent.com/132260/141597446-ea0df34e-7ec9-402f-8e60-6a1b97f40a39.png">

**Comment by jasonLaster** [comment]
good call
