### ISSUE TITLE
The timestamp is "sticking" in the timeline

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4484]
![image](https://user-images.githubusercontent.com/9154902/141604977-d10f12ff-a209-4ad2-858f-2dab995282a0.png)

Notice the 0:10 in the timeline. That should only show when attached to a mouse cursor. Right now it sticks on the bottom, which is a bug.

**Comment by jasonLaster** [comment]
I've noticed this behavior in other tooltips too - like the gutter hits, bp timeline timestamp etc... maybe we can address this in the shared component?
