### ISSUE TITLE
Cannot scroll in the Events pane.

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#4495]
Here's a recording I was playing around with: https://app.replay.io/recording/e2d12050-4392-4ceb-8d95-657c4c27d1f9

It's not a recording of the bug, but when you open that recording and make your browser window small enough that the number of Events start falling off the edge, you'll notice you can't scroll down to click on more events.

I believe a user should be able to scroll in the Events pane.

**Comment by jasonLaster** [comment]
fixed by https://github.com/RecordReplay/devtools/pull/4497
