### ISSUE TITLE
What gets rendered in the Viewer changes based upon my mouse leaving the breakpoint "box"

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#4496]
Here's a recording with comments explaining the unexpected behavior: https://app.replay.io/recording/49d2725b-af09-4f1d-ae1c-7828bf2c3fcd

**Comment by jasonLaster** [comment]
cc @jonbell-lot23 curious what you think of this loading state

**Comment by jonbell-lot23** [comment]
It's a tough one. We have two extreme options, and the answer will be somewhere in the middle:

1. Never show loading state, meaning surprising jumps like this (current approach)
2. Show loading state, which can feel heavy

Here's a "loading states powers of ten" video I made for situations like this:
https://www.loom.com/share/6a73dcc7aba643709e8366f60fa57232

I don't think it's tenable to never show loading states. I understand a reluctance to put a spinner up there every time we seek in the video, but the alternative is this sort of disjointed and jumpy experience. So I agree with @jasonLaster 's comment in the Replay:

"We should show probably show a spinner in the bottom right of the video to make it clear that we're still painting..."

**Comment by gideonred** [comment]
FYI, I don't think this was loading in the background and catching up. There's a clear change happening as my mouse is leaving the breakpoint dialogue. If I left my mouse in the breakpoint dialogue the repaint never happens.

**Comment by jonbell-lot23** [comment]
@gideonred Never mind, then! My loading stuff is relevant overall but maybe not for this particular issue.
