### ISSUE TITLE
[Debugger] Call stack is missing async section

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#451]
https://replay.io/view?id=053d8409-c074-42a9-879c-ff29643eb921

STR:

1. go to https://replay.io/view?id=ceb8a319-3daa-4384-b12a-7add6cc85998
2. click the 2nd comment "type is undefined"

The call stack should have EventListener.handleEvent

<img width="305" alt="Screen Shot 2020-08-22 at 10 39 52 AM" src="https://user-images.githubusercontent.com/254562/90962334-16e21800-e464-11ea-9f22-546f480b65e6.png">
<img width="467" alt="Screen Shot 2020-08-22 at 10 39 49 AM" src="https://user-images.githubusercontent.com/254562/90962336-177aae80-e464-11ea-90f4-48928d3115e9.png">

**Comment by bhackett1024** [comment]
Can you explain why EventListener.handleEvent should be on the stack?  _onStorageChange is directly added as an event listener on the window on line 497, so it will be called directly by the browser and shouldn't have a caller AFAICT.

**Comment by bhackett1024** [comment]
cc @jasonLaster

**Comment by jasonLaster** [comment]
I think the screenshot of the console helps.

My expectation is that async call stacks should stitch together call stacks in the same way

**Comment by jasonLaster** [comment]
Here's an example of aysnc call stacks with promies
STR:
1. actions/app.js
2. add a breakpoint in setupApp

<img width="424" alt="Screen Shot 2020-09-04 at 6 41 08 PM" src="https://user-images.githubusercontent.com/254562/92294165-43734680-eede-11ea-84e6-e79697c44042.png">
<img width="301" alt="Screen Shot 2020-09-04 at 6 40 49 PM" src="https://user-images.githubusercontent.com/254562/92294168-44a47380-eede-11ea-8a7f-76d34714a641.png">

**Comment by jasonLaster** [comment]
STR:

1. go to https://replay.io/view?id=07276e83-ac6a-422a-bb75-7f8d27c71468
2. add a breakpoint on `actions/app.js#9`
3. seek to that location

Here's a recording: https://replay.io/view?id=7b34125a-31c8-49be-bfdd-2d294a4e209d

**Comment by jasonLaster** [comment]
This feature seems to be especially high impact. 

* Async debugging, especially with promises, is a sore spot in JS.
* Async call stacks are one of Replay's most magical features
* This bug is fairly common. I ran into this while pairing with a beta user last week

**Comment by jasonLaster** [comment]
Closing so we can track this feature request in canny

https://replay.canny.io/admin/feedback/feature-requests/p/async-stacks-promise-settimeout-fetch?boards=feature-requests
