### ISSUE TITLE
Remove z-index style from ToolboxOptions

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4515]
Not sure why this style is there but it doesn't appear to be doing anything except place the element higher when it has no business doing so.

We should double check that this isn't doing anything and remove it.

https://github.com/RecordReplay/devtools/blob/master/src/ui/components/SecondaryToolbox/ToolboxOptions.css

**Comment by jasonLaster** [comment]
@jaril feel free to track in a personal todo-list
