### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4532]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=8911%3A76584)

Default search state:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/9154902/142167845-85058115-a2e7-4dd8-9bb1-5ea051ff218b.png">

Search in progress:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/9154902/142167922-1ae1c4bd-1dbe-4dc4-801e-1e3a1cb6ae89.png">

Search complete:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/9154902/142167951-2c5eb118-b6f8-4bf2-8fa4-2754ac42e830.png">

Notes:

* We don't think we need an X. This is a keyboard-driven flow, so a person will type, hit enter, and get results. People who want to clear out the field and try a new term are likely to hit backspace or command-A -> delete.

* The indeterminate spinner will be there while searching, and will be replaced with a number of returned matches when the search is done. Maybe we'll end up having both parts of the UI there at once, but we think we can get away with not cluttering it up.

* This is taking queues from other onboarding feature improvements. The shade of gray, the magnifying glass icon, etc. Wherever possible, these should be aligned.

**Comment by jaril** [comment]
Fixed by #4553.
