### ISSUE TITLE
[Debugger] functions are shown as invalidObject

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#454]
STR:

1. go to https://replay.io/view?id=71daacb2-c6aa-459f-856f-96f5174f4f1e
2. open NewNote.tsx
3. add a breakpoint on 29
4. evaluate `this` (I think)

<img width="380" alt="Screen Shot 2020-08-20 at 8 04 18 AM" src="https://user-images.githubusercontent.com/254562/90965951-e14c2780-e481-11ea-9de8-190f36d48c0c.png">

**Comment by bhackett1024** [comment]
"this" is undefined here.  Can you create a recording of the problem?  cc @jasonLaster

**Comment by jasonLaster** [comment]
okay. I think `e` was being evaluated, but now it works

<img width="837" alt="Screen Shot 2020-08-29 at 4 58 04 PM" src="https://user-images.githubusercontent.com/254562/91648151-dca2e880-ea18-11ea-9ab3-1ed3f3b797d8.png">
