### ISSUE TITLE
Time tooltip on the timeline remains even after the mouse has left the timeline

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4554]
![image](https://user-images.githubusercontent.com/15959269/142337266-c7803730-132b-486d-b1d5-e48a17d4415c.png)

**Comment by jasonLaster** [comment]
I think there's another really similar issue

**Comment by gideonred** [comment]
Might be related to Holger's fix to hover state? https://github.com/RecordReplay/devtools/pull/4518

**Comment by jaril** [comment]
Also tracked in #4484.
