### ISSUE TITLE
Update team settings for organizations

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#4575]
We need to add support for configuring organization-specific settings in the team settings pane (if the team is an org).

* Upload a team logo
* Disable "My Library"
* Disable public replays
* Set a Message of the Day
* Set Block list / Allowlist for recordings

**Comment by ryanjduffy** [comment]
@jonbell-lot23 - fyi

**Comment by ryanjduffy** [comment]
@jasonLaster left some comments in figma

**Comment by jonbell-lot23** [comment]
Here's a design for the logo.

**Sizes**
Max-width: 121px (will be fine-tuning)
Max-height: 48px

**Margins**
Logo: 20px from the top
Text only: 32px from the top
Bottom: 14px
Left: 32px;

**Text behaviour**
* If there's no logo, we show text only
* If the text is long, it wraps

![image](https://user-images.githubusercontent.com/9154902/142954615-e1a5fc4a-b31e-486f-ab3a-809512e9b9d9.png)

**Comment by jonbell-lot23** [comment]
Here's a design for the viewer and dev-specific invite links. It's a design that looks straight-forward but actually it's a bit tricky figuring out how to make it all work together!

![image](https://user-images.githubusercontent.com/9154902/142957230-0fdfd4d2-1eef-49c6-9330-a32268b23c74.png)

([Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9081%3A80802))

**Comment by jasonLaster** [comment]
yep - looks great!

**Comment by jonbell-lot23** [comment]
Adding #4663 to track the billing flow.
