### ISSUE TITLE
End to end test failures

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#4589]
Some failures I've seen recently with Replays

### Failures

1. I cannot make heads or tails of this and the replay is just blank and 1 second long.
- [Failure Log](https://github.com/RecordReplay/devtools/runs/4268143325?check_suite_focus=true#step:5:966)
- [Replay](https://app.replay.io/recording/673afac4-51b8-42df-aed7-3a1c400e9199?point=2305843009213693954&time=1784&hasFrames=false)

2. Suuuuuper long start-up time (2 minutes ish), so the test timed out.
- [Failure Log](https://github.com/RecordReplay/devtools/runs/4268204521?check_suite_focus=true#step:5:706)
- [Replay](https://app.replay.io/recording/a9301a8a-e776-43fe-80e8-ce75e1bd95dd?point=133052607002959375729614529287427134&time=131134&hasFrames=false)

3. Another 2 minute start.
- [Failure Log](https://github.com/RecordReplay/devtools/runs/4268204780?check_suite_focus=true#step:5:756)
- [Replay](https://app.replay.io/recording/439ef45f-2a9a-46e4-947b-da5b58f269cd?point=83401268292019321090586636227447536&time=123852&hasFrames=false)

4. Failed because the console message isn't visible. It seems like maybe the 'Show Exceptions' filter isn't behaving properly? This test also breaks for me on trying to click the warpTo button even when the filter is set properly.
- [Failure Log](https://github.com/RecordReplay/devtools/runs/4269788148?check_suite_focus=true#step:5:691)
- [Replay](https://app.replay.io/recording/792a6bec-9ce5-44c1-90b0-3a7cfd521338?point=25961484294790364763689097881453034&time=53460.099703142594&hasFrames=true)

Other changes to make:

- [x] Add a pending or skip flag to manifest, rather than commenting things out, so the test runner can yell at us 😄
- [x] Add back the commented out tests and mark them as skipped or pending
- [ ] Fix them 🚀 🚀 🚀

**Comment by jcmorrow** [comment]
I'm going to add to this task: some of the tests that fail are just tests that take a long time, for instance `breakpoints-07`. We  should add a lower default timeout, and an optional `timeout` field to the manifest, so that we can keep the timeouts reasonable, but allow for some tests that are just doing a lot of stuff to take a long time without it being considered a failure.

**Comment by jcmorrow** [comment]
One trail of clues on `breakpoints-07` from https://github.com/RecordReplay/devtools/runs/4490107621?check_suite_focus=true:

```
console.log: "Starting addBreakpoint" "bundle_input.js" 5
console.log: "Finished addBreakpoint in 1540ms"
console.log: "Starting rewindToLine" 5
console.log: "waiting 50ms for execution to pause"
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
console.log: "waiting 50ms for execution to pause"
console.log: "action[MESSAGES_ADD].messages[0].parameters[0] is of type ValueFront"
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
...
console.log: "waiting 200ms for execution to pause"
JavaScript error: , line 0: uncaught exception: Object
JavaScript error: , line 0: uncaught exception: Object
...
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
...
JavaScript error: , line 0: uncaught exception: Object
JavaScript error: , line 0: uncaught exception: Object
...
console.log: "Message failed" "Session.createPause" "<unavailable>" (void 0)
JavaScript error: , line 0: uncaught exception: Object
console.log: "waiting 200ms for execution to pause"
console.log: "waiting 200ms for execution to pause"
...
[162.644] Test failed: JavaScript error: http://localhost:8080/_next/static/chunks/pages/_app.js?ts=1639183544356 line 7992 > eval, line 225: Error: waitUntil() timed out waiting for execution to pause
```

It looks like the `addBreakpoint` (which I think dispatches a redux action and sends a request via protocol to the backend) is succeeding, but the backend is failing to correctly process and add that breakpoint. I'm not sure why this would be happening in this test but not locally?

**Comment by bhackett1024** [comment]
Hmm, with issues like this it is much much easier if we have a recording of the devtools.  The harness should be generating and logging those, is there one available?

**Comment by jcmorrow** [comment]
For some reason these particular failures never log a replay, which is another mystery to me. (Most of them do log one correctly now).

**Comment by jcmorrow** [comment]
Oh, actually, nvm, it looks like it's not getting included in the failure line, but we *do* have a useful replay: https://app.replay.io/recording/05212773-f908-4bef-a794-1ed68d96bbf9?point=35697040904448365290624879314341252&time=56915&hasFrames=false

**Comment by jasonLaster** [comment]
@jcmorrow oh great. I wonder how hard it would be to start getting PR comments w/ replay links?

**Comment by bhackett1024** [comment]
> @jcmorrow oh great. I wonder how hard it would be to start getting PR comments w/ replay links?

Hmm, if we want to start building in new features like this I think we should switch our test runner over to playwright first.  It should be easier to make the test runner more reliable, and will give us something to build on which users can also take advantage of if they want to record their tests.  Our current test runner is a sort of glue-and-tape thing that predates the playwright work and would be nice to sunset.

**Comment by jcmorrow** [comment]
100% agree with @bhackett1024 here. Local test runner improvements are helpful internally, playwright progress is helpful internally *and* externally.

**Comment by bhackett1024** [comment]
To be clear, we shouldn't have to rewrite the tests themselves, they can still run as part of the page.  But it shouldn't be hard to launch playwright to create a recording of the example site, and then launch it again to replay that earlier recording (and also record the viewer).

**Comment by jcmorrow** [comment]
Ah, ok, for some reason I thought playwright had a runner aspect to it as well, but that makes sense.

**Comment by jcmorrow** [comment]
Still pretty boggled by this. I got some of the issues in the test to reproduce here: http://localhost:8080/recording/d3a5ed53-49b6-4168-b5bd-1fbdd5687969?point=1947111321950675652849396808155171&time=3434&hasFrames=false but it seems to only happen intermittently, so it's hard to record. It seems like protocol calls fail at first, but at some point start working again, for reasons unknown to me.

**Comment by jasonLaster** [comment]
Good call!

We have this DevTools [project](https://github.com/RecordReplay/devtools/issues/4501) for migrating to playwright.

**Comment by jcmorrow** [comment]
Alright, so there seems to be a long-tail of sometimes failures, but the only consistent one is `breakpoints-07`. As my message above summarizes, I don't have a good fix for it, it seems like there's a failure when at a particular pause. Reproduction here: https://app.replay.io/recording/939daecc-372f-4d39-ab89-a44e2a2d4183

I'm going to close this for now, as this test has been marked as pending and fixing it is not the highest priority, but when we get around to it, that replay should help 🤞
