### ISSUE TITLE
Default editor state revisions #2

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4596]
Sorry guys, I still can't figure out how to fix the editor stuff. Here's how it should work:

The editor pane can't get smaller than 240px. Easy. We don't even need the narrow class, now that I think about it.

Sorry I couldn't figure out the CSS! There's some stuff going on in the code I couldn't work out.

See previous PR: https://github.com/RecordReplay/devtools/pull/4584?notification_referrer_id=NT_kwDOAIuxVrIyNzExMDkwMzA1OjkxNTQ5MDI#issuecomment-974596445

**Comment by jasonLaster** [comment]
@jonbell-lot23 what would you like the design to look like?

**Comment by jonbell-lot23** [comment]
The editor pane should not get smaller than 240px. And we don't need the narrow class.

(And then the bars themselves should fit within that 240px of course)

**Comment by jaril** [comment]
Closed by #4655
