### ISSUE TITLE
[Console] Cannot jump to a node in the inspector

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#460]
https://sentry.io/organizations/replay/issues/1854092946/?query=is%3Aunresolved

**Comment by bhackett1024** [comment]
It's hard to fix/test this without STR.  Can you create STR or a recording for this problem?

**Comment by bhackett1024** [comment]
cc @jasonLaster

**Comment by jasonLaster** [comment]
https://replay.io/view?id=ef81471c-f0b7-4333-9722-84869d3a4ad2

I think the goal is to be able to jump to the node in the inspector

**Comment by jasonLaster** [comment]
This worked for me:

1. go to https://replay.io/view?id=284da194-e97a-4bb8-879a-abc417b76f79
2. in the console type `document.body`
3. click the jump button
