### ISSUE TITLE
Outline function call counts

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4615]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9115%3A80493)

* We're adding hit counts
* We're showing when something has a breakpoint set
* We're adding an entry point to set a breakpoint (via right-click)
* I also added the ability to add a comment. To discuss

**Standard**
![image](https://user-images.githubusercontent.com/9154902/143153984-2ecbf286-ae27-4f7d-9c13-fd60fd6d6d48.png)

**Breakpoint set / highlight shown**
![image](https://user-images.githubusercontent.com/9154902/143154014-950be249-4327-4388-8686-4eab6b0048f8.png)

**When breakpoint and highlight conflict**
![image](https://user-images.githubusercontent.com/9154902/143154035-cf3816cf-f0ee-48ae-9244-8b457c497748.png)

**Right-click to add breakpoint or comment**
![image](https://user-images.githubusercontent.com/9154902/143154067-05175551-563c-4b2f-9ec6-80f0dcd12aa5.png)

**Comment by jonbell-lot23** [comment]
Here's the design proposal! We haven't discussed as a group yet, but this should be similar to what @jasonLaster and @jonbell-lot23 discussed a few days back.

**Comment by jaril** [comment]
@ankitr You got this 👍

**Comment by jonbell-lot23** [comment]
Ping @jaril @jasonLaster where'd we end up on this?

I remember Jason saying the number of hits didn't seem high priority. Should we close this out?

**Comment by jasonLaster** [comment]
Lets close it and come back to it later
