### ISSUE TITLE
Fit & Finish UI Bugs

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4616]
This is a grab bag of items that came out of my UX audit last week. Most of these are easy/small, but put together they will add a good level of polish to our existing features.

- [x] https://github.com/RecordReplay/devtools/issues/4596
- [x] https://github.com/RecordReplay/devtools/issues/4401
- [x] https://github.com/RecordReplay/devtools/issues/4539
- [x] https://github.com/RecordReplay/devtools/issues/4402
- [x] https://github.com/RecordReplay/devtools/issues/4484
- [ ] https://github.com/RecordReplay/devtools/issues/4425
- [ ] https://github.com/RecordReplay/devtools/issues/4180
- [ ] https://github.com/RecordReplay/devtools/issues/4129
- [ ] https://github.com/RecordReplay/devtools/issues/4131
- [ ] https://github.com/RecordReplay/devtools/issues/4138

**Comment by jasonLaster** [comment]
Added a couple of additional items as well. Lets prioritize during design sync

**Comment by jaril** [comment]
Punted on #4359 since it's not a priority.
