### ISSUE TITLE
Support switching subscriptions

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4663]
[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9081%3A80952)

**Four options for the entry point**
![image](https://user-images.githubusercontent.com/9154902/143156351-e21aaa83-26bd-4703-9e32-818dd02c6dd6.png)

**Plan selection (placeholder)**
![image](https://user-images.githubusercontent.com/9154902/143156387-67360b8a-78c6-4687-8000-7b05fbe1bf7a.png)

**Comment by jonbell-lot23** [comment]
This is a quick sketch to get us on the same page. Next I need to build the actual plan selection page.

**Comment by jasonLaster** [comment]
Nice! Stylistically i'm a fan of 3

**Comment by jonbell-lot23** [comment]
I'm going through old tickets and I see we never landed the plan selection page. Here's where we are [in the Figma](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9152%3A105871):

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/9154902/144763767-6c0050c9-c36c-488c-8f17-a033b993d423.png">

This isn't high priority on my list right now, but it won't be hard to land when it does become P1.

**Comment by jonbell-lot23** [comment]
Going through design tickets. In the past, I've been told that this issue isn't pressing quite yet. How about now @ryanjduffy ? Getting to a point where we should really land this? :)

**Comment by jasonLaster** [comment]
@jonbell-lot23 I don't think this is a priority. It would be if there were active teams that were either hitting the user or recording count.

Also a couple of thoughts for posterity.

1. I wonder if Enterprise could get a different treatment, like a full width box...
2. I wonder if we could move the org upgrade to the Members page when they hit the user count threshold...
3. We should probably keep this UI simple and route folks to /pricing for more info

**Comment by ryanjduffy** [comment]
agree. I think the lapsed trial flow needs attention before the switch plans / upgrade flow.

**Comment by jonbell-lot23** [comment]
Thanks!

(And as a note, yeah, the design isn't landed yet. When we do work on finalising the design I agree with your ideas above Jason)

**Comment by jonbell-lot23** [comment]
Adding a note to say that this is still on my radar for when the priority level warrants landing the final design

**Comment by jaril** [comment]
This might be a hot take but if we all agree that this isn't going to be worked on anytime soon, there's no reason for this to be open. Closing it for now.
