### ISSUE TITLE
Outline view should have an empty state

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4676]
**Description:**

This could be similar to other empty states

[Figma link](https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9165%3A116596)

**Comment by jonbell-lot23** [comment]
![image](https://user-images.githubusercontent.com/9154902/143504904-399b888c-468b-4029-b36a-e486cb9c2004.png)

Q: Why are we using a spinner?
A: It's a side effect of our new UI. The progress bar requires a tight interface with right angles so the bar can go from 0% to 100% complete without complication. We're using a lot of spacing and rounded edges, so they don't work as well. So we'll use a spinner instead!
