### ISSUE TITLE
Make sure that our GraphQL queries will use exponential backoff during an outage

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#4677]
Based on my limited experience with our cloud dev environments, it seems like if the GraphQL server is failing to respond altogether, the Apollo exponential backoff retry won't kick in. This means that the client will just start constantly retrying requests, seemingly without much delay or any limit to the number of attempts made. I'm guessing this is because, as [the docs](https://www.apollographql.com/docs/react/api/link/apollo-link-retry/) say, the `retryLink` from Apollo handles cases "if [they fail] due to network or server errors". At least in cloud dev, when the GraphQL server goes down, it doesn't even return a 500, it just doesn't accept the incoming connection at all. I'm not sure how well this mimics our production setup, but if that happened during a real outage it could create a [thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem) scenario, which could compound an already stressful outage.

**Comment by abstractalgo** [comment]
relevant docs:
- [default config](https://master--apollo-client-docs.netlify.app/docs/react/api/link/apollo-link-retry/#default-configuration) for retry link
- [avoiding thundering herd](https://master--apollo-client-docs.netlify.app/docs/react/api/link/apollo-link-retry/#avoiding-thundering-herd)

By default, it uses exponential backoff, which means it's already there. Need to confirm that GraphQL server being down triggers the exponential backoff though.

**Comment by abstractalgo** [comment]
Checked the configuration for retrylink and logged delays, which seem to increase at an ~expected rate.
