### ISSUE TITLE
Start analysing our guest flow UX

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4683]

**Comment by jaril** [comment]
Duplicate #4684.

**Comment by jonbell-lot23** [comment]
This was a ticket for me to do an audit, which is different from the instrumenting one

**Comment by jonbell-lot23** [comment]
I've filed one ticket with a Loom here: https://github.com/RecordReplay/devtools/issues/4859

**Comment by jonbell-lot23** [comment]
This ticket was for tracking the overall audit. That's moving along well so I'm going to close this in favour of the issues where I fix it.
