### ISSUE TITLE
Start instrumenting our guest flow UX

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4684]

**Comment by jasonLaster** [comment]
@jonbell-lot23 what's the goal here?

**Comment by jonbell-lot23** [comment]
This was from a call with you, me, and Jaril where we discussed tracking the guest journey

**Comment by jasonLaster** [comment]
Thanks. Wonder if there is something simple we can do in mixpanel here. Lets discuss on monday.
