### ISSUE TITLE
Default to Replay Info unless there are comments

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4687]
**Description**
Today we default to the comments pane, which is usually blank. We're going to default to Replay Info ... unless there's a comment.

**Scenarios**
Author of Replay loads Replay for first time: default to Replay info
Author of Replay loads Replay every other time: default to last place they were

Someone loads Replay for the first time and there's no comment: default to Replay info
Someone loads Replay for the first and there is a comment: default to Comment
Someone loads Replay every other time: default to the last place they were

**Comment by jaril** [comment]
This one's challenging. 

Comments have to load, so there's some period of time where we don't know whether or not a replay has a comment. We can only apply the defaulting behavior after comments have loaded. So whatever the previous pane was, it's possible that we end up yanking them away from it and into the "default" pane.

Either we delay being in a state where we show the pane at all until we know what comments are (and know what pane to show), or we allow the yanking behavior.

@jonbell-lot23 thoughts?

**Comment by jaril** [comment]
Talked to @jonbell-lot23 — apparently we've discussed this before and the conclusion was that the backend should send us recording data that includes a `hasComments` flag. That way, we can identify and present the default pane immediately.

**Comment by jaril** [comment]
This is easier to do now that we have the `layout` reducer that we can initialize separately after we have access to queries.
