### ISSUE TITLE
Explicit click target to add a print statement

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4698]
This is an exploration for now. This change is based off of the our observation that the replay a-ha moment is usually locked behind adding a breakpoint/print statement. That UI is not immediately obvious, unless you're familiar with how to add breakpoints in the first place.

We've made some changes to make it more obvious that there's a click target by the gutter — adding a tooltip with the number of hits when hovering on the gutter, and extending that hover target to the entire editor row. This makes it slightly less subtle but we don't highlight the click target to add a print statement explicitly (apart from a light gray hover effect to preview the breakpoint visual)

It would be nice to feel out a UI similar to how GitHub's comment-adding affordance — a small green plus button right beside the line that yells "Click me!".

https://github.com/RecordReplay/devtools/pull/4697

**Comment by jonbell-lot23** [comment]
Really liking this direction!
