### ISSUE TITLE
Outline view displays classes incorrectly

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#4700]
Classes are displaying their first method's name as the class name.

Demo: https://share.descript.com/view/aUpx4OKb8DP
Replay: https://app.replay.io/recording/a733cc6f-96ac-428c-ba39-d39fe77ef899

**Comment by jaril** [comment]
@jasonLaster Do you remember why this change was made? Undoing parts of it seem to have fixed the problem here.

https://github.com/RecordReplay/devtools/commit/5ad46a34b3bcf6d2b4b19c6e551241365d458299

**Comment by jasonLaster** [comment]
Good call. This logic is pretty confusing
