### ISSUE TITLE
Notaku sourcemaps are off by ~10 lines

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4705]
https://app.replay.io/recording/e3670058-f91b-48d7-86e8-78d2beff79cd?point=67499859174273779102899121019684225&time=25934&hasFrames=false

**Comment by jcmorrow** [comment]
For now, going to close this in favor of the Issue page for Source Maps (which tracks work that is valid, but not currently on the immediate roadmap): https://www.notion.so/replayio/Source-Map-Issues-e761f8ac000d4bcd94adb9a8c2f74d38
