### ISSUE TITLE
Node Picker does not find elements in hamburger modal

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4706]
Replay: https://app.replay.io/recording/deffb552-51a2-4721-ba24-cdcd41dfc4ce?point=18497557562378107867466381014337391&time=8324&hasFrames=false
Replay of the bug: https://app.replay.io/recording/20a567a5-089d-4cbe-a7f9-ca5ec7d3ddc1

**Comment by hbenl** [comment]
Fixed by RecordReplay/gecko-dev#614
