### ISSUE TITLE
Wrong this in arrow functions in breakpoint print expression

### ISSUE THREAD

**Issue by tslocke** [RecordReplay/devtools#4710]
**Description:**

I'm using the print debugging on a breakpoint, and to get the data I want to inspect, I need to map over an array:

`block.children.map(id => this.blocks[id])`

I get an error that `this.blocks` is null, but outside of that arrow function I can log `this.blocks` and it's not null.

**Comment by jasonLaster** [comment]
@tslocke could you share the replay where this happened with us. If it is private, would it be possible to add jason@replay.io or logan@replay.io as collaborators?

**Comment by tslocke** [comment]
I’m not sure I still have it. Seems like it would be easy to replicate? Unless it doesn’t happen generally I guess

**Comment by jasonLaster** [comment]
Yep - this is probably a babel / sourcemap issue, so having the original replay would help

**Comment by tslocke** [comment]
Sorry, I don't have it.

To add a bit more detail, if I set a breakpoint in a method, I can use `this` in my debug expressions and it is correctly bound to the object instance. However in an arrow function (which is supposed to inherit the same `this` as the lexical context), `this` had become the global `this` (`window`).

**Comment by jasonLaster** [comment]
No worries - should be easy to add a couple of test cases

**Comment by hbenl** [comment]
I tried to reproduce this but Replay always showed the correct `this` value for me. I agree that this is most likely a sourcemapping issue (i.e. the debugger shows you being paused in a different location than the one you're actually paused in). To verify, have a look where you're paused in the generated source and see if it really corresponds to the location in the original source that the debugger is showing you.

**Comment by tslocke** [comment]
I’m sorry I don’t have a repro, but I don’t think this was the issue, because ‘this’ outside the arrow-fn was correct. I remember that pretty clearly because I was able to do a hacky workaround with the outer this, and get the info I wanted. Sorry that’s not more helpful.

Tom

**Comment by jasonLaster** [comment]
Thanks @tslocke. Going to close for now since it's not actionable, but we can re-open when if see it again.
