### ISSUE TITLE
Long time waiting for recording to load without any messages

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#4735]
I've been creating some node recordings to debug some stuff, but the UX while waiting for the recording to load isn't very good.  The tab sits for a long time when trying to view the recording, with no messaging at all about what is happening.  Here is the recording FWIW https://app.replay.io/recording/71194c1d-b4e8-4c44-91c8-a6ac12bc1f58

**Comment by jasonLaster** [comment]
Just saw the same thing here 
https://app.replay.io/recording/dbbdab48-85b8-436d-9335-980020a62971?point=7139408181531136216610799924281967&time=4018.5893223819303&hasFrames=true#


https://github.com/RecordReplay/devtools/issues/3523 will help, but we should also figure out why we're slow

**Comment by bhackett1024** [comment]
This is an important area to have good telemetry I think.

**Comment by jasonLaster** [comment]
Agreed.

Okay - so this is a regression in the backend time it takes to create a session.

At a minimum, I think Replay could start showing the progress bar loading when we start creating the session as opposed to waiting until it's created.

**Comment by kannanvijayan** [comment]
Is this possibly related to the database perf regression @gideonred mentioned?  The alleged cause there was the large number of entries created by our pentester.

Also please invite me to view the recordings.  I don't currently have access.

**Comment by gideonred** [comment]
Our database was hit very hard by our penetration tester 2 days ago and since people have been complaining about slow times to get to the loading bar when viewing a recording. I suspect our graphql responses are slower when creating a recording.

We have a database view here: https://app.datadoghq.com/screen/integration/239/aws-rds-postgresql?from_ts=1638531524793&to_ts=1638535124793&live=true

But I'm not aware if we have a GraphQL health dashboard. I'll see if I can find one.

**Comment by gideonred** [comment]
FYI Here's a picture of our pentester loading up a bunch of teams and comments:

![Screen Shot 2021-12-03 at 7 43 13 AM](https://user-images.githubusercontent.com/28845582/144604515-0b1d3ba0-9d0f-4cdf-8b04-c9d328383a81.png)

I'll ask the team to delete today. Hopefully we can do this in the admin panel in the future.

**Comment by bhackett1024** [comment]
I think the long delays in session creation are happening due to https://github.com/RecordReplay/backend/pull/3839.  This shouldn't affect the total time to load the recording, but it will take a lot longer to get the session from the backend.  The regression being fixed was deployed two days ago.  There is a big spike in session creation times from around then, which is clearly visible in this graph:

https://ui.honeycomb.io/replay/datasets/backend/result/gCSvpoDAat4

**Comment by gideonred** [comment]
I'll add session creation time to our Team KPI report.
