### ISSUE TITLE
Put Loom link behind experimental flag

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4744]
Our Loom functionality doesn't look particularly ready for prime time yet. We originally pushed it out to gather information, but there's a branding overhead to having something feel half-baked in the UI like this. Everything a new user sees needs to feel polished and relevant.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/9154902/144682143-83902c96-fe73-44e1-b060-2f287958cbfc.png">

I recommend putting it behind an experimental flag while we work out what to do with this feature idea.

**Comment by jasonLaster** [comment]
https://github.com/RecordReplay/devtools/pull/4487

will try and wrap soon
