### ISSUE TITLE
Update Accordion component

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4748]
Our current accordion has a couple of issues:

1. the panels can be awkward sizes
2. the panels cannot be resized

this library should be a good starting point
https://github.com/DanFessler/react-panelgroup

**Comment by jasonLaster** [comment]
After doing some more research I found:
* https://github.com/leefsmp/Re-Flex
* https://github.com/tomkp/react-split-pane

re-flex is pretty close, but has some weird behavior when you add in panes that are collapsible

**Comment by jasonLaster** [comment]
closing as this is probably a nerd snipe and we can revisit down the road

**Comment by jaril** [comment]
Bumping.

**Comment by jcmorrow** [comment]
Some notes from our exploration of VS Code's accordiong: https://www.notion.so/replayio/Accordion-06d91f9d65d24cd88020fd9f5b7dc3c5

**Comment by abstractalgo** [comment]
related #5317
