### ISSUE TITLE
Elements - arrow key navigation should be faster

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4756]
**Description:**

The up / down arrow keys should not scroll unless the next element is out of view. Also, they should be a lot faster. Right now it feels like we're doing something heavy like re-rendering the whole tree

https://app.replay.io/recording/b9353076-ba95-4062-ad46-5b0ae4ce628c

**Comment by hbenl** [comment]
The scrolling is fixed by #4759 but the performance still needs to be improved.
