### ISSUE TITLE
Elements - left arrow should not go back to a prior frame

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4757]
**Description:**

The default behavior works, but if you go quickly you can cause the elements panel to miss one and then seek backwards

https://app.replay.io/recording/b9353076-ba95-4062-ad46-5b0ae4ce628c

**Comment by jasonLaster** [comment]
This is difficult to do in practice, but we could make it clearer by 

a) having a different select / focus state https://github.com/RecordReplay/devtools/issues/4908
b) ensuring that arrow keys always bring the focus to another node. This is an important invariant we should maintain and perhaps test for.

**Comment by hbenl** [comment]
I was finally able to reproduce this:
- click on a child element
- press the left key twice:
  - the first keypress selects the parent element, but the child still has focus
  - the second keypress collapses the parent element, now the focused child has disappeared and hence the markup box loses focus
- press the left key again -> the recording jumps to the previous screenshot
