### ISSUE TITLE
Symbol tooltips closed too eagerly

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#4774]
**Description:**

It happens for me quite often that a tooltip that gets displayed when I hover over a symbol~ gets closed when I try to move my pointer to it.

Consider this situation
<img width="376" alt="Screenshot 2021-12-07 at 22 38 32" src="https://user-images.githubusercontent.com/9800850/145110355-9fdc437b-56b3-416f-bca6-3e157ce59c46.png">

When I see this I intuitively move my cursor towards "entries" in the tooltip, so I can try to expand that and inspect the content of this data. However, that name is quite short and the tooltip is somewhat wide and my pointer trajectory is connecting those 2 points in a straight line - this makes my pointer leave the source symbol area for a short moment without yet entering the tooltip itself. 

You naturally must close the tooltip when I move my pointer out of the source element and the tooltip - but it seems that timings and stuff could be fine-tuned here because it really happens quite often for me (not every time though!)

**Expected Result:**

I should be able to move my cursor to the tooltip content without the tooltip being closed - if I do that reasonably fast.

**Comment by jasonLaster** [comment]
totally, i've noticed this too. Could you record a couple replays of this?

**Comment by jaril** [comment]
Tried replicating this and yeah I do see the effect. The tooltip's somewhat debounced to keep you from collapsing the tooltip on the way to a property, but the time window still appears to be a bit fast.

[target replay](https://app.replay.io/recording/tooltip-delay--c741999f-f50e-4754-8bba-46c04fb6107e)

https://user-images.githubusercontent.com/15959269/151015941-445df8ff-980a-4af7-90f0-8bf991de4ce6.mov

**Comment by jaril** [comment]
Replay: https://app.replay.io/recording/replay-of-replay-with-tooltip-issue--ad18659f-8451-4294-89c7-4c8570d73d80

**Comment by jaril** [comment]
Before: https://app.replay.io/recording/smart-gap-not-working--dadd5e2e-27a0-4366-90cb-48832a274d16
After: https://app.replay.io/recording/smart-gap-working--81767e25-6e18-4b7e-9321-6fed55a51656
