### ISSUE TITLE
Impove the filter styles ui

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4777]
**Description:**

- Lets remove the clear button. It is ugly and doesn't add much
- Let's use the tailwind checkbox in settings > experimental which looks better

### Current ui
![image](https://user-images.githubusercontent.com/254562/145122627-66a28b56-3d79-47b8-8298-d3a730b4347b.png)

### experimental
<img width="307" alt="Screen Shot 2021-12-07 at 3 39 35 PM" src="https://user-images.githubusercontent.com/254562/145122758-123308bf-1e86-454f-a42c-ac6e0af31116.png">

**Comment by abstractalgo** [comment]
Spoke to @hbenl and got some help. On it.

**Comment by abstractalgo** [comment]
PR ready and approved, feel to merge whenever (I have no write perms for this repo so somebody else has to do it).
