### ISSUE TITLE
New CSP restrictions break usage of non-cloud backend dev 

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4778]
<img width="832" alt="Screen Shot 2021-12-07 at 5 26 36 PM" src="https://user-images.githubusercontent.com/132260/145132056-7e6a4b2b-5fd1-44e7-a57e-cc393fb812f6.png">

**Comment by ryanjduffy** [comment]
I'm confused by this because `ws://localhost:*` is included in the CSP for local dev. 

https://github.com/RecordReplay/devtools/blob/43ca6db2db87ab77390d33e2c87304c1a247a9bf/pages/_document.tsx#L16-L19

**Comment by ryanjduffy** [comment]
I tried this by running the backend locally, creating a new recording, and the loading the recording with the frontend at `http://localhost:8080` from `npm run dev` and everything worked without any CSP errors.

Can you give it another try today and perhaps create a replay if it still repros for you?

**Comment by loganfsmyth** [comment]
Sorry I could have been clearer on this. This is when using `https://app.replay.io/recording/<ID>?dispatch=ws://localhost:8000` for local dev of the _backend_ while using the production deploy of devtools. Is the expectation that we always run against local-dev devtools now even for that?

**Comment by ryanjduffy** [comment]
Ah! Gotcha ... I'm not sure how to handle that, tbh. I guess we should add `ws://localhost:8000` to the prod CSP. Seems not ideal but I'm not sure it opens any significant security holes since it would require the user to have had someone inject a local websocket server running on that port to exfiltrate data from their session.

**Comment by loganfsmyth** [comment]
Yeahh, I don't love it and it is probably something we shouldn't do long-term.

**Comment by gideonred** [comment]
I think it's ok to have "bad" CSP first, as the hardest part is to introduce any CSP. Over time we can sharpen our CSP.

**Comment by loganfsmyth** [comment]
> I think it's ok to have "bad" CSP first, as the hardest part is to introduce any CSP. Over time we can sharpen our CSP.

Agreed
