### ISSUE TITLE
Rules view should have a filter bar

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4784]
It would be nice to be able to filter in the Replay rules view in the same way that you filter in chrome devtools.

**Comment by abstractalgo** [comment]
On it.

**Comment by abstractalgo** [comment]
`Toolbar` includes also `ClassListPanel` and `PseudoClassPanel` and toggles for them, which seem severely broken (probably the reason why it was commented out in the first place ~16 months ago).
![image](https://user-images.githubusercontent.com/1355455/145268775-17bec4e8-46aa-4227-9813-cfb188461ec9.png)

Do we focus just on getting search input and filtering working, or making the entire Toolbar work?

**Comment by jasonLaster** [comment]
Yep - the other features dont make sense for us at the moment

**Comment by jasonLaster** [comment]
They will down the line though :)

**Comment by abstractalgo** [comment]
The entirety of the rule filtering functionality is missing (i.e. `src/devtools/client/inspector/rules/rules.js` knows nothing about it, and neither does any of `RulesApp`, `Rule` or `Declaration` components etc).

Looking at Firefox's filtering capability (video), we can see that it filters by selector and declarations (CSS attributes), and it highlights elements accordingly, plus it actually filters rules.

https://user-images.githubusercontent.com/1355455/145375251-cb538f14-e7ad-4b4e-9f6e-72126d596ea4.mp4

**Comment by abstractalgo** [comment]
Checked with Holger, and indeed, by his recommendation to also check through Git history, this kind of functionality was never there, so we'd have to handle it ourselves.

Splitting work into some sensible, independent chunks:
- [ ] basic filtering by selectors and attributes
- [ ] highlighting

**Comment by jasonLaster** [comment]
Makes sense
