### ISSUE TITLE
Event tie-in new icon

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4798]
Jon to try new icon for the event tie-in.

**Comment by jonbell-lot23** [comment]
@jaril can you give me a sample Replay where I can try this feature? I have it turned on in my experimental settings but can't seem to make it show up.

**Comment by jonbell-lot23** [comment]
@jaril It's Sunday in the US but when you get back online can you help me out here? Thanks!

**Comment by jasonLaster** [comment]
Hmm, it looks like it might not be ready https://app.replay.io/recording/b4349409-1de9-422d-8b47-6579d46137e7?point=58413339660689052133306126678622275&time=36792.73824668633&hasFrames=true#

**Comment by jaril** [comment]
> @jaril It's Sunday in the US but when you get back online can you help me out here? Thanks!

Added a guard to fix that. https://github.com/RecordReplay/devtools/pull/4890

**Comment by jaril** [comment]
Let me get a good replay for testing out the icon. I'm not sure but on a quick check I think it might be broken — we're not receiving the event listener breakpoints that I expect to get in the first place.

**Comment by jonbell-lot23** [comment]
@jaril sorry, still don't seem to be able to repro this?

**Comment by jaril** [comment]
@jonbell-lot23 are you blocked on this? if it's not high priority we should close it.
