### ISSUE TITLE
Tooltip hiding behind editor

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4801]
![image](https://user-images.githubusercontent.com/9154902/145328345-23e99ad9-d5a4-4a66-9a26-9a51615342ca.png)

**Comment by jonbell-lot23** [comment]
Repro:

Click the icon for the section you're on, which removes the left column
Hover over an icon

Result:

Notice how the tooltip is hidden (at least) in Safari and Chrome

**Comment by jonbell-lot23** [comment]
Would like to get this fixed, re-upping

**Comment by jasonLaster** [comment]
Here's a replay that shows the tooltip being clipped by the editor, but not the left sidebar
https://app.replay.io/recording/a70a7264-fa2e-4c9f-a363-dee92c180b6e#
