### ISSUE TITLE
Command Palette V1 bugs

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4819]
We have a prototype version of command palette, but this ticket is tracking its readiness for public release.

- [x] Work through the keyboard shortcuts we want to use
-  [x] [Command palette should have cursor up/cursor down support](#4803)
- [x] Support options doesn't seem to work (I'm in Safari)
- [x] Show privacy information takes me to a page that says "Application error: a client-side exception has occurred (see the browser console for more information)."
- [x] Open console should focus text field but doesn't seem to
- [x] Open outline should expand the area -- for me it stayed collapsed
- [x] Keep the current active command scrolled into view

**Comment by jonbell-lot23** [comment]
This is a technical set of bugs, not a design task. Recommend one of two things:

1. Remove needs-design label and assign to a developer
or
2. Re-open #4812, which is being used as a series of technical tasks, and let this one be the design task.

I recommend #2 because these are two different workstreams, and combining them confuses my tracking.

**Comment by jasonLaster** [comment]
Updated!
