### ISSUE TITLE
Expired team settings goes to wrong place

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4827]
This is what I see when I go to an expired team:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/9154902/145732417-d2ff5dcb-d58c-49d7-b641-fb18d0edfac9.png">

But I should be taken here:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/9154902/145732424-d22f1b79-f11d-44e0-bd3f-080deb851036.png">

Assigning to Ryan and not putting in the sprint, feel free to sort and prioritise of course

**Comment by jonbell-lot23** [comment]
Hey @ryanjduffy is this issue addressed?

**Comment by jasonLaster** [comment]
It looks like it is still relevant
https://app.replay.io/recording/55c698e4-d5f5-4c2a-85d2-25dbe74108c1
