### ISSUE TITLE
Our "are you sure" screen when inviting users is finicky

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4831]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/9154902/145737883-1b1719de-faf8-45c7-9a9b-cc1845e6f493.png">

1. This appeared even though I don't remember adding someone
2. Once I dismissed it and tried again, it showed up a second time. That feels broken.

**Comment by jaril** [comment]
Fixed by #4932.
