### ISSUE TITLE
Stored breakpoints do not seem to be updating properly

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#484]
I have a bunch of logpoints which get reinstalled every time I open the viewer on a replay.io recording.  I keep deleting the logpoints when loading, but they keep reappearing the next time I open a new viewer tab.  The logic for syncing breakpoints with local storage does not seem to be working as it should.

**Comment by jasonLaster** [comment]
Here is a recording
https://replay.io/view?id=17a009ba-9167-4ec1-b37b-de2f7dbf7094
