### ISSUE TITLE
Markup Root should fill the panel

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4872]
The component should fill the width of the panel

<img width="755" alt="Screen Shot 2021-12-17 at 7 46 00 PM" src="https://user-images.githubusercontent.com/254562/146627861-c61d03c3-8918-44d1-8d9d-b2bf67ebbec1.png">

**Comment by abstractalgo** [comment]
Done with https://github.com/RecordReplay/devtools/pull/5045.
