### ISSUE TITLE
Net Monitor fast forward button

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4873]
There are two visual issues with the fast forward button

1. the button overlaps the name of the request. Maybe we need to have something to the left of the name like status code that is less important
2. the fast forward button bleeds into the selected row

---
<img width="697" alt="Screen Shot 2021-12-17 at 7 47 40 PM" src="https://user-images.githubusercontent.com/254562/146627942-0aa74175-2e42-4672-9075-0b57879151d4.png">

---
<img width="698" alt="Screen Shot 2021-12-17 at 7 47 51 PM" src="https://user-images.githubusercontent.com/254562/146627927-df1081e4-8fce-4663-a814-5a158201213b.png">
<img width="692" alt="Screen Shot 2021-12-17 at 7 47 45 PM" src="https://user-images.githubusercontent.com/254562/146627937-18a248a5-0076-42ae-9334-953063c5549b.png">

**Comment by jasonLaster** [comment]
@jonbell-lot23 would love you're thoughts on this one. 

We've fixed the first issue, but the second one is still out there.

**Comment by jonbell-lot23** [comment]
Great question! My recommendation is to use --primary-accent-hover for the entire row, then continue using --primary-accent for the rewind/fast-forward button. We should also bring in a shadow-md to set offset it.

Here's a loom explaining the thinking:
https://www.loom.com/share/c44a35545f5c4155919dc4640ac6fba8

Here's a visual representation of the proposal to go alongside the Loom:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/9154902/148673499-e64db3f8-e662-43b2-a735-90d8ccdf30bb.png">

**Comment by jasonLaster** [comment]
Thanks! Looks good

**Comment by jonbell-lot23** [comment]
Assigning to @jcmorrow to apply this change
