### ISSUE TITLE
Sharing dropdown doesn't update

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#4878]
Originally reported by [@bird](https://github.com/birdeatsbug) via https://app.birdeatsbug.com/sessions/lRvsIajgrNPKeDDAN-J7k

https://app.replay.io/recording/378fcd58-3f08-440e-9825-76bfe553f02b#

**Comment by jaril** [comment]
This is currently breaking a QA Wolf test so give them a heads up once it's closed!

**Comment by jaril** [comment]
This seems like an errant refetch. Switching from team -> public appears to work and the correct mutation is applied. If you were to refresh the page, the correct text shows (public). But if not, it doesn't show the correct text until you click it another time.
