### ISSUE TITLE
React tab sometimes disappears after clicking

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#4884]
Reported by [@bird](https://github.com/birdeatsbug) via https://app.birdeatsbug.com/sessions/xmIyKwwGtKKs8OFJqOLga

I've seen this before as well. I tried to find a repro to make a replay but didn't come across one immediately.

**Comment by jasonLaster** [comment]
This happens because we think there is a React app, but then we go to view the panel check and confirm that there isn't... it's definitely a flow that could/should be improved

**Comment by markerikson** [comment]
Captured a repro while debugging someone else's app: https://app.replay.io/recording/1cda1287-7f0f-4c87-8b98-7635b81bb951

**Comment by ceceliacreates** [comment]
Another replay here: https://app.replay.io/recording/react-tab-disappears-when-clicked--2fde5c26-cac0-4a0d-8d23-f6251b9eada6

**Comment by hbenl** [comment]
@bhackett1024 Any thoughts on this? In particular how is it possible that these recordings contain annotations although they don't contain the `__RECORD_REPLAY_REACT_DEVTOOLS_SEND_BRIDGE__` hook?

**Comment by bhackett1024** [comment]
> @bhackett1024 Any thoughts on this? In particular how is it possible that these recordings contain annotations although they don't contain the `__RECORD_REPLAY_REACT_DEVTOOLS_SEND_BRIDGE__` hook?

Do we have complete STR for this problem?  I don't remember a whole lot about how these hooks work, but is it possible they're defined on some window globals but not others?

**Comment by hbenl** [comment]
@bhackett1024 Unfortunately this seems to happen sporadically to some recordings, I couldn't find a way to create recordings myself that show the issue.

**Comment by ceceliacreates** [comment]
I added a repro to the PR here: https://github.com/RecordReplay/devtools/pull/5134

Not sure if you had already seen or if that's unrelated.

I also am only experiencing this if I click the React tab right at the beginning of the Replay, like you stated.

**Comment by hbenl** [comment]
@ceceliacreates Actually that recording didn't have the issue that we're talking about here: there's another issue where the React tab disappears if you try to open it while you're paused somewhere at the beginning of the recording (usually the first 1-2 seconds), but at later points in the recording it works.

**Comment by ceceliacreates** [comment]
@hbenl I might be misunderstanding, but that happens here. I recorded a replay of this replay -- https://app.replay.io/recording/react-calculator-react-tab-disappears--338edf8a-01c2-4488-98d1-0136b7a04f5d

The tab appears fine when later in the recording, but disappears when clicked early. 

It's a local recording of the React Calculator app, repo linked in the comment here: https://github.com/RecordReplay/devtools/pull/5134#issuecomment-1024710037

**Comment by hbenl** [comment]
Yes, that's exactly what I meant.
