### ISSUE TITLE
Replay failing every time I load it

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4927]
Here's a Replay of the issue happening:
https://app.replay.io/recording/1710ae91-ac76-4287-85aa-cf06ba61cca8

Here's the URL:
https://app.replay.io/recording/8df35348-cac8-4657-a7ae-ce6538c7a69f?point=32127336827600189973931518322544453&time=26147&hasFrames=false

What I did:
* I was looking at a standard Replay, everything was fine
* I opened the Command Palette
* I selected Viewer
* I got an error, and now every time I load it I get the same error shown in the Replay link above
* I also get an error when I remove the params

More info:
* Jason can't repro
* Jason says this doesn't appear straight-forward to him
* Replay wasn't updated -- updated it and I'm seeing the same error
* Safari is working fine, so this appears to be unique to my Replay browser install

**Comment by jasonLaster** [comment]
@jonbell-lot23 my hunch is that this has something to do with corrupted `localStorage` state.

**Comment by jonbell-lot23** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/9154902/147890792-6dad9e9d-4445-40db-a94e-1bcdd8a94cc3.png">

When I deleted all my key/value pairs from here, it fixed the problem. And then I was able to repro!

* Go to devtools
* Go to command palette 
* Select a bunch of options -- sources and print options may be what did it?
* Then go to Viewer

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/9154902/147890884-181d2c62-fe67-46c4-bb69-d2ddea4f3c6e.png">

This is the bit that causes the crash. If you remove it, it's fine. It might be the yank_to_sources?

**Comment by jasonLaster** [comment]
@jonbell-lot23 can you record with replay?

**Comment by jonbell-lot23** [comment]
Yup @jasonLaster it's at the top of the ticket

**Comment by jonbell-lot23** [comment]
@jaril we talked about this last week, here's the issue and repro steps

**Comment by jasonLaster** [comment]
@jonbell-lot23 I was not able to reproduce. Could you try reproducing again while recording?

**Comment by jonbell-lot23** [comment]
Good news, I think this may have been addressed.

Not today, Satan! [Close]
