### ISSUE TITLE
Unable to select recordings once Edit is pressed on library

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#4938]
**Description:**

It seems that the click on the checkbox on the recording entry in the library is triggering the click handler for the recording overall so it navigates to the recording right away instead of selecting the item.

**Steps to Reproduce:**

1. Load Library
2. Press "Edit"
3. Click checkbox on an item in the library list

**Expected Result:**

Checkbox is selected

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay: https://app.replay.io/recording/b575c99d-aadd-41b1-be07-fcf60b5eea5d

**Comment by jcmorrow** [comment]
It's weird, this happens in FF/Replay browser, but not in Chrome 🤔
