### ISSUE TITLE
Design share card

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4959]
![image](https://user-images.githubusercontent.com/9154902/148471396-e1b34b75-ab48-44e3-ad71-e9232b914eb5.png)

See #3634

**Comment by ryanjduffy** [comment]
V1

![localhost_3000_cf2da81f-3a74-45ba-9241-f6d4361a52f5 png (1)](https://user-images.githubusercontent.com/788456/148487887-e9f1a192-038a-4273-9ecd-28977c23ff7c.png)
![localhost_3000_cf2da81f-3a74-45ba-9241-f6d4361a52f5 png](https://user-images.githubusercontent.com/788456/148487892-ce5e9479-78e3-4b40-8913-0261019792f5.png)

**Comment by jasonLaster** [comment]
Just want to chime in that this design is really good. 

* Love the gradient which reinforces the brand
* Love the dropshadow for the photo
* Love the use of Inter for the title

It's all really good

**Comment by ryanjduffy** [comment]
Couple adjustments:
* noticed the byline text wasn't sized correctly so this should be better and
* experimented with bottom-aligning the image so it aligns with the icon for single line text but then is clipped for longer text.

![localhost_3000_cf2da81f-3a74-45ba-9241-f6d4361a52f5 png (2)](https://user-images.githubusercontent.com/788456/148492059-76787723-c7cd-4cf5-9935-639cbb70f3d5.png)

![localhost_3000_cf2da81f-3a74-45ba-9241-f6d4361a52f5 png (3)](https://user-images.githubusercontent.com/788456/148492147-30ee8ac4-b244-4e09-a0c4-9cb78c6be4ef.png)
