### ISSUE TITLE
Network monitor table loading bar

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4972]
We should show a loading progress bar similar to how the console will soon have a progress bar

https://github.com/RecordReplay/devtools/pull/4902

**Comment by jcmorrow** [comment]
Is the idea here that the loading bar is just to let the user know that something is going on, but its not actually linked to the progress of the loading, or that it actually knows how far along we are in the loading process?

**Comment by jasonLaster** [comment]
yeah - it just shows that we are loading the network activity, but no notion of actual progress
