### ISSUE TITLE
Pause info should have notification badge

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4980]
Notification badges are a standard part of software UX, and people typically understand what they represent. In contrast, our current design is far less clear. So we're going to go with a standard notification badge.

Here's how it would look zoomed out:
![image](https://user-images.githubusercontent.com/9154902/148865342-eb84d7c7-a796-45bc-9435-25dac43e73f2.png)

And here's a zoomed-in version:
![image](https://user-images.githubusercontent.com/9154902/148865431-4401e73f-5665-4ad5-9a59-16d4e1f12769.png)

Notice the dot is hanging off the edge of the gridline, which is by design. We don't want the dot to be within the 24x24 icon bounds, we purposely design it to break out of the grid to denote status and its separation from the icon.

**Comment by jaril** [comment]
Fixed with #4989
