### ISSUE TITLE
Social previews are sometimes missing

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#4983]
Sometime when you paste a link to a public replay, the preview isn't displayed.

For new recordings, I suspect that the first render of the page for upload occurs when the recording is still private so the metadata doesn't load until the page is re-rendered after the 360s timeout.

For existing recordings, I assume that the rendering is too slow but there could be errors. Some telemetry could be useful though I want to be careful adding processing to something that is time bound..

- [x] https://github.com/RecordReplay/backend/issues/4202
- [ ] ~https://github.com/RecordReplay/devtools/pull/5015~
- [ ] #5395

**Comment by jaril** [comment]
@ryanjduffy How do we feel about this? Does this look like it should be prioritized for the next ~3mos, or backlog for now?
