### ISSUE TITLE
Add tooltip to icon that clears console evaluations and disable when no evaluations present

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#4997]
**Description:**
There is a trashcan icon in the Console tab next to the Filter Output input field. It is not clear that this icon clears console evaluations, and when there are no evaluations present, clicking the icon does nothing with no error or message.

**Steps to Reproduce:**

**Expected Result:**
Icon should explain function with tooltip on hover, and icon should be disabled when there are no evaluations present to clear.

**Additional Context:**

* Screenshots:
<img width="683" alt="Screen Shot 2022-01-11 at 10 41 22 PM" src="https://user-images.githubusercontent.com/40367173/149063566-1f27c282-8ecb-483a-b796-7b712499bcad.png">

* Video (Loom):
* Replay:

**Comment by jaril** [comment]
https://user-images.githubusercontent.com/15959269/150617372-1783485a-5af4-4e30-b891-a1016aae09df.mov

We already have both the disabled state button/tooltip text, as well as the tooltip text for when the button is clickable.

Closing pre-emptively, feel free to reopen if I've missed something!
