### ISSUE TITLE
[Debugger] loadChildren

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#501]
./src/devtools/client/debugger/packages/devtools-reps/src/object-inspector/utils/load-properties.js in loadItemProperties at line 13:17

```
can't access property "loadChildren", o(...) is undefined
```

https://sentry.io/organizations/replay/issues/1852115007/?project=5399075&query=is%3Aunresolved

<img width="817" alt="Screen Shot 2020-08-25 at 5 01 23 PM" src="https://user-images.githubusercontent.com/254562/91239552-b61d3e80-e6f4-11ea-90ef-22617fed2d0d.png">

**Comment by jasonLaster** [comment]
This is by far and away our #1 reported issue in sentry.

**Comment by hbenl** [comment]
One scenario where this happens is whenever the mouse hovers over a variable in the debugger's editor that was optimized away.
STR:
- open a recording of firebugs.dev
- set a breakpoint in `static/js/components/App.js` (e.g. line 16)
- navigate to the breakpoint being hit
- hover over the `React` or the `Table` import

We could add a check in `src/devtools/client/debugger/src/actions/preview.js`, function `setPreview()` if the `result` we get from `client.evaluate()` is `undefined` (or if its return value has an `exception` property) and disable the preview in this case.
Alternatively, we could show a hover with the value "undefined", that's what the Firefox debugger does in this case.

**Comment by jasonLaster** [comment]
I think showing `undefined` is better because the user doesn't wait for the value to appear.
