### ISSUE TITLE
Load frame is collapsed into the Babel function group

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5028]
**Description:**

It'd be nice to first reproduce the problem locally and then adjust the framework grouping logic.

<img width="254" alt="Screen Shot 2022-01-14 at 5 08 42 PM" src="https://user-images.githubusercontent.com/254562/149602962-d8ff8cf4-81d2-4695-ab48-232a04aa69b2.png">

**Comment by jaril** [comment]
@jasonLaster how do you feel about this?

**Comment by jasonLaster** [comment]
lets close it since we can't repro
