### ISSUE TITLE
Elements panel's Breadcrumbs improvements

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5032]
**Description:**

Improvements to breadcrumbs part of the Elements panel regarding having left-most and right-most `...` buttons for scrolling through node's breadcrumbs (currently missing).

![image](https://user-images.githubusercontent.com/1355455/149817865-a982c7e3-8a18-49c0-8a0a-355f2300f902.png)

Clicking on the breadcrumb item already navigates to the item properly.

**Comment by hbenl** [comment]
This works in Firefox but not in other browsers. The reason is that the `visibility` of the buttons is changed in `overflow`/`underflow` event handlers, but those events are only supported in Firefox.
