### ISSUE TITLE
Better unauthorized viewer flow

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5061]
This is regarding the case where a user opens a replay that they're not authorized to view. 

For the most part, these are user errors that are avoidable if they sharer had just made the replay public in the first place. For the times they forget to, we should have a better fallback experience.

Leaving the implementation open for now, but some flow that helps bridge the user from A) opening the replay and see the "Not authorized to view", to b) User is able to open the replay.

Mixpanel dashboard: https://mixpanel.com/s/47Izle

Related issue: https://github.com/RecordReplay/devtools/issues/3853

**Comment by jaril** [comment]
Right now, if User A opens User B's replay while they're unauthorized, they're faced with the "You're not authorized" screen. They then have to ping User B to add them as a collaborator. Once User B adds them as a collaborator, User B tells User A that they should be able to access it now.

The current steps are pretty long (and we can do quite a bit to make it much faster), but the smallest step (V1) for now would be to have some request access functionality in the "You're not authorized" page for User A to click on. User B still needs to be notified manually, but the difference is when User B opens up their share modal, they will see that User A has already requested access and they can simply click either Accept / Decline. In this form, everything's still the same but we're saving User B the effort of having to manually get and type User A's email down as a collaborator. 

The next step (V2) would be to add email notifications so that, provided that User A and User B check their emails frequently, they can skip the step of having to notify each other above the stage of the request access process. User B gets an email giving them a heads up to approve User A's request, and User A gets an email giving them a heads up that User B has accepted their request.

The last step (V3) would be some form of notification system where even if User A and User B didn't check their emails, they would still be notified in-app.

**Comment by jaril** [comment]
Notes:
- [ ] Add support for storing collaborator requests in the database
- [ ] Add the frontend piece for the user to click on when they're locked out of a recording
- [ ] Hook up the graphql -> replit endpoint -> courier -> send collaborator request email
- [ ] Add an requests UI in the sharing modal

**Comment by jaril** [comment]
![image](https://user-images.githubusercontent.com/15959269/151458693-ebcb1968-5508-478c-9573-5789e9cf0847.png)

**Comment by jaril** [comment]
Requests are showing up in the modal now!

![image](https://user-images.githubusercontent.com/15959269/151466748-02f4fc67-ecef-4f0b-8114-be3b50df4fd6.png)

**Comment by jasonLaster** [comment]
Nice this is coming together!

**Comment by jaril** [comment]
![image](https://user-images.githubusercontent.com/15959269/151595118-43071430-cad0-442c-8380-9a5f4a2e3223.png)

Everything's wired up (minus the routing that I'll file a separate PR for just to keep this clean). Gonna do some quick testing and we're off to the races.
