### ISSUE TITLE
DevTools can take awhile to load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5063]
When we talked to Victor, the devtools panel took awhile to load. 

Here's what we saw:

1. The viewer opened quickly
2. The ViewToggle showed up quickly
3. Clicking the DevTools button transitioned quickly
4. The NonDev view seemed stuck and did not transition to the DevView quickly

**Comment by jasonLaster** [comment]
I took a look at artificially blocking our async imports and nothing held up the transition

```diff
diff --git a/src/devtools/client/debugger/src/components/App.js b/src/devtools/client/debugger/src/components/App.js
index 71049b01..505f103f 100644
--- a/src/devtools/client/debugger/src/components/App.js
+++ b/src/devtools/client/debugger/src/components/App.js
@@ -298,6 +298,7 @@ function DebuggerLoader(props) {
   useEffect(() => {
     (async () => {
       try {
+        await new Promise(r => setTimeout(r, 10_000));
         await waitForEditor();
         setLoadingEditor(false);
       } catch {
@@ -308,7 +309,11 @@ function DebuggerLoader(props) {
 
   return (
     <div className="debugger" ref={wrapperNode}>
-      {loadingEditor || loadingSettings ? null : (
+      {loadingEditor || loadingSettings ? (
+        <div>
+          <h1>Loading!!!!</h1>
+        </div>
+      ) : (
         <Debugger
           {...props}
           wrapper={wrapperNode.current}
diff --git a/src/devtools/client/webconsole/components/Input/JSTerm.js b/src/devtools/client/webconsole/components/Input/JSTerm.js
index cad8e524..ef48a017 100644
--- a/src/devtools/client/webconsole/components/Input/JSTerm.js
+++ b/src/devtools/client/webconsole/components/Input/JSTerm.js
@@ -15,9 +15,15 @@ import { getCommandHistory } from "../../selectors/messages";
 
 import clamp from "lodash/clamp";
 
+async function waitForEditor() {
+  await new Promise(r => setTimeout(r, 5_000));
+  const Editor = (await import("devtools/client/debugger/src/utils/editor/source-editor")).default;
+  return Editor;
+}
+
 async function createEditor({ execute, historyCursorUp, historyCursorDown }) {
   await gToolbox.startPanel("debugger");
-  const Editor = (await import("devtools/client/debugger/src/utils/editor/source-editor")).default;
+  const Editor = await waitForEditor();
 
   const editor = new Editor({
     autofocus: true,
diff --git a/src/ui/components/DevTools.tsx b/src/ui/components/DevTools.tsx
index 79ebb04c..4cb78ed7 100644
--- a/src/ui/components/DevTools.tsx
+++ b/src/ui/components/DevTools.tsx
@@ -15,7 +15,10 @@ import KeyboardShortcuts from "./KeyboardShortcuts";
 import { useUserIsAuthor } from "ui/hooks/users";
 import { CommandPaletteModal } from "./CommandPalette/CommandPaletteModal";
 
-const DevView = React.lazy(() => import("./Views/DevView"));
+const DevView = React.lazy(async () => {
+  await new Promise(r => setTimeout(r, 2_000));
+  return import("./Views/DevView");
+});
 
 type _DevToolsProps = PropsFromRedux & DevToolsProps;
 
@@ -54,10 +57,6 @@ function _DevTools({
   const { recording } = useGetRecording(recordingId);
   const { userIsAuthor, loading } = useUserIsAuthor();
 
-  useEffect(() => {
-    import("./Views/DevView");
-  }, []);
-
   useEffect(() => {
     if (loading) {
       return;
diff --git a/src/ui/components/Header/ViewToggle.tsx b/src/ui/components/Header/ViewToggle.tsx
index 723089ad..ef65d41a 100644
--- a/src/ui/components/Header/ViewToggle.tsx
+++ b/src/ui/components/Header/ViewToggle.tsx
@@ -47,6 +47,13 @@ function Handle({ text, mode, localViewMode, handleToggle, motion }: HandleProps
   );
 }
 
+async function loadFramer() {
+  console.log("load framer");
+  await new Promise(r => setTimeout(r, 15_000));
+  const framer = await import("framer-motion");
+  return framer;
+}
+
 function ViewToggle({
   viewMode,
   setViewMode,
@@ -60,10 +67,9 @@ function ViewToggle({
   const [framerMotion, setFramerMotion] = useState<typeof import("framer-motion") | null>(null);
   const [localViewMode, setLocalViewMode] = useState(viewMode);
   const toggleTimeoutKey = useRef<NodeJS.Timeout | null>(null);
-  const preloadPromise = useRef<Promise<typeof import("../Views/DevView")> | null>(null);
 
   useEffect(() => {
-    import("framer-motion").then(framerMotion => setFramerMotion(framerMotion));
+    loadFramer().then(framerMotion => setFramerMotion(framerMotion));
   }, []);
 
   useEffect(() => {
```

**Comment by jasonLaster** [comment]
@abstractalgo just assigned you and moved it to the current sprint. This issue has hit me several times this week and can easily be affecting users as well.

**Comment by jasonLaster** [comment]
https://sentry.io/organizations/replay/issues/3016733821/?project=5399075&query=is%3Aunresolved&sort=freq&statsPeriod=7d

**Comment by abstractalgo** [comment]
related: https://github.com/RecordReplay/customer-support/issues/31

**Comment by jasonLaster** [comment]
@abstractalgo Yes, but the important thing here is that when you click the DevTools button you should transition to the devtools view instantly. For some reason, this occasionally takes 5-30 seconds. That's why i think it might be a networking issue

**Comment by jcmorrow** [comment]
I've looked into this issue when I've seen it locally and, at least during the times I've attempted to diagnose it, it has only been reproducible in chrome, never in Replay, which I found odd.

**Comment by jasonLaster** [comment]
Yep - same

**Comment by jcmorrow** [comment]
I am relatively certain after playing with this over the past two days that the console is the worst culprit here. When I have a recording that is slow to switch from Viewer -> DevTools the console is always the current secondary pane and there are always a lot of console statements. If I switch to the network monitor and do the toggle again it is smooth. Likewise with dragging the window to resize it - if the console if open with a couple of hundred messages it moves in fits and starts - with the network monitor open it is smooth.

https://www.loom.com/share/c71246666cf84fd3b0ac6e40f755ac36

**Comment by jasonLaster** [comment]
ooh - this is an insight that I believe @jcmorrow

**Comment by jcmorrow** [comment]
> ooh - this is an insight that I believe @jcmorrow

Are you implying that my other insights are *un*believably good? 🙃

**Comment by abstractalgo** [comment]
See the aforementioned PR for some of the things that have been considered so far.

It was noticed that loading is split into ~4 phases: initial page load and hydration, then a bunch of very small and sparse tasks (unknown atm in their origin/purpose) taking a few seconds, then a lot of UI rendering, and then again sparse small tasks. It seems that there is a huge potential for improvements as nor CPU nor GPU are utilised as much as they could be, yet no clear indication that we're simply waiting for some other async task (e.g. networking). Utilizing CPU to the fullest and even parallelizing work in multiple threads could spell huge wins in the future.

**Comment by jasonLaster** [comment]
closing since Jaril's improvements on friday to toggling view modes is a significant improvement. there's a good chance that there are still some lingering issues that will come up at which point we can open new more targeted issues. The important thing is that the new work is significant enough that much of this analysis is now stale.

**Comment by abstractalgo** [comment]
This was something that I passed onto Jaril on Friday as something that could be improved, good to see it implemented. 🚀

**Comment by jaril** [comment]
> closing since Jaril's improvements on friday to toggling view modes is a significant improvement. there's a good chance that there are still some lingering issues that will come up at which point we can open new more targeted issues. The important thing is that the new work is significant enough that much of this analysis is now stale.

I've only finished a small chunk (layout modes) bit of it. There's still a handful:

```
perf for codemirror/tiptap: https://github.com/RecordReplay/devtools/issues/6033
general performance: https://github.com/RecordReplay/devtools/issues/5063#issuecomment-1084928347
```

Will slowly chip away at it. Or maybe not so slowly. Thanks @abstractalgo!
