### ISSUE TITLE
Variable is incorrectly shown as optimized away

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5068]
`currentURL` is reported as optimized away when the generated variable is available. This feels like it should not happen because optimized away is an engine term.

STR:
* go to [replay](https://app.replay.io/recording/title-swapping-repeatedly--686c2dcf-5bd0-4d71-8689-bee99bc70dda?point=15901409131543364137135189719515406&time=6789.914182386863&hasFrames=true)
* click on the comment
* evaluate `currentURL`

**Comment by hbenl** [comment]
This is actually a good example where "optimized away" is correct:
Original source:
![Screenshot_2022-02-02_13-44-00](https://user-images.githubusercontent.com/16060807/152156732-c521f0e0-379c-41f0-9f4e-c3e76a2d29fe.png)

Generated source:
![Screenshot_2022-02-02_13-44-38](https://user-images.githubusercontent.com/16060807/152156746-bdbb43bc-a593-4eeb-ac42-a79fc12ec7e1.png)

When I follow the STRs I get:
![Screenshot_2022-02-02_13-46-11](https://user-images.githubusercontent.com/16060807/152156755-65d89844-fbe5-4483-8cf1-34f72617ef61.png)

**Comment by jasonLaster** [comment]
hmm - should we have a more descriptive message like. `Not defined`?
