### ISSUE TITLE
EventListeners fals with empty frameLocation

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5088]
**Description:**

STR:
1. select event listeners
2. refresh the page

Replay crashes with a type error

https://app.replay.io/recording/eventlisteners-crash--e72af74c-3915-4abd-aa68-b97a9a6dc22a

<img width="278" alt="Screen Shot 2022-01-24 at 9 21 04 AM" src="https://user-images.githubusercontent.com/254562/150837436-38893a0b-0b60-424f-b37e-6fab40983535.png">

**Comment by abstractalgo** [comment]
Addressed by https://github.com/RecordReplay/devtools/pull/5091.
