### ISSUE TITLE
When adding a comment fails, the comment should not be lost

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5090]
I am not 100% sure what went wrong in the Replay below, so reproducing will require forcing a GraphQL error on adding a comment (which is not too difficult, just leave off a field or something). The important bit here is that in general, when mutations fail, we should recover gracefully. For comments, that means restoring the editor to its previous state, with a message that the save failed.

Replay: https://app.replay.io/recording/replay-comment-disappears--0137cc40-50d6-448a-bf52-06329986b013?point=39266745007963963191169002128804199&time=15729&hasFrames=false

**Comment by jasonLaster** [comment]
here's a replay with th repro

https://app.replay.io/recording/stubhub-expired-listing--b29bb7ab-a072-4f34-90fa-1b8d6104a501
