### ISSUE TITLE
iframe's children do not load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5097]
This example's iframe children do not load.

[original replay ](https://app.replay.io/recording/masonry-imagesloaded-callback--f2101d68-1b47-4728-b6ab-a9673536a556?point=9735556610279774553134359805690725&time=4218&hasFrames=false)
[replay of the issue](https://app.replay.io/recording/iframe-children-do-not-load--e6eafe63-a2b8-4c41-bf1a-1f258698b399)

**Comment by hbenl** [comment]
This happens because there's some whitespace between the opening and closing tags of the iframe, see RecordReplay/backend#4325.

**Comment by abstractalgo** [comment]
Can we close this, @hbenl (since https://github.com/RecordReplay/backend/issues/4325)?
Then https://github.com/RecordReplay/ops/issues/223 can also be closed.

**Comment by hbenl** [comment]
@abstractalgo Thanks, I overlooked this.
