### ISSUE TITLE
Network Monitor - Stack trace framework groups

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5107]
(Created from the [Replay Roadmap Airtable](https://airtable.com/appSzSiRS6UdFlXKj/tblpTtDTV98hPX4m0/viwyIRSTFuDV9bzCx?blocks=hide))

**Comment by jaril** [comment]
Need more info. Is this about our framework groups in the debugger call stack specifically, or network monitor? Or react devtools?

@jasonLaster @abstractalgo

**Comment by jasonLaster** [comment]
Yep - the net monitor stack trace should be able to show framework groups in the same way the debugger and console can
