### ISSUE TITLE
setTimeout events show as blank in the console

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#5112]
**Description:**

When viewing this replay, selecting 'setTimeout fired' events in the Console settings adds rows for the events and the line of code, but the row is blank.

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
![Screen Shot 2022-01-25 at 3 30 02 PM](https://user-images.githubusercontent.com/40367173/151054890-971504c5-f72e-4791-8132-9be84f48f390.png)

* Video (Loom):
* Replay:

https://app.replay.io/recording/replay-demo--44d33115-6be1-4fb7-95d9-26c83f008568

**Comment by jaril** [comment]
Related to #5577.
