### ISSUE TITLE
Loom video attached to comment does not play

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#5113]
**Description:**
The video will add but when clicking on it to play, in Chrome I get a "this content is blocked" popup, and in the Replay browser the screen just dims but there's no error.

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:

Screenshot from Chrome Version 97.0.4692.99 (Official Build) (arm64)

![Screen Shot 2022-01-25 at 3 43 47 PM](https://user-images.githubusercontent.com/40367173/151056843-7b247436-0886-463e-81cd-9f2ac4f5fd8d.png)

* Video (Loom):
* Replay:

https://app.replay.io/recording/loom-comment-attachment-video-replay-not-working--d11ea290-abbf-498f-bd66-807c8d59a05d

**Comment by jaril** [comment]
The error:
![image](https://user-images.githubusercontent.com/15959269/152036960-df67cbff-caf5-459f-91c2-6401c255d5be.png)
