### ISSUE TITLE
[Replay] Browser can't connect for a user

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#513]
Replay can't connect for one user. It connects for me though.

<img width="678" alt="Screen Shot 2020-08-26 at 5 23 09 PM" src="https://user-images.githubusercontent.com/254562/91369520-d4e90700-e7c0-11ea-8b84-c3feb94e5d4c.png">

**Comment by jasonLaster** [comment]
It's likely a VPN issue

**Comment by hemanth** [comment]
Seeing the same in with VPN turned off.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/18315/91375976-e5a17900-e7d0-11ea-90aa-a7794d7ef7b2.png">

The below, works in the browser.

```js
const ws =  new WebSocket('wss://dispatch.replay.io/');
ws.onmessage = msg => console.log(msg.data);
ws.onopen =  () => ws.send("{}");
```

**Comment by jasonLaster** [comment]
This works for me in Replay

<img width="741" alt="Screen Shot 2020-08-26 at 7 20 09 PM" src="https://user-images.githubusercontent.com/254562/91376113-3add8a80-e7d1-11ea-92b0-99fbbaa7a136.png">

**Comment by hemanth** [comment]
Interesting! I do see:

![image](https://user-images.githubusercontent.com/18315/91376212-711b0a00-e7d1-11ea-8f60-d1edc679b8a5.png)

**Comment by hemanth** [comment]
Ah, ha!

I noticed a `MOZILLA_PKIX_ERROR_MITM_DETECTED`

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/18315/91376345-b50e0f00-e7d1-11ea-9025-cc2fbd586481.png">

**Comment by hemanth** [comment]
Found a workaround! YAY!

With the below, I was able [record](https://replay.io/view?id=eac418ff-0314-4daf-be02-2253acc12d3d).

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/18315/91376563-31a0ed80-e7d2-11ea-9438-7e8ca428f1ea.png">

**Comment by jasonLaster** [comment]
Just to summarize the issue:

When Replay tried to talk to `dispatch.replay.io` it got a `MOZILLA_PKIX_ERROR_MITM_DETECTED` error. 

By enabling `security.enterprise_roots.enabled` @hemanth was about to save the recording, but could not view it.

**Comment by jasonLaster** [comment]
Interestingly, i did a quick search and found MOZILLA_PKIX_ERROR_MITM_DETECTED in a couple of places https://searchfox.org/mozilla-central/search?q=MOZILLA_PKIX_ERROR_MITM_DETECTED&path=
