### ISSUE TITLE
Click events show in Replay Browser but not in Chrome

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#5135]
**Description:**

When viewing [this replay](https://app.replay.io/recording/replay-demo--44d33115-6be1-4fb7-95d9-26c83f008568?point=18173039004872523889155243277025745&time=7496&hasFrames=false#) in Chrome, the click events do not appear in the console settings. The marker moves in the console but it doesn't give the option to show the actual click event.

In the Replay Browser, the click event are shown in the console settings and I can see the output.

**Steps to Reproduce:**

View https://app.replay.io/recording/replay-demo--44d33115-6be1-4fb7-95d9-26c83f008568?point=18173039004872523889155243277025745&time=7496&hasFrames=false# in Chrome and Replay Browser.

**Expected Result:**

**Additional Context:**

### Chrome Version 97.0.4692.99 (Official Build) (arm64)

* Screenshots:
![Screen Shot 2022-01-27 at 10 28 50 AM](https://user-images.githubusercontent.com/40367173/151390235-926f33af-9f95-40fa-9f1d-f0aafc205c2f.png)

### Replay Build macOS-gecko-20220124-1f52ea6ae2d4-aa7c4dd3e9cf (64-bit)

![Screen Shot 2022-01-27 at 10 28 31 AM](https://user-images.githubusercontent.com/40367173/151390261-3eb0101d-e92c-4b3b-9e51-8dcda5f8771b.png)

* Video (Loom):
* Replay:

**Comment by hbenl** [comment]
I don't think it's related to performance since this is a small recording that loads fast. But it's definitely intermittent, I couldn't reproduce it.

**Comment by ceceliacreates** [comment]
I just checked again and it's working now. so might have just been something going on that day? I think it's okay to close since it appears to be resolved.
