### ISSUE TITLE
Replay DevTools take awhile to load

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5139]
**Description:**

The Devtools take awhile to load for heavy sites

https://app.replay.io/recording/f5f9e962-5612-422f-ac8e-cc756e6c96e1
https://app.replay.io/recording/devtools-takes-awhile-to-load-2--1c3f91eb-dfe2-4add-a45e-ef7172d53a61

**Comment by jasonLaster** [comment]
https://www.loom.com/share/b6df9d99f41543b583ce1a0820759354

**Comment by jaril** [comment]
Closed in favor of #5063.
