### ISSUE TITLE
Adding a comment or reply flickers

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#5174]
Comment: https://app.replay.io/recording/comment-flicker--e0349d8d-18e9-4695-86a4-a220916d6122
Reply: https://app.replay.io/recording/reply-flicker--7a67acb7-3d2f-47d5-ae75-6c8ced779298

**Comment by jasonLaster** [comment]
Thanks - i've been meaning to file this since it is so visible.

**Comment by jasonLaster** [comment]
closing since this is stale
