### ISSUE TITLE
Replay Check-in component

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5186]
**Background**  
We'd like more signal about how well Replays are solving our users' needs.

**Initial insights**   
Check out [this Discord conversation](https://discord.com/channels/779097926135054346/937458413355532288) where I link to this initial video:
https://user-images.githubusercontent.com/9154902/151868701-40082893-c3c3-492d-9329-242656428b6b.mp4

Key insights/goals:
* The feature needs to benefit the user in a tangible way
*  Asking "how is Replay doing?" isn't super valuable to people
* But "mark as resolved" is a common pattern that can benefit users

**Design proposal**
By using a simple label at the top part of Replay Info, we can provide valuable information while feeling part of the UI:
![image](https://user-images.githubusercontent.com/9154902/151869024-dc6cf23a-0d8d-4222-b6fd-cd33e00b1299.png)

There could be a few options like so:
![image](https://user-images.githubusercontent.com/9154902/151869252-99d363c2-610c-430a-b02e-e6e649258a45.png)

Confetti can sprinkle down when you set something to active:
![image](https://user-images.githubusercontent.com/9154902/151869736-2f10d715-6ce5-42c5-86df-a460373220ec.png)

And after selecting, it can look like this:
![image](https://user-images.githubusercontent.com/9154902/151869312-aa41360d-0692-42bc-8a2d-a7e7c32f9c00.png)

Then the library could look like this:
![image](https://user-images.githubusercontent.com/9154902/151869788-9230b441-bef7-4304-8ee4-754f80f8eaf9.png)

**Status**
Jon's been working [on this branch](https://github.com/jonbell-lot23/devtools/tree/replay-checkin)

Working:
* Confetti animation is looking good
* Dropdown options are coming along

Needs work:
* The dropdown needs to be in the top header of the accordian
* We need to wire it up to track "status" as a property
* We need to make the confetti animation work, not sure how

**Comment by jcmorrow** [comment]
Nice. I think there's also something about like, turning this replay into an Issue/PR/Card somewhere that feels likely relevant? Because in many ways Replay doesn't help you *resolve* your problem, it helps you *define* your problem, and the output of that is some artifact about *how* to resolve it. I don't know if that makes sense or not?

**Comment by jonbell-lot23** [comment]
Thanks for the help today, @jcmorrow ! Here's a quick loom showing how things are working so far:
https://www.loom.com/share/460a787337f0433798376eff2181e73b

@jaril I think we're at a place to start thinking about stuff I don't know how to do:

* Putting this in the top header of the accordion
* Swapping out the colour when you select a new item
* And of course connecting it to the back-end

**Comment by jonbell-lot23** [comment]
Good morning @jaril ! Pinging you so we can discuss this today

**Comment by jaril** [comment]
Tracking the ongoing work here:
- [ ] Frontend: https://github.com/RecordReplay/devtools/pull/5309
- [ ] Backend: https://github.com/RecordReplay/backend/pull/4617

**Comment by jaril** [comment]
https://user-images.githubusercontent.com/15959269/160508009-e6701954-8380-4cb1-8e6b-06399f886907.mov
