### ISSUE TITLE
Can't replay a replay

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#5193]
* Replay: https://app.replay.io/recording/xstate-visualizer--a86b7b44-0548-4378-a65f-04b1af240ce7

I've recorded a replay but now I can't replay it cause it ends up crashing at the initialization time with:
<img width="428" alt="Screenshot 2022-02-01 at 14 43 58" src="https://user-images.githubusercontent.com/9800850/151979511-04362424-c4c8-4efb-9039-ca63d9257fa9.png">

**Comment by bhackett1024** [comment]
Hi, looking at the backend crash report it looks like you're hitting an issue which should be fixed in the latest release.  Can you try updating the browser and creating a new recording?

**Comment by Andarist** [comment]
It works now, thanks for taking a look and sorry for wasting your time

**Comment by bhackett1024** [comment]
No problem, I'm hoping before too long we'll be able to surface this information better when replaying fails and be able to give more useful suggestions based on the error which occurred.
