### ISSUE TITLE
Delay viewMode change to allow for toggle animation when changing mode from command palette

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#5202]
> That's fair. I would have expected the toggle to not animate if using the command palette.

It looks like this happens because we adjust localViewMode when it is out of sync with viewMode. This triggers a refresh of the ViewToggle, which animates to align with the viewMode when it is updated elsewhere. (Added a comment in the replay where this occurs).

Because the ViewToggle animation is reactive to the viewMode change, it will always happen after the layout has already updated. 

I made the changes to fix the sidebar, but will create a separate issue for the toggle animation timing issue.

I believe a potential fix would be to change `localViewMode` to `toggleViewMode` that is tracked in Redux instead of locally. Then, when the setViewMode function is called, we would update `toggleViewMode` to trigger the animation, have a setTimeout to allow for the animation, then move forward with dispatching the `selectedPrimaryPanel` and `viewMode` updates. We'd want to ensure `toggleViewMode` is only ever updated in the same function as `viewMode` to keep them in sync. Not sure if this is the best approach though.

_Originally posted by @ceceliacreates in https://github.com/RecordReplay/devtools/issues/4939#issuecomment-1027261238_

**Comment by jaril** [comment]
Yep. Solid assessment of the tricky part!

**Comment by jaril** [comment]
@ceceliacreates still wanna work on this one?

**Comment by ceceliacreates** [comment]
@jaril Ah yes! This one got lost in the shuffle. Unless you're already in the area, I can set aside time to knock out this week.
