### ISSUE TITLE
Dropdowns in the team modal have transparent backgrounds

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5216]
Looks like something messed with the styling?

![image](https://user-images.githubusercontent.com/15959269/152257915-cc2e04d3-e739-47b5-a922-3cc7bb62ebe3.png)

**Comment by gideonred** [comment]
Replay: https://app.replay.io/recording/devtools5216--9c6fb562-940f-4cac-ac5b-f14836bea7a3
