### ISSUE TITLE
Enforce the backend's 200 hit limit on analysis results

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5222]
The backend limits full analysis results to 200, but we still allow users to perform actions that lead straight to that error.

This limit only applies to more complex expressions (e.g. `console.log(">>", window)`). This doesn't apply to an expression that only has primitives, like our default expression (e.g. `console.log(123, "runScript")`).

We should disable editing the default expression if there's more than 200 hits for that location. We had this check in place before, but it seems to have regressed.

AND write a QA wolf test for it :).

**Comment by jaril** [comment]
@jonbell-lot23 sticking your head on this for now until we dig up the designs from figma!

**Comment by jasonLaster** [comment]
We should also limit console events that are 200+

We could also implement paging to get the first 200

**Comment by jaril** [comment]
events: 
- cap the hit count to `200+` instead of 201 or 1k
- clicking on `200+`, disable checkbox, then tooltip
