### ISSUE TITLE
If paints are available before the rest of basic processing, DevTools should load the viewer

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5239]
Once https://github.com/RecordReplay/backend/pull/4460 is landed (🤞 soon), the backend will be capable of delivering paints in a separate process from the rest of basic processing. We'll need to be able to detect that scenario, and make the viewer available.

**Comment by jasonLaster** [comment]
@jcmorrow I think Brian's comment here is a great blueprint
https://github.com/RecordReplay/backend/issues/4320#issuecomment-1030697004
