### ISSUE TITLE
Editor's "node" button should highlight a node in Viewer

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5255]
A report from a user:

> this "target" icon (in the console) doesn't highlight the node on the canvas, perhaps this is hard to do as maybe u dont have immediate access to this info, but when i click on this and I get to the Elements panel (which loads rather slow and "unfolds" itself in multiple steps, so the loading sequence is somewhat distracting for me) then highlighting works when done from the Elements panel, but this icon still has no effect on the highlight
>
> <img src="https://user-images.githubusercontent.com/1355455/152988115-aec1e132-0e46-4bb1-8906-a85d00b935e2.png" width="400" />
>
> also - clicking on this target icon rewinds me to some point in the debugger
> right now I got rewinded to some rather random place:
> 
> <img src="https://user-images.githubusercontent.com/1355455/152988150-48a2092b-b26a-4562-8a49-5ba7b31eda1f.png" width="400" />
> 
> but either way... ideally, i dont want this click to change the state of my debugging session, im just poking around, gathering intel etc, I've just wanted to know what got clicked and i didnt mean to jump anywhere in the debugger itself

**Comment by jasonLaster** [comment]
@hbenl that's a great point. The easiest thing to do would be to hide the button if it's at a different point. We can do fancier stuff later :)
