### ISSUE TITLE
Source tree has empty directories

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5265]
This is probably because of the new URL parsing that we're doing. It would be nice to try and be consistent with what chrome is doing

[Replay of bug](https://app.replay.io/recording/climatescape-saf--041cda01-595d-4a80-ab1e-7e954d689c4a)
[Replay of str](https://app.replay.io/recording/climatescape-saf--822770aa-bd50-4cfe-967c-5810d5f9ac13?point=5516815412802996492690084948084126&time=3699.614147909968&hasFrames=true)

**Comment by jaril** [comment]
@hbenl mind taking this??

**Comment by jasonLaster** [comment]
will go on record saying i think we want to special case some of these since` webpack:///<>` is a little non standard
