### ISSUE TITLE
:bug: on DevTools - Give access to anyone with domain ema...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5283]
:bug: on DevTools - Give access to anyone with domain email address not adding team to invited member
• Check give access to anyone with a <http://qawolf.com|qawolf.com> email address on team owner account
• Log in with user with <http://qawolf.com|qawolf.com> email address and go to invite link
• Expect new team to be in the left menu
• Actual is that no new team added to invited member with <http://qawolf.com|qawolf.com> email \- [Chris](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1644522175794339)

**Comment by jaril** [comment]
This appears to have been caused by the same thing as #5288. Now that that's fixed this should be ready to close soon as well. Will close once qawolf confirms.

**Comment by jaril** [comment]
Nevermind it looks like it's because there's a hardcoded URL.

https://www.qawolf.com/test/ckxi2jo1d000109jk7bw3egrq

**Comment by jaril** [comment]
All fixed!
