### ISSUE TITLE
Files open in replay X also open in replay Y (when from same domain)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5285]
**Reported by @Andarist:**

"Open files "leaking" between replays are kinda annoying to me. I mostly debug the same app, but with different recordings and if I open files F1 and F2 in the recording R1 then they are also open in R2."

**Steps to repro**

1. Record a replay on domain x -- name it replay 1
2. Record a second replay on domain x -- name it replay 2
3. Open some files on replay 1
4. Launch replay 2

**Expected**

Replay 2 should be a completely fresh replay, not affected at all by whatever was opened in replay 1

**Actual**

@Andarist is reporting that replay 2 is seeing files he opened in replay 1.

**Comment by jaril** [comment]
Replay of the replay app opening with some tabs stored in memory:

https://app.replay.io/recording/tab-memory--358151fc-47af-4d76-8edf-c8cb72c88063
