### ISSUE TITLE
:bug: on DevTools - Invalid invite link error
• Copying a...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5288]
:bug: on DevTools - Invalid invite link error
• Copying and navigating to link produces error
• Old link: _<https://app.replay.io/?invitationcode=6b8700c0-58e8-437a-9c2f-112cc51bf6c8>_
• New link that fails: <https://app.replay.io/team/invitation/6b8700c0-58e8-437a-9c2f-112cc51bf6c8> \- [Chris](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1644532603370279)

**Comment by jaril** [comment]
This should be fixed by #5289. Will alert on deploy.

**Comment by jaril** [comment]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/15959269/153622656-cebe0cc7-b056-4c03-af1c-7568f33774e1.png">
