### ISSUE TITLE
[Timeline] The loading status of the timeline gets cleared from both ends

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#529]
I haven't been able to get a recording but I've noticed that sometimes when a recording's timeline is being loaded, the greyed out timeline gets cleared from both ends, often unevenly.

Instead of:
```
-------------------------       -------------------------       -------------------------
grey grey grey grey grey   =>   blue blue blue grey grey   =>   blue blue blue blue blue
-------------------------       -------------------------       -------------------------
```
It goes:
```
-------------------------       -------------------------       -------------------------
grey grey grey grey grey   =>   blue blue grey grey blue   =>   blue blue blue blue blue
-------------------------       -------------------------       -------------------------
```

Is this intentional?

**Comment by bhackett1024** [comment]
Yeah, this is intentional.  The grayed out sections of the timeline indicate areas that haven't been fully processed by the backend.  Because the backend processes different parts of the recording in parallel, they can finish out of order.
