### ISSUE TITLE
:bug: on PR `jm-source-loading` (https://github.com/Recor...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5296]
:bug: on PR `jm-source-loading` (<https://github.com/RecordReplay/devtools/commit/e4be1dad2ef1befb4c3f3905dd994c4ca4b7e19e|e4be1da>): Source files are not loading in DevTools
<https://www.qawolf.com/suites/ckziq5oiv12648750lt1y5te4i5?status=fail|These tests> are affected \- [Chris](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1644610082103959)

**Comment by jcmorrow** [comment]
@jperl here's what I see when I click that link:
![CleanShot 2022-02-11 at 19 17 51](https://user-images.githubusercontent.com/5903784/153694727-9256b007-60e3-4cce-a909-908a19bee823.png)

**Comment by jcmorrow** [comment]
I'm 99% sure this is solved? At least, I haven't seen the test fail at all recently.
