### ISSUE TITLE
Nebula overlapping devtools in certain loading states?

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5300]
![CleanShot 2022-02-11 at 19 16 15](https://user-images.githubusercontent.com/5903784/153694752-6f804820-130b-4c25-827f-5cb28005970d.png)

This has been happening with the many-sources replay that I've been trying to diagnose.

**Comment by jcmorrow** [comment]
https://app.replay.io/recording/showing-the-lessloadingscreengreater-loads-nebulas--5f6c6422-73db-4864-a50e-fedd00841943#

**Comment by jaril** [comment]
Looks like the problem here was because you passed in a `notARealSlice`, which the WaitForReduxSlice component never sees in the state so it ends up rendering the loading screen improperly.

Tbh not sure why this is a component this feels like it should be a hook.

**Comment by jaril** [comment]
@ceceliacreates if you're looking for fun bugs that were resolved using a replay this was a pretty dang good one!
