### ISSUE TITLE
Recording Item menu in Library is sometimes missing

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#5332]
Reports that some node recordings in the team do not have a menu to delete the recording.

**Comment by jaril** [comment]
I've got some suspicions. Got a recording ID?

**Comment by jaril** [comment]
We hide the recording item menu in the library when the user is not the owner of the recording. We should expand that to make it so that in the case of workspace api-key recordings, the check falls back to whether the user is part of that workspace.
