### ISSUE TITLE
More informative error messages when internals fail

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5343]
While discussing session creation failures, it was noticed that it can happen that the only information we receive from `@recordreplay/protocol` lib is something along the lines "Internal error", that we then display simply as "Unexpected session error Internal error", which is not super useful.

Adding more (meta) information about what went wrong, either on the frontend or in the protocol library itself would be much better and help triage issues with more precision.

**Comment by gideonred** [comment]
Usually when reporting an error back it's important to report if it is a dependency that failed or if it is an internal failure.

My understanding of what's happening here is that the frontend (devtools) is talking to an agent over a websocket using the recordreplay/protocol library. That library reported back to the frontend that the person you're talking to (the agent) is return Internal errors. So, it would be nice if the devtools then sent to Honeycomb "Failure talking to backing/agent, getting "Internal Error"".

**Comment by gideonred** [comment]
> I'm not sure if the frontend should be sending this event to honeycomb. Internal Errors occur in the backend so it should probably be emitted there. Additionally, the frontend should not know about the backend's internals. Things like the Agent are not in the frontend's perview

Assume the following scenario:
- Service A is doing a thing and needs to ask Service B for something
- Service B reports back "Internal Error".

In this case I expect two Honeycomb metrics: 
- One from Service A saying Service B is giving it problems, 
- and then another from Service B reporting that it's running into problems (with hopefully more info). 

We have both report the problem to be defensive and allow a person debugging to go through a process of elimination to figure out the source of the problem.

In our current case Service A (devtools) is reporting "internal error" which would make someone (like myself) not familiar with the devtools conclude it's an issue in Service A (devtools) which is far from the truth.

**Comment by jasonLaster** [comment]
Where are we reporting internal errors from devtools? maybe that's where i'm confused...

This change is user facing https://github.com/RecordReplay/devtools/pull/5315 but notice how we have more descriptive errors now.

**Comment by gideonred** [comment]
I assumed this is coming from Devtools, as it states it's Devtools running  into errors?

https://ui.honeycomb.io/replay/datasets/backend/result/cqxeWMDQqwh/a/hHDNL2KspS4

**Comment by gideonred** [comment]
Actually, here's the above honeycomb query with better where:

https://ui.honeycomb.io/replay/datasets/backend/result/Jq8sZRxLgPq/a/hHDNL2KspS4?tab=raw

**Comment by loganfsmyth** [comment]
In theory right now we try to have this `err.data.internalCode` on errors: https://github.com/RecordReplay/backend/blob/29d08aa09bb7f1500df4d951298456a19e0a7f87/src/protocol/socket.ts#L299

But that said with all the new changes for multiple controllers and pipe errors around, that probably isn't getting set consistently anymore, so fixing that is one project we could do.

Ideally we'd stop keep InternalError to a minimum in favor of explicit error codes, so we should fix up that `internalCode` stuff so we can at least look up what happened if the frontend _does_ get an InternalError, then we can start fixing up the backend code to get a sense for why the internal errors are happening.

**Comment by abstractalgo** [comment]
Moved to the `backend` issue for now as it's a prerequisite.
