### ISSUE TITLE
"No sourcemaps found" shown even if there are sourcemaps

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#5345]
If you look at the source of a bundle while _not_ being paused in that source, Replay shows:
![Screenshot_2022-02-17_18-48-54](https://user-images.githubusercontent.com/16060807/154540738-552e8771-521f-453b-bdea-b199cebf18f2.png)
But this is not necessarily the case: the issue is that there are many original sources associated with a bundle and we don't know which one you're interested in, so we can't select an alternate source.

**Comment by jasonLaster** [comment]
@hbenl good find. I think it is okay in these cases to link to the first alternate source. Users can find the others in the source tree or pause in another. Down the line, we can provide a more sophisticated context menu too
