### ISSUE TITLE
Inviting users to an expired team fails silently

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#5346]
GraphQL throws an error but we don't message the user

**Comment by jasonLaster** [comment]
oh no! filing as a P1

**Comment by gideonred** [comment]
FYI, going forward for SOC2 I've defined P1 as an ongoing outage with customer impact that needs to be resolved immediately (I picked P1 as that was using somewhat existing labels).

I assume @jasonLaster  you meant this is an item we should work on soon, not an item that we should all jump on call and mitigate immediately.

@jasonLaster happy to sync up on how we can distinguish between the priority of a ticket and the severity of a ticket.
