### ISSUE TITLE
Start building dark mode

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5347]
**Background**
We're not going to push out one giant dark theme PR at once, we're going to move in two steps to give us time to test in production. This ticket represents step one: get dark theme 90% of the way there and push an "invisible" release once we make sure light mode hasn't been affected.

Follow along in my journal here:
https://www.notion.so/replayio/Dark-mode-journal-7ba34d337a1645aeb439d1ca38eb834c

**Dragan's suggested steps for this PR**
- [x] determine tokens that can be shared between different themes
- [x] structure the design system accordingly (either with tokens in plan JS/TS files, or CSS files, or via Tailwind config)
- [x] specify colors for light and dark themes accordingly
- [x] determine and specify tokens for other design tokens (not just colors; e.g. border-width, text size, spacing,...)

**Items we're addressing in a follow-up PR**
- [ ] Fix remaining 10% of polish items
- [ ] Add dark theme to settings
- [ ] Purge unused tokens from components and general design system

**Looms showing Jon testing the visuals**
[Checking light theme](https://www.loom.com/share/d3e2cc83460a4e1fa03891e4b9b2845d)
[Checking dark theme](https://www.loom.com/share/2f8a4367a9bf4c1cb6a277aece41d495)

**Comment by jonbell-lot23** [comment]
Hey @abstractalgo thanks for these comments! Going to add some replies in the interest of aligning perspectives and documenting it.

Item #1 (determine tokens) has always been done, and this work is adding on top of that.
Item #2 (structure accordingly) also has a system, and we'll be adding on top of that.
Item #3 (specify colours) is the meat of the work
Item #4 (purge unused) brings up a philosophical thing. I am removing tokens as I go, but I'd also make this its own clean-up task.
Item #5 (use other tokens) -- yup, we've done this before and that work is continuing here.

What I'm envisioning for this change is that I post a good "first draft" into production. As you said on Discord, that change should be pretty invisible. But putting it into production means we have a good starting point to build from. I'd like to post this once I get some obvious issues done, like net monitor.

At that point, having this work ready to go in the background means that it'd be easier to split out tasks. For example, maybe someone wants to take on elements panel and someone else wants to work on net monitor.

So I'm thinking of pushing things out iteratively and invisibly rather than all at once. Wanted to share my thinking so we're on the same page!

**Comment by jaril** [comment]
Continued in #5423 so closing.
