### ISSUE TITLE
Source  Map Visualizer adjustments

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5377]
- [ ] Update the Header
- [ ] Style the select box (https://headlessui.dev/react/listbox)
- [ ] Use a material icon for the link

**Comment by abstractalgo** [comment]
Also:
- [ ] hide "Visualize sourcemap" button when there is no sourcemap

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1355455/154773423-fc5a86fc-ea2e-4dbb-bb39-e3083bd87639.png">

**Comment by jaril** [comment]
@jasonLaster mind checking if these already had been covered?
