### ISSUE TITLE
Control-F too subtle

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5394]

**Comment by jaril** [comment]
@jonbell-lot23 more details?

**Comment by jonbell-lot23** [comment]
It was come feedback from Jason at Glide. Says when he hits control-F in the editor, his eye doesn’t see the textfield that appears.

**Comment by jcmorrow** [comment]
Also it's generally hard to know if `cmd-F` will open the browser or the text editor find window. Likewise with where arrow-keys/spacebar are directed (text field, console bar, playback controls)

**Comment by jonbell-lot23** [comment]
Note while tagging tickets:

I'm not convinced cmf-F's screen needs a ton of rework, but @jcmorrow 's point about keyboard navigation is a meaty and important issue.
