### ISSUE TITLE
"Visualise sourcemap" link shouldn't appear if there are no source maps

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5396]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/9154902/154828773-c2687338-34c2-4059-9991-83f264d497a5.png">

**Comment by hbenl** [comment]
This is already implemented. The reason for the confusion is the "No sourcemaps found" claim which is wrong, see #5345

**Comment by jonbell-lot23** [comment]
We may still have a bug. This Replay has no sourcemaps, yet shows the "visualise sourcemaps" link:
https://app.replay.io/recording/flicker-bug--7703cce9-ece6-4a58-9737-2d3049ab39c2?point=4218741197564930438686037636022395&time=1583&hasFrames=false#
