### ISSUE TITLE
Support searching in excluded files

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5418]
The full text search feature is confusing when trying to search in sources that are excluded from the search.

STR:

1. Visit https://app.replay.io/recording/6d4337b7-95d5-4a8a-a795-c85b0b497718
2. Search in all files for "onTestFileStart" or anything else which appears in the recording's javascript.

Actual results: No results are returned.

The problem here is that the devtools are excluding almost all of the sources in this recording from searching, I think because they are in a node_modules folder. The devtools should support searching in all the recording's sources (maybe using a checkbox), or at least indicate that it isn't actually going to search through all the sources.

**Comment by jasonLaster** [comment]
Good call.  We can either do a checkbox or support VS Code style include/exclude paths


I bet this will be related to this issue as well https://github.com/RecordReplay/customer-support/issues/32

**Comment by jasonLaster** [comment]
First pass based on VS Code

![Frame 1 (2)](https://user-images.githubusercontent.com/254562/156394761-161dc1aa-73a9-4110-bdbc-7dd5a8628eed.png)

**Comment by jonbell-lot23** [comment]
Note while tagging tickets:

Important issue to get right. Meatier.

**Comment by jonbell-lot23** [comment]
Here's a one minute loom: https://www.loom.com/share/af8070cef23a4a01a752f4c6031bb304

Here's a high level sketch:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/9154902/160022772-7c9d4775-492a-405c-91b3-d49c6709b474.png">

The actual pixels will be super simple:

1. The default state and search results stay the same.
2. We add a filter button at the top right
3. Filtering uses two simple text fields, a la VS Code

**Comment by jaril** [comment]
@jonbell-lot23 Discount time. _Technically_, the problem that Brian ran into was that the files he intended to search in were being excluded (because they're in `node_modules`). 

We could scope this much narrower and just say that:
1) We should communicate to the user that we're excluding folders matching `node_modules`.
2) Allow them to toggle that "exclude node_modules" rule on and off

Eventually we should get a full include/exclude UI. But that's a larger project that probably belongs in a separate Project ticket, and that shouldn't keep us from getting the fix in specifically for the problem specified here.

**Comment by jonbell-lot23** [comment]
Great point @jaril ! So yeah, in my boxes above the teal boxes will be a simple switch rather than the full two textfields solution. Same general UX but a smaller short term gain.

Thanks for keeping an eye on prioritisation!

**Comment by jonbell-lot23** [comment]
Ah yes. @jasonLaster following up on our chat, this is Jaril optimising for addressing the main issue (node modules) rather than going broader (building the whole experience) ... but of course we can/will do that later

**Comment by jaril** [comment]
> Ah yes. @jasonLaster following up on our chat, this is Jaril optimising for addressing the main issue (node modules) rather than going broader (building the whole experience) ... but of course we can/will do that later

Turns out this is all in the frontend so if we wanted to do a full include/exclude, it's totally a <1 hr project. :)
