### ISSUE TITLE
Can't tell which file tab is selected

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5429]
When browsing files, the selected tab and background tabs are rendered the same way, and I can't tell which one is selected.  This is disorienting and makes it especially hard to keep track of where I'm at when looking at a recording of unfamiliar code.  Noticed while working on https://github.com/RecordReplay/node/issues/40.

**Comment by jasonLaster** [comment]
Hmm - this might be a regression from the recent dark mode work.

**Comment by jonbell-lot23** [comment]
Apologies! Fixed about an hour ago with https://github.com/RecordReplay/devtools/pull/5428
