### ISSUE TITLE
Login button on recording page goes to Google instead of our new auth page

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#5432]
This login button:
<img width="569" alt="Screen Shot 2022-02-22 at 3 51 11 PM" src="https://user-images.githubusercontent.com/132260/155239460-d5076aaa-a0f2-4e9c-93f6-e5cf4a5bf309.png">

**Comment by loganfsmyth** [comment]
@jaril Maybe a quick one to jump on?

**Comment by bhackett1024** [comment]
I think I saw something similar today after being prompted to login to add a comment to a public recording.

**Comment by jasonLaster** [comment]
cc @ryanjduffy

**Comment by ryanjduffy** [comment]
Posted a fix for this
