### ISSUE TITLE
Dark mode for sourcemap visualization

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5443]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/15959269/155409062-8b5f5caf-b905-40f7-81f0-321c6f5dc73e.png">

**Comment by jasonLaster** [comment]
I believe we fixed this by disabling dark mode

**Comment by jonbell-lot23** [comment]
Yup -- we can bring it back of course, but there was a strange bug in the code we inherited. To explore
