### ISSUE TITLE
Elements panel does not load for the initial pause

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5451]
**Description:**

I've noticed that the elements panel will often not load for the initial pause.

Here is a replay of the problem
https://app.replay.io/recording/elements-do-not-load--71519781-33d3-46eb-9b1a-22531234d4c7?point=16225927698961196515911419230684627&time=8536&hasFrames=false

Here is the original replay
https://app.replay.io/recording/print-statements-not-working-on-one-line--dc561490-ad1b-4119-90a2-f47ffe26517f?point=81454156972581399810618210377533213&time=28740&hasFrames=true

**Comment by jaril** [comment]
This might belong in the backend.
