### ISSUE TITLE
[Inspector] Consider supporting or removing user agent style handling

### ISSUE THREAD

**Issue by gabrielluong** [RecordReplay/devtools#546]
Currently, we skip adding all user agent styles in `element-style.js#_maybeAddRule`. We should think about whether or not we want to support displaying the user agent styles that would come from the Replay browser.

**Comment by jasonLaster** [comment]
This feels like something we can remove and then revisit later.

**Comment by gabrielluong** [comment]
> This feels like something we can remove and then revisit later.

I think so as well.

**Comment by jaril** [comment]
Not supporting this for the next 4-8 weeks so closing for now and can revisit later
