### ISSUE TITLE
Recording never loads

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5466]
After trying to load the recording below, the viewer or devtools never actually load after waiting a few minutes.  Looking in the browser console doesn't show any errors, and `outstanding()` doesn't show any pending messages we need responses to in order to load.

https://app.replay.io/recording/081fa3a4-d94e-4a18-9dbf-8034af4b5390

Here is a replay of the problem:

https://app.replay.io/recording/recording-never-loads--e2657e3b-2f21-4c6a-bb51-2aafc43c9696

**Comment by gideonred** [comment]
I'm seeing "ProtocolMessageExcessiveTime | Network.findRequests" and "IntervalOvertime" for this recording, here: https://ui.honeycomb.io/replay/datasets/backend/result/izEUAy5F8md?tab=raw

**Comment by gideonred** [comment]
I'm guessing these led somehow to the frontend failing.

**Comment by gideonred** [comment]
I'm seeing Recording.getDescription failing, that might cause the frontend to stop working?

![Screen Shot 2022-02-24 at 3 57 33 PM](https://user-images.githubusercontent.com/28845582/155606572-da6ddc4b-bbdb-4533-9868-a7d56b8fa65a.png)

**Comment by bhackett1024** [comment]
> I'm seeing Recording.getDescription failing, that might cause the frontend to stop working?

I believe this always happens with recordings we generated programmatically, which this one was (it's a node recording made using a custom build).

**Comment by jaril** [comment]
This appears to load for me now. Can somebody check again?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/15959269/155609375-c1dfbf7b-5293-4c64-8f08-e48a64a0af3d.png">

**Comment by jaril** [comment]
[Revert](https://github.com/RecordReplay/devtools/commit/30bdf2a4054813ba18c3c5fc2cf5e730ce42fa62) took care of this. @jcmorrow I'll leave it to you to close once your new fix is in?

**Comment by bhackett1024** [comment]
This is fixed and working now, we can close it.
