### ISSUE TITLE
Dark theme bugs Jon is stuck on

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5508]
1. Codemirror has a 8x8 white box
<img width="195" alt="image" src="https://user-images.githubusercontent.com/9154902/155901813-4d12a565-9e5c-439e-974c-27b8d502b1d9.png">

I can't figure out how to remove this.

2. The console is using hard-coded black icons
<img width="148" alt="image" src="https://user-images.githubusercontent.com/9154902/155901833-0b71162e-343e-458c-a39e-a4d342b130bc.png">

I want to move this to our css mask approach but I had some trouble getting it working.

3. I can't tone down the gradient in our css
<img width="459" alt="image" src="https://user-images.githubusercontent.com/9154902/155902037-4e8d8e93-c188-4864-8abc-e2feb38d2bb9.png">

This is really bright. I tried making a new gradient in our variables.css doc but it didn't take.

**Comment by abstractalgo** [comment]
1. add `background:transparent` for `.CodeMirror-scrollbar-filler`

**Comment by abstractalgo** [comment]
2. had success by modifying `background-color`, and adding `mask-image` and `mask-repeat`.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1355455/155904131-53ce206d-0550-4ef9-b31b-d31e6108fa6a.png">

**Comment by jonbell-lot23** [comment]
1. I tried this but for some reason I couldn't find the right place to add the CSS to make it stick.
2. That should work! Thanks!

**Comment by jonbell-lot23** [comment]
@abstractalgo Same with item 2. I can change it in devtools, but actually figuring out where to change the code itself is where I'm having trouble.

**Comment by jonbell-lot23** [comment]
2/3 have been addressed, closing
