### ISSUE TITLE
Hard to add comment on where execution is paused

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5527]
When stepping around in the recording it is pretty hard to add a comment for the current point.  There doesn't seem to be any way to add a comment for the place where I'm currently paused, other than adding a line breakpoint and clicking the add comment button there, making sure the add comment button is red and not blue so that the comment actually gets added for the place I'm paused and not on the line itself.

I may have filed an issue like this before, this has annoyed me for a while.  I think the comments pane should have an "add comment" button.

**Comment by jasonLaster** [comment]
Agreed.  This is also something that we hear from users as well.

@jonbell-lot23 is this something you could take a look at post-dark-theme?

**Comment by jonbell-lot23** [comment]
Absolutely. I've filed bugs on this in the past as well, and I remember my solutions being infeasible or inaccurate. (I vaguely remember recommending we pick the first hit, but that wasn't a good idea) So it sounds like we have some work to do on the design side first talking through how we want it to work.

**Comment by jasonLaster** [comment]
Totally - the advantage of what Brian is suggesting is that we can go with the current point. 
* If the user is pause at a point in time it would use that. 
* If the user is paused at an execution point it would use that (line of code, etc)


Here's my dead-simple version 
https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=10523%3A99482

**Comment by jasonLaster** [comment]
Following up on a conversation in slack:

1. we should add a keyboard shortcut. Perhaps `c`
2. we should support right clicking in the timeline as well with two items: Comment at point, Comment at current point

**Comment by jonbell-lot23** [comment]
It sounds like we have a few different items here, logic and visual design.

Logic: imagine having a keyboard shortcut (such as C) for adding a shortcut from anywhere at all. Sounds great, but we do need to wire up the logic for making sure that keyboard shortcut does the right thing in all cases.

Visual design: How should the button look in our comments pane?

Sounds like we can get started on the logic/code part, which is the hardest part anyway. Who's best to work on that? Meanwhile, I'll work on a visual design. It's on my list.

**Comment by jaril** [comment]
Moved it to April/Q2 since it doesnt sound likely to be a march thing. Let me know otherwise!
@jonbell-lot23

**Comment by jonbell-lot23** [comment]
This issue isn't as important as the code wiring we need to set up first, which is tracked here: https://github.com/RecordReplay/devtools/issues/5741

When that's addressed, we can talk about the "add comment" button in a separate ticket. Closing for now and can re-open then.
