### ISSUE TITLE
The timeline has a weird loading / buffering effect

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5532]
**Description:**
This looks like a regression from the dark theme work

probably came from https://github.com/RecordReplay/devtools/commit/bf3a278e8436973e9753b2c2a3827035568fdc33

<img width="517" alt="Screen Shot 2022-02-28 at 7 51 04 AM" src="https://user-images.githubusercontent.com/254562/156014145-684e3f7f-93c8-46d3-9523-6e5e89e85c57.png">
<img width="1502" alt="Screen Shot 2022-02-28 at 7 49 52 AM" src="https://user-images.githubusercontent.com/254562/156014153-757733f7-5bcd-4210-a302-d20c6e7a36b8.png">

https://app.replay.io/recording/timeline-has-a-weird-buffering-effect--d81fe445-31f1-4182-bbf0-5f9a5ed5e9fc

**Comment by jaril** [comment]
@jonbell-lot23 did https://github.com/RecordReplay/devtools/pull/5537 take care of this?

**Comment by jasonLaster** [comment]
we did
