### ISSUE TITLE
Devtools e2e tests perma-fail

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5562]
The devtools e2e tests have started perma-failing it looks like sometime within the last couple of days.  The backend CI which is based on this has started perma-failing as well, see https://github.com/RecordReplay/backend/issues/4821

It doesn't look like the tests are running on pushes to master like they used to, so it's hard to tell when this started regressing.

**Comment by ryanjduffy** [comment]
Should be fixed once https://github.com/RecordReplay/gecko-dev/pull/740 is released
