### ISSUE TITLE
Show an object's classname in object previews

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#5570]
Currently the object previews usually look like `Object { ... }` even if the object is an instance of a class. The preview should show the classname instead of `Object` instead.

**Comment by hbenl** [comment]
This is actually the same in Firefox devtools:
![Screenshot from 2022-03-25 16-16-15](https://user-images.githubusercontent.com/16060807/160149076-6d1f816f-cbc2-4751-b5c2-c7dabab835f4.png)

But not in Chrome devtools:
![Screenshot from 2022-03-25 16-16-31](https://user-images.githubusercontent.com/16060807/160149084-e58a737d-4e77-4480-bb0e-917dc26179f4.png)

I think we should follow Chrome devtools in this case.

**Comment by jaril** [comment]
This will be fixed in new recordings once we make a proper deploy of the browser.
