### ISSUE TITLE
:bug:on Production - Filtering console by "setTimeout fir...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5577]
:bug:on Production - Filtering console by "setTimeout fired"  doesn't display filtered event text.
• Check "setTimeout fired" in console filters
• Expect filtered event text to be visible
• Can fast-forward and rewind from filtered line
*Re-reporting to get into bug tracking*
Original bug report <https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1642707511060800|here> \- [Chris](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1646246643069079)

**Comment by jaril** [comment]
It looks like there's no parameters being returned by the backend for setTimeout events. I'm not sure that it's supposed to in the first place.

@jperl mind clarifying 1) when this test was written, 2) if it ever passed?
