### ISSUE TITLE
Add metrics for various console features

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5590]
Add metrics to count how often various console features are being used (`.trace()`, `.table()`, console groups).

**Comment by abstractalgo** [comment]
This is the info that the protocol returns for console messages:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/1355455/156651078-de1a9ad0-1339-4e89-998a-a8ab8645059b.png">

The most granular level of grouping is by `level`, which is insufficient. From protocol PDL:

```pdl
type MessageLevel extends string
    enum
      info
      trace
      warning
      error
      assert
```

Basically, we can't tell if something is `console.group()` or `console.table()` (however, we have `level` for "trace").

So we can't implement detecting which console method is being used to then track metrics. This also affects the ability to implement #3836.

We either need to extend the protocol, or maybe try fetching from source and then manually parsing for information.

**Comment by abstractalgo** [comment]
cc @hbenl

**Comment by jasonLaster** [comment]
@abstractalgo I wonder if @loganfsmyth or @hbenl can help find where `console.group` and `console.table` is handled in either the backend or actor

**Comment by jasonLaster** [comment]
@abstractalgo thanks for investigating. I bet you can add `group`, `groupEnd`, and `table` here:

https://github.com/RecordReplay/gecko-dev/blob/webreplay-release/devtools/server/actors/replay/module.js#L763-L793 


looking at how firefox devtools handles groups, it looks like group is one of several other types of level
https://sourcegraph.com/github.com/mozilla/gecko-dev/-/blob/devtools/client/webconsole/utils/messages.js?L130

There is also `count`, `countReset`, `timeStamp`, `timeLog`, `timeEnd`, and `groupCollapsed`

**Comment by jasonLaster** [comment]
some other fun files for reading
https://sourcegraph.com/github.com/mozilla/gecko-dev/-/blob/dom/console/ConsoleAPIStorage.jsm

**Comment by abstractalgo** [comment]
I've updated the suggested function to `function consoleAPIMessageLevel({ level })=> level` to not do any grouping but just pass it as is, recorded it with a new build of Gecko and opened a recording, but opening the recording was still showing exact same amount and type of information. So seems it's not _that_ easy (but still doesn't mean it ain't something relatively simple).
