### ISSUE TITLE
🐛 on Staging: User role and developer role able to se...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5591]
:bug: on Staging: User role and developer role able to select recordings for bulk editing.
• Log in with User or Developer role
• Go to team recordings and click on edit button
• Expect bulk editing to be disabled
• Checkboxes do not appear but recordings can still be selected if recording rows are clicked \- [Chris](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1646330730591159)

**Comment by jaril** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/15959269/158936667-cd58ddf8-62b8-4cf3-b4b5-f3cd9a3af7c1.png">
