### ISSUE TITLE
Get the user more quickly into interacting with a Replay

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5595]
This is a tracking ticket for me to bring together the work that has been done, is being done, and is planned.

- [x] #5475 (done)
- [x] Batch sources and console messages (investigated, did not see much difference in performance, not pursuing further for now)
- [x] #5596
- [x] Use protobuf for console messages and/or sources (investigated, notes below)
- [x] https://github.com/RecordReplay/backend/pull/4840

**Comment by jcmorrow** [comment]
As a follow-up to the results of the web-socket compression change I have tested a couple of replays with compression toggled on and off and I got these results for data over the wire from the dispatcher:

30 second replay with a lot of paints - loaded and played the video through to the end:
```
Without compression: 81MB
With compression:    29MB
Change:             -64.2%
```

A Replay with lots of repeated JSON structure (50K newSource messages) only loading, without playing the video:
```
Without compression: 7.3MB
With compression:    2.2MB
Change:             -69.8%
```

So, in both cases a significant (though not earth-shattering) reduction in size.

**Comment by jcmorrow** [comment]
I want to follow up on `Use protobuf for console messages and/or sources`. I have never actually used protobuf, having only heard of it sometimes as a neat thing from Google. Upon researching it I learned that:

- It's useful for making messages slightly smaller
- It's useful for making messages faster to deserialize
- It's useful for interop between different languages, particularly in something like an RPC client
- It's useful for data structures with changing schemas that are concerned with backwards compatibility

We would primarily want it for the first two, but I suspect based on the evidence above that websocket compression has taken a lot of the shine off of `protobuff as compression method`, because JSON keys are almost certainly getting compressed across similarly shaped messages thanks to context takeover. So the big win would be probably be in deserialization performance, but I don't see much evidence from profiling loading times that it's deserialization that is taking the bulk of the time when it comes to loading resources. Further, if we allow for some clients to use protobuf, we are now in a situation where either: 

- clients have to be able to opt-in to protobuf, and we have to support using both that and JSON or
- all clients have to commit to using protobuf

This is not a huge deal, but for the amount that it's getting us in exchange, it felt like a serious drawback. I'm still curious about how deserializing tens of thousands of sources or console messages would be affected by protobuf, but my intuition (and the admittedly scanty hard evidence I've seen) suggest it's not worth it right now, but might be worth revisiting later.

**Comment by jcmorrow** [comment]
Alright, it's always tough to know when to do this with large, exploratory works, but I am going to call this ticket done. I think it's safe to say the next things that would most speed up the user experience are the *hard* things, like speeding up replaying itself 😄 .

**Comment by gideonred** [comment]
Sorry for being late to this ticket, and your reasoning sounds good. Another contender might also be messagepack.
