### ISSUE TITLE
Add some form of paging support for the library

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#5622]
With teams starting to add CI, the number of recordings in the library is going to increase quickly. We need to add some form of paging to help maintain a reasonable load time.

**Comment by jonbell-lot23** [comment]
Note that this UX shouldn't exist in a vacuum. We used to have a search with dropdowns that lets you select views like "only this week" and so forth.

We paused that feature and planned to bring it back alongside pagination. Looks like the time is right to bring back that work!

**Comment by jasonLaster** [comment]
The simplest would be to load the first 100 replays and add a Load More below it.

**Comment by ryanjduffy** [comment]
> We should also think about organization with CI, but that is not really a pagination thing

Agree in concept but I think it is a pagination thing up until we have that in place. Concretely, if i click on our "Playwright Tests" team, I try to click on something else quickly because that load will be a while. Would rather our users not have that experience :)

**Comment by jasonLaster** [comment]
Agreed - the first load should only load the first N replays.

**Comment by jonbell-lot23** [comment]
Last I checked, this page was slow because of the thumbnail images. Curious to know two things:

1. Do we know if a Replay came from CI?
2. Do we lose a lot by dropping the thumbnail? I suspect not.

--

For this ticket, I'd just do the top 100 with a load more, as Jason said. More robust pagination, CI-specific designs, and a return of the filter dropdowns can come later.

**Comment by ryanjduffy** [comment]
For a data point, i loaded up our playwright test library page and it took 9 seconds of scripting and rendering to display even with lazy loading the above the fold thumbnails.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/788456/158309987-825f65ae-1816-4112-95a0-ce9861418daa.png">

**Comment by jonbell-lot23** [comment]
Proposal: show raw JSON where each title has a link to the replay itself 😂

9 seconds just for above the fold (and recall that our loading screen is also slow and flickery) is really bad

**Comment by jasonLaster** [comment]
closing because it is now faster and we will revisit in April
