### ISSUE TITLE
Object getters should be in autocomplete

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5652]
**Description:**
We should show the list of getters in autocomplete.

This came up quite a bit while pairing with @Andarist

**Comment by hbenl** [comment]
@jasonLaster This is already working for me: https://app.replay.io/recording/getter-in-autocomplete--5a89347e-7eea-4a08-b731-f2dd9fba297f
My guess is that it didn't work in your case because the getter was defined on the prototype and the prototype's preview hadn't been loaded yet. Do you have a recording?

**Comment by Andarist** [comment]
@hbenl I've added a comment pointing to the exact location [here](https://app.replay.io/recording/composed-conditional-type-expands-into-union-of-its-its-branches--3362459f-d68d-40af-997b-7f407643f642?point=16720116146273000930410542&time=1816.0520101193392&hasFrames=true). I've also added some, maybe interesting, information there. You are right that those are defined on the prototype.

**Comment by jasonLaster** [comment]
Thanks @Andarist 

here is a replay of the problem
https://app.replay.io/recording/bb3a151b-ac0e-4ad2-8764-65a3f5861325

This should help us narrow it down

**Comment by jasonLaster** [comment]
For what it's worth I looked briefly and could not find the object getters that we'd want to show which was surprising.

cc @hbenl

**Comment by hbenl** [comment]
Actually we already tried to show all properties, including getters and those from the prototype. But we didn't ensure that the prototype was loaded before collecting those properties, so we missed them if not.
