### ISSUE TITLE
Unknown inviter text when invited via invite link

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#5653]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/15959269/157107962-48614674-a1b7-486d-9836-04c3b38cb4af.png">

A few of the Dynaboard folks ran into this onboarding flow after having signed up for Replay using the team invite link. The team invite link is not connected to a user/inviter so it's returning empty.

I think the screen is correct — we need to direct them to download Replay. But in the case of the invite link we should probably just leave out the inviter's name.

**Comment by jasonLaster** [comment]
oh ha - yeah. team invite

**Comment by jaril** [comment]
Closed by https://github.com/RecordReplay/devtools/pull/5660
