### ISSUE TITLE
:bug: with PR (https://github.com/RecordReplay/devtools/c...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5658]
:bug: with PR (<https://github.com/RecordReplay/devtools/commit/0a62ee170d98834809369ba5aac8d00a0cf9b5a1|a62ee1>) - Being redirected to <https://devtools-ormqcnnzt-recordreplay.vercel.app/> when navigating to <http://staging.app.replay.io|staging.app.replay.io> \- [Ty](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1646688486127349)

**Comment by jaril** [comment]
@ryanjduffy any idea what might have happened here?

**Comment by ryanjduffy** [comment]
No. A replay would be helpful to see what's going on. Also unclear why we'd be navigating to staging when testing a PR with its own preview branch

**Comment by jaril** [comment]
@jperl is this still a problem??

**Comment by jaril** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/15959269/158936649-09e198bb-7a9a-4819-83ee-da60c4ea5dea.png">
