### ISSUE TITLE
Maintenance mode doesn't apply to recording view page

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#5663]
In [this Replay](https://app.replay.io/recording/maintenance-mode-doesnt-apply-to-view-recording-page--9eafcfad-606e-4b78-bf59-dc3f29faffe5), maintenance mode is enabled (I was running the app locally) but instead of getting a notification about maintenance mode I get an error page when viewing a replay.

**Comment by jazzdan** [comment]
I am definitely in favor of that :)

Is there a convenient place to put the maintenance mode logic, which should apply to every page and view?

**Comment by abstractalgo** [comment]
Probably `_app.tsx` then.
