### ISSUE TITLE
Fix storybook setup

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5667]
<img width="1366" alt="Screen Shot 2022-03-07 at 6 57 20 PM" src="https://user-images.githubusercontent.com/254562/157157498-fce069a9-8709-4f33-afee-1770f490030c.png">

**Comment by abstractalgo** [comment]
Hmm, I had no problems with neither `storybook` nor `build-storybook`.

---

Videos just as a sort of confirmation.

https://user-images.githubusercontent.com/1355455/157176070-21bb7fee-7ecb-47b6-baac-af0412b19cef.mp4


https://user-images.githubusercontent.com/1355455/157176085-5580fba5-1df9-48b7-9e11-7e34c5bcb808.mp4

**Comment by jasonLaster** [comment]
Wonder if this is a node version thing

I'm on v17.0.1 which failed, but `replay-node` worked. The recording itself
is not loading though :P

https://app.replay.io/recording/924372ec-e04f-4d58-bf32-5b660fd4886b?id=924372ec-e04f-4d58-bf32-5b660fd4886b

**Comment by abstractalgo** [comment]
Confirmed, it is a Node version thing (fails on 17.0.1):

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1355455/157178268-4b8de1a2-93ec-4df6-bbd3-8df69c1f7ddb.png">

---

I'll close this for now as this will be a part of upgrading Node version at some point, but it's not an issue for now.

**Comment by abstractalgo** [comment]
Confirmed, it is a Node version thing (fails on 17.0.1):

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1355455/157178268-4b8de1a2-93ec-4df6-bbd3-8df69c1f7ddb.png">

---

I'll close this for now as this will be a part of upgrading Node version at some point, but it's not an issue for now.
