### ISSUE TITLE
Improve DevTools CI metrics

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5701]
Following https://github.com/RecordReplay/devtools/pull/5668#issuecomment-1063094155, to consider adding more reported details:

- [ ] bundle size + bundle size changes relative to `master`
  - https://github.com/ai/size-limit
- [ ] web metrics (aka lighthouse scores)
- [ ] CI steps timings

**Comment by bvaughn** [comment]
Would be nice for us to have a CI action that comments on PRs saying how much the change increases or decreases the devtools bundle size (relative to `master` branch). React used this approach to help prevent us from accidentally increasing the package size without intending to.

**Comment by jaril** [comment]
Generally this is good. But it's not high priority since bundle size is not a critical metric.

**Comment by jasonLaster** [comment]
Agreed - let's bring this back after we are in a better place with our existing tooling (e2e, jest, ts ...)
