### ISSUE TITLE
Settings background in Firefox/Replay is semi-transparent

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#5704]
**Description:**
In Chrome, the background on the settings modal is opaque, but is semi-transparent in Firefox and the Replay Browser.

**Steps to Reproduce:**

https://app.replay.io/recording/settings-background-semi-transparent--acf3ae76-6a69-484c-9d44-09c943f7bb99

**Expected Result:**

**Additional Context:**

* Screenshots:
In Chrome:

![Screen Shot 2022-03-09 at 2 46 54 PM](https://user-images.githubusercontent.com/40367173/157521888-8f5c2044-1bc2-41eb-9005-9c27b1f7ebc8.png)

In Firefox:

![Screen Shot 2022-03-09 at 2 47 22 PM](https://user-images.githubusercontent.com/40367173/157522046-6e8384bd-efc7-4e63-a0d7-c6d2ed4b2c6d.png)

See replay above for Replay Browser.

* Video (Loom):
* Replay:

**Comment by jonbell-lot23** [comment]
Thanks!

I had no idea Firefox didn't support the blurred transparency thing I was using. I dialled the transparency way down as a result.
