### ISSUE TITLE
Add browser/OS alignment to our dark mode

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5719]
We'll also need a setting for "respect browser settings" versus letting people manually select.

**Comment by jasonLaster** [comment]
<img width="867" alt="Screen Shot 2022-03-14 at 2 08 29 PM" src="https://user-images.githubusercontent.com/254562/158261763-bae66b00-fddc-4816-a067-b9ea270c96a9.png">

**Comment by jonbell-lot23** [comment]
Yeah, we were aligning with GitHub, pretty similar: 
![image](https://user-images.githubusercontent.com/9154902/158267666-899aea85-b35f-40e5-a8d9-54aff8a3d6aa.png)
