### ISSUE TITLE
Long comments change size of viewer

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#5733]
**Description:**
If you type in a long comment it changes the size of the viewer

**Steps to Reproduce:**

https://app.replay.io/recording/replay-comments-affect-size-of-viewer--2e7bd3a3-ec21-4cf3-a883-e3ec61d8e04f

**Expected Result:**

I think the comment should continue on the next line, rather than continuing to grow on one large line.

**Comment by jaril** [comment]
https://app.replay.io/recording/sidebar-width-is-changing--5f8b7ea0-767d-4201-a8e0-23f49167b37b
