### ISSUE TITLE
Graphics are off when seeking to a point (excalidraw)

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5738]
I think that the repaintGraphics are wrong because when i seek to a spot it looks right, and then reverts to something that looks wrong.

https://app.replay.io/recording/graphics-flicker--03e69807-f0dd-4536-b215-b1ed054d247b

**Comment by jcmorrow** [comment]
At a first glance this look like the repainted graphics fighting with the recording's paint data, but I'll look a little closer.

**Comment by jasonLaster** [comment]
totally - started dropping some print statements to get oriented

**Comment by jcmorrow** [comment]
I haven't actually re-read what graphics does when you seek, but if I recall correctly from when I was working on this, when you seek to a point it finds the most recent paint in the past, and paints that immediately, and then it requests the properly repainted screen from the backend. If those two are not the same then it will update the paint again once the backend request returns.

One option - I made this change on line 299 of `graphics.ts`:

```
  store.dispatch(setPlaybackStalled(true));
  // This is here just to make sure we get a chance to see the spinner on every paint reload
  await new Promise<void>(resolve => {
    setTimeout(() => resolve(), 500);
  });
```

And that will cause the spinner to get shown (assuming that there is a long enough gap between requesting the repaint and getting it). It's a subtle spinner, so we could do something a little more noticeable, but this is a very easy start. As to which of these visuals to trust - I'm not sure I can speak to that. I don't actually know basically anything about how repainting works, or when it might be off.

**Comment by jasonLaster** [comment]
@jcmorrow nice - i think we should file a new issue for showing the spinner when we're waiting for the repaint to come back. We could use stalled, but it feels like that is abusing the feature.

re painting: i think it is safe to assume there is an issue with the repaint data we're getting from the backend because we know excalidraw is drawing the selection. The only thing i can think of is if excalidraw always removes it and redraws it, but that would be surprising.

**Comment by jasonLaster** [comment]
re painting - i wonder if we have a good generic way to inspect the paints we get back to even see what they look like... I kinda feel like we need some mechanism to draw an arbitrary image to the canvas.

**Comment by jcmorrow** [comment]
> re painting

I see what you did there...

**Comment by jasonLaster** [comment]
Turns out that replay was right and i was wrong. The canvas was updating on each render
