### ISSUE TITLE
It should be possible to add a comment from anywhere

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5741]
As noted in https://github.com/RecordReplay/devtools/issues/5527 , we need a keyboard shortcut that will add a shortcut in all scenarios.

* If the user is paused at a point in time, we use time
* If the user is paused at an execution point, we use that

Once we have the back-end logic wired up to a keyboard shortcut, the remaining work is just designing a button and slapping it into the Comments pane.

(For now, the shortcut can be shift-C, but this can be modified as we go)

**Comment by jonbell-lot23** [comment]
Following up on a chat with @jasonLaster --

If this logic is already locked in @jaril , let's make a keyboard shortcut and close this out. Separately, I have a task to make a new comment button.

**Comment by jonbell-lot23** [comment]
Design ticket filed here: https://github.com/RecordReplay/design/issues/24

**Comment by souporserious** [comment]
Closed in #6742

**Comment by jonbell-lot23** [comment]
Re-opening because we do need a few more things:

1. We need a keyboard shortcut for adding a comment from anywhere (Shift-C perhaps?)
2. We need to make sure the logic does the right thing based on where you are
3. We need to make sure it doesn't trigger when you're in a text region, which is an issue we had with Shift-T changing the theme

**Comment by markerikson** [comment]
Kinda-nitpick / observation:

Can we move away from `SHIFT-$LETTER` shortcuts?

At a minimum, `CTRL-` oughta be involved.  Although as I just was noticing from trying to use Github's "VS Code in a browser" implementation, you _do_ promptly start running into collisions with browser built-in shortcuts if you're not careful :)

**Comment by jonbell-lot23** [comment]
* Some things are common enough that they should be just a letter, no modifier (like in Figma, or even just using arrows in the console)
* Some things are uncommon enough that you bury them under three modifier keys
* There are always issues around browser collisions, moreso when you use control
* Shift is a good middle ground
* But of course you also want to make sure you don't collide with standard stuff, like the theme toggle bug we had earlier

So my point of view is that step one is not having collision bugs, and step two is finding the right amount of keyboard tucking away without it being ridiculous. (Adobe Photoshop calls for command-option-shift-s for one of its most common actions, which is a mistake) I think shift is absolutely valid as long as there aren't collisions, and as you say, command has its own browser-level things to deal with.

[Outdated doc from when we were first exploring this space](https://www.notion.so/replayio/ea1e85a8ad6d46b88bb315a1cf337243?v=8ea1fd7ed2bf4e0dbbd7cd1c4bbecc37)

**Comment by souporserious** [comment]
@jonbell-lot23 question, when a comment is currently in-progress should we:

1. Move the comment to the new point in time / execution point and keep the inputted text?
2. Prevent adding a new comment and just focus the input at the original time / execution point?
3. Something else?

To me, it feels like I'd want to move to the new state and have a revert button for so many milliseconds that would take me back to the previous state if I still wanted to finish commenting on that line. Alternatively, we could focus the in-progress comment so you can finish it and then offer to or automatically jump to where you were headed.

**Comment by jonbell-lot23** [comment]
Apologies @souporserious this comment slipped by me.

If I'm understanding correctly, this the flow we're asking about:

1. User starts writing a comment
2. User attempts to add a second comment

Am I understanding right? If so, I'd treat it like trying to hit command-S in a desktop app twice. The first time you're taken to a save dialog. The second time, nothing should happen. Modes are their own UI universe, until the user chooses to cancel or commit something, they should stick with the mode they're in.

So I'd go with number two. Please let me know if I'm misunderstanding the question!

**Comment by souporserious** [comment]
Nope, this is perfect, thank you for clarifying! I'll get my PR wrapped up for this 😎
