### ISSUE TITLE
Explore different shades for dark theme

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5745]
Jason wonders if we can add more colour back in to help it feel warmer

**Comment by jasonLaster** [comment]
I bet we can use the replay.io hero background for starters

<img width="2562" alt="Screen Shot 2022-03-18 at 11 37 23 PM" src="https://user-images.githubusercontent.com/254562/159110572-630e6bb0-1cb0-4cec-aaa8-2b39b8639275.png">

**Comment by jasonLaster** [comment]
This is a rough sketch of what it would look like, basically adding a dab of zypsy blue to all the greys

<img width="2880" alt="Screen Shot 2022-03-18 at 11 47 28 PM" src="https://user-images.githubusercontent.com/254562/159110811-be0312eb-1c61-4de8-89ea-5545bec1dbaa.png">
