### ISSUE TITLE
Specific layout toggle defaults to no other panel

### ISSUE THREAD

**Issue by abstractalgo** [RecordReplay/devtools#5761]
https://user-images.githubusercontent.com/1355455/158153439-754cc73d-265d-474e-8056-5055c440fb1c.mp4

Notice that there's no selected tab for the panels that remain in the bottom right.

**Comment by jaril** [comment]
This was fixed by https://github.com/RecordReplay/devtools/commit/d20adc2472aeb0c64f9fcd67b077dd15730de291

Uploading Screen Recording 2022-03-24 at 3.49.32 PM.mov…
