### ISSUE TITLE
[Inspector][Rules] Display the shorthand properties instead of the longhand properties

### ISSUE THREAD

**Issue by gabrielluong** [RecordReplay/devtools#578]
Currently, we are displaying only the longhand properties in the Rules view. For instance, "margin: 0" is displayed only as "margin-left: 0; margin-right: 0; margin-top: 0; margin-bottom: 0;".

**Comment by bhackett1024** [comment]
It seems like using the longhand properties in the data returned from the server and having the client convert things to a shorthand representation would leave us with the simplest protocol and most flexible client.  The firefox devtools should have MPL code for this that we can use in the client.

**Comment by hbenl** [comment]
[This](https://github.com/mozilla/gecko-dev/blob/1843375acbbca68127713e402be222350ac99301/layout/style/test/property_database.js#L1378) should contain the information we need.

**Comment by hbenl** [comment]
Firefox only shows the shorthand property if it was used in the declaration:
![Screenshot_2020-12-07_16-21-35](https://user-images.githubusercontent.com/16060807/101369342-7a277700-38a8-11eb-81eb-f6f405179f49.png)
In this example, the `overflow-x` and `overflow-y` properties were set in an inline style and `overflow` was set in a stylesheet - the rules panel reflects this.
Currently the only way to get this information in the client would be to parse the raw `preview.style.cssText`.
