### ISSUE TITLE
Improve the first login in our onboarding flow

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5785]
![image](https://user-images.githubusercontent.com/9154902/158296066-d2088779-7a73-43ea-a6c7-1aea13985176.png)

1. Visually these should be more consistent
2. The login screen should be customised with onboarding text. So instead of boilerplate Replay stuff, it should say things like "Almost there!" to make it part of the flow.

**Comment by jaril** [comment]
@jonbell-lot23 I'm not sure I understand what work needs to happen here. Mind clarifying?

**Comment by jonbell-lot23** [comment]
@jaril Instead of showing the boilerplate login pane, we need to show different text. So instead of "Replay captures ..." it should say something like "Almost there!"

**Comment by jonbell-lot23** [comment]
Update:

I'm also seeing issues where when I hard-code dark theme for onboarding I get this:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/9154902/159376962-a17a7b4d-126a-49b7-ac15-7470648be76f.png">

So that's another reason why a specific login page for onboarding will help. Not just the text change, but also making sure the colours are set right.

**Comment by jaril** [comment]
Once https://github.com/RecordReplay/devtools/pull/5957 is merged, you should be good to go to change up the copy! @jonbell-lot23

**Comment by jonbell-lot23** [comment]
Woo, thank you!

**Comment by jonbell-lot23** [comment]
Hey @jaril I'm having more trouble with this page. Check out this screenshot:



1. I don't want the learn more link
2. Like we discussed earlier, I need this page to be dark theme
3. I'd also like to change the modal design (logo, sizing, etc)

What we're seeing here is the limitations of making everything into a component with small params passed in. It's fine when we only want to change one or two things, but really we just need a totally different login page here. We can't rely on the same template because the page is just too different.

**Comment by jaril** [comment]
@jonbell-lot23 need help getting unblocked here?

**Comment by jonbell-lot23** [comment]
Yeah @jaril can you just make this a separate page? See my notes in the previous comment.

**Comment by jaril** [comment]
> Yeah @jaril can you just make this a separate page? See my notes in the previous comment. I need full flexibility for this page, so trying to tie it to our standard login screen isn't going to work.

Not in good conscience. Let's pair on it later and see if we can keep from branching out!

**Comment by jonbell-lot23** [comment]
Duplicating comments from DMs:

Philosophically there's a middle ground between DRY and Constantly Repeat Yourself (or CRY, an acronym I just made up :)

As we do more illustration + visual work, we're going to find ourselves splitting things out more. In this case, the only thing that we should repeat is the login button. Everything else on this page -- everything! -- should be different so I can align it more with onboarding. It means we're making two pages, but that's ok. They've earned the right to be different.

This issue is also seen elsewhere in our onboarding, where our dark theme isn't working for similar reasons. To discuss soon!

**Comment by jonbell-lot23** [comment]
I made a new tag called "design-needs-codehelp." This is going to be my way to point to issues where components might be so DRY that it's hard for me to add my design magic to them without hacking a bunch of stuff.

This ticket is a great example. Not a super short term priority, but would be good to get to in the next few weeks, perhaps when Jaril is back from holiday
