### ISSUE TITLE
Light up the sources tab when we open the editor in the background

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5804]
**The issue**

When you're in one of our new layouts, clicking stuff in the console or network monitor will open a new file in the editor, but you won't see it because it's opening in a separate sources tab. This is fine for now, but we need to at least message to the user that something happened.

**The proposal**

This is a UX regression. The best way to fix this quickly and subtly is to simply light up the sources tab with a white color that then fades back to the default gray over 2 seconds. This gives an indication of state change.

**Other ideas**

Jaril talked about completely suppressing things opening in the editor and Jason talked about navigating you to the editor. I disagree with both approaches because they're both too extreme imo, but let's leave that for the next iteration of this feature.

Short term, a simple color state change. Longer term we can debate whether we suppress (Jaril), yank (Jason), or message (Jon). But let's not let the product regression live on prod any longer than we need to. Part of shipping things we know are rough is being able to quickly address regressions, so let's quickly address this regression and iterate from there.

**Comment by abstractalgo** [comment]
+1 for switching to Editor because that seems like a logical consequence of one's intent of clicking on a certain thing

Also, indicators and animations can start complicating things with their transitive states.
