### ISSUE TITLE
[Protocol] optimize getMappedLocation

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#581]
There are two ways of getting mappedLocations `getPreferredMappedLocation` and `getPreferredLocation`

* `getPreferredMappedLocation` queries the server
* `getPreferredLocation` uses existing data

We should be able to switch `getPreferredMappedLocation` in logpoint.js to `getPreferredLocation`, which will reduce a lot of network traffic.

In general, we should do a better job of avoiding network calls, by caching mapped locations fetched from the server and first reading from the new location cache and scripts cache.

```js
diff --git a/src/protocol/thread.js b/src/protocol/thread.js
index d7493bdb..f3bb1fd7 100644
--- a/src/protocol/thread.js
+++ b/src/protocol/thread.js
@@ -1153,6 +1153,9 @@ const ThreadFront = {
   // Map scriptId to info about the script.
   scripts: new Map(),

+  // map scriptId to locations array
+  mappedLocations: new Map(),
+
   // Resolve hooks for promises waiting on a script ID to be known.
   scriptWaiters: new ArrayMap(),

@@ -1859,11 +1862,20 @@ const ThreadFront = {

   // Get the location to use for a generated location without alternatives.
   async getPreferredMappedLocation(location) {
+    // check to see if the location is available by
+    let existingMappedLocation = await this.getPreferredLocation(location);
+    if (existingMappedLocation) {
+      return existingMappedLocation;
+    }
+
     const { mappedLocation } = await sendMessage(
       "Debugger.getMappedLocation",
       { location },
       this.sessionId
     );
+
+    // cache the results s
+
     return this.getPreferredLocation(mappedLocation);
   },
```

**Comment by hbenl** [comment]
We can't switch to `getPreferredLocation` in logpoint.js because (in my experiments at least) it always gets an array with only one location (for which the server will return an array with several locations).
I've added a cache for `MappedLocation`s in #680.
