### ISSUE TITLE
:bug: on Staging: Error for too many exceptions is not di...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5817]
:bug: on Staging: Error for too many exceptions is not displaying in the console
• Navigate to the <https://devtools-38gskb4bm-recordreplay.vercel.app/recording/7c05aa57-7ceb-4d40-ab05-bc435f704941|replay>
• Click on exceptions to make them visible in the console
• Note the lack of the expected error message
 \- [Ty](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1647446821539489)

**Comment by jaril** [comment]
This looks like it's working now. @jperl mind checking?

![Uploading image.png…]()
