### ISSUE TITLE
[PrettyPrint] react-devtools

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#583]
STR:
1. go to  https://replay.io/view?id=22383d90-7286-4ec3-b78b-ece9a259aa04
2. select devtools.js

Notice that the file is a collection of minified lines.

**Comment by jasonLaster** [comment]
Lines like 23820 are good examples of long lines that are actually clipped at column 1000

Given that we no longer let users pretty print on the client, we should probably update the heuristic to pretty print if any line is longer than 1000 chars. We could also go as low as 400 too, perhaps with a check that it is JS and not a comment.  Honestly there also isn't a harm pretty printing more files, its a bit slower but could be helpful.

**Comment by hbenl** [comment]
Fixed by RecordReplay/backend#205
