### ISSUE TITLE
Using arrow keys to move cursor in editor also moves the recording timeline

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#5839]
**Description:**
https://app.replay.io/recording/using-arrow-keys-in-editor-also-moves-in-timeline--d80a6626-46d8-496d-9a45-f81b914b7883?point=48028745944638700543075875408578059&time=18380&hasFrames=true

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:

**Comment by jaril** [comment]
```
There's already somec ode for ignoring the … keys if the focus is in a textarea. That just needs to understand this case.
```

**Comment by hbenl** [comment]
This is the code I was talking about:
https://github.com/RecordReplay/devtools/blob/cce522bd5f42b8c6d396dfc6bf037e34cea5af34/src/ui/utils/key-shortcuts.ts#L83-L92
