### ISSUE TITLE
Console timestamps are shown by default

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5845]
**Description:**
I bet @markerikson recent console pref change removed a pref which was storing console timestamps

Bug: console logs now show timestamps by default
ER: the pref is off by default and persisted

**Comment by markerikson** [comment]
Either #5800 or #5812 most likely, yeah

**Comment by markerikson** [comment]
If I had to guess:

https://github.com/RecordReplay/devtools/pull/5800/files#diff-a116b8b40764e948cd40355c23a64c132dde346a05aba5fcb19f1061149929d1L25-L28

**Comment by jasonLaster** [comment]
Should be easy to record a replay in the morning

**Comment by jasonLaster** [comment]
@markerikson I think it is better to persist the change, but i trust your judgement. also as an aside, these stories are better when theres also a replay with comments :P
