### ISSUE TITLE
Timeline head should be clamped to the right

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5847]
**Description:**
It looks like our recent change to timeline scrubbing could have unintentionally let the timeline head escape the right of the timeline

https://app.replay.io/recording/clown-nose-escaped-the-timeline--0bbfb4f8-8ae4-4bfc-9c91-20bbde1796bf

**Comment by jaril** [comment]
Check if this was closed by https://github.com/RecordReplay/devtools/pull/5916

**Comment by jaril** [comment]
@jasonLaster thanks!
