### ISSUE TITLE
SessionErrorMessages does not cover UnknownFatalError

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5856]
Related to https://github.com/RecordReplay/backend/issues/4450.  The session error messages https://github.com/RecordReplay/devtools/blob/master/src/ui/setup/dynamic/devtools.ts#L69-L90 do not include one for unknown fatal errors, causing the resulting error message to be a generic one which doesn't indicate that this is probably a problem with the replay itself and the user will need to make a new recording.

**Comment by jasonLaster** [comment]
@jonbell-lot23 happy to help if this is not clear
