### ISSUE TITLE
RequestDetails can fail if there is no request

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5876]
This happens when i have `NetworkComment` enabled, but i'm not sure if it is actually because of that. I think i'm just trying to view a weird request

https://app.replay.io/recording/cannot-find-point--d3a42faf-3e2b-4cb4-8b2a-7fb40dfb8b17?point=109038234045924845411913413005672654&time=38984.28250233632&hasFrames=true

**Comment by jaril** [comment]
Odd — i just tried replicating the steps in the replay and not only did the exact same bug occur, going to `app.replay.io` just, stopped working?
