### ISSUE TITLE
Ongoing Redux logic RTK+TS migration

### ISSUE THREAD

**Issue by markerikson** [RecordReplay/devtools#5893]
I'm working to migrate all of our existing Redux logic (actions, thunks, and reducers) from plain JS to TypeScript, and from legacy "hand-written" Redux patterns to modern Redux Toolkit.

I've done a SLOC scan of the client codebase of 2022-03-21, converted that into CSV, and imported it into Notion here:

https://www.notion.so/replayio/53ab38f98a9144259b753165fb84730f?v=62ec21471ae549d0a2e237c16e65066a

The primary focus here is to migrate files that live in `actions` and `reducers` folders.  

Currently, the plain JS code is 58 files and about 7000 SLOC.  Additionally, the existing TS code needs to be migrated to RTK as well.  That's another 51 files and 4700 SLOC.

In the couple reducers I've migrated so far, I've also had to touch some of the `utils` files as well.

Given that, my estimate is that we're looking at (58 + 51 + ~16 = 125) files and (7000 + 4700 + 1300 = 13000) SLOC that needs to be migrated.

My first couple migration PRs have been around 250-300 SLOC each and taken a day or two.  So, this effort could easily take 2-3 months.

I'll keep track of progress in that Notion page, and try to file individual issues for chunks of the code that I'm working on for sprint-level tracking.

Per discussion with Jason: we're going to scope the initial effort to a couple high-priority sections (likely `messages` and `sources`), then leave the rest of this for later.

**Comment by jasonLaster** [comment]
Our next goal is to refactor Console Messages + Debugger Sources in the next two weeks (#5903, #5902). We'll use these two projects to come up with goals for the following two weeks.

The project scope will likely be tightened to: setup best practices for RTK + TS on the frontend. As opposed to, refactor the entire redux frontend.

**Comment by markerikson** [comment]
This is partially done, but we're going to call it completed for now.

All of our reducers have been converted to TS, and the `messages` reducer is using RTK.  However, most of them are still "hand-written" Redux logic rather than fully migrated to RTK.  As much as I'd love to be using `createSlice` here, doing so would require more effort than we can justify at this moment.

I'm also going to knock out converting the rest of our selector files to TS today as well.

I'll close this issue, and we'll add more issues at some point when we decide it's time to do further RTK migration.
