### ISSUE TITLE
Set the focus start/end from a call stack frame

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5895]
**Description:**

Focus mode is a powerful feature for narrowing in on a hot code path. Today it is limited to what you can do with the timeline.

We should let users narrow in by right clicking on a call stack frame, console log, etc

A simple place to start would be to add 4 menu items here

* Set focus start to current point
* Set focus end to current point
* set focus start to frame enter
* set focus end to frame exit

<img width="401" alt="Screen Shot 2022-03-21 at 10 31 09 AM" src="https://user-images.githubusercontent.com/254562/159330939-4201de23-9e4c-4f00-831f-4b725abe48c9.png">

**Comment by bgirard** [comment]
I wouldn't think of clicking there TBH.

I'd find it more intuitive if the Focus Mode UI incorporated this somehow.

Either this dialog:
<img width="473" alt="Screen Shot 2022-03-21 at 10 37 09 AM" src="https://user-images.githubusercontent.com/793565/159331704-c1eec0c6-0fc6-42f7-9cb4-137dcce61f4f.png">

Or the focus button, or some UX in the timeline. But just my 2C. Anything that works.

**Comment by jaril** [comment]
Opened https://github.com/RecordReplay/devtools/pull/6022, which checks off the following boxes:
- [ ] Set focus start to current point
- [ ] Set focus end to current point
