### ISSUE TITLE
:bug: on DevTools:
When toggling the log filter checkbox,...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#5899]
:bug: on DevTools:
When toggling the log filter checkbox, nothing is happening in the console. In the passing version of the test, the logs would appear and disappear.
Chris mentioned looking into similar issues filtering errors and warnings as well.
Link to buggy behavior replay: <https://app.replay.io/recording/airtable-playwright-test--8cb961bf-5e89-4c15-b7e6-45a66e90665d>
Attached recording shows the passing behavior. \- [Jordan](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1647895130528989)

**Comment by jaril** [comment]
Check if it's passing.

**Comment by jaril** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/15959269/159784735-b5f2208e-ac26-4fbe-bc9f-b9650c366908.png">

**Comment by markerikson** [comment]
This was very likely in the 2-3 hour timespan between when I merged #5896 , which broke filtering messages, and #5898 which fixed that
