### ISSUE TITLE
Set an Editor min-width

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5908]
It's possible for the editor to be so narrow that it no longer is recognizable. We should set a min-width of 200 or something that's fine Also below that we could then collapse the editor and switch to dock to the bottom. (nice to have)

![Screen_Shot_2022-03-21_at_5 03 32_PM](https://user-images.githubusercontent.com/254562/159386102-744c7580-7242-4d5f-80bf-704eeda1e8b3.png)

**Comment by jaril** [comment]
> @jasonLaster I am not able to reproduce this. For me, it has min-width of 300px. You can see screenshots below
> 
> ![image](https://user-images.githubusercontent.com/53361996/162761265-31cc4ee0-d7ad-4f99-aca5-6bb279cdb2da.png) ![image](https://user-images.githubusercontent.com/53361996/162761443-bccd9994-42be-4503-aa11-d9cfd92642e5.png)

Thanks for checking! You're right — we pushed a new layout change sometime last week which just might have taken care of this. Will close it!
