### ISSUE TITLE
New comment edge cases

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5912]
Filing this issue to track some additional edge cases that i'm seeing with comments

(These are probably all three the same bug with the pending id)

- [x] Comment created with S [link](https://app.replay.io/recording/comment-created-with-s--3cfd9ddc-32a0-46d8-ab12-197f28219464?point=47055190303382940201897219929934167&time=20086&hasFrames=false)
- [x] New comment opened with the same text [link](https://app.replay.io/recording/new-comment-opened-with-the-same-text--1632929f-34d0-4d9c-8910-d88ca7ba7387?point=61009488110431175889454583095757519&time=23796&hasFrames=false)
- [x] Comment created with draft [link](https://app.replay.io/recording/comment-is-created-with-draft--eccedc3e-ea86-4b4a-88d7-e11f950169f3)

**Comment by abstractalgo** [comment]
This is all pretty much the "desired" behavior.

The change with persisting comments added the ability to persist unsubmitted text per comment or reply.

For the first replay - it just means that there's something persisted from a previous load of the same recording.

For the second - actions to add a comment on both lines create a "pending comment". We can have only one "pending comment", so the content is shared. A slight improvement could be adding additional context for the pending comments, so it tries to restore the exact information. That could complciate things. This UX would be so much better if the editor inside the comment wasn't unmounting/mounting and creating that brief moment of "respawned comment"; without that remounting, the user would get the feeling that only the header field (with richtext info about the source line) changed, which is basically what we want.

For the third one - the same thing, there's only one "pending comment", and we just try to keep the text you've written from being lost.

All was described here: https://github.com/RecordReplay/devtools/pull/5864

**Comment by jasonLaster** [comment]
> The change with persisting comments added the ability to persist unsubmitted text per comment or reply.

That makes sense. It looks like today we store the comment/reply globally, but it should also be associated with the location. 

> This UX would be so much better if the editor inside the comment wasn't unmounting/mounting and creating that brief moment of "respawned comment"; without that remounting, the user would get the feeling that only the header field (with richtext info about the source line) changed, which is basically what we want.

Agreed. It should be possible to have multiple drafts. And avoiding the remounting would be smoother.

**Comment by abstractalgo** [comment]
After a discussion, this will be a two-part thing:
- [ ] associate draft comment with additional context (e.g. source line) to de-dupe drafts
- [ ] investigate using `ReplaySession` instead of local storage

**Comment by jaril** [comment]
Closing this as the top 3 issues outlined in the original post have been fixed since.
