### ISSUE TITLE
Add React Testing Library + Redux test setup

### ISSUE THREAD

**Issue by markerikson** [RecordReplay/devtools#5917]
We currently only have a handful of unit tests in the codebase, and those are true "unit" tests that just check some basic functions.

I want to add the ability to test Redux-connected React components.  This will require:

- Adding React Testing Library
- Adding a `render` wrapper function that either creates or accepts a Redux store, and renders a `<Provider>`, per https://redux.js.org/usage/writing-tests#components

I'll hold off on doing anything with `msw` for mock data fetching for now.

This is prep for #5903 , so that I can add some unit tests for the entire "log messages" section of the UI (list component, filter text input, filter checkboxes) and verify that it works before I start rearranging things.

**Comment by jaril** [comment]
Done!
