### ISSUE TITLE
Run e2e tests on pushes to master

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#5928]
I tried fixing this in https://github.com/RecordReplay/devtools/pull/5563 but it got backed out for reasons I don't understand.  We need to be running tests on pushes to master in all our repos or we'll never be able to figure out what is going on when perma-failures or intermittent failures start showing up in the tests.

**Comment by abstractalgo** [comment]
If we want to just run tests on pushes to `master`, that's fine, and they'll be as flaky as on PRs, with questionable value then.

If we want to block deployments on tests, then we'd need to improve our tests. @hbenl is now working on having sourcemaps with recordings (see list with PRs bellow), and he mentioned that it would indeed be much easier to improve tests once those are in.

Source maps:
- https://github.com/RecordReplay/gecko-dev/issues/759
- https://github.com/RecordReplay/gecko-dev/pull/760
- https://github.com/RecordReplay/backend/pull/5031

Also related: there were also sometimes problems with the way we trigger our e2e tests - we poll for Vercel deployment, and then start them. It also seemed unreliable, and the tests timedout in combination with that, but even with https://github.com/RecordReplay/devtools/pull/5668 (don't poll, but instead manually deploy to Vercel and trigger tests in succession) it was still behaving pretty much the same.

**Comment by abstractalgo** [comment]
We can enable them without blocking deployment (^ the PR) and improve tests over time and also decide if we want to block on failures.

**Comment by abstractalgo** [comment]
Spend some time debugging the GHA action but couldn't find obvious wrong things with it in that time. https://github.com/RecordReplay/devtools/pull/5668 is worth resurrecting.

**Comment by abstractalgo** [comment]
See last comment in:
- https://github.com/RecordReplay/devtools/pull/6042
