### ISSUE TITLE
`Loading...` state on console input looks broken while video is playing.

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#5936]
I'm not 100% sure what is supposed to be going on here, but if you have the console open, and you use `space` to play the video, the console prompt renders a `Loading...` statement *under* the chevron prompts:

https://user-images.githubusercontent.com/5903784/159622535-28ecda06-3bad-49c0-bee1-d7b4e63bd08c.mp4

Replay: https://app.replay.io/recording/loading-statement-under-chevron--1f1ea0d7-dc94-4f46-b2fd-64030b2d0148

**Comment by jcmorrow** [comment]
Hope you don't mind me putting your face here @jaril, this looks very up your alley!

**Comment by jaril** [comment]
Yeah this is for me!

**Comment by jaril** [comment]
Fixed by #5941.
