### ISSUE TITLE
Dock dropdown should overflow its panel container

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#5939]
**Steps to Reproduce:**

1. narrow down your window
2. open the dock dropdown

**Expected Result:**

It should be fully visible

**Additional Context:**
<img width="312" alt="Screenshot 2022-03-23 at 11 01 02" src="https://user-images.githubusercontent.com/9800850/159673951-7cbd5ed3-876e-4c49-b384-a39cdedb40d5.png">

**Comment by jasonLaster** [comment]
I think we can achieve this with a React Portal
