### ISSUE TITLE
Conditional filter UX cleanup

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5945]
There are a few dark theme issues to address here

**Comment by jaril** [comment]
@jonbell-lot23 Got a list of specific ones that we consider a done state for this issue? Or is this a string around your finger for something you're intending to get around to yourself, in which case maybe leaving it out is okay?

**Comment by jonbell-lot23** [comment]
Neither and both -- we should keep this issue where it is, and I know what to fix

**Comment by jaril** [comment]
Got it!!

**Comment by jonbell-lot23** [comment]
Closing this out in favour of https://github.com/RecordReplay/devtools/issues/6418
