### ISSUE TITLE
[dark] Ready when you are! could use a tad more saturation

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5971]
It feels like this modal and perhaps others could use a bit of zypsy blue or straight black

<img width="744" alt="Screen Shot 2022-03-24 at 9 16 54 PM" src="https://user-images.githubusercontent.com/254562/160053344-ad8b755e-2cef-4209-97ad-67217277a71b.png">

**Comment by jonbell-lot23** [comment]
Good call, this page somehow missed our dark theme update.

@jasonLaster and @jaril can you remind me how to trigger the "ready when you are" screen? I know there's a way but I forgot it

**Comment by jasonLaster** [comment]
pro tip you can call any action from the console like this `app.actions.setUnexpectedError` just copy and pasted this which should just work. by the way, you could do something similar in storybook to have this story show up too :)

```js
app.actions.setUnexpectedError({
    message: "Ready when you are!",
    content: "Replays disconnect after 5 minutes to reduce server load.",
    action: "refresh",
  })
```
