### ISSUE TITLE
[dark] Collaborator request modal 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5975]
<img width="746" alt="Screen Shot 2022-03-25 at 7 46 47 AM" src="https://user-images.githubusercontent.com/254562/160143788-85a6bfb5-7f67-4734-bf49-820916baa153.png">

**Comment by jasonLaster** [comment]
This component would be tougher to just show because you also need to see a replay with an open request. 

You could either do that or fake it. In this case, I'd use one account to request access to a private replay and then view that replay with a second account that has permission to view the replay.

**Comment by jonbell-lot23** [comment]
A note about needs-design -- we should distinguish between "needs UX thinking" versus "the design is well understood but Jon needs to do some front-end work." This ticket doesn't need design, it's just a dark theme regression.

**Comment by jonbell-lot23** [comment]
This was fixed in another ticket. Screenshot:

![image](https://user-images.githubusercontent.com/9154902/160488035-dfc40c5b-53b2-4d72-816b-71fc36c98fec.png)
