### ISSUE TITLE
New team dialog doesn't look right in dark mode

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#5978]
Looks like this, which seems wrong:
![Screen Shot 2022-03-25 at 12 49 52 PM](https://user-images.githubusercontent.com/452453/160191815-9207e094-cdf0-4715-a3b5-c0bfd154d622.png)

**Comment by jasonLaster** [comment]
yikes

**Comment by jonbell-lot23** [comment]
Ugh, I fixed another bug one level deeper (when you successfully create the team) so I feel like this regression was caused by something else. bg-white is the bane of my existence.
