### ISSUE TITLE
Credit card field looks odd in dark theme

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#5989]
Hey @ryanjduffy I remember we talked about how we pull this information externally, so I'm not sure how to fix this:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/9154902/160331300-0d4fba2f-2bf0-45cd-a6dc-0b0cc5b92069.png">

(It's also dinnertime so it's possible the fix is easy but I can't address right now)

See also https://github.com/RecordReplay/devtools/issues/5987 that I just fixed on my way to discovering this

**Comment by ryanjduffy** [comment]
You can use these global classes (https://stripe.com/docs/js/element/the_element_container) or we can customize them with our own classes / inline style using the `options` prop on the `CardElement` component (https://stripe.com/docs/js/elements_object/create_element?type=cardNumber).

**Comment by jaril** [comment]
@jonbell-lot23 still looking good for this sprint or move to next one?

**Comment by jonbell-lot23** [comment]
Always assume this one until I move it

**Comment by jonbell-lot23** [comment]
@ryanjduffy I wasn't able to figure this one out. Here's a Loom explaining what's up:
https://www.loom.com/share/826b19f1ea6f48299c5e9910340a5db4?from_recorder=1&focus_title=1

I want to pass a dynamic color into the element like so to make it work in dark/light themes:
color: "var(--body-color)"

But this syntax isn't working, for any design variables. Do you have any suggestions?

**Comment by jonbell-lot23** [comment]
> The CC field is in an iframe so the CSS doesn't cascade across that boundary. We'll have to do something like this I think
> 
> 
> 
> https://stripe.com/docs/js/appendix/style

Yup, that's the exact code I'm using. But now I need it to work with design variables.

**Comment by ryanjduffy** [comment]
CSS variables can't be passed across the document boundary so we'll have to get their value in script and then refresh the component on theme change.

```window.getComputedStyle(document.documentElement).getPropertyValue("--theme-focus-border-color-textbox")```

**Comment by ryanjduffy** [comment]
I don't recall off hand how the theme change is managed (probably redux?) so it'll probably look something like:

```jsx
function PaymentComponent({theme, ...otherProps}) {
  const style = useMemo(() => {
    const bodyColor = window.getComputedStyle(document.documentElement).getPropertyValue("--body-color");
    return {
       theStripeClassName: {
           color: bodyColor
      }
    };
  }, [theme]);

  return <...>;
}
```

**Comment by jonbell-lot23** [comment]
Thanks @ryanjduffy ! PR is up here: https://github.com/RecordReplay/devtools/pull/6272
