### ISSUE TITLE
Consider changing keyboard shortcuts to match Chrome Devtools

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6]
Keyboard shortcuts in the devtools do not quite match those in Chrome.  For example, global search in files is cmd-shift-F in our devtools, and cmd-option-F in Chrome.  Most of our users will be used to Chrome's devtools, and having matching keyboard shortcuts will reduce onboarding issues.

**Comment by jasonLaster** [comment]
I agree with this principle. 

I think matching expectations is important with VS Code (editors) DevTools (chrome)

 cmd-shift-F comes from vscode, sublime, and other editors, so i think it is safe. We should also expose it via a context menu somewhere.
