### ISSUE TITLE
Add allow list / block list config to Org settings pane

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#6019]
We support setting an allow list / block list for organizations but that has to be configured manually and should be user-configurable.

**Comment by jaril** [comment]
Allow / Block list for what thing??

**Comment by jaril** [comment]
@ryanjduffy do you think we'll be getting around to this next/next-next sprint? Or move it to May?

**Comment by ryanjduffy** [comment]
It can move to may

**Comment by jaril** [comment]
@ryanjduffy What's your gauge on urgency for this issue? I don't have much context so can't say if this is super important to figure out soon, or is a nice to have that can be iceboxed, or somewhere in between.

**Comment by ryanjduffy** [comment]
Dropping it into next sprint. Small enough that I'd rather get it done than continue to punt it out.

**Comment by ryanjduffy** [comment]
Fixed by
- [ ] https://github.com/RecordReplay/devtools/pull/6830
- [ ] https://github.com/RecordReplay/backend/pull/5639
