### ISSUE TITLE
E2E test inspector-05 fails intermittently

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6037]
It looks to be source related. Here's a replay:

https://app.replay.io/recording/b927ab42-281c-4b97-a446-51b57f920f2e

**Comment by jaril** [comment]
Looks like this is now passing. Not sure what happened but I'll take it:

https://github.com/RecordReplay/devtools/runs/5862964886?check_suite_focus=true#step:4:2449

**Comment by jaril** [comment]
@hbenl Any idea which patch did the trick? It's not [this guy](https://github.com/RecordReplay/backend/commit/4ab4fa4112fcfc1dc88171599f7745b0995b19fe), is it?

**Comment by hbenl** [comment]
I wanted to say #6198 :smile: but then I realized that the recording shows another issue, namely #5384.

**Comment by jaril** [comment]
> @jaril I wanted to say #6198 😄 but then I realized that the recording shows another issue, namely #5384.

🤦‍♂️ totally missed that. Thanks!!!!!
