### ISSUE TITLE
Browser forward/back buttons don't do anything

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6050]
The forward/back buttons update the URL to change the current point/time, but the UI doesn't update to match.

**Comment by jaril** [comment]
@loganfsmyth Any chance you can get a replay? Tried reproducing but couldn't.

https://user-images.githubusercontent.com/15959269/161582201-d889981d-605e-4038-bb83-776973ca871a.mov

**Comment by loganfsmyth** [comment]
Hmm that video is so quick I have a hard time following it, but here's a recording: https://app.replay.io/recording/repro-for-devtools6050-clicking-to-create-history-entries-then-pressing-forwardback-does-nothing--96aa54d3-c25e-49af-ad6c-13c67cd3a6d7?point=95732973348708141776794826609529436&time=37580&hasFrames=false

**Comment by jaril** [comment]
> Hmm that video is so quick I have a hard time following it, but here's a recording: https://app.replay.io/recording/repro-for-devtools6050-clicking-to-create-history-entries-then-pressing-forwardback-does-nothing--96aa54d3-c25e-49af-ad6c-13c67cd3a6d7?point=95732973348708141776794826609529436&time=37580&hasFrames=false

Whoops yeah, could have been smoother. Checking!!

**Comment by jaril** [comment]
I think in this case we shouldn't be pushing history state for previous pause points. Hijacking the browser back/forward buttons for timeline navigation feels off. It also gets in the way in flows where you're looking at a replay, playing around with it, and hitting back to go back to the Library (or wherever you came from).

Will file a PR!
