### ISSUE TITLE
🐛 on DevTools: Attempting to delete comments from Rep...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6062]
:bug: on DevTools: Attempting to delete comments from Replays
Steps to recreate:
• 		Log in to Replay
• 		Open a Replay
• 		Click on the #video or click on existing comments
• 		No comment dropdown visible
Expected: Dropdown menu on hover or click
Results: The three dots for comment settings aren’t visible

I’ve attached a video of the bug and a screenshot of what is missing or expected.
Thank you! \- [Ben](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1648614446028709)

**Comment by jaril** [comment]
let's get a replay for this.

**Comment by jaril** [comment]
This looks like it might have been fixed: 

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/15959269/161123786-26511643-b50c-44f1-a7f3-ee1cd126c596.png">

[Confirming with QA](https://replayio.slack.com/archives/C02GEJCC9JP/p1648750892225089). Will close when confirmed.
