### ISSUE TITLE
Pending comments should have an ID  

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6063]
**Description:**

This replay shows that it is possible to add a new reply while an existing one is in flight. And when you do, the second one's content is replaced with the first. This is an easy fix once we can create the ID in the client

https://app.replay.io/recording/editing-two-comments-in-parallel--5f154ef4-797e-4299-a520-d90b178c6ab6?point=50624894377369512462688679419185803&time=20726&hasFrames=false

**Comment by jcmorrow** [comment]
I've closed https://github.com/RecordReplay/backend/pull/5091, see: https://github.com/RecordReplay/backend/pull/5091#issuecomment-1084932991

But it's still possible to solve this, we'll just hold the ID's locally (which we were going to need to do anyways).

**Comment by jcmorrow** [comment]
Happy to have this assigned to me, but I'll also note that depending on how far @bvaughn decides he wants to go on #6138 he may or may not end up tackling some or all of this.

**Comment by bvaughn** [comment]
Yeah seems like this one should hold off for now.

**Comment by bvaughn** [comment]
Now that https://github.com/RecordReplay/devtools/pull/6335 has landed, this is no longer blocked.

**Comment by bvaughn** [comment]
Looks like https://github.com/RecordReplay/devtools/pull/6335 fix this so I'm going to close it 😄
