### ISSUE TITLE
Show security sensitive information when sharing a recording publicly

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6064]
The upload screen for a recording shows security sensitive information when sharing a recording publicly, but if a recording has been created and then the "share" screen is used to make it public, the security sensitive information is not shown.  Sensitive information in a recording should be shown when the "share" screen when opening a recording for public access.

**Comment by jasonLaster** [comment]
cc @jonbell-lot23 

We currently show the "sensitive information" link in the Info panel and upload screen. We should have a similar treatment in the share modal

**Comment by jonbell-lot23** [comment]
Prioritisation exercise complete. I'll get to this by early next week

**Comment by jonbell-lot23** [comment]
Hey @bhackett1024 ! I have two screens to share here. One is the simplest possible tweak, where we add a line of text explaining security stuff:
![image](https://user-images.githubusercontent.com/9154902/161876876-ebb9547e-7668-418d-b10c-5d06bcddebf0.png)

Just wanted to call out that this current share screen has a lot of UX issues that we've discussed over the past year, and adding this line of code just amplifies my concerns that much more :)

Here's how it would look after we aligned the share dialog with our other components such as our upload screen:
![image](https://user-images.githubusercontent.com/9154902/161877012-7243f54a-1568-482d-80d1-bb967ba52bda.png)

Sharing for paper trail reasons. We will eventually update this share screen!

**Comment by jasonLaster** [comment]
@jonbell-lot23 The second option does not look as bad as it did a couple of months ago :)

**Comment by jonbell-lot23** [comment]
Tangible next steps: I should be able to slap in the single line of text pretty easily. On my plate this sprint.

**Comment by bhackett1024** [comment]
The new line looks good to me, we should be clear in the "learn more" link about where in the viewer the user can go to see details about what is in the recording.
