### ISSUE TITLE
Show that node recordings include environment variables in security sensitive information

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6065]
All node recordings include the contents of the environment in which they ran.  Once we support redaction this will change, but for now we should indicate this when sharing a recording publicly.  Since node recordings are only created via API keys, and API key recordings are not public, a recording needs to be explicitly made public to expose this information, but the "share" screen needs to indicate this.  See also https://github.com/RecordReplay/devtools/issues/6064

**Comment by bhackett1024** [comment]
For now I think it's fine to just say more generally that the recording includes all environment variables.

**Comment by jonbell-lot23** [comment]
Note to self: this should trigger on "is node recording"

**Comment by jonbell-lot23** [comment]
Prioritisation exercise complete. I'll get to this by early next week

**Comment by jonbell-lot23** [comment]
Here's a quick sketch -- 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/9154902/161180906-022f62ae-1a60-4866-ab56-bb053e7a2e62.png">

I should be able to write the code as well, stay tuned.

**Comment by jasonLaster** [comment]
Seeing this makes me think we should revisit the Security panel in the Node context as well. 

1. The 4 domains dont make sense in Node
2. Do the security sections make sense here?

**Comment by jonbell-lot23** [comment]
1. Good call
2. Yeah Jaril and I thought no

**Comment by jonbell-lot23** [comment]
* I put a half-done draft review [here](https://github.com/RecordReplay/devtools/pull/6141/files). Tomorrow I need to figure out how to trigger the "is node recording" thing. 

* Duh, there's no upload screen for a node recording. So that screen is completely irrelevant, not just the domain stuff.
