### ISSUE TITLE
Fallback to analyses for old recording hit counts

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6076]
This is a blocker for turning on Code Heat Maps by default. When someone has Code Heat Maps enabled and is viewing a recording that is too old to support it, we should fall back to an analysis. One suggestion was shoving a sentinel value into the store upon receiving the related error message (Linker is too old or something like that), and using that errorMessage to set a flag in localState for that recording. Another option would be to check the linker version just like we do in the backend, but I think we are trying to keep the amount that the clients know about Linkers to an absolute minimum, so that's probably not a great idea.

**Comment by bhackett1024** [comment]
It would be fine for the backend to return an error that a recording is too old.  I don't know if the fallback operation will be efficient enough for a good UX, our biggest concern here is to make sure we don't kill performance regardless of the settings that are enabled.

**Comment by bhackett1024** [comment]
Hmm, I might be misunderstanding the idea here, do we want to show the heat map in old recordings, or is there older functionality like the line hits hover that is based on the source hit counts now and needs a fallback to continue working?

**Comment by jcmorrow** [comment]
Yeah, this is falling back for old operations like line hovering, which we were already using analyses for, but now we use hitcounts if it's available. And I actually did this this morning in https://github.com/RecordReplay/devtools/pull/6078!

**Comment by jcmorrow** [comment]
But yeah, agreed that other features (for instance, the outline hitCount for every function in a file) we are just not going to do for older recordings, since it means fetching analyses for potentially *many* breakpoints, which could cause problems.
