### ISSUE TITLE
Search doesn't return results from node_modules

### ISSUE THREAD

**Issue by bgirard** [RecordReplay/devtools#6083]
**Description:**
I use the Network inspect to find a request. But the backtrace isn't helpful because it looks like a function was scheduled (setTimeout maybe). So try to find who calls `dispatchRequest` from axios. But it gives me no results even though this file clearly exists.
<img width="943" alt="Screen Shot 2022-03-30 at 1 44 00 PM" src="https://user-images.githubusercontent.com/793565/160927570-5bf6b594-038f-4cd4-8514-e1ab6b6a3815.png">

**Steps to Reproduce:**
Search in node_modules

**Expected Result:**
Should find axios results.

**Comment by bgirard** [comment]
Looks like the result should have been here: https://sourcegraph.com/github.com/axios/axios/-/blob/lib/core/Axios.js?L109:15

Not sure why it's not in my stacktrace but that's another issue.

**Comment by jaril** [comment]
Thanks for filing @bgirard. This looks like it's related to https://github.com/RecordReplay/devtools/issues/5418.

I've got this queued up for this week. Will keep you updated as we get a fix in!
