### ISSUE TITLE
:bug: on DevTools: Admin changed to a developer
Steps to ...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6090]
:bug: on DevTools: Admin changed to a developer
Steps to recreate:
• Log in to Replay
• Click test permissions
• Click the test permission settings
Expected:  Chris Burton to be Admin
Results: Chris Burton is a developer \- [Ben](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1648690799711219)

**Comment by jaril** [comment]
This seems to be [passing on prod](https://www.qawolf.com/test/cky1ulpv0000h09l97hvfhn2x).

[Confirming](https://replayio.slack.com/archives/C02GEJCC9JP/p1648691719034929) if we can close this.
