### ISSUE TITLE
🐛 on DevTools: Rewind/Fast forward button can not be ...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6094]
:bug: on DevTools: Rewind/Fast forward button can not be clicked in console.
Test: <https://www.qawolf.com/test/ckzcww59j162991150mf8l6kh88q?suite_id=cl1egyo4y119838851o3uabwoaal|Advance and rewind callstack from print statement and view callstack as user role>
Steps to repro:
1. Log in
2. Go to recording
3. Enter devtools
4. Open source
5. Open utils.js
6. See that Rewing/Fast forward can't be clicked
Apologies cant access replay app needed to take a separate video. \- [Ben](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1648702198916609)

**Comment by jaril** [comment]
This looks like it's working: https://www.qawolf.com/test/ckzcww59j162991150mf8l6kh88q

[Confirming](https://replayio.slack.com/archives/C02GEJCC9JP/p1648702198916609) to see if it's still a problem. Closing otherwise.
