### ISSUE TITLE
[Debugger] Editor jumps to the panel while scrolling

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#610]
https://replay.io/view?id=d867a8b1-2238-4880-ab08-d08b0367da5e

STR:

1. add some breakpoints in the editor
2. edit them, leave cursor in the input
3. scroll down

at some point the editor will jump back to the panel...

**Comment by jasonLaster** [comment]
@jaril here's a good video of what's happening
https://www.loom.com/share/fb64da4e5d89416593352614cff78cff

**Comment by jaril** [comment]
Still not sure why this is happening but this is a reproducible example:

https://replay.io/view?id=377dad23-8188-4eb3-bb27-4166f6a85bc3

The jumping behavior appears to happen when you place a breakpoint on a line that has column breakpoints (`console.log("stuff");`. It doesn't happen if you place a breakpoint on lines without column breakpoints (`logStuff();`).

Will keep looking into it.
