### ISSUE TITLE
[Console] There should be a way to clear user-evaluated statements in the console

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#611]
The console gets filled up pretty quickly with just logpoints. It gets way worse when you're jumping between multiple logpoints and evaluating statements at that pause point. Because we insert evaluations in the console relative to where they were executed, it becomes harder to see the logpoints that the user may be relying on for navigation. 

This can be fixed by adding a button for clearing all user-evaluated statements in the console.

**Comment by jasonLaster** [comment]
Thanks!

I couldn't find the original issue for adding a remove button to a console evaluation. So lets treat this issue as both :) 

Do you have an idea for where clear all evals button would go? Maybe we could put it a context menu when you click on an eval? This is hidden, but atleast the label would be clear.

**Comment by jaril** [comment]
Ideally it would be visible and not just tucked away in a context menu. We already have a clear button in the console, so it feels natural to put this beside that. But it's challenging to think of an icon that conveys "Clear evaluations" while still being distinct from the clear button's trashcan icon.

What if we think of it more as a "refresh" instead of a "clear"? Right now, the solution in Replay when the console becomes a mess of logpoints/events/evaluations is to just refresh the page anyway. Why not just riff off of that idea and put it in the console as a button?

In the future it would also be useful since it can be used to flush out other non-logpoint changes (e.g. expanded comments) to the console and allow the user to start from scratch.

![image](https://user-images.githubusercontent.com/15959269/92549938-6b3d1400-f228-11ea-9d1f-8e8c9acf748f.png)

**Comment by jaril** [comment]
We should also probably think about what to do with that clear button. In the context of Replay, I can't think of a reason why a user would clear __all__ of their console messages. Sure they might want to get rid of all evaluations, but logpoints? 

There should definitely be a way to clear all logpoints, but I think we can create a better UI for it somewhere else in devtools.

So if the console's clear button isn't doing being used much anyway, then we should either repurpose it as the clear evaluations button, or replace it with the refresh button instead.
