### ISSUE TITLE
:bug: on DevTools: Clicking Control+Shift+O opens file se...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6123]
:bug: on DevTools: Clicking Control+Shift+O opens file searchbar instead of function searchbar

(in the video I'm clicking Control+Shift+O offscreen to open the searchbar, when I enter @ini it should populate the results with the @initialize function. When I delete the search term the placeholder text reveals that the searchbar is searching for a file, not a function) \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1648853963377989)

**Comment by jaril** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/15959269/161676182-ec27cacd-a903-4b94-b9ee-0f2189bb222f.png">

**Comment by jaril** [comment]
It looks like this was being caused because we listed the wrong shortcut in the command palette. It should be:
Current file function search: `Cmd/Ctrl+Shift+O`
Global function search: `Cmd+O`

**Comment by jaril** [comment]
Keeping this open until we get confirmation that the test is passing.
