### ISSUE TITLE
Improve DevTools Loading

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#6124]

**Comment by jaril** [comment]
Do you know what this is referring to? If we just put this as a note during the planning meeting it's likely referring to https://github.com/RecordReplay/devtools/issues/5848, in which case we should use that to track it instead.

Let me know!

**Comment by jaril** [comment]
@gideonred bump

**Comment by gideonred** [comment]
It was an item created in the Q2 Airtable: https://airtable.com/appSzSiRS6UdFlXKj/tbl9fqrlZz2qMbcAF/viwwMHLAYzDi0oFZa/recDLWDGrE3Q8gagX?blocks=hide

Jason created it and Jon upvoted it. So I suspect they know more.

**Comment by jasonLaster** [comment]
Closing as a dupe of #5848
