### ISSUE TITLE
React devtools does not pay attention to annotation kind

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6132]
I noticed that setupReactDevTools does not seem to pay attention to the annotation kind when feeding them to the frontend here:

https://github.com/RecordReplay/devtools/blob/10312a15c8b802dd07124a3c4a94963db0587737/src/ui/actions/reactDevTools.ts#L19

React devtools annotations will have a "react-devtools-bridge" kind, per `__RECORD_REPLAY_REACT_DEVTOOLS_SEND_BRIDGE__` in gecko-dev.  If there are other kinds of annotations in the recording (I don't know if we're doing that right now, but we certainly will in the future) then this will I think break when trying to process those annotations.  Only annotations with the right kind should be fed to the frontend.

**Comment by markerikson** [comment]
I'm going to be working on adding Redux DevTools support shortly.  While I haven't yet investigated or wrapped my head around how the React DevTools integration works, the bits and pieces I've picked up from discussions like this have me assuming it will behave similarly.  So, yes, this would likely be an issue, and we should fix that shortly.

**Comment by bhackett1024** [comment]
Sounds good.  I just added a writeup at https://github.com/RecordReplay/devtools/issues/6126#issuecomment-1086903866 describing how things currently work with the react devtools integration, and how they could work with a client side backend once we have persistent object IDs (later this year, but I'd like to start experimenting in Q2).

**Comment by bvaughn** [comment]
> I'm going to be working on adding Redux DevTools support shortly. While I haven't yet investigated or wrapped my head around how the React DevTools integration works

@markerikson Happy to talk this through with you if you'd like.

**Comment by jaril** [comment]
@markerikson this still look right for next sprint? or do we need to move it?

**Comment by markerikson** [comment]
Yeah, I should be starting to make actual code changes in the next few days.
