### ISSUE TITLE
When leaving a comment, keyboard shortcuts should be disabled

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6136]
As reported by Jason, it's possible to press Shift-T in comments and see the entire theme shift. That's a bug.

But there are other issues to consider as well. We have multiple places where keyboard input is received, including:

* Comments
* Console
* Editing the Replay title
* Print statements
* etc

And every one of them might fall into this same keyboard shortcut issue.  Here's what I propose:

1. Remove our Shift-T shortcut. Command-K, D-A (for "Dark Theme"), Enter-> is how I toggle quickly and it's fine.
2. Disable keyboard shortcuts when in comments or editing the Replay title
3. Let's keep an eye on this issue, because it's a broader system we need to think through

**Comment by jasonLaster** [comment]
True - I fixed the `shift-t` this morning, but it'd be better to do this in a more intentional way.

Perhaps `cmd-k` should still launch the command palette. Not sure, but that should be a decision not an implementation detail

**Comment by llaver** [comment]
This occurs with Shift+F (Toggle Edit Focus Mode) as well. For me personally, I never expect only shift and a key to perform a command. I always expect a modifier (ctrl/cmd) plus a key, and then shift as an extra modifier for even more commands as needed.

**Comment by jasonLaster** [comment]
Good call - just found that too :)

**Comment by jonbell-lot23** [comment]
Hey @jaril remember our discussion three months ago about when to use single characters, when to use shift, and when to use additional modifiers? [Here's where we were tracking the details](https://www.notion.so/replayio/ea1e85a8ad6d46b88bb315a1cf337243?v=8ea1fd7ed2bf4e0dbbd7cd1c4bbecc37). 

![image](https://user-images.githubusercontent.com/9154902/161632506-32531388-c195-4a47-91c7-5cf7fc2bfd37.png)

One approach is to make absolutely everything have a keyboard modifier, which will significantly decrease use because they'll be hard to remember. Might as well just use the command palette.

Another approach is to keep using shift as a modifier, which increases use. But we'd just need to be careful about text input. It should only work if you're not adding a comment, in the console, etc.

--

Here's what I propose:

1. Remove the dark mode keyboard shortcut entirely
2. Change focus mode to a keyboard modifier like command-option-shift-F
3. More medium-term, we should think through these different approaches.
