### ISSUE TITLE
:bug: on DevTools: Entering specific replay listed return...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6139]
:bug: on DevTools: Entering specific replay listed returns an internal server error.
Steps to repro:
1. Log in
2. Enter <https://www.qawolf.com/test/ckybr3rgb000609l94glz0d9y?suite_id=cl1h4hz2n61316351n978ke9r8g|"User role commenter test">
3. View internal server error
Apologies, whenever I launch replay to take a recording the app crashes. Had to take a normal recording. \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1649031414020109)

**Comment by jaril** [comment]
https://replayio.slack.com/archives/C02GEJCC9JP/p1649031414020109

<img width="378" alt="image" src="https://user-images.githubusercontent.com/15959269/161609351-596ccbb0-e2dd-4fbb-9901-51f2b1ce89d0.png">
