### ISSUE TITLE
MarkupContextMenu is not defined

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#615]
./src/devtools/client/inspector/markup/markup.js in event at line 341:5

```js
  get contextMenu() {
    if (!this._contextMenu) {
      this._contextMenu = new MarkupContextMenu(this);
    }
    return this._contextMenu;
  },
  get eventDetailsTooltip() {
    if (!this._eventDetailsTooltip) {
      // This tooltip will be attached to the toolbox document.
```

https://sentry.io/organizations/replay/issues/1884740055/?project=5399075&referrer=alert_email

**Comment by jaril** [comment]
This is because we've disabled the markup context menu for now:

https://github.com/RecordReplay/devtools/blob/4abf5011e1f3e1a519774f7efaa58ec51df9929c/src/devtools/client/inspector/markup/markup.js#L40-L44

Enabling the MarkupContextMenu again should fix it.

**Comment by jasonLaster** [comment]
I _fixed_ it by disabling the call :) we can come back to this
