### ISSUE TITLE
window.elementIsHovered is not defined

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#616]
./src/ui/components/Timeline/index.js in apply at line 269:30
```
    this.debugger?.clearPreviewPausedLocation();
  }
  hoverTimer = () => {
    const { hideTooltip } = this.props;
    const isHovered = window.elementIsHovered(this.$progressBar);
    if (!isHovered) {
      clearInterval(this.hoverInterval);
      hideTooltip();
    }
  };
```

https://sentry.io/organizations/replay/issues/1884447388/?project=5399075&referrer=alert_email

**Comment by jaril** [comment]
This shouldn't happen anymore. The timeline is now hidden (#605) until the recording is fully loaded, so it shouldn't be possible to hover on the timeline before `window.elementIsHovered` is defined here: https://github.com/RecordReplay/devtools/blob/4abf5011e1f3e1a519774f7efaa58ec51df9929c/src/main.js#L117-L123

Closing for now - we can always reopen if we see it again in Sentry.
