### ISSUE TITLE
Replace "internal Error" With more descriptive message

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6170]
We already have some special casing for other error messages. We should say something a bit more user friendly in this case as well.

<img width="846" alt="Screen_Shot_2022-04-03_at_8 12 17_PM" src="https://user-images.githubusercontent.com/254562/161669538-4ad1d2d9-51fe-4d9a-9d34-3e5b96182e31.png">

**Comment by bvaughn** [comment]
Context from bug-bashing session: The frontend just displays the backend error message (if there is one). In this case, "Internal error" seems to be all the backend is sending.

**Comment by jaril** [comment]
> Context from bug-bashing session: The frontend just displays the backend error message (if there is one). In this case, "Internal error" seems to be all the backend is sending.

Lol you're the best thanks!

**Comment by jonbell-lot23** [comment]
Hey @jaril @jasonLaster or @bvaughn -- I can write something up, but I need some more details.

Do we at least know if the issue will be resolved by reloading? If so, I can write something like "An error occurred. Please try reloading."

**Comment by jasonLaster** [comment]
@jonbell-lot23 this is our grab-bag of issues. I think it is safe to say reloading has a good chance of working, but we probably should say something warm and apologetic

**Comment by jaril** [comment]
@jonbell-lot23 wanna sync on this later so i can provide more info??

**Comment by jonbell-lot23** [comment]
Thanks @jasonLaster will add warm generic message here

@jaril don't think we need to meet on this one
