### ISSUE TITLE
Comments shouldn't gray out on submit

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6185]
**Problem**

Last week, I recommended graying-out comments while waiting on the server based on my experience at Twitter. I now realise it's an apples-to-oranges comparison. Tweets can dim out because you're done with them. But comments shouldn't dim or they appear to be broken.

**Proposed fix**

We shouldn't dim and disable the field. A person should always be able to add a new comment or reply, even if the response hasn't yet returned from the server. There's no benefit to preventing further input, but the drawback is the app feels slow and broken.

**Tradeoffs/worst-case scenarios**

Typically "single source of truth" edge cases cause trouble in situations like this. But I'm not sure I see one here. The server will never return data that would overwrite anything you're putting into a text field, so that's not an issue.

The only issue I can imagine is the server failing outright, which would cause a new comment to get lost. In that case, we should count to 10 seconds and display a "try again?" button.

**Comment by jasonLaster** [comment]
@jonbell-lot23 this feels like a technical limitation with the way that comments are built now. We should be able to resolve this though with graphql subscriptions and figuring out why replies can take five seconds. In the meantime, lets close this so we can focus on fixing the flickering and other focus state issues.

**Comment by jonbell-lot23** [comment]
"It will be faster later" isn't a full credit answer because there are always cases where it's not slow, and the dimming/graying will always feel awkward.

Let's cost it and prioritise it. One week ago it didn't do this, so I suspect it won't be super difficult to get right.

**Comment by jcmorrow** [comment]
I'm not sure what the right thing to do is. However, I will drop this in here. If this line is deleted the comments will stop being grayed-out 

https://github.com/RecordReplay/devtools/blob/master/src/ui/components/Comments/TranscriptComments/CommentCard.tsx#L270

Maybe it's a place for you to play around @jonbell-lot23 and see if there's something that still gives a cue that something is in flight but doesn't feel as broken?
