### ISSUE TITLE
New comments should always focus on the new comment textfield

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6186]
**Current**

When I click "add comment", the text field isn't auto-focused.

**Expected**

I should be able to click "add comment" and then immediately start typing my comment.

**Comment by jaril** [comment]
I tried it for all three entry points (video/network monitor/editor) and it seems to work… fine? 

https://user-images.githubusercontent.com/15959269/162046101-397ce065-50ca-4f51-91d0-6f4cc366d71d.mov

Let me know if you can still reproduce it! Or a replay :)
