### ISSUE TITLE
New comment textfield should always appear in the viewport

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6187]
**Current**

It's possible to add a new comment but have it "beneath the fold," where you have to scroll to see it.

**Expected**

When you add a new comment, the region should jump me down to the textfield. (And auto-focus the field, which I've filed in another comment)

**Comment by jaril** [comment]
@jonbell-lot23 Mind getting a replay??

**Comment by jonbell-lot23** [comment]
Here you go!
https://app.replay.io/recording/adding-comments--d4afaf63-1766-4281-a0ef-b06e03e41a19?point=100925270199248397248981589133626899&time=34817&hasFrames=false

In this case, it did scroll down. But there was a strange bug that occurred -- take a look at the video to see the textfield not clear out
