### ISSUE TITLE
Be much smarter about which hitCounts we query for

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6205]
Basically, implement [this idea](https://github.com/RecordReplay/devtools/pull/6162#discussion_r843027633). This is kind of like a first-pass at an naively-AST-aware heat map. The primary insight is that the work that Jason did around identifying the first position in a function along with the lines of that function give us a potentially huge optimization that makes https://github.com/RecordReplay/devtools/pull/6162 totally unnecessary in most cases. Basically: fetching *all* hitCounts for a file should almost never be necessary, we can use places where the hitCount reads as 0 to eliminate whole function bodies from the query. We could also do something quite smart, where we load for the first point in a scope, but then don't actually load the *rest* of the scope until it scrolls into view (or close to view). This gives us outline view with high performance on each smaller scope. I dunno, I have a lot of thoughts on this, but I'm also focusing on network monitor stuff right now, so if anyone else wants to pick this up maybe just ping me for a context dump, otherwise, I'll get to it when I can!

**Comment by jcmorrow** [comment]
As an example, `react-dom` is a file which has 5000 lines in the replay I looked at. From those 5,000 lines it has 3,600 breakable points. When I queried for all of those, 1,800 of them were hit 0 times. So theoretically we could reduce the number of hitsCount we asked for in that file by nearly half. And that's a file which I would expect to have a relatively *high* percentage use rate in a React replay.

**Comment by jaril** [comment]
@jcmorrow Put it in next week sprint let me know if we should move elsewhere

**Comment by jcmorrow** [comment]
I really like this feature, it really tickles my nerd brain, but it's also an unnecessary improvement right now, especially after https://github.com/RecordReplay/devtools/commit/3804c0999f1d26c0741100081e1dd045f79969ae, which is like a simpler version of this (kind of, not really, but it achieves the desired effect). Anyways, gonna close for now, I think this will come up again some day 👍
