### ISSUE TITLE
Loading screen for a recording flickers

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6212]
Copied from https://github.com/RecordReplay/devtools/issues/5848#issuecomment-1088304812.

This loom does a good job of showing the flickering as well. This video is for the loading screen while uploading where as the replay above was for the library.
https://www.loom.com/share/456e6f8e4dbe44c1809b20b17bf3e9da

https://user-images.githubusercontent.com/254562/161664513-601d5732-d27b-4db1-bf50-2bc0bf5d9d7a.mov

**Comment by jaril** [comment]
Notes:
- [replay](https://app.replay.io/recording/climatescape--722902b3-bf45-429a-85c0-eb85c53fae99?point=45757116071041867005331452052111360&time=21390&hasFrames=false) that is being recorded
- [replay](https://app.replay.io/recording/replay-flickering-while-loading--38f93791-5414-4efa-b631-23338090e621) of the replay that's produced after it's saved at 0:10

**Comment by jaril** [comment]
Alright I gave it ~15mins and can't reproduce this. @jasonLaster I might bug you tomorrow to see if this is still a thing (I'd be surprised if it weren't) and what kind of secret incantations are required to make it happen.

**Comment by jasonLaster** [comment]
@jaril wasn't doing anything special. Weird

**Comment by jaril** [comment]
Yeah really can't reproduce this. @jasonLaster closing for now but feel free to reopen the second you see it happen again.
