### ISSUE TITLE
Dont show the trial when there is a payment method

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6214]
We should be able to hide the `trial expiring` badge when the account has an active payment method.

**Why?**
The badge is designed as a warning and there is nothing to worry about at this stage.

<img width="460" alt="Screen Shot 2022-04-05 at 9 49 43 PM" src="https://user-images.githubusercontent.com/254562/161879512-76ec7239-a7d9-4ca2-b52e-7692a499f27d.png">

**Comment by jasonLaster** [comment]
@ryanjduffy is there anything we need to do from a backend perspective here?

**Comment by ryanjduffy** [comment]
i don't think so. I think all the necessary data is already there to fix this.
