### ISSUE TITLE
Hits being incorrectly reported in the gutter

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6242]
https://www.loom.com/share/5c9c5f73897e452a83f465e377375fab

https://app.replay.io/recording/double-upload-screen--28ad79a7-c964-49a5-bd48-de9983e9138d

**Comment by jaril** [comment]
Working on https://github.com/RecordReplay/customer-support/issues/57 this morning so there's a chance I sort this out or I have better explanations in a few hours. @jcmorrow might have to pull you in but I'll let you know! :)

**Comment by jaril** [comment]
Ran into this again today. It looks like the code heat map hits that it's getting is different from the one that findAnalysisPoints is returning.

https://app.replay.io/recording/double-upload-screen--5a80b271-fdbc-4890-9316-01f6d79a031e
https://www.loom.com/share/af4c109fcbdc461fb7b1bea948a2efd7

@jcmorrow would you mind if i assigned this to you??

**Comment by jcmorrow** [comment]
Diagnosis: https://www.loom.com/share/865f7ba8bf5c47838ab1166d0925d536

**Comment by jcmorrow** [comment]
Will submit a patch right now!
