### ISSUE TITLE
Supported OS/Browser

### ISSUE THREAD

**Issue by staabm** [RecordReplay/devtools#625]
Shouldn‘t the readme mention on which platforms RecordReplay works and for which browsers?

I know time travel debbugging only for macos in firefox.. does this project has the same restrictions?

**Comment by jasonLaster** [comment]
That's a great point @staabm 

We support recording a fork of Firefox on Mac OSX.  We are still in closed beta so we don't have any public instructions on how to get setup, but it would be nice to be more transparent.
