### ISSUE TITLE
Dark theme doesn't apply to the pending team invite screen

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6254]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/15959269/162276207-f7afd212-a5d5-4595-9e6c-d28bd8cbe4d9.png">

This is me with my theme set to "dark".

**Comment by xeonstaff** [comment]
I'd love to help!

**Comment by jaril** [comment]
> I'd love to help!

Please go ahead! If you need help getting started feel free to say hi in the [discord channel](https://discord.gg/replayio) 👋

**Comment by xeonstaff** [comment]
> 

on it, would you assign me please?

**Comment by xeonstaff** [comment]
> > I'd love to help!
> 
> Please go ahead! If you need help getting started feel free to say hi in the [discord channel](https://discord.gg/replayio) 👋

Apologies, I can't do it :'( I've just been troubleshooting nvm for an hour and can't even run development

**Comment by jaril** [comment]
> > > I'd love to help!
> > 
> > 
> > Please go ahead! If you need help getting started feel free to say hi in the [discord channel](https://discord.gg/replayio) 👋
> 
> Apologies, I can't do it :'( I've just been troubleshooting nvm for an hour and can't even run development

Oh no! I think you're in the Discord already — I'll ping you and we can go from there. Let's see if we can sort you out and update the setup docs for the next person. :)

**Comment by ashwinkhode** [comment]
Hey @xeonstaff , did you manage to get started on this? Let me know if you need any help

**Comment by xeonstaff** [comment]
I couldn't get started, and honestly, I think I bit off more than I could chew! I'm new to coding and have never made a contribution-- I thought this would be manageable but after poking around for a few hours, I don't think I could fix it even if I could get the dev server running! My apologies-- I'll investigate much more before volunteering in the future. @ashwinkhode @jaril

**Comment by jaril** [comment]
> I couldn't get started, and honestly, I think I bit off more than I could chew! I'm new to coding and have never made a contribution-- I thought this would be manageable but after poking around for a few hours, I don't think I could fix it even if I could get the dev server running! My apologies-- I'll investigate much more before volunteering in the future. @ashwinkhode @jaril

No worries! Feel free to ping me in the discord if you want help going through the set up together

**Comment by ashwinkhode** [comment]
Hey @jaril , does this look correct to you? I couldn't find any design related to this in figma file which I found on discord. Let me know what changes to be made else I can raise the PR :)
![image](https://user-images.githubusercontent.com/53361996/162982444-500d6147-be8c-4721-a752-8f200aa56736.png)

**Comment by jaril** [comment]
> Hey @jaril , does this look correct to you? I couldn't find any design related to this in figma file which I found on discord. Let me know what changes to be made else I can raise the PR :) ![image](https://user-images.githubusercontent.com/53361996/162982444-500d6147-be8c-4721-a752-8f200aa56736.png)

That looks right! Can you post the PR?
