### ISSUE TITLE
Replay throws an error when inspecting certain React components

### ISSUE THREAD

**Issue by bvaughn** [RecordReplay/devtools#6318]
**Description:**
While investigating #6138, I noticed that the React DevTools inside of Replay could not inspect certain components (e.g `CommentEditor`) but not others (e.g. `KeyModifiers`). Seems like anything nested below the `Transcript` component fails to load.

Looking at things, it seems like this is the `remove` method that throws:
https://github.com/facebook/react/blob/f7cf077cca6524877cb837adb9a8ff54242672b1/packages/react-devtools-shared/src/inspectedElementMutableSource.js#L102-L107

It's referring to this variable, which when I inspect it, seems to be a Webpack wrapper module type object rather than an LRU instance:
https://github.com/facebook/react/blob/f7cf077cca6524877cb837adb9a8ff54242672b1/packages/react-devtools-shared/src/inspectedElementMutableSource.js#L40-L45

**Steps to Reproduce:**
1. Open [this Replay](https://app.replay.io/recording/react-devtools-leftright-arrow-functionality-broken--8a21b88e-71d5-4a7c-8c3b-1bc62621164c?point=120396383439142186344776119026196437&time=51002&hasFrames=true#)
2. Jump to the 2nd comment.
3. Search React DevTools for the `CommentEditor` component.

### Replay
https://app.replay.io/recording/replay-react-devtools-cant-inspect-certain-components--153f9b5f-04f3-4728-a2e0-3747448b38e2

~~https://app.replay.io/recording/replay-react-devtools-inspection-error--76ade59a-b26e-48ba-b2f3-2b585a8c6833~~

**Comment by bvaughn** [comment]
The Replay above seems to load okay for Jaril, but I'm not able to view it myself for some reason. 😅

**Comment by bvaughn** [comment]
Huh. I am still unable to view my own replay ([this one](https://app.replay.io/recording/replay-react-devtools-inspection-error--76ade59a-b26e-48ba-b2f3-2b585a8c6833)). It loads a little but then shows an error dialog when I try to fast forward to view the bug I was reporting.

> **Our apologies!**
There was an error. Please try recording again.

Here is a Replay of _that_ error:
https://app.replay.io/recording/replay--377a3283-a104-4c24-bd64-6f387a71fb34

**Comment by bhackett1024** [comment]
It looks like we're having a backend problem specific to that replay, it's hitting https://github.com/RecordReplay/backend/issues/4387.  Can you try making sure your browser is up to date and creating a new replay?

**Comment by bvaughn** [comment]
@bhackett1024 Roger that. Running the latest Replay locally and recorded this one:
https://app.replay.io/recording/replay-react-devtools-cant-inspect-certain-components--153f9b5f-04f3-4728-a2e0-3747448b38e2

**Comment by bvaughn** [comment]
Okay now that I'm able to inspect the Replay in question, it looks like this bug is just a silly one on the React DevTools side. It's calling `.remove()` on the LRU cache but there is no such function. Looking at the [LRU documentation](https://www.npmjs.com/package/lru-cache), it seems like the function it should be calling is `.delete()`.

**Comment by bvaughn** [comment]
Fixed with upstream PR: https://github.com/facebook/react/pull/24477

**Comment by bvaughn** [comment]
Fix has landed up stream. React DevTools release is currently blocked (see https://github.com/facebook/react/pull/24482#pullrequestreview-960623545) but since there's nothing more to be done on this side I'm going to close this issue.

**Comment by bvaughn** [comment]
This fix will go out with the upcoming 4.24.5 release: https://github.com/facebook/react/pull/24503

Then we'll just need to upgrade to that version on our end.

**Comment by bvaughn** [comment]
Updated via #6653 so this should be good!
