### ISSUE TITLE
Default libraries have 10 Replays, 9 of which are not theirs

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6345]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9154902/163082369-fdc4d98d-e1c9-4342-962f-f2a808aa7d5f.png">

Having a demo Replay is fine, but this is a lot. And it's not possible to delete them.

**Comment by jaril** [comment]
This feels like we should get it taken care of sooner than later. Setting it for april — let me knowotherwise @jonbell-lot23

**Comment by jonbell-lot23** [comment]
@jaril I don't know how to fix this. Thoughts?

**Comment by jaril** [comment]
> @jaril I don't know how to fix this. Thoughts?

We have an `example` flag on recordings. I _think_ that's what puts them into the bucket of recordings that forces them into every person's library. This should take <5mins to actually fix once we know which ones we want to keep.

Drag me in later and we can go through it together??

**Comment by jonbell-lot23** [comment]
Assigning to @jaril , grab me when you want to talk about the details

**Comment by jasonLaster** [comment]
Agreed that this is confusing

a) it's a lot of example replays
b) it's impossible to remove (not sure if there's an easy fix)
c) they are not badged
d) these examples are old and not that relevant

How do we want to improve it?

**Comment by jasonLaster** [comment]
One idea which might be in line with some of our recent conversations is to show a Replay examples team in the left sidebar. This team would make it clear that these replays are not theirs. 

We could also add a bit of logic for showing some examples in the library if there are fewer than 3 or so replays... 

Spitballing, dont read too much into this...

**Comment by jonbell-lot23** [comment]
Agree, and here's how I'd chunk the work

Step one: leave only a single demo and call it replay demo. That addresses our short term issue where the library is confusing (and annoying) because it's hard to understand where all these un-deletable Replays are from

Step two: yeah, I'd just make a second team entirely. And there should be a way to delete/mute/opt-out of it. But this is lower priority than lots of our other tasks

**Comment by jasonLaster** [comment]
Works for me. Easy to add and easy to add a pref to hide that team...

**Comment by jaril** [comment]
Recording the old demo recordings here before removing all but the TodoMVC
```
0: "efab9eb0-cb79-43ac-9ff0-5d90e9fb0389"
1: "cf2da81f-3a74-45ba-9241-f6d4361a52f5"
2: "6847ab82-8b0a-4dc2-af73-eb6bf14918e7"
3: "e1003a48-08dd-46f4-b765-2c3666d6ddb0"
4: "30e2b127-f860-408f-b088-ab2004f5eb31"
5: "e64e05d0-7e55-4165-aa03-0e026335785a"
6: "aae188fb-57d2-46af-a23a-0adba3ed0687"
7: "0ff790cd-81fc-441d-8a33-b570fc7850c4"
8: "fc8dade7-d55c-41aa-8f34-8476f809f5d4"
```

Taking everything out except that last one — Replay To Do List("fc8dade7-d55c-41aa-8f34-8476f809f5d4")

**Comment by jaril** [comment]
Finished taking out everything except for Replay To Do List.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/15959269/164341489-e6453c17-dd6d-4b3f-afec-5664b1ee755e.png">

**Comment by jaril** [comment]
Nope this completely broke QA Wolf tests because they use our demo replays for testing. Will figure out some way to let them do their thing and not inundate the users with 9 demo replays as they sign in, but for now this is getting reverted.

**Comment by jaril** [comment]
QA Wolf modified our tests so that we're not dependent on those demo replays anymore. I've taken them off (again) so this is ready to be closed!
