### ISSUE TITLE
"this replay is private" notice shown when viewing a replay that I should be able to view

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6370]
Couldn't reproduce this but have seen it a few times. A refresh would usually fix it. I'll fill this in more if I see more info. Thankfully I saw it in one of our failing mock tests.

Replay of the bug:
https://app.replay.io/recording/replay-of-devtools-lwn0eipop-recordreplayvercelapp--0ce8885d-8740-45fa-95e5-ad507cfb4c74?point=35372522354509346348051743331320704&time=25165&hasFrames=false

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/15959269/163263506-dff0c4c0-c418-4f10-a8c6-f5e3e26f3234.png">

**Comment by jaril** [comment]
Another replay: https://app.replay.io/recording/authentication-error-bug--ebd1809b-16f2-4ad2-bee1-f2b94cc31055

**Comment by markerikson** [comment]
I saw this message yesterday with something that Josh had linked in an issue, but I don't know if it was supposed to be public in the first place.

**Comment by jaril** [comment]
Left a comment in the [replay](https://app.replay.io/recording/replay-of-devtools-lwn0eipop-recordreplayvercelapp--0ce8885d-8740-45fa-95e5-ad507cfb4c74?point=16225927688513434523300555105763403&time=17935.777859103386&hasFrames=true). In short, it looks like we're getting undefined from [this query](https://github.com/RecordReplay/devtools/blob/425e5d83744a30217a52f493a88ffe58960b7c48/src/ui/hooks/recordings.ts#L152-L155).

It's hard to figure out how to proceed on this / whether it's still happening in the first place. Closing this for now and will revive in case we see it out in the wild again.
