### ISSUE TITLE
Add filters to library

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6382]
**Background**

While exploring [Design Library 1.5](https://github.com/RecordReplay/devtools/issues/6265), it was clear that we have three different changes, which I've split into three GitHub tasks:

* [Add details pane to library](https://github.com/RecordReplay/devtools/issues/6384)
* Add filters to library  (this issue)
* [Create CI-specific library design](RecordReplay/design#8)

**The design direction**
![image](https://user-images.githubusercontent.com/9154902/163308609-da267fef-1f59-4876-b754-8c29d1350069.png)

![image](https://user-images.githubusercontent.com/9154902/163309240-8e6cfd73-4f85-4154-903b-f5ad1f685004.png)

GitHub does a great job providing a big list and then letting you filter it. We're looking to do a similar thing, as shown here.

**What's the problem we're trying to solve?**
Our over-arching goal is to make it easier to focus on the replay you're looking for. Our search bar works for plain text, but there's currently no way to only see Replays with comments, or only see replays you've been invited to. In the future, we may want to filter by things like "archived replays" or "test runs". So this filter model helps us get there.

**Shipping now versus shipping later**
The design point of view is that we don't need to save queries just yet. Let's pick a small handful of parameters such as:

* Type: Normal Replay vs CI
* Runtime: Node versus browser
* Date: ("only show replays in last x days")
* Author: Me versus not me

If the textfield is editable and the URL is linkable, we get most of the way to saved queries without having to actually build saved queries just yet.

**Next steps**

Design's going to hand this over to the spirit process to start thinking through the code side of how to light this up.

**Comment by jaril** [comment]
Forgot to add our notes from last time we talked about this. For now, we're going to limit the filters to:
- Runtime: Node versus browser
- Date: ("only show replays in last x days")

### Spec
Allow the users to use GitHub-style filter syntax in the library's search box.
- [ ] It should be able to handle a `created` filter, e.g. `created:YYYY-MM-DD`
- [ ] It should be able to handle a `target` filter, e.g. `target:node`
- [ ] Changes should apply after the user hits enter
- [ ] Filters should be persisted in the URL so they stay intact on refresh
  - [ ] If the user opens a team link with filters in the URL, but they're not a part of that team, they should be redirected to their main library
  - [ ] The library should be able to use the filters in the URL when fetching the recordings

**Comment by markerikson** [comment]
Nit: should it be `createdSince` instead of `created`?  Or should it be `created:>=YYYY-MM-DD`, which I think is how GH does it, but leads into a lot more complication for parsing time range syntax

**Comment by jaril** [comment]
> Nit: should it be `createdSince` instead of `created`? Or should it be `created:>=YYYY-MM-DD`, which I think is how GH does it, but leads into a lot more complication for parsing time range syntax

Totally missed this! 

It's just `created` ([docs](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated)), but yeah we do need to know how to parse greater/less than qualifiers as well!

**Comment by jaril** [comment]
Closed by https://github.com/RecordReplay/devtools/pull/6533
