### ISSUE TITLE
Source doesn't load in the editor.

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6390]
Ran into a situation today where I opened a source (Toolbar.tsx) and there was no loading bar. Instead of the regular text in the editor, there was a string error message that just said something along the lines of "we couldn't map this source properly so it's all broken sorry".

I tried to get a replay but the refresh seems to have fixed it. Filing this here anyway so that it's tracked.

Close this issue if it's been 2 weeks and there's been no further information, since it's not actionable.

**Comment by jaril** [comment]
It's not clear but maybe it's related to https://sentry.io/organizations/replay/issues/3188330864/?project=5399075&query=source&statsPeriod=14d ?

**Comment by jasonLaster** [comment]
cc @hbenl might be related to getting rid of the source queue which should largely help but could have an edge case

**Comment by jaril** [comment]
I've not seen this happen again. Closing this for now and re-opening if we do happen to see it in the wild!
