### ISSUE TITLE
Discard screen is not aligned with the theme

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6404]
Hitting Discard after the upload screen sends you to a temporary page before sending you back to your Library. But it looks like that screen doesn't align with the user's theme (e.g. dark). Screenshots/Replays below.

[Replay with light theme](https://app.replay.io/recording/72f6465a-2e0d-41c7-babb-d1ef4c0a0360)
[Replay with dark theme](https://app.replay.io/recording/upload-screen-discard--27e72fc0-29b7-4207-809a-397c50733660)

x | Before discarding | After discarding
-- | -- | --
Light | <img width="1404" alt="image" src="https://user-images.githubusercontent.com/15959269/163579253-e78fd97d-dcd6-4c99-a919-7dafdfed9e00.png"> | <img width="1412" alt="image" src="https://user-images.githubusercontent.com/15959269/163579273-710dbf92-ffb3-48a9-8bf4-98892dd6097c.png">
Dark | <img width="1790" alt="Screen Shot 2022-04-15 at 6 55 59 AM" src="https://user-images.githubusercontent.com/15959269/163579557-f2194195-e113-40df-a479-be23342eeab5.png"> | <img width="1791" alt="Screen Shot 2022-04-15 at 6 56 07 AM" src="https://user-images.githubusercontent.com/15959269/163579568-1c039d09-5245-47ce-8ff5-4c6b73c88404.png">

**Comment by johnathan-co** [comment]
@jaril I can nab this one if you'd like to assign this to me.

**Comment by johnathan-co** [comment]
I have the changes ready, but I'd like a second set of eyes before on how the modal looks before making the PR.

https://user-images.githubusercontent.com/50154787/163657619-dc3aa0c7-7a33-4ccf-a86b-e8e8aa8ca135.mov

1.  Ensure the general background and modal background flow with the theme
2. I added the logo and centered the items to flow along with other modals that appear throughout the app (e.g. Launch Replay)

**Comment by jasonLaster** [comment]
@johnathan-co looks good! Feel free to open WIP PRs too

**Comment by jaril** [comment]
Closed by https://github.com/RecordReplay/devtools/pull/6417. Thanks @johnathan-co
