### ISSUE TITLE
Accordion bug with big sources

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6425]
Auto-generated from product office hours chat

@jasonLaster brought this up two weeks ago in a product office hours chat and provided this Replay: https://app.replay.io/recording/source-text-is-big--ddeda0c6-f90e-4120-8e95-c95b1d9b7496?point=29531188400505872939761036355962405&time=12461&hasFrames=true

**Comment by jonbell-lot23** [comment]
Assigning to @jcmorrow , feel free to re-assign

**Comment by jaril** [comment]
This was fixed when we applied the accordion to the pause info: https://github.com/RecordReplay/devtools/pull/6284
