### ISSUE TITLE
Clown nose doesn't stop

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6430]
Auto-generated from product office hours chat

Apologies @jaril I forgot the details here since we discussed in product office hours two weeks ago. Do you recall this issue and how to reproduce it? Was this related to the item you fixed last week?

**Comment by jaril** [comment]
I don't remember anything related to a clown nose not stopping? I think this might have been referring to the console stealing focus when toggling the pause with the spacebar. In which case, it's definitely taken care of!
