### ISSUE TITLE
🐛 on DevTools: Clicking “Learn More” now redirects to...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6435]
:bug: on DevTools: Clicking “Learn More” now redirects to a <http://medium.com|medium.com> page with captchas
Steps to recreate:
• Go to <https://replay.io>
• Click Learn More underneath Universal Recorder
Expected: Article of “How Replay Works” by Brian Hackett
Results: Captcha page

Affected tests:
<https://www.qawolf.com/test/ckx0xcemt001e08mtgtbe3rst?suite_id=cl23xky22152137250l0skxbxpdh> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1650248482338499)

**Comment by jaril** [comment]
This passes:

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/15959269/164340346-c95acdfb-a1fd-4a19-8e16-ad92f893dec0.png">

Will confirm, but closing for now.
