### ISSUE TITLE
Hits stuck on "loading" after using file search

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6439]
See replay and comment below.  This seems related to using file search to move around the file and then look at hits on lines nearby.

https://app.replay.io/recording/hits-loading-forever--3a8e97f8-0ee2-4b10-82f5-98af3a912fc0?point=93461343463184194617469009251011317&time=38057&hasFrames=false#

**Comment by jcmorrow** [comment]
Yep, this is a new bug in the front-end code for which parts of a file need to be requested. Good catch, I'll put in a fix for this today!
