### ISSUE TITLE
:bug: on DevTools: different number of errors in console ...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6443]
:bug: on DevTools: different number of errors in console than expected

steps to repro:
• log in 
• go to recording "Airtable: Playwright Test"
• go to devtools
• filter console by errors
• wrong number of errors in console (icon next to errors button says 6, but there are 5 in console)
• some errors in chrome console \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1650312135968939)

**Comment by jaril** [comment]
https://replayio.slack.com/archives/C02GEJCC9JP/p1650312135968939
