### ISSUE TITLE
:bug: on DevTools: exception warning for a large number o...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6444]
:bug: on DevTools: exception warning for a large number of exceptions not appearing

steps to repro:
• log in 
• go to '<http://staging.app.replay.io/recording/7c05aa57-7ceb-4d40-ab05-bc435f704941|staging.app.replay.io/recording/7c05aa57-7ceb-4d40-ab05-bc435f704941>' (this replay should display the exception warning)
• show console exceptions
• no exception warning in console \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1650312693734329)

**Comment by jaril** [comment]
https://replayio.slack.com/archives/C02GEJCC9JP/p1650312693734329
