### ISSUE TITLE
Progress bar in the console can be scrolled away from view

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6459]
We have a blue progress bar at the top of the console messages to indicate that we haven't finish loading all the messages yet.

It's a pretty important signal. But apparently it's possible to scroll and have it be hidden from view. 

https://user-images.githubusercontent.com/15959269/164058330-e4cdf345-4b47-4527-9b1d-968f4f4424bd.mov

**Comment by johnathan-co** [comment]
@jaril [PR](https://github.com/RecordReplay/devtools/pull/6469) is ready. 

Sorry for the delay. This bar is utilized by a few different components, and I thought I was running into issues with the bar on the Markup (Elements) tab after the change, but all seems well.

**Comment by jaril** [comment]
No worries — appreciate the help!!!!

**Comment by johnathan-co** [comment]
I've gotta run and won't be able to pick [this](https://github.com/RecordReplay/devtools/pull/6469#issuecomment-1103192241) back up until tomorrow, so @ashwinkhode feel free to jump in if you'd like! Otherwise, I'll be back tomorrow.

**Comment by jaril** [comment]
Fixed by https://github.com/RecordReplay/devtools/pull/6469.
