### ISSUE TITLE
:bug: on DevTools: Invitation email not received when inv...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6466]
:bug: on DevTools: Invitation email not received when inviting a team member
Test: <https://www.qawolf.com/run/cl26j812a144780451qots6o039d|Create organization: edit name, invite team members, skip download>
• Log in &amp; create a new team
• Invite a new team member
Expected: Email invite received
Result: Email not received after waiting 5 minutes \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1650397393970559)

**Comment by jaril** [comment]
https://replayio.slack.com/archives/C02GEJCC9JP/p1650397393970559
