### ISSUE TITLE
Having hover text on network monitor table fields that may be cropped would be really nice

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6472]
I'm looking at the network monitor on a complicated site with lots of deep paths and long domains can be a bit painful.

For example:
<img width="707" alt="Screen Shot 2022-04-19 at 6 05 45 PM" src="https://user-images.githubusercontent.com/132260/164126539-b26d4fd1-2b25-4f1c-83b3-fbc886f6d226.png">

The domain was "3ce165edb7aa0fe3c3d2f297cc48839.safeframe.googlesyndication.com". I could select the entry and look at the general request data to get that, but that's not a trivial amount of work to process manually and visually.

Similarly for "Name" I could do that, or enable the "Path" column instead, but that makes skimming harder and can make the table overflow.

For both of these, my first reaction was to hover my mouse over the table cell, hoping for a longer descriptive version. We don't have it now but sure would be nice!

**Comment by jonbell-lot23** [comment]
Going through UI polish tasks and adding comments:

Sounds like the best thing to do here is add a simple tooltip.

**Comment by jonbell-lot23** [comment]
I tried to do this and couldn't figure it out. Waiting for eng to pick it up.

**Comment by jaril** [comment]
I misjudged this. This sounds like it's fairly low effort, and it does sound like a bad debugging dead end to try to figure out what that domain value is but not be able to view the entire string.

Adding it to this sprint!

**Comment by gideonred** [comment]
@markerikson to follow up on PR that was merged that may have fixed this.

**Comment by markerikson** [comment]
Yep, should be resolved by #6905
