### ISSUE TITLE
Filtering network monitor for HTML requests also filters out root document

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6474]
https://github.com/RecordReplay/devtools/blob/45894bc20e3d390f178d8e995f7a6a8ef00c4f18/src/ui/components/NetworkMonitor/utils.ts#L66 is missing
```
document: CanonicalRequestType.HTML,
```

**Comment by jaril** [comment]
@jcmorrow mind taking a look?

**Comment by jcmorrow** [comment]
Oh yeah, that's an easy one, thanks Logan!
