### ISSUE TITLE
CI-oriented Library V1

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6475]
This is a ticket for tracking the changes we want to add to the library to make it more CI-oriented.

- [ ] New row ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11433%3A102222))
- [ ] New detail pane ([Figma link for group by test](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11433%3A102361)) ([Figma link for group by run](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11433%3A102363))
- [ ] Filters menu ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11433%3A102383))
- [ ] View 1: Group by test ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11432%3A97989))
- [ ] View 2: Group by run ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11432%3A98643))
- [ ] View 3: Run view ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11432%3A99298))
- [ ] View 4: Test view ([Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11432%3A99686))

**Comment by jonbell-lot23** [comment]
Design handoff complete! Here are some simple screens for discussion, and the Figma links will always have the latest POV.

![View 1_ group by test](https://user-images.githubusercontent.com/9154902/164140886-fbf7c12b-81a9-4e96-8015-3f27a3376269.png)
![View 2_ group by run](https://user-images.githubusercontent.com/9154902/164140889-d00e6418-2efb-4581-85f6-ea3228fca95f.png)
![View 3_ run view](https://user-images.githubusercontent.com/9154902/164140892-cdde23a2-f71f-416b-b781-e9463b5cc82e.png)
![View 4_ test view](https://user-images.githubusercontent.com/9154902/164140901-3f72b4ed-af50-4a08-9758-aef2f57f6478.png)

![Filters](https://user-images.githubusercontent.com/9154902/164140914-372b4729-530c-4bfb-a4ad-7b4a50cd5102.png)

**Comment by jaril** [comment]
Closing this but linking it to the main roadmap item so that it's all in one place: https://github.com/RecordReplay/devtools/issues/6475
