### ISSUE TITLE
Add error "toast" for when indexing fails

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6476]
[Original Figma explorations](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11413%3A88139)

![image](https://user-images.githubusercontent.com/9154902/164143018-48e1a57e-8e81-40a8-850f-473d70ff6448.png)

**Design details**

1. When we know that indexing has failed and requires a restart, we show this
2. We can show different messages here for different states. For example, if we know the replay is going to need re-recording, we'd put that messaging here.
3. We'll be re-using this component for other states like when things are slow, or when someone hovers looking for more details

**Comment by jaril** [comment]
@jonbell-lot23 sync on this later?

**Comment by jonbell-lot23** [comment]
Hey @jaril since you're on the east coast (and even when not), I think we should get in the habit of moving things forward via text so we don't have to remember which items we're waiting for further discussion on.

Need any additional details from me?

**Comment by jasonLaster** [comment]
I wonder if this should get even more visual weight
<img width="688" alt="Screen Shot 2022-04-22 at 4 40 02 PM" src="https://user-images.githubusercontent.com/254562/164817570-3003e7ac-38e2-4ca0-bc2e-fab006d250c1.png">

https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11413%3A85630

**Comment by jonbell-lot23** [comment]
Not against pink but would rather start subtle and feel it. We always have pink in our back pocket for if we want to be bold.

**Comment by jasonLaster** [comment]
I hear where you're coming from. Two additional thoughts,

1. the refresh button on the right still makes sense because it is (a) good to differentiate between buttons and links, (b) it buys us space to link to the docs and explain what happened
2. more importantly, if the session failed to index, shouldnt we show an error modal similar to other unexpected session errors?

**Comment by bhackett1024** [comment]
I'm not sure what backend problems this is trying to deal with.  The backend does not have a stable state where basic data processing has finished but indexing has failed --- it will keep trying to index the recording, and it will either eventually succeed or it will encounter an unrecoverable error and the session will no longer be usable.

**Comment by jonbell-lot23** [comment]
@jasonLaster agree with the reload button concept 

@bhackett1024 ah ha, I didn’t realise that. So it sounds like the design is as simple as “when you hit this error, show our standard error modal.” Sounds like no new design required.
