### ISSUE TITLE
Replay devtools shows duplicate row in Network panel

### ISSUE THREAD

**Issue by bvaughn** [RecordReplay/devtools#6487]
Don't want to get side tracked digging into this but it seems unexpected to me so I wanted to file it away for later:
* Replay: https://app.replay.io/recording/replay-has-duplicate-row-in-network-panel--b05c1f81-6088-442b-b831-97fc63cd44b1
* Loom: https://www.loom.com/share/c98dbf9a9a384d2b8efeb3726193d6f0

**Comment by jcmorrow** [comment]
Yeah this is not a devtools thing, we are actually [recording duplicate requests](https://github.com/RecordReplay/gecko-dev/issues/821)
