### ISSUE TITLE
Loading progress bar rubberbanding behavior

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6500]
There are times when the main loading progress bar goes backward instead of forward. Not 100% sure what the reason is, but there's a few suspects in the way we calculate what that progress number is:

https://github.com/RecordReplay/devtools/blob/716baa2f99f68076d118f21b2cf31af2b50c4f5c/src/ui/actions/app.ts#L178-L200

**Comment by bhackett1024** [comment]
I got a replay of jittery behavior while loading, see below (with comment).

https://app.replay.io/recording/jittery-loading--17398c14-d172-4dc8-b9c9-0a33be423c74?point=11033630826160532088195952278506484&time=11607&hasFrames=false
