### ISSUE TITLE
Plain error shows as [invalid object]

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6501]
This is a node recording so things might be specific to that.  Replay with comments:

https://app.replay.io/recording/invalid-object-error--c79b3bf2-9e6b-49f6-af55-3c729351f01a?point=111309863912254057236692658116627581&time=45944&hasFrames=true#

Original replay:

https://app.replay.io/recording/407a531c-042e-416c-9d80-0a2a97a5890b?point=649037112121473968260628145504324&hasFrames=true&time=4577.956745832958

**Comment by bhackett1024** [comment]
This is a frontend bug.

**Comment by gideonred** [comment]
@jaril to triage!

**Comment by jaril** [comment]
Tried triaging this but I was bumping up against my object inspector/JS error knowledge. Found the part that was causing the problem, just not sure what the best fix would look like—here's a loom walkthrough.

https://www.loom.com/share/61fb4c9f0d934961b50b4fdb447087ba

@hbenl mind taking a look and see if you get any farther?
