### ISSUE TITLE
"Lohits" typo/bug in tooltip for print statements

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6527]
![image](https://user-images.githubusercontent.com/9154902/164674038-fc7bc573-8ff1-4cff-a845-a05c901292a8.png)

Here's a Loom showing the issue in Safari. I can't get a Replay because of a login issue:
https://www.loom.com/share/be92b12d839b4243a29046fdcf495da6

**Comment by jaril** [comment]
HA I have zero clue how this could have happened.

https://github.com/RecordReplay/devtools/blob/eb5eecfcd298e08317c2ab81d8da208ba6ba26ec/src/devtools/client/debugger/src/components/Editor/LineNumberTooltip.tsx#L36

Say `points` got `Lo` for some reason, even then the resulting text should have been `Lo hits`.

Let me know if you can get a replay 😬

**Comment by jasonLaster** [comment]
so how could `Lo` even show up there... that's the weirdest part

**Comment by jonbell-lot23** [comment]
Hey @jaril try clicking around in Safari. I can do it pretty reliably there. And of course if it's Safari specific I can't get a replay)

As for where "lo" comes from, I think it's taking the word "loading" and then "0 hits" comes on top.

Lohits

**Comment by jonbell-lot23** [comment]
Alright here's another Loom, and I'm sure you can reproduce this in Safari. It's quite common.
https://www.loom.com/share/a6b368eea674414f878be6bf099f1e0f

It looks like we're swapping out the string in a way that's causing a collision.

**Comment by bvaughn** [comment]
Not able to repro this after a few tries, in either Safari or Replay browser. You still seeing this @jonbell-lot23?
