### ISSUE TITLE
Clicking login button doesn't do anything

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6528]
Here's a Loom of me experiencing the issue:
https://www.loom.com/share/e756991dea394c5394faa14b0ac191b3

Here's the URL I'm attempting to load:
https://app.replay.io/login?returnTo=%2Frecording%2Fwhy-no-unicorn--31471181-0570-43cc-b939-638eea464380%3Fpoint%3D31802818261350273996851254302608822%26time%3D26357%26hasFrames%3Dfalse

**Comment by ryanjduffy** [comment]
This is a regression from my login change. I think it only affects going to the login route specifically when already logged in but I’ll confirm.

**Comment by ryanjduffy** [comment]
This is working for me so I suspect your browser needs updated. I think I rolled out the devtools change too soon and should have allowed more time for users to apply updates.

**Comment by jonbell-lot23** [comment]
Still happened after toward update when I initially saw it

**Comment by ryanjduffy** [comment]
When you come online for the day, let's connect up so I can see what's happening and decide if we need to roll back that change.

**Comment by ryanjduffy** [comment]
Right ... your Saturday ... I'll roll it back and we can revisit next week ...
