### ISSUE TITLE
React DevTools should show a loading screen

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6540]
React DevTools will not be available until the replay finishes indexing. 

In that time, we show the message "React has not loaded" which implies that React will bootstrap in the future. 

[replay](https://app.replay.io/recording/react-devtools-loading--a799dd1b-d754-43e4-b627-8ed6b1e42b01?point=108713715482818343399949416250998784&time=46643&hasFrames=false
)

**Comment by bvaughn** [comment]
What's the desired end goal here?
