### ISSUE TITLE
Rainbow Console 1.0

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6569]
This is a dev task to follow-up on [this design task](https://github.com/RecordReplay/design/issues/9). Stay tuned for more details.

[Jon Loom video explaining the details](https://www.loom.com/share/cd71db39efd7417183bd632b14814bfc)

[Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/?node-id=11569%3A109413)

![image](https://user-images.githubusercontent.com/9154902/165399952-87e7071b-4b90-4f8b-a18f-4d81088bcd74.png)

**Note: I'm fine making the border less thick, this was a bit of an issue with the Figma sizing, but we'll fine-tune to taste**

**Comment by jonbell-lot23** [comment]
@markerikson we don't consider this a project?

**Comment by jasonLaster** [comment]
@jonbell-lot23 it's a pretty simple task. Could be completed in one go

**Comment by jonbell-lot23** [comment]
This shipped, closing
