### ISSUE TITLE
The white screen of death

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6588]
Sorry for the no-replay, but I haven't been able to reliably repro this yet. Sometimes when I visit Replay I will just get a white screen, and I know others have run into this as well without diagnosing it. This time, I happened to have my network monitor open, and I saw 403's from auth0:

![CleanShot 2022-04-28 at 11 41 55](https://user-images.githubusercontent.com/5903784/165824735-d57a7447-4b7b-4ff5-a6ca-7dbed9eb4910.png)

Originally this happened for [this replay](https://app.replay.io/recording/replay-never-finishes-loading--df7ab282-9751-4b4a-abc5-e92459a61973?point=54843635599285170025888920675288930&time=21775&hasFrames=false).

I then opened a new tab and navigated to `app.replay.io` (so the library page, not a recording page) and I was redirected to sign-in. Let me know if I can add any more detail here!

**Comment by jcmorrow** [comment]
@ryanjduffy I don't like assigning things to other people, but this feels like it would be in your wheelhouse?

**Comment by ryanjduffy** [comment]
Unfortunately, I missed the 3 day window for the log entries for this. Will keep an eye out for it but hoping someone else will catch it too

**Comment by jaril** [comment]
🙋‍♂️ keeping an eye on it as well.

**Comment by jcmorrow** [comment]
Maybe I caught it? https://app.replay.io/recording/untitled--135705dc-5103-470b-a1b9-1b1287fb2bcc?point=11358149379168460902414346918821888&time=5740&hasFrames=false

**Comment by ryanjduffy** [comment]
> Maybe I caught it? https://app.replay.io/recording/untitled--135705dc-5103-470b-a1b9-1b1287fb2bcc?point=11358149379168460902414346918821888&time=5740&hasFrames=false

It's definitely a bug but I don't think it's an auth issue like this reports. I've added some comments that describe why it's blowing up and will move it over to another ticket.

**Comment by jaril** [comment]
Since it's already moved to another ticket, and we can backlink to this one, closing it!

**Comment by gideonred** [comment]
We have seen white screens that are "failing to open websockets" related: https://github.com/RecordReplay/customer-support/issues/108
