### ISSUE TITLE
Remove Auth0 development warning

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#660]
<img width="1399" alt="Screen Shot 2020-09-15 at 5 18 08 PM" src="https://user-images.githubusercontent.com/254562/93277747-75569980-f777-11ea-88c8-dd84c5f9e660.png">

**Comment by Garbee** [comment]
Jason and I talked about this in the morning. It's blocked on us getting a public Privacy Policy up. That way we can give Google all the info they need so we can get our own OAuth keys there to give Auth0 to talk to them on our behalf.
