### ISSUE TITLE
Contrast on network monitor entries after selected one extremely bad

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6603]
<img width="709" alt="Screen Shot 2022-04-29 at 2 21 07 PM" src="https://user-images.githubusercontent.com/132260/166071019-80e0cb01-5ff1-43c4-90b8-589e478682a3.png">

**Comment by bvaughn** [comment]
This regressed in #6534. I fixed it in #6605.

**Comment by loganfsmyth** [comment]
thanks!
