### ISSUE TITLE
API Key Settings should be dark theme friendly

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6606]
<img width="1096" alt="Screen Shot 2022-04-29 at 9 14 33 PM" src="https://user-images.githubusercontent.com/254562/166090176-ae8509b9-c857-495d-b730-862a31d2c764.png">

**Comment by jonbell-lot23** [comment]
@jasonLaster what are you calling out here? Are there things that are black on black that we need to address, or is this a comment about the low contrast between the modal bicolour and the app bgcolor?

**Comment by jasonLaster** [comment]
Sorry for not being specific. The white API KEY input bg and pink warning message look like they are for light theme, but not dark theme.
