### ISSUE TITLE
:bug: on DevTools: Warnings number no longer visible
Step...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6625]
:bug: on DevTools: Warnings number no longer visible
Steps to recreate:
• Log in to Replay
• Go to AirTable replay (<https://staging.app.replay.io/recording/airtable-playwright-test--6847ab82-8b0a-4dc2-af73-eb6bf14918e7?point=12331705040172899620536796682649667&amp;time=5072.277283660569&amp;hasFrames=true|https://staging.app.replay.io/recording/airtable-playwright-test--6847ab82-8b0a-4dc2-af[…]99620536796682649667&amp;time=5072.277283660569&amp;hasFrames=true>)
• Filter console by warnings
Expected: A number of warnings to appear beside it
Results: No value, TypeError can’t access dead object possibly related?

Affected tests:
<https://app.qawolf.com/test/ckz2xr1f984214951p4w9uydpnm?suite_id=cl2m9d8ha10716401equzxotg75r>
and
<https://app.qawolf.com/test/cl1xv0dck101894350nfm9u62ihc?suite_id=cl2m9d8ha10716401equzxotg75r> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1651470448131859)

**Comment by jaril** [comment]
To triage.

**Comment by jaril** [comment]
Tests are passing on prod. Closing
