### ISSUE TITLE
Recordings for workspace are fetched twice when app loads

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#6640]
I noticed that when we load the app we fetch all of the recordings for the workspace twice, see this replay https://app.replay.io/recording/workspace-recordings-are-fetched-twice--4bdb3c13-3e40-488c-8f4f-ba038d65e11d?point=19471113236572462048695161978881478&time=9169&hasFrames=false

(This Replay is private because it's a recording of our private workspace)

Can we reduce the number of times we make this query to one? It can be a pretty expensive query for the backend to perform.

**Comment by ryanjduffy** [comment]
I think this is the polling that is configured for this query. Every 5 seconds we refetch the workspace recordings. Agree that it's not ideal for large workspaces so we should plan to get either subscriptions or pagination in place before we have a large adoption of automate test recordings.
