### ISSUE TITLE
:bug: on DevTools: Messages and pointerup events not load...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6652]
:bug: on DevTools: Messages and pointerup events not loading properly in console
• Navigate to <https://staging.app.replay.io/recording/great-scott--558693fb-ddcc-4798-bef5-14d1d47f4946?point=49002301604679427163477051738949771&amp;time=22599&amp;hasFrames=true|Great Scott> or another Replay
• Toggle on the message filter in the Worker category
• Note the message does not finish loading
• Toggle on the pointerup filter in the Pointer category
• Note that only some of the pointerup events load
Replay: <https://app.replay.io/recording/messages-and-pointerup-events-not-loading-properly-in-console--b8ab0510-0623-45d6-9ff3-45c9fca92b51>
Affected tests: <https://app.qawolf.com/test/ckz327u1u114841951p43t4ace73|Hide node modules with user role>, <https://app.qawolf.com/test/ckz31hxq0108798750ki1azib03h|Filter console by event type (search) on user role> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1651695193675669)

**Comment by jaril** [comment]
Adding it to my list to triage and know whether we can close it or fix it.

**Comment by jaril** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/15959269/169839014-8c937f1c-9ca4-4aab-8913-6c0d69fd8684.png">
