### ISSUE TITLE
Interacting with hot analyses

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6659]
We tell the user to "Use focus mode to reduce the number of hits" when there is an analysis with too many points, but they can still use right and left arrows to jump between points, even though the warning is there. This is really weird, it feels like things should either be 100% working or 100% disabled, but this being partially enabled and partially disabled feels wrong.

https://user-images.githubusercontent.com/5903784/167214852-71cd6461-782d-4129-be2a-c3d7254c789f.mp4

**Comment by jcmorrow** [comment]
https://app.replay.io/recording/partially-disabled-breakpoint--ddc66b3c-6f84-4c24-96a4-e56848db3da2?point=125588680283323097429934195444023296&time=43830&hasFrames=false#

**Comment by jcmorrow** [comment]
Will be fixed by https://github.com/RecordReplay/devtools/pull/6663

**Comment by jaril** [comment]
#6663 was merged so I'm assuming this can be closed. Let me know otherwise @jcmorrow !
