### ISSUE TITLE
If we are soft-focused and you try to move on the timeline nothing happens

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6662]
https://user-images.githubusercontent.com/5903784/167218136-8e92fdaf-7104-4715-8a4c-d0aeae69f8db.mp4

This is not entirely unexpected, and it's a pretty difficult state to get into right now, because we will always try to unload sections that are completely outside of the focus window right now (the one exception is when you have multiple sessions going). But once #6590 is done, we should double check that this is also fixed.

**Comment by jaril** [comment]
@jcmorrow investigate then close?

**Comment by jcmorrow** [comment]
We changed what happens when you click on the unloaded area, so now this is the correct behavior I believe!
