### ISSUE TITLE
Global loader 1.5

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6671]
We're updating our global loader!
[Link to design ticket](https://github.com/RecordReplay/design/issues/40)

**The problem we're trying to solve**
We handle buffering, loading, and indexing, and it can be hard to give people enough information without being overwhelming. This design attempts to be more clear (by using a literal progress indicator) without showing too much (we are calling everything "loading" and we're retiring the word "indexing" from this view.

![image](https://user-images.githubusercontent.com/9154902/167339741-d345b037-7ba7-4310-bdcc-31ecf19602bd.png)

**Details**

* In the default view, things will work the same as before
* There's a new unified "capsule" design to visually group everything
* We changed the icon to look more like a trim (rather than "full screen")
* When things are slow, we'll show a turtle icon
* When things fail, we'll show a storm icon
* Hovering over the left side could show indexing information in the timeline (to discuss)
* Hovering over the right side should show a highlgiht
* When focus mode is deployed, the right side should stay lit up to show state

**Design notes**

I need to cut some of these icons. Keep me posted before starting work and we can make sure we're synced!

### Code changes
* #6750
* #6769

**Comment by jaril** [comment]
Linking https://github.com/RecordReplay/devtools/pull/6725 since that seems to be related.

**Comment by bvaughn** [comment]
Just wading into this and already it feels better 😄 
![Kapture 2022-05-12 at 20 04 40](https://user-images.githubusercontent.com/29597/168186363-610ee76c-3607-4b74-8077-1418ea481df4.gif)

**Comment by jonbell-lot23** [comment]
Oh gosh <3 Really looking forward to this!

**Comment by bvaughn** [comment]
> When things are slow, we'll show a turtle icon

What does "slow" mean?

**Comment by bvaughn** [comment]
@jonbell-lot23 Where are these icons (the turtle, the cloud, even the radial loader) ?

This issue links to a design ticket (https://github.com/RecordReplay/design/issues/40) which links to a Figma but I'm not sure how to extract them– and they weren't included in the recent icon extraction script (#6746).

**Comment by bvaughn** [comment]
> When things are slow, we'll show a turtle icon

What does "slow" mean? Judging from the Figma mocks, it seems like we should only (and always) show the turtle icon on hover. Is this true? If not, what are the criteria for showing it?

I'm also a little unclear about what conditions we should show the error icon under. I will dig into that though.

**Comment by bvaughn** [comment]
Update: I am going to take a stab at what "error" and "slow" mean. I will explain the heuristics used on the PR and in a Loom. :)

**Comment by jonbell-lot23** [comment]
@bvaughn Sorry, I just saw these comments!

It's good to install SF Symbol -> https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/
Then you can access those icons the font SF Pro.

I was thinking the turtle would be there when things get slow, not just on hover.

**Comment by bvaughn** [comment]
No worries. I figured out the font thing, and the turtle thing, a couple hours after asking.

**Comment by bvaughn** [comment]
Ball should be back in your court, @jonbell-lot23. Believe I landed all of the changes you enumerated on the PR and in Loom.

**Comment by jonbell-lot23** [comment]
@bvaughn Looking wonderful! 

I've lost track in the hustle and bustle -- are we to the point where we can close this out?

**Comment by bvaughn** [comment]
Yup I think we can.
