### ISSUE TITLE
Dark Theme Unicorn

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6688]
<img width="339" alt="Screen Shot 2022-05-10 at 8 05 03 AM" src="https://user-images.githubusercontent.com/254562/167660733-03295d67-dc03-47fb-ac61-70e7dedb6c04.png">

**Comment by jasonLaster** [comment]
Down the line we might also want a lower contrast unicorn for dark theme, but that is a project for another day

https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12008%3A76115

**Comment by jonbell-lot23** [comment]
Fixed
