### ISSUE TITLE
Clean up unicorn console code

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6693]
In [this PR](https://github.com/RecordReplay/devtools/pull/6670) @jcmorrow had some suggestions that Jon wasn't able to figure out. This is a separate ticket to handle them ->

DARK_PREFIX_COLORS and PREFIX_COLORS are no longer used because we're using CSS instead. This means PrefixBadge.jsx needs to be updated to address that change.

**Comment by jonbell-lot23** [comment]
Sorry for the lame issue assignment @jcmorrow 😅

**Comment by jasonLaster** [comment]
this is now fixed
