### ISSUE TITLE
Print statement disappearing

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6698]
@jonbell-lot23 and I just had the experience of a Print Statement disappearing when changed to a Primitive Value.

Replay: https://app.replay.io/recording/consolelogs-disappearing-when-edited--95644baf-99e7-4ff8-9658-548e00c736ae?point=8762000949961048582013352891384201&time=3426&hasFrames=false

**Comment by markerikson** [comment]
This sounds like it's https://github.com/RecordReplay/devtools/pull/6686 - we should just merge that PR

**Comment by jonbell-lot23** [comment]
I checked back on the file, and the print statement did eventually end up in the console, for what it's worth.

So it was slow (and lacking a loading message) rather than being straight-up broken.

**Comment by jcmorrow** [comment]
Closing since it's a duplicate of https://github.com/RecordReplay/customer-support/issues/87
