### ISSUE TITLE
Don't request repainted graphics when the recording has no graphics

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6710]
![CleanShot 2022-05-11 at 10 03 12](https://user-images.githubusercontent.com/5903784/167906753-59f88e7a-9c5d-4d93-a319-79a55485d6b2.png)

**Comment by Andarist** [comment]
I might be responsible for a good chunk of those 🤣 node recordings ftw 🚀

**Comment by jcmorrow** [comment]
Haha, I can neither confirm nor deny the email address under that black box 😉

**Comment by Andarist** [comment]
Ah, so it's **all** me 😅

**Comment by hbenl** [comment]
Repainting was disabled for node recordings in #6559. In Honeycomb I see these errors only for gecko recordings that are more than a year old (probably before repainting was implemented). In newer recordings I only see repaint failures with different error messages ("Failed to perform command", "This part of the recording has been unloaded", "Painted graphics are not available at this point").
