### ISSUE TITLE
Netmonitor attempts to render "multipart/form-data" request bodies even though they may contain binary data

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6712]
The "Request" tab in the netmonitor tries to render request bodies as text if it can, but it appears to also try to do so for `multipart/form-data` bodies. That can work some of the time, but since these responses may contain binary data, it's probably a bad idea unless we explicitly parse the parts out and only show text if it looks like text.

Here's an example recording: https://app.replay.io/recording/request-body-binary-data-example-for-devtools6712--13410b47-d24c-4078-b899-d008a71789d9

**Comment by jcmorrow** [comment]
> it's probably a bad idea unless we explicitly parse the parts out and only show text if it looks like text.

If we had a good "does this look like text?" test we could use that elsewhere too. Some random response types like `application/octet-stream` very well *may* be text, but it's really up to the program interpretting them to peek and decide whether or not to say "Eh, close enough to text".

**Comment by jcmorrow** [comment]
For instance, I believe socket.io will sometimes send `application/octet-stream` where the first couple of bytes are used like bitflags to signal some stuff, and then the rest of the response is just plain text.

**Comment by jcmorrow** [comment]
oh, we do this wrong because I'm an idiot, sorry. We are interpreting the request body based on the response body header 🤦
