### ISSUE TITLE
Can't type in search full text input

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#6716]
Search full text is broken for me. I tried it in a newer replay too (the one below is older) and had the same issue.

Replay: https://app.replay.io/recording/replay-cant-type-in-search-full-text-input--a207b7f1-b383-479a-8534-82d38ec9bcf6
Loom: https://www.loom.com/share/315ff868d92e4e449f8be2e58892fcc8

**Comment by markerikson** [comment]
Yep, this is my fault from merging #6696 . Apparently I need to make sure more of the action creators get exported.  Fixing!
