### ISSUE TITLE
Focus Mode 1.2

### ISSUE THREAD

**Issue by bvaughn** [RecordReplay/devtools#6735]
Build on top of #6571

- [x] Implement design in https://github.com/RecordReplay/design/issues/46, [Figma](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12220%3A92306)
- [x] ~~Jon reaching out to @souporserious to learn how to do the cool auto-sync icon thing~~

**Comment by jonbell-lot23** [comment]
I have some items to add when I'm awake

**Comment by jonbell-lot23** [comment]
* I'm keeping an eye on dismiss versus cancel, and when to show a destructive action confirmation
* Also thinking about the color of the discard button. Might be best to make it white with red text, still thinking about it

But that's about it, to discuss later as we try it out more

**Comment by bvaughn** [comment]
I think this bullet point should probably be tracked via a design ticket:
- [ ] Jon reaching out to @souporserious to learn how to do the cool auto-sync icon thing

**Comment by souporserious** [comment]
Oops my bad, I should have commented on this earlier. I'm going to do another pass on the icon script right now and then we should be good to get the set updated.

**Comment by bvaughn** [comment]
There's some follow up animation polish to work on with Jon, but this issue is done for now
