### ISSUE TITLE
Playhead can go past the end of the timeline

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6748]
A Replay is worth a thousand words (but I left some comments anyways):
https://app.replay.io/recording/playhead-can-go-past-the-end-of-the-timeline--397dcb2e-cf68-49ea-bc8e-e85e65124795

<img width="566" alt="image" src="https://user-images.githubusercontent.com/15959269/169088444-7416be62-a3bf-4a86-962e-370c4dc5bbe4.png">

**Comment by bvaughn** [comment]
Ugh, I wrote a stupid `clamp` statement:
```js
const percentage = clamp(x / rect.width, 0, 100);
```

This should be:
```js
const percentage = clamp(x / rect.width, 0, 1);
```
