### ISSUE TITLE
Reenable React DevTools

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#6749]
#6738 disabled fetching annotations if the user hasn't enabled *Redux* DevTools. But if we don't fetch any annotations, this also disables  *React* DevTools.

**Comment by markerikson** [comment]
Pasting my comment from Discord:

So in that sense it sounds like the code is working as expected, but we really need a way to separate these out ASAP. I suspect what we'll end up needing to do is 1) ask the backend if Redux annotations exist, 2) show the tab if they do, 3) only request Redux annotations once that tab is focused.

But, this really depends on having two (three?) updates to the backend APIs.  We need one that tells us what annotations exist by type, `getAnnotations` needs to be able to do server-side filtering of annotations by a requested type, and the client needs to be able to have multiple simultaneous active subscriptions to `getAnnotations`.

**Comment by markerikson** [comment]
A couple additional thoughts for possibly improving behavior here:

- We could go back to always loading annotations, but start it on a delay (like _after_ the rest of the indexing/whatever data is loaded)
- The Redux annotations in particular can be large. We could consider gzipping them when we do the recording, and decompress on the client when they're received.
