### ISSUE TITLE
:bug: on DevTools: Open React DevTools not available

ste...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6754]
:bug: on DevTools: Open React DevTools not available

steps to repro:
• open a replay
• view devtools
• react devtools not available
affected tests: <https://app.qawolf.com/test/cl1xt3zli27421950p9q7yhmnk1> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1652475905413099)

**Comment by markerikson** [comment]
Yep, known issue due to changes with how we're fetching annotations, and we're working on fixing this.

Refs: #6749 , #6753
