### ISSUE TITLE
:bug: on DevTools: Sharing recording with link and email ...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6756]
:bug: on DevTools: Sharing recording with link and email errors out

steps to repro:
• log in 
• click "share" on a replays dropdown
• error page, errors in console
affected tests: <https://app.qawolf.com/test/ckw3yu4r8000o09l9ak4t99u9> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1652476819745089)

**Comment by jaril** [comment]
![image](https://user-images.githubusercontent.com/15959269/168841997-648e897b-ffea-48bc-b4f3-e34849e442dd.png)

There was a problem in the SecurityWarnings component and it was throwing in the test's console.

I'll file a PR to add a guard for that component.
