### ISSUE TITLE
[Assert] should have been an originalId

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6770]
Here's a replay of a source map related assert i'm seeing in dev which might be interesting to investigate.
* [replay](https://app.replay.io/recording/should-have-been-an-originalid--eff01dd1-67e6-4b62-9145-30fd0d4b1814?point=115528605864914238382363912605547553&time=95711&hasFrames=true) 
* [loom](https://www.loom.com/share/4017401c7b174040859a451ec5bae0e1)

**Comment by hbenl** [comment]
This is another instance of RecordReplay/backend#1310.
Note that asserts do not crash replay in prod anymore (but you were looking at the recording in dev) and if the assert fails, the fallback sourceId is returned (as suggested in the loom).
