### ISSUE TITLE
Pressing Shift-C will nuke the existing comment

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6776]
https://app.replay.io/recording/shift-c-blows-away-comment--7861b28f-5b93-4700-9028-2e4934959d9f?point=37319633696907564500449217124237614&time=16140.991396244206&hasFrames=true

We have a mechanism for protecting other handlers which we should use here as well
https://cs.github.com/?scope=org%3ARecordReplay&scopeName=RecordReplay&q=isEditableElement

**Comment by souporserious** [comment]
Yikes, I'll get this fixed up this morning!
