### ISSUE TITLE
Regression due to missing `ThreadFront` in `createSession` action dispatch

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#6783]
Looks like this probably happened in https://github.com/RecordReplay/devtools/pull/6758

<img width="751" alt="Screen Shot 2022-05-16 at 12 28 19 PM" src="https://user-images.githubusercontent.com/132260/168667940-19a24ce5-64ab-4dd4-8da6-7869a64c53cb.png">
<img width="1322" alt="Screen Shot 2022-05-16 at 12 30 30 PM" src="https://user-images.githubusercontent.com/132260/168668031-7fd368ab-0948-4af8-a50d-40bb9de4891a.png">

I can repro reasonably consistently if I open https://app.replay.io/recording/cf2da81f-3a74-45ba-9241-f6d4361a52f5
 Note that this URL does not have a recording title slug. Once you refresh and the slug is added, this appears to not happening.

**Comment by markerikson** [comment]
Ah. I changed all thunks, and I'm injecting `ThreadFront` inside of `devtools.ts`, but I bet this one gets run _before_ the `devtools.ts` setup work happens.
