### ISSUE TITLE
Disable editing a team name if the team is not an organization

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6799]
We have an edit team name feature that a user can access by going into team settings > profile, but it's only enabled for [organizations](https://github.com/RecordReplay/backend/blob/f5c4edac6fe15add730cc5828f956d2df05e6639/src/graphql-api/models.ts#L2205).

Right now, we have the same input box for the title regardless of whether or not the team is an organization. We should disable that input box if the team is not an organization to keep the user from trying to edit it in the first place.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/15959269/168834306-38bb4c7a-d346-4187-b356-ea175e233957.png">

**Comment by ryota-murakami** [comment]
Hello @jaril !
I came from your good first issue tweet and this is looks good for me.
Can I take this? 👨‍💻

**Comment by jasonLaster** [comment]
@ryota-murakami go for it!

**Comment by ryota-murakami** [comment]
@jasonLaster Thank you, I got it!
