### ISSUE TITLE
[Replay] Upgrade popup copy is missing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#683]
<img width="347" alt="Screen Shot 2020-09-18 at 4 58 07 PM" src="https://user-images.githubusercontent.com/254562/93653969-29eaf800-f9d0-11ea-9154-5d241fe8e101.png">

I believe we've fixed similar issues like this

**Comment by jaril** [comment]
Moved to [gecko-dev](https://github.com/RecordReplay/gecko-dev/issues/252).
