### ISSUE TITLE
Add loader indicator on playhead when buffering

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6833]
[Here's a Loom](https://www.loom.com/share/baa518df41f343178bc51dd2014d31ae), but I can save you three minutes by summarising what is said:

* [In this ticket](https://github.com/RecordReplay/design/issues/52), I said we should get Global Loader 1.5 out and then revisit
* We've taken a big step forward, and I think the next step forward is adding a loading indicator on the playhead while buffering

Here's a representative image:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/9154902/169199202-f4a0fb6c-c60a-4ab5-833c-bc37b67e86d9.png">

When a user clicks into a region that's going to cause some loading, we do this:

1. Show the global loader 1.5 design on the far right
2. Show an indeterminate spinner on the progress indicator (icon not yet cut, stay tuned -- I used material's "autorenew" icon but will cut when we decide on the final visual
3. No tooltip required because it's covered by the Global Loader 1.5 UX

Here's a Loom walkthrough of my thinking:
https://www.loom.com/share/2b7039bec64c4eadb8311534e88f0289

**Comment by jasonLaster** [comment]
I have a couple questions, but it's late, so flagging this and will come back tomorrow.

**Comment by jasonLaster** [comment]
Left some thoughts here
https://www.loom.com/share/d709134e2f874e2aa653d5b16e2a57d9

https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12314%3A94603

**Comment by jaril** [comment]
It feels like the conversation is diverging a bit. Buffering is also a concept in replay, but it's a loaded term and wanted to make sure we get the terms straight.

I understood what @jonbell-lot23 is saying as: 
1) show the spinner on a clown nose when we're "not ready to go yet", i.e. we're "loading" and we're showing the global loader
2) actual video buffering progress is not relevant to the original proposal
3) the clown nose spinner is a simple redundancy on top of the global loader. 

Did I get that right?

**Comment by bvaughn** [comment]
@jaril I don't think that represents my understanding of where things stand with this issue.

So the global loader already handles the loading vs loaded+indexed case. I agree with @jasonLaster that we shouldn't overload that UI to _also_ address video playback / buffering.

> actual video buffering progress is not relevant to the original proposal

I agree that it's not related to Global Loader issue, though we should address it (via this issue?)

> the clown nose spinner is a simple redundancy on top of the global loader.

FWIW I like Jason's mockup of showing a "buffering" tooltip rather than showing a spinner in place of the current time indicator.

**Comment by jaril** [comment]
> > actual video buffering progress is not relevant to the original proposal
> 
> I agree that it's not related to Global Loader issue, though we should address it (via this issue?)

I completely minimized why it's necessary to have that buffering tooltip since we already have two indicators: the buffered line on the timeline and the little spinner on the video. Didn't think about what Jason pointed out here, which is what happens when the user plays into an unloaded region, where we hide the buffered line 😬

https://github.com/RecordReplay/devtools/issues/6622#issuecomment-1131897290

**Comment by jonbell-lot23** [comment]
cc @jaril @jasonLaster @bvaughn I looked for time on the calendar but I don't see any good slots. So in the meantime, let's jump over here to this Discord file -> https://www.notion.so/replayio/Loading-buffering-loading-states-design-discussion-2c6b4e0a13f845ddb09221a3a3231631

**Comment by jcmorrow** [comment]
1. Right now, we show you what regions are focused, and if you hover over the loading status for the global loader you will see (on the timeline) the areas that are loaded vs. loading). I think it could be helpful to have a hover target somewhere which will do a similar action, but for video - show you where we are and are not ready to play video yet. This gets a little complicated with "where we are buffered" vs. "where we could buffer from", but I'll leave that digression alone for now.
2. This is only tangentially related, but I think we should swap out the term "Unloaded" in the UI for "Video-only". Unloaded has a technical definition which makes sense to us, as people who work on Replay, but I don't know that it means all that much to the average Replay user, or that it is a term that we actively want to be using. Most of the time, users hopefully won't have to worry about the details of unloading, they will just have focused regions which they can move around, and the rest of the recording is video-only (but be careful how you word this when we are in Node land!!!)

**Comment by jonbell-lot23** [comment]
@jcmorrow I love both of these ideas, thank you!

1. We had discussed showing this information when you hover over the play button. I could see this working.
2. Good gravy, the idea of calling something "video only" might really unlock some good thinking here. Stay tuned.

**Comment by jonbell-lot23** [comment]
This ticket got confusing because of poor naming in the title followed by a bit of a pivot. I'm going to close it for now in favour of tracking in other issues. Here's what happened:

1. I set up a ticket to do a clown nose -- I meant it for unloaded states but I accidentally said "buffering" which made the team think I was talking about video. Apologies for that!
2. We think the clown nose is a bit much, so we're not going to do that
3. Jason and Jon had a good discussion and decided the next baby step forward is to design better messaging for trying to play video from outside a Focus Window. I'll set up a ticket for that.
4. Josh had two great points up above that I will fold into the thinking for better messaging.

Questions or comments, please let the team know! Feel free to add something to [our Notion doc](https://www.notion.so/replayio/Loading-buffering-loading-states-design-discussion-2c6b4e0a13f845ddb09221a3a3231631).

**Comment by bvaughn** [comment]
> This is only tangentially related, but I think we should swap out the term "Unloaded" in the UI for "Video-only". Unloaded has a technical definition which makes sense to us, as people who work on Replay

I like this suggestion!
