### ISSUE TITLE
:bug: on DevTools: Sharing recording with link and email ...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6835]
:bug: on DevTools: Sharing recording with link and email errors out

steps to repro:
• log in
• click “share” on a replays dropdown
• error page, errors in console
affected tests: <https://app.qawolf.com/test/ckw3yu4r8000o09l9ak4t99u9>

NOTE: Initial report <https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1652476819745089|here> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1652930238410929?thread_ts=1652930191.993289&cid=C02GEJCC9JP)

**Comment by jaril** [comment]
![Uploading image.png…]()
