### ISSUE TITLE
Cursor shouldn't change to text input cursor on timestamp

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6839]
![image](https://user-images.githubusercontent.com/9154902/169202236-fe5b289d-39de-49a7-918c-fd047b2ff557.png)

This region isn't actionable, so the cursor needs to stay standard.

When in Focus Mode, the cursor changes to a text input cursor because at that point it's actionable.

**Comment by bvaughn** [comment]
Not sure what you're describing, Jon. The cursor is standard (assuming you're not editing the focus mode). Just double checked out CSS and we aren't specifying any custom cursor for that component.

Just point of clarification: The cursor you're seeing (at least in Safari) is just the default _text selection cursor_ (which is shown whenever you hover over selectable text). We can override the browser's default behavior in this case. 😄
