### ISSUE TITLE
Transcript fails when the comment has a null point

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6865]
Replay of crash
https://app.replay.io/recording/crash-app-with-typeerror-cant-convert-null-to-bigint--7f2c75c3-b022-4562-a9b9-3cbc73645ba3

This is original replay
https://app.replay.io/recording/learning-replay-debugger--472c3cc2-da57-46ca-91b8-b9adba09e03c

**Comment by jcmorrow** [comment]
This should be an easy fix.
