### ISSUE TITLE
Breakpoints and Logpoints are not persisted anymore

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#6870]
STR:
- open any recording
- set a breakpoint or logpoint
- reload

Expected result:
the breakpoint or logpoint should still be there
Actual result:
it isn't

**Comment by markerikson** [comment]
Hmm. I did touch some of this code recently, so there's a good chance this one is also my fault :(

The main change I made was to move the "pending breakpoints" persistence logic into a central location.  It _was_ being saved as `prefs.whatever = someValue` in reducer cases, which runs but is conceptually the wrong place.  I moved it into `ui/setup/prefs.ts`, which is a central location where we've been trying to handle that sort of thing:

```ts
  if (state.pendingBreakpoints && oldState.pendingBreakpoints) {
    // @ts-ignore `asyncStoreHelper` is untyped, so TS doesn't know keys here
    updateDebuggerAsyncPrefs(state, oldState, "pendingBreakpoints", getPendingBreakpoints);
  }
```

This _may_ not be the actual cause of the issue, but it sounds like it _could_ be related.
