### ISSUE TITLE
Chrome takes awhile to load many replays at once

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6883]
Chrome
https://www.loom.com/share/5fdc609ce11045178ff5095b6b62687b

Firefox
https://www.loom.com/share/4f943fd5df744cc596a00cc73f957c49

Migrated from https://github.com/RecordReplay/customer-support/issues/107

**Comment by jaril** [comment]
@ryanjduffy mind taking a look? It looks like quickly opening multiple replays from the library into new tabs results in those tabs not loading properly. The last network activity seems to be stripe-related so not sure if that might be the culprit?

**Comment by jasonLaster** [comment]
closing as a dupe of https://github.com/RecordReplay/customer-support/issues/108
