### ISSUE TITLE
[Console] openNodeInInspector fails

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#691]
It looks like any call to `openNodeInInspector` should fail, with that said, when I 

1. go to a recording
2. open the console
3. evaluate `document.body`
4. click on the inspector button

it seems to work...

https://sentry.io/organizations/replay/issues/1854092946/?project=5399075&query=is%3Aunresolved&statsPeriod=14d

**Comment by jaril** [comment]
Played with this a bit and it looks like `openNodeInInspector` fails silently. It does open the Inspector panel, but it only looks like it works because the `<body>` tag is highlighted by default.

**Comment by jasonLaster** [comment]
Good call. I was totally fooled.

1) my test was selecting the body el
2) my other tests were for elements already selected in the inspector :facepalm:

**Comment by hbenl** [comment]
The way that `openNodeInInspector` tries to get a `NodeFront` doesn't work in our devtools.
But even when I do get the `NodeFront` (using `Pause#ensureDOMFrontAndParents`) and pass that to `toolbox.selection.setNodeFront`, the breadcrumbs are updated but the Inspector doesn't show the node as selected.
I think before I dig into that, I'll wait for the new Inspector to arrive.

**Comment by hbenl** [comment]
Note that the `DebuggerPanel` contains a very similar implementation (`openElementInInspector`) which also needs to be fixed.

**Comment by jaril** [comment]
Is this finished??
