### ISSUE TITLE
:bug: on Deploy PR: Error on loading a public replay from...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6914]
:bug: on Deploy PR: Error on loading a public replay from library

NOTE: This is the Deploy PR test environment

Steps to recreate:
• Log in to Replay
• Go to your library
• Click the Clade replay
Expected: Clade replay to load
Results: POST errors. missing component error and an uncaught promise

Affected tests: <https://app.qawolf.com/test/ckw3tcfhk000w09mhhfjshoff?suite_id=cl3hqrg9m56243453s5tpmlsaot|Make recording private and public>

commit: <https://github.com/RecordReplay/devtools/commit/810a055fd97b841c7fda0627a9cb4a0d502440b1|810a055>
branch: refactor/dropdown \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653277112191819)

**Comment by jaril** [comment]
![image](https://user-images.githubusercontent.com/15959269/169854640-2e029e5f-6149-47c9-9278-8e37a62f0f54.png)
