### ISSUE TITLE
Fix language around "There was an error. Please try recording again."

### ISSUE THREAD

**Issue by gideonred** [RecordReplay/devtools#6920]
As per this discussion in Notion: https://www.notion.so/2022-05-16-Glide-s-quality-journey-for-the-last-7-days-5fc8b6bf7e5e44f49be6c70404bcbd59?d=c398d565b1ad469398ca13ca2cb9ec72#ebaa9ab6b30c4c9a8b383ebdae7754e9

The frontend sometimes shows the message "There was an error. Please try recording again." to the user when encountering a problem with the session. This suggested action "Please try recording again." is not always guaranteed to be most efficient solution, or even a solution. In some cases the user could just refresh the session and it will continue to work. Encouraging the user to do a lot of work (end the session, record again, begin a new session) is asking a lot and without a guarantee it will even work will probably lead to less confidence in the product.

**Comment by jaril** [comment]
It seems like the full fix would be to require being able to tell apart controller fatals better. If we were, then we'd be able to clearly say "A refresh should do the trick", or "Please record a new replay".

Small fix we could do here is just a more nuanced message like, "Something went wrong. Refreshing should help, but if the problem persists, please try recording again", then have a Refresh button call to action immediately below.

How does that sound? @gideonred @bhackett1024

**Comment by jasonLaster** [comment]
@jaril that's right. We discussed this earlier and for the moment, it is fine to go with the small fix which will be clearer to users.
