### ISSUE TITLE
Add granular invite links

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6937]
Here's the Figma: https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12482%3A96588

![image](https://user-images.githubusercontent.com/9154902/170144290-d577524e-31f0-446b-94fc-daa35534ad7c.png)

Note that this design was iterated on and agreed on many months ago. Which means a) I think the design is solid b) but it's been a while, so things have likely changed. To discuss!

**Comment by jaril** [comment]
Closing this for now since @ryanjduffy addressed the original issue with https://github.com/RecordReplay/devtools/pull/6943.
