### ISSUE TITLE
:bug: on DevTools: opening "sample-folder" on Replay goes...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6942]
:bug: on DevTools: opening "sample-folder" on Replay goes to blank page with error in console

steps to repro:
• navigate to <https://staging.app.replay.io/recording/sample-folder-visual-studio-code-insiders--99215af1-7f6f-4db2-84e4-7a2ea6142240?point=10384593718233283943681123422306591&amp;time=4183&amp;hasFrames=true|https://staging.app.replay.io/recording/sample-folder-visual-studio-code-insiders--9921[…]384593718233283943681123422306591&amp;time=4183&amp;hasFrames=true>
• blank page, error in console. \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653434431089839)

**Comment by jaril** [comment]
This appears to work just fine.
