### ISSUE TITLE
:bug: on DevTools: Search filter for “Replay” doesn’t fin...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6944]
:bug: on DevTools: Search filter for “Replay” doesn’t find a result
Steps to recreate:
• Log in to Replay
• View library
• One of the replays “Replay prompts for auth when commenting” isn’t being filtered when searching with keyword “Replay”
Expected: 3 results in my library to appear
Results: 2 results filtered and “Replay prompts for auth when commenting” not visible.

Affected tests: <https://app.qawolf.com/test/ckw3r5xjb000008mkcjyr2vb0|View and search library>
Link to replay: <https://app.replay.io/recording/view-and-search-library-replay-qa-wolf--b0eac33b-f9bf-4c54-a785-5a2605ceaed4?point=94759417685116976089134295913857024&amp;time=33942&amp;hasFrames=false#|https://app.replay.io/recording/view-and-search-library-replay-qa-wolf--b0eac33b-f9[…]94759417685116976089134295913857024&amp;time=33942&amp;hasFrames=false> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653439518257799)

**Comment by jaril** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/15959269/170500898-80a28f1a-3972-4d0b-ba9e-0cf5a8df1a56.png">
