### ISSUE TITLE
:bug: on Staging: Checkbox on team settings to restrict /...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6952]
:bug: on Staging: Checkbox on team settings to restrict / allow access by domain is disabled
Tests affected:
<https://app.qawolf.com/test/ckxi2jo1d000109jk7bw3egrq|Team settings: give access to anyone with email domain>
<https://app.qawolf.com/test/ckwlb0434000i09mq4h10aszc|Create team: invite team by link, limit access to domain, no invites dialog appears>
Steps to repro:
1. Go to team settings
2. Click team members tab
3. Attempt to click check box to restrict by domain. 
4. Nothing happens \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653510565601609)

**Comment by jaril** [comment]
This should be fixed as soon as https://github.com/RecordReplay/devtools/issues/6966 is addressed.
