### ISSUE TITLE
Comments no longer linking to correct source

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#6988]
**Description:**
Recorded this replay on Monday and added comments. Now, the comments aren't linked to the correct source in all cases. Sometimes it opens the minified code (not sure if even accurate file location) with no source maps toggle, other time it doesn't open a file at all.

Console logs are still linked correctly, and the source files do exist in the Source Explorer.

Potentially unrelated, but the comment notification also appears briefly then disappears.

These comments worked earlier this week, so likely a recent regression.

Link to original replay: https://app.replay.io/recording/subscribe-to-updates-not-working--3afe0c21-954e-4df9-b960-a4e79630b7f5
**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):
* 
https://app.replay.io/recording/replay-comments-not-linked-to-source-anymore--c3e3e1ae-f478-4541-81c1-d3c7ec0db31b

**Comment by jcmorrow** [comment]
Closed with https://github.com/RecordReplay/backend/issues/5767 and  #6994
