### ISSUE TITLE
Unsubscribing from an email fails 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#6991]
Laura from qawolf reported this issue

![image](https://user-images.githubusercontent.com/254562/170813230-38a04aea-19a8-4c6c-ab65-0db1cea7f150.png)

**Comment by jaril** [comment]
The problem appears to be a broken route `https://app.replay.io/settings/preferences`. Switched it to `https://app.replay.io/settings` and everything works fine now.
