### ISSUE TITLE
[Timeline] playing the recording could be smoother

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#704]
**Describe the bug**
Playing a recording starts and stops at different spots

**To Reproduce**

1. go to http://localhost:8080/view?id=81a8a24c-14dd-49f9-8856-c58e64ae6910
2. hit play and watch the recording

![](http://g.recordit.co/FY0gX3Zkxo.gif)

**Comment by jasonLaster** [comment]
@hbenl what do you think we could do here?

**Comment by jasonLaster** [comment]
I imagine we could use JS to render intermediate locations inbetween frames... not really sure

**Comment by hbenl** [comment]
I think the marker should simply run smoothly through the timeline "in real time" (i.e. it traverses one recorded second in one second). Of course it has to pause when it's still downloading data for the next frame - but in that case it should keep running until it is immediately before that frame in the timeline and only pause there if the data still hasn't arrived.

**Comment by jasonLaster** [comment]
@hbenl that sounds right. perhaps we can show a loading indicator if we're waiting on something :)
