### ISSUE TITLE
[Debugger] Add multiplayer breakpoint syncing

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#736]
During a user interview, I made them copy their recording link and open it in a different browser (Chrome). They were pleased that they saw the comments that they've made from before. They did, however, have a negative reaction to not seeing their breakpoints persist in the new browser.

It makes sense since they're still debugging the same thing. With an in-browser debugger, you would expect that breakpoints persist between refreshes. In this case, the user feels like they just refreshed since they're still debugging the same target; however, the breakpoints don't persist.

This won't be a case that comes up often. But when it does, it will happen to new users when they opened that recording in their non-Replay browser. That makes it worth taking a look at.

To solve it, we should have something that allows them to indicate whether they want the breakpoints to "sync". This would affect multiplayer use cases, so let's call it multiplayer breakpoint syncing. Some options are:
- Add multiplayer breakpoint syncing by default
- Have a checkbox somewhere in the debugger that toggles breakpoint syncing
- Have a share button that upon clicking, opens up a model with a toggle for breakpoint syncing and the recording link

**Comment by jasonLaster** [comment]
I think we can do this as a fast follow to comments in hasura/db. 

Alternatively we can prototype it with the existing metadata support :) 

I think the easiest way to do this would be to look at how we persist breakpoints with pending breakpoints and save them see `utils/bootstrap` 

Note, i am not sure if we need to start with a toggle for permissions, i think we can start with the default being to share and then add it when we get feedback that its invasive. I'm curious what users would find.
