### ISSUE TITLE
Add a way for users to be redirected to login from the replay.io homepage

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#761]
All of our login functionality is currently contained within `replay.io/view`.

For the less savvy user who is looking to login to see their recordings, they're probably going to go to `replay.io` and look for a login button. That login button should then kick off a flow that ends with them being able to see their recordings. 

We don't have that, and we should.

**Comment by jasonLaster** [comment]
Great call!

Do you think we should have a signin button on replay.io and a `replay.io/signin` page?
