### ISSUE TITLE
Apollo warning (Cache data may be lost when replacing the recordings field of a Query object)

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#786]
**Describe the bug**
This error shows up when you delete a recording from the recordings page.
```
react_devtools_backend.js:2273 Cache data may be lost when replacing the recordings field of a Query object.

To address this problem (which is not a bug in Apollo Client), define a custom merge function for the Query.recordings field, so InMemoryCache can safely merge these objects:
```
As I understand, there's extra steps we have to do when we mutate a GraphQL entity that's saved in the cache. Details here:

  * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
  * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects

**To Reproduce**
1. Open http://localhost:8080/view
2. Try deleting a recording
3. Recording is deleted properly, but the console warning shows up

**Screenshots**
![image](https://user-images.githubusercontent.com/15959269/94879476-4f471f80-042e-11eb-99ab-724f6744ca7f.png)

**Comment by jasonLaster** [comment]
_stale_
