### ISSUE TITLE
Simplify header ui

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#831]
**Summary**

We currently have a fairly large call to action for logging in and logging out. It'd be nice to think through what we're getting out of these CTAs and perhaps find ways to 

**Login** 
* logging in lets us see who's viewing a recording which is great for customer support / telemetry
* logging in lets us associate a comment with the user. 

Eventually, I think it would be nice to fold logging in with onboarding. We could do a lightweight interstitial / modal to welcome them and then prompt them to login. If they skip that step, they can always be prompted to login before commenting on a recording or sharing the recording.

**logout**
I don't think there's a great reason for logging out to be prominent. We should probably fold that into a dropdown that we can also use for other settings.

---

### Existing Logout

<img width="680" alt="Screen Shot 2020-10-16 at 11 19 48 AM" src="https://user-images.githubusercontent.com/254562/96294681-9c380380-0fa1-11eb-8cbb-a2d5f36d4428.png">

---

### Proposed logout

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay%3A%3ASketeches?node-id=974%3A878
<img width="1500" alt="logout" src="https://user-images.githubusercontent.com/254562/96295730-fa191b00-0fa2-11eb-9fc6-9197f5f5aff4.png">

**Comment by ienjoy** [comment]
I like this a lot. As time goes on, we'll end up wanting to put more things in the header. But it's good to start more sparse early on.

Question 1: what happens when I click my avatar? Might be good to put a visual there so we can see what's tucked away there. 

Question 2: where is share? Is that behind the avatar?

Follow up: on Slack we discussed adding a little dropdown arrow beside the avatar. I think that's wise.

**Comment by jasonLaster** [comment]
> Question 1: what happens when I click my avatar 

I would guess that it would open the dropdown

> Question 2: where is share?

I think it would be next to the avatar

**Comment by ienjoy** [comment]
Would you mind showing a screenshot of what's in that dropdown? I don't have an account to see it myself.

And if Share is up there, it sounds like we want that in the visual as well, so the image is our "source of truth."

**Comment by jasonLaster** [comment]
@ienjoy https://github.com/RecordReplay/devtools/pull/832

**Comment by jaril** [comment]
Fixed by #832
