### ISSUE TITLE
New recordings are blocked initially

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#833]
I tried creating a recording and initially the viewer said i did not have permission to see it. When I refreshed it was shown though.

<img width="957" alt="Screen Shot 2020-10-17 at 3 23 50 PM" src="https://user-images.githubusercontent.com/254562/96354596-2741f800-108d-11eb-8854-59244f9d0928.png">

**Comment by jaril** [comment]
This appears to be a race condition. 

The order of events should be:
1. Recording is uploaded
2. Recording info is sent to Hasura
3. The client fetches the record info from Hasura

In my testing this happens intermittently, where I think #2 and #3 get swapped. If we fetch the info from Hasura and it comes back empty, we infer that you don’t have permissions for that recording. I think that's what's causing this screen.

Can we emit something from the backend or the dispatcher to let the client know that it's okay to check Hasura?

**Comment by jaril** [comment]
This is fixed by https://github.com/RecordReplay/gecko-dev/pull/193
