### ISSUE TITLE
Highlighter doesn't work for nodes shown in the webconsole

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#860]
**Describe the bug**
When hovering over an HTML node in the webconsole, that node should be highlighted in the current screenshot.

**To Reproduce**
Open any recording. Enter `document.body` in the console. Wait for the evaluation result to appear and hover over it.

**Expected behavior**
The document body should be highlighted.
 
**Analysis**
The Highlighter is called, but the argument of the call is rejected [here](https://github.com/RecordReplay/devtools/blob/abc27d1a53f28338d2ddd6bccd67d390e2843c58/src/devtools/server/actors/highlighters/utils/markup.js#L130). `node.nodeType` is usually a getter property here, but in this case it is a method. I'm guessing that the `isNodeValid` function expects a `NodeFront` but in this case it receives a `ValueFront` (see [here](https://github.com/RecordReplay/devtools/blob/abc27d1a53f28338d2ddd6bccd67d390e2843c58/src/protocol/thread/node.js#L46) and [here](https://github.com/RecordReplay/devtools/blob/abc27d1a53f28338d2ddd6bccd67d390e2843c58/src/protocol/thread/value.js#L199)).

**Comment by jasonLaster** [comment]
@hbenl does this work now?

**Comment by jasonLaster** [comment]
This might already be fixed...
