### ISSUE TITLE
[Debugger] Breakpoint markers can be collapsed 

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#889]
I've noticed occasionally that if breakpoints can shift to the left and not be resized.

I believe the steps to reproduce are

1. set a breakpoint
2. select the console
3. refresh
4. select the debugger

<img width="705" alt="Screen Shot 2020-10-28 at 8 18 07 AM" src="https://user-images.githubusercontent.com/254562/97456704-54e13980-18f6-11eb-9b22-5895b5e13655.png">

**Comment by jaril** [comment]
https://discuss.codemirror.net/t/my-gutter-marks-appear-outside-the-gutter/1695
