### ISSUE TITLE
[UX] Indent the Breakpoint Panel

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#941]
The Breakpoint Panel is currently aligned against the left-hand side of the window. (See image)

@jaril , please indent the whole panel to be aligned with the line above it. Further visual changes are coming next week, but let's start with this for now.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/9154902/98187197-425da480-1f75-11eb-813a-9d3f2ad68294.png">

**Comment by jasonLaster** [comment]
I am beginning to wonder if we want to do this because the panel handles horizontal scrolling kind of weirdly.

**Comment by jonbell-lot23** [comment]
Happy to mark as lower priority for now.

**Comment by jasonLaster** [comment]
closing as it's a lower priority
