### ISSUE TITLE
Refactor SourceId references to ScriptId

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#958]
One of the relics of the old debugger and firefox protocol is references to `sourceId`. The Replay protocol uses ScriptId, so we should rename the variable and remain consistent.

**Comment by bhackett1024** [comment]
I think we should be going in the opposite direction, actually.  I think that using ScriptId in the protocol was a mistake and we should change it to SourceId before things get too entrenched and difficult to change.  See https://github.com/RecordReplay/protocol/issues/9
