### ISSUE TITLE
Replay should show a nicer 5 minute shutdown message

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#978]
Replay will stop a debugging session after 5 minutes of inactivity.

We currently show the standard session died unexpectedly message. It would be nice to show something special for this. Perhaps a sleeping panda? 

<img width="1402" alt="Screen Shot 2020-11-07 at 6 33 13 AM" src="https://user-images.githubusercontent.com/254562/98443902-48fa3200-20c3-11eb-8f7f-e28328bc7251.png">

**Comment by jaril** [comment]
Closing this and moving to #1230.
